### ISSUE TITLE
nach Update auf aktuelle Version greift ALIAS in Mehrsprachigkeit nicht!

### ISSUE THREAD

**Issue by haendersonfox** [MetaModels/core#1008]
Lösung:

die Namensfelder der jeweiligen Sprachen müssen ausgefüllt werden!

https://community.contao.org/de/showthread.php?62115-sprachumschaltung-funktioniert-nicht-mehr&p=405809&viewfull=1#post405809

**Comment by discordier** [comment]
Need more details, please do not only link to forum posts as these may get lost in the future and we have to check too many resources if we have to hunt down the information of issues from various places.
In the end, we do have the issue template (which you deleted entirely in your issue) for a reason.

**Comment by haendersonfox** [comment]
nach Update auf aktuelle Version greift ALIAS in Mehrsprachigkeit nicht!

das bedeutet, wenn im attribut des ALIAS kein Name bei der jeweiligen sprache steht,
gibt es eine fehlermeldung in der jeweiligen sprache, dass kein datensatz vorhanden ist.
füllt man im alias-attribut den namen aus (schreibt also zb. "alias" hinein), wird der datensatz in der jeweiligen sprache auch angezeigt...

**Comment by michelbalzer** [comment]
Kann ich mit Contao 3.5.9, dc_general 2.0.0-beta34, MetaModels 2.0.0-alpha10 so erstmal bestätigen. 

```
{
    "name": "local/website",
    "description": "A local website project",
    "type": "project",
    "license": "proprietary",
    "require": {
        "comolo/contao-supertheme": ">=2.3.1.0,<2.4-dev",
        "contao-community-alliance/composer-client": "~0.16",
        "contao-legacy/boxes": ">=1.16.2.9004,<1.17-dev",
        "contao-legacy/cssexport": ">=3.2.1.9003,<3.3-dev",
        "menatwork/piwiktrackingtag": ">=2.3.3.0,<2.4-dev",
        "metamodels/bundle_all": ">=2.0.0.0,<2.1-dev",
        "smohring/taxonomy": ">=1.0.0.0,<1.1-dev",
        "terminal42/contao-changelanguage": ">=2.2.11.0,<2.3-dev"
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "config": {
        "preferred-install": "dist",
        "cache-dir": "cache",
        "component-dir": "../assets/components"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
        },
        {
            "type": "artifact",
            "url": "packages"
        },
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
        }
    ],
    "extra": {
        "contao": {
            "migrated": "done"
        }
    }
}
```
Und in bunt:

![metamodels-alias-mehrsprachig](https://cloud.githubusercontent.com/assets/1337412/14675676/7074a9f0-070a-11e6-9838-d62d0f5bf7e5.jpg)

**Comment by zonky2** [comment]
bitte mal prüfen, ob bei der Sprache ohne Beschreibung ein Alias-Wert in der DB gespeichert wird

**Comment by haendersonfox** [comment]
wenn alle felder ausgefüllt sind, sieht es so aus:
a:7:{s:2:"de";s:5:"Alias";s:2:"en";s:5:"Alias";s:2:"nl";s:5:"Alias";s:2:"fr";s:5:"Alias";s:2:"it";s:5:"Alias";s:2:"es";s:5:"Alias";s:2:"pl";s:5:"Alias";}

wenn englisch nicht ausgefüllt ist, sieht es so aus:
a:7:{s:2:"de";s:5:"Alias";s:2:"en";s:0:"";s:2:"nl";s:5:"Alias";s:2:"fr";s:5:"Alias";s:2:"it";s:5:"Alias";s:2:"es";s:5:"Alias";s:2:"pl";s:5:"Alias";}

**Comment by zonky2** [comment]
this sounds like the same as #985

**Comment by zonky2** [comment]
kann das Phänomen bestätigen - im Log kommt bei dem Aufruf
```
The request for page ID "meine-detail-seite" contained unused GET parameters: "auto_item" (http://domain.tld/meine-detail-seite/detail-alias.html)
```

**Comment by discordier** [comment]
@zonky2 We need to debug this in your installation.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@haendersonfox could you please have a final look at this and tell if your issue has been resolved?
