### ISSUE TITLE
Filter count reagiert nicht auf unveröffentlichte Items $this->count zählt diese mit.

### ISSUE THREAD

**Issue by MacKP** [MetaModels/core#1010]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [ ] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    php 5.3      |                                  |
| Contao version:                     |    contao 3.2.11      |                                  |
| MetaModels version:                 |     alpha10     |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |    bundle_all      |                                  |

## Issue description

Ich habe einen Filter und eine Liste auf der gleichen Seite. Beide benutzten die selben Filtereinstellungen (Filter). Die Anzahl $this->count wird mit ausgegeben beim Filter. Leider wird im Filter aber nicht berücksichtigt, das einige Items nicht öffentlich sind und werden mit gezählt. 

## Steps to reproduce
- Ein MM Items (inkl. Checkbox 'Veröffentlicht')
- Ein MM Kategorien
- Filter in Items anlegen mit den Kategorien und einem Filter für 'Veröffentlicht'
- Anlegen von zwei Modulen -> Filter und Liste für MM Items. Bei beiden ist der Filter ausgewählt, mit den Kategorien, wo auch der Filter (aktiv) drin ist für 'Veröffentlicht'.

## Describe the behaviour of the application
Beispiel
* 6 Items / 4 Items nicht veröffentlicht / 2 Items veröffentlicht
* Anzahl der Items in der Liste (wenn gefiltert) -> 2
* Anzahl die beim Filter ausgegeben wird -> 6 (egal ob gefiltert wird oder nicht... aber das ist ja ein anderer Bug).

## Describe the expected behaviour of the application
Es sollten im Filter nur 2 Items angezeigt werden.

## Was ich mir denken könnte, woran es liegt...

Bei den Filtern kann/muss ausgewählt werden, welche Filter überhaupt genutzt und ausgegeben werden sollen. Da ist natürlich der Filter für 'Veröffentlichen' nicht mit drin. Ich schätze mal, das es daran liegt, das dieser nicht ausgewählt ist und deswegen nicht greift. Diese Stelle sollte man sich zumindest mal näher anschauen.

**Comment by zonky2** [comment]
duplicate issue #896
