### ISSUE TITLE
change all composer.json: required PHP to 5.4 and contao/core to 3.5

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1011]
change **all** composer.json: required 
- `"php": ">=5.4"`
- `"contao/core": "^3.5.5"`

(see https://docs.contao.org/books/manual/3.5/en/01-installation/configuring-the-live-server.html and
http://metamodels.readthedocs.io/en/latest/manual/install.html#install-and-update-metamodels)

AND

change .travis.yml

e.g. https://github.com/MetaModels/attribute_alias/commit/2256246bbc706575888e1691b6b9b23df3787294
- [X] [MetaModels/attribute_alias](https://github.com/MetaModels/attribute_alias)
- [X] [MetaModels/attribute_checkbox](https://github.com/MetaModels/attribute_checkbox)
- [x] [MetaModels/attribute_color](https://github.com/MetaModels/attribute_color)
- [x] [MetaModels/attribute_combinedvalues](https://github.com/MetaModels/attribute_combinedvalues)
- [x] [MetaModels/attribute_country](https://github.com/MetaModels/attribute_country)
- [x] [MetaModels/attribute_decimal](https://github.com/MetaModels/attribute_decimal)
- [x] [MetaModels/attribute_file](https://github.com/MetaModels/attribute_file)
- [x] [MetaModels/attribute_geoprotection](https://github.com/MetaModels/attribute_geoprotection)
- [x] [MetaModels/attribute_langcode](https://github.com/MetaModels/attribute_langcode)
- [x] [MetaModels/attribute_longtext](https://github.com/MetaModels/attribute_longtext)
- [x] [MetaModels/attribute_numeric](https://github.com/MetaModels/attribute_numeric)
- [x] [MetaModels/attribute_rating](https://github.com/MetaModels/attribute_rating)
- [x] [MetaModels/attribute_select](https://github.com/MetaModels/attribute_select)
- [x] [MetaModels/attribute_tabletext](https://github.com/MetaModels/attribute_tabletext)
- [x] [MetaModels/attribute_tags](https://github.com/MetaModels/attribute_tags)
- [x] [MetaModels/attribute_text](https://github.com/MetaModels/attribute_text)
- [x] [MetaModels/attribute_timestamp](https://github.com/MetaModels/attribute_timestamp)
- [x] [MetaModels/attribute_translatedalias](https://github.com/MetaModels/attribute_translatedalias)
- [X] [MetaModels/attribute_translatedcheckbox](https://github.com/MetaModels/attribute_translatedcheckbox)
- [x] [MetaModels/attribute_translatedcombinedvalues](https://github.com/MetaModels/attribute_translatedcombinedvalues)
- [x] [MetaModels/attribute_translatedfile](https://github.com/MetaModels/attribute_translatedfile)
- [x] [MetaModels/attribute_translatedlongtext](https://github.com/MetaModels/attribute_translatedlongtext)
- [x] [MetaModels/attribute_translatedselect](https://github.com/MetaModels/attribute_translatedselect)
- [x] [MetaModels/attribute_translatedtabletext](https://github.com/MetaModels/attribute_translatedtabletext)
- [x] [MetaModels/attribute_translatedtags](https://github.com/MetaModels/attribute_translatedtags)
- [x] [MetaModels/attribute_translatedtext](https://github.com/MetaModels/attribute_translatedtext)
- [x] [MetaModels/attribute_translatedurl](https://github.com/MetaModels/attribute_translatedurl)
- [x] [MetaModels/attribute_url](https://github.com/MetaModels/attribute_url)
- [x] [MetaModels/core](https://github.com/MetaModels/core)
- [x] [MetaModels/filter_checkbox](https://github.com/MetaModels/filter_checkbox)
- [x] [MetaModels/filter_fromto](https://github.com/MetaModels/filter_fromto)
- [x] [MetaModels/filter_perimetersearch](https://github.com/MetaModels/filter_perimetersearch)
- [x] [MetaModels/filter_range](https://github.com/MetaModels/filter_range)
- [x] [MetaModels/filter_register](https://github.com/MetaModels/filter_register)
- [x] [MetaModels/filter_select](https://github.com/MetaModels/filter_select)
- [x] [MetaModels/filter_tags](https://github.com/MetaModels/filter_tags)
- [x] [MetaModels/filter_text](https://github.com/MetaModels/filter_text)

**Comment by discordier** [comment]
Would be cool if we could also add #846 in the repositories at the same time.

**Comment by zonky2** [comment]
... and we look at #1061

**Comment by zonky2** [comment]
ready... all other checks at https://github.com/MetaModels/core/issues/1061
