### ISSUE TITLE
`ToolBoxFile` should implement download key handling

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#1014]
## Issue description

The `ToolBoxFile` should implement download key handling
See also MetaModels/attribute_file#6 for further details and discussion.
## Describe the behaviour of the application

The file attributes allow to download any file from `TL_FILES`, no matter if they are linked or not.
## Describe the expected behaviour of the application

The file attributes should only serve files for download when they are indeed allowed to be downloaded.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@discordier could you please have a final look at this and tell if your issue has been resolved?
