### ISSUE TITLE
Attribut Checkbox breaks with current MM and DCG

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1015]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  5.6        |                                  |
| Contao version:                     |  3.5.12        |                                  |
| MetaModels version:                 | alpha11         |       core |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |  bundle_all |                                  |
| DCG                                             | beta35

## Issue description

* It´s not possible to save input screens with checkbox(es) [but you can toggle with the "eye-icon"]

look at https://community.contao.org/de/showthread.php?62697-Fehler-bei-MM-Inaktiv-Labels

## Steps to reproduce

1. add Attribute Checkbox, add to list and input screen
2. at input screen select the checkbox and save

## Describe the behaviour of the application

* the Attribute Name is at every Checkbox "Inaktiv"
* the value at source is 1
* its not possible to save - we habe error "not right value: 1"
* JS-Error: not found element label with class "error" - ```getElement('label.error')```

The debug at checkbox attribute ```getFieldDefinition``` look good...

## Screenshots

![shot222](https://cloud.githubusercontent.com/assets/1045318/15805789/6bf2b022-2b34-11e6-8c48-03c8ecf59c71.jpg)

![shot223](https://cloud.githubusercontent.com/assets/1045318/15805794/76d05058-2b34-11e6-8f4a-f502eca13cfb.jpg)

**Comment by daniel-nemeth** [comment]
I can confirm this bug.
Thanks four your work guys!

**Comment by stefanheimes** [comment]
Fix is in the DCG hotfix/beta-36

**Comment by zonky2** [comment]
checked with C 3.5.12, MM a11 DCG hotfix/b36 => works fine

Thanks!!

**Comment by albirs** [comment]
+1

checked also with C 3.5.12, MM a11 DCG hotfix/b36 => works fine

Thank you!!

**Comment by zonky2** [comment]
Tested!

**Comment by zonky2** [comment]
> Fix is in the DCG hotfix/beta-36

@stefanheimes How can I found the related PR?
