### ISSUE TITLE
Auswahl der Javascript- und CSS-Dateien in den Render-Einstellungen per Simple Modal

### ISSUE THREAD

**Issue by stefanmeschke** [MetaModels/core#1016]
## Beschreibung

In den [Rendereinstellungen](http://metamodels.readthedocs.io/de/latest/manual/metamodel-first/rendersettings.html) kann man unten Javascript- und CSS-Dateien auswählen. Dies führt bei vielen Javascript- und CSS-Dateien zu einem `memory_limit`-Fehler im PHP.
## Lösungsvorschlag

Daher wäre mein Vorschlag zur Diskussion, dass man dies mit einem Modal (File-Picker) löst.
Wie seht ihr das?

**Comment by zonky2** [comment]
> Dies führt bei vielen Javascript- und CSS-Dateien zu einem memory_limit-Fehler im PHP.

* wenn diese vorhanden sind?
* während der Auswahl?
* beim Rendern der BE/FEListe?

**Comment by stefanmeschke** [comment]
Wenn ich eine vorhandene Rendereinstellung bearbeiten oder eine neue erstellen will. Also immer, wenn das [Formular](http://metamodels.readthedocs.io/de/latest/manual/metamodel-first/rendersettings.html) im BE gerendet wird.

**Comment by zonky2** [comment]
btw: wieviel RAM ist den vorhanden? wieviel will PHP haben?

... für neue Tickets gibt es eine Vorlage - die wurde aus gutem Grund erstellt ;-)

**Comment by stefanmeschke** [comment]
- Vorhanden: 2GB
- `memory_limit ` stand auf 128 MB mit 256 MB geht es jetzt für unsere Konfiguration und unserem derzeitigen Datenbestand

**Comment by zonky2** [comment]
uff... so macht das keinen Spaß - jede Info mit einem einzelnen Posting abfragen...

* alle "Systeminfos"
* was sind "viele"
* wie kann man das Nachstellen

**Comment by stefanmeschke** [comment]
## Systeminformationen

- Contao: 3.5.12
- PHP: 5.6.10
 - `max_execution_time = 240`
 - `max_input_time = 60`
 - `memory_limit = 128M`
- MetaModels/core: 2.0.0-alpha11

## Reproduktion
- Installation Contao
- Installation MetaModels-Core
- MetaModel "Test" erstellt
 - Name: Test
 - Tabelle: `mm_test`
- Erstellung eines neuen Ordners: `/files/test`
- Innerhalb `/files/test`: `npm init` (default-config)
- Installation der Packages von der ersten Seite auf [most starred npm packages](https://www.npmjs.com/browse/star)
- Den Ordner `/files/test` duplizieren (`/files/test2`)
- Den Ordner `/files/test` duplizieren (`/files/test3`)
- Den Ordner `/files/test` duplizieren (`/files/test4`)
- Contao Backend: _Einstellungen_ > _Fehlermeldungen anzeigen_
- Navigation zu _MetaModels_ > _Alle Render-Einstellungen von "Test"_
- Klick auf **Neu**
- Fehler: `Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1573927 bytes) in /Users/stefanmeschke/Sites/mm-issues-1016/system/modules/core/widgets/SelectMenu.php on line 164`

![error](https://cloud.githubusercontent.com/assets/3972213/15890809/b03757a8-2d71-11e6-848d-540eeab22cb9.png)

**Comment by zonky2** [comment]
so scheint es, das das Problem eher bei Contao-Core liegt... hast Du nach der "Installation der Packages" die Dateien in der Dateiverwaltung gesynct?

**Comment by stefanmeschke** [comment]
Eine Synchronisation in der Dateiverwaltung (siehe Screenshot) bleibt ohne Erfolg.

![dateiverwaltung-result](https://cloud.githubusercontent.com/assets/3972213/15894102/4caf75e0-2d84-11e6-91e3-1407ee06aa54.png)

Wenn man einen Theme im Contao bearbeitet/anlegt und da externe Stylesheets wählen möchte (siehe Screenshot) wählt man diese auch per Modal aus. Somit würde man da auch in der UX des Benutzers bzw. in dem Handling wie von Contao vorgesehen bleiben.

![theme](https://cloud.githubusercontent.com/assets/3972213/15894197/e9079b34-2d84-11e6-8f81-b65ce1be09d1.png)

Der Lösungsvorschlag würde somit das Problem mit dem `memory_limit` beheben und auch das Handling verbessern.

**Comment by zonky2** [comment]
wäre dennoch spannend, warum die Dateiverwaltung nichts findet...
...ich habe übrigens während der "Entwicklung" den Wartungsmodus aus und Internen Cache "umgehen"

**Comment by zonky2** [comment]
den Eintrag verstehe ich nicht recht
> * Installation der Packages von der ersten Seite auf most starred npm packages

nachdem "damit" Dateien unter /files gelandet sind können die von Contao offensichtlich nicht gesynct werden (Screenshot oben) - was ist den nun in dem Ordner?

**Comment by zonky2** [comment]
@stefanmeschke gibt es zu dem Ticket aktuelle Informationen? ansonsten bitte schließen

**Comment by discordier** [comment]
Einen picker an dieser Stelle einzubauen ist aktuell nicht moeglich. Der MCW versteht keinen file picker in einem DcGeneral backed Widget.

@stefanheimes Kann man da was machen?

**Comment by zonky2** [comment]
@baumannsven hatte angeboten, einen FilePicker in MCW (per "Mini-Fundrasing") einzubauen - bisher ist das Geld noch nicht zusammen...
