### ISSUE TITLE
tl_metamodel_dca_sortgroup / Default isn't working right

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#1018]
## Checklist before I submit this issue report

I confirm that:
- [X] I am one of the programmer
## My environment is:

| Key | Value | Comments |
| --- | --- | --- |
| PHP version: | n.a. |  |
| Contao version: | 3.5.12 |  |
| MetaModels version: | 2.0.0-alpha11 |  |
| DCG version: | 2.0.0-beta35 |  |
| Installation via composer | yes |  |
| Installed MetaModels packages | all |  |
## Issue description

See: Describe the behaviour of the application
## Steps to reproduce
1.  Go to the tl_metamodel_dca_sortgroup for mm_1
2. Add a new Setting
3. Activate "As default"
4. Go to the tl_metamodel_dca_sortgroup for mm_2
5. Add a new Setting
6. Activate "As default"
## Describe the behaviour of the application

If you activate the "As default" in the second sortgroup the "As default" is gone for the first one. So you can only set one "As default" for the whole table and not only for one MetaModels. So i can't activate for each MetaModels a defailt sortgroup.
## Describe the expected behaviour of the application

You should be able to set more "As default" for eacht metamodels and not for the whole system.

**Comment by daniel-nemeth** [comment]
+1
It have the same behaviour like for DCA fields with 'unique'=>true

**Comment by discordier** [comment]
The reset fallback in dcg must somehow become aware of filters.
This was sadly not implemented.

**Comment by zonky2** [comment]
same https://github.com/contao-community-alliance/dc-general/issues/303

**Comment by discordier** [comment]
Related to #35

**Comment by zonky2** [comment]
fixed with https://github.com/contao-community-alliance/dc-general/issues/321
