### ISSUE TITLE
Visibility condition set to value: inactive for attribut: checkbox doesn't work

### ISSUE THREAD

**Issue by daniel-nemeth** [MetaModels/core#1022]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 5.6         |                                  |
| Contao version:                     | 3.5.12        |                                  |
| MetaModels version:                 | a11         |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       | bundle_filter, bundle_nontranslated, attribute_timestamp, attribute_color         |                                  |

## Issue description

I have added and input screen with different fields and checkboxes. I have a field called 'allday' with 'submit on change' activated.
![screen shot 2016-06-15 at 18 12 50](https://cloud.githubusercontent.com/assets/5083254/16088122/ef8722da-3325-11e6-85ae-2ab507e6f5dc.png)

With the visibility conditions I defined, that 2 textfields should only be shown only, if the field 'allday' is inactive.
![screen shot 2016-06-15 at 18 13 14](https://cloud.githubusercontent.com/assets/5083254/16088130/f4b2d16e-3325-11e6-8525-9eedb3a05972.png)

Currently it works fine if the visibility filter is set to 'active', but with the value set to inactive it doesn't show the two textfields.

## Steps to reproduce

1. Create MetaModel with one checkbox and two textfields
2. Add input screen with all 3 fields
3. Activate the option 'submit on change' for the checkbox
4. Go to the visibility conditions for both textfields and create a visibility condition with the condition 'Attribute value is..'.
5. Set the following options for the condition: Enabled is active, attribute: the checkbox, value: inactive
6. Go to the input screen and try to add a new item. Both textfields aren't shown.

**Comment by zonky2** [comment]
you can try a workaround: at your condition add a negation rule "NOT" - you cyn see the textfields if "NOT && Active"

**Comment by daniel-nemeth** [comment]
Hi,
I changed the condition - hopefully in the right way - and it doesn't work:

![screen shot 2016-06-27 at 09 29 20](https://cloud.githubusercontent.com/assets/5083254/16371909/c0f2f232-3c49-11e6-9415-8e54fbc33502.png)

Now the textfield is visible, when the checkbox is checked instead of unchecked.

**Comment by zonky2** [comment]
you can use the workaround - pls look at http://metamodels.readthedocs.io/de/latest/cookbook/panels/checkbox-negation.html

**Comment by daniel-nemeth** [comment]
Thanks!



On 03 Jul 2016, at 09:20, zonky2 <notifications@github.com> wrote:

you can use the workaround - pls look at http://metamodels.readthedocs.io/de/latest/cookbook/panels/checkbox-negation.html

**Comment by zonky2** [comment]
Our "Thank you page" ;-)
https://now.metamodel.me/de/unterstuetzer/spenden
