### ISSUE TITLE
Bei Anlegen von Rendereinstellungen verschwinden die meisten Metamodels aus dem Backend

### ISSUE THREAD

**Issue by Rotbarsch** [MetaModels/core#1023]
Hallo,

bei der Arbeit mit dem Paket "MetaModels/bundle_all" in der Version 2.0.0 beobachten wir seit kurzem ein eigenartiges Verhalten. Es existieren bereits mehrere MetaModels; legen wir nun für ein bestehendes oder ein neues MM ein Rendersetting oder eine Eingabemaske an, verschwinden die meisten (aber sonderbarerweise nicht alle) MetaModels aus dem Backend. Eine Überprüfung der Datenbank zeigt, dass die isdefault Spalte sowohl in tl_metamodel_rendersettings als auch in tl_metamodel_dca auf einen leeren String gesetzt wird. 

Anzumerken ist dass wir vorher auf dem Stand dev_master aus dem Paket "MetaModels/core" waren; dort war dieses Verhalten auch schon zu beobachten.  Die verwendete Contao Version ist die 3.5.6.

**Comment by zonky2** [comment]
wurde bei den MMs die "Eingabe-/Render-Zuordnung" gesetzt?

**Comment by Rotbarsch** [comment]
Nein, daran haben wir händisch nichts verändert.

**Comment by zonky2** [comment]
die Frage war, ob die Zuordnung gesetzt wurde bzw. ist? "früher" reichte es für die Anzeige eines MM im BE eine Eingabemaske auf Standard zu setzen ohne die Zuordnung zu setzen...

**Comment by Rotbarsch** [comment]
Haben auf Ihre Anregung die Zuordnungen überprüft und festgestellt, dass alle mit gültigen Werten gefüllt sind. Nachdem wir hier manuell nochmal auf "Speichern" geklickt haben taucht das betreffende Metamodel wieder im Backend auf. Das Problem ist also von unserer Seite her behoben. Danke für Ihre Hilfe.
