### ISSUE TITLE
Make the number of pagination links configurable.

### ISSUE THREAD

**Issue by bastlwastl** [MetaModels/core#1025]
Wäre es möglich die Anzahl der Pagination-Links konfiguriebar zu machen?

Siehe: https://github.com/contao/core/issues/4601

**Comment by zonky2** [comment]
probiere es doch mal aus https://github.com/MetaModels/core/blob/master/src/MetaModels/Helper/PaginationLimitCalculator.php#L278
und wenn es funktioniert, mach einen PR

**Comment by zonky2** [comment]
duplicate with #920
