### ISSUE TITLE
Page picker without preselected page with storred value

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1026]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    5.6      |                                  |
| Contao version:                     |    3.5.14      |                                  |
| MetaModels version:                 |    core a12      |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |    bundle_all      |                                  |

## Issue description

If we have stored value and open the page picker, we don´t see a selected radio button.

## Steps to reproduce

1. ope e.g. redner settings
2. select a page with picker (the blue world bullet)
3. save and open again

=> the saved page has no selected radio button

## Describe the behaviour of the application

(Tell us what happens)

## Describe the expected behaviour of the application

(Tell us what should have happened)

## Screenshots

![shot251](https://cloud.githubusercontent.com/assets/1045318/16739708/c2cbc73e-479b-11e6-84f6-01bbdced4f44.jpg)

**Comment by discordier** [comment]
Should be fixed with beddc36, please test.

**Comment by cliffparnitzky** [comment]
I've tested this in my environment. Generally this seems work. But clicking the "Apply" button causes an JS error.

**Comment by discordier** [comment]
Oh? That should not happen, will have to take a look again.

**Comment by discordier** [comment]
@cliffparnitzky Could you test with commit 7888d3d please?

**Comment by cliffparnitzky** [comment]
Great, now it works in my environment.
