### ISSUE TITLE
Metamodel lässt sich nicht anlegen

### ISSUE THREAD

**Issue by Olli** [MetaModels/core#1028]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   5.5       |                                  |
| Contao version:                     |   3.5.15       |                                  |
| MetaModels version:                 |  dev-hotfix/alpha-13 (dcea4d50)       |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |  none        |                                  |

## Issue description

Kann kein Metamodel anlegen - sieht dann so aus
http://imgur.com/a/RfNVf

## Steps to reproduce

1. "Neues Metamodel" klicken

## Describe the behaviour of the application

Nichts - siehe Screener

## Describe the expected behaviour of the application

Anlegen eines metamodels

**Comment by zonky2** [comment]
warum verwendest Du den Hotfix statt des getaggten alpha12?
DCG auch mit hotfix versehen?

**Comment by Olli** [comment]
Weil er oben war und hotfix alpha-13 klingt wie "neuer als alpha-12" und ich dann hier nicht lesen wollte "installier mal den Hotfix weil da genau das Thema gefixt ist" ;)
Also in der alpha-12 gehts auch nicht. Die Install des Contao ist auch recht plain weil das meine Demo ist.

**Comment by zonky2** [comment]
hotfix ist für "ich weiß was ich mache" ;-)

wenn Du mir im Forum eine PN mit den Zugangsdaten sendest, kann ich mal kurz rein sehen...

**Comment by zonky2** [comment]
Thema Installation:

1.) http://metamodels.readthedocs.io/de/latest/cookbook/checklists/mm-start.html
2.) nicht an den Composer-Einstellungen schrauben, wenn Du nicht genau einen Plan hast...
3.) http://metamodels.readthedocs.io/de/latest/manual/install.html#installieren-via-composer

Install so eben mit einer 3.5.12 getestet - o.k.

solange der Header des Panels nicht so aussieht wie auf dem Screenshot, ist irgendwas "schief"

![shot260](https://cloud.githubusercontent.com/assets/1045318/17056362/1e2fda28-5013-11e6-96d9-4d50955d1edb.jpg)

**Comment by Olli** [comment]
Danke erst mal soweit. 
Ich habe nicht zum ersten mal MetaModels installiert. Von daher ist das eigentlich Business as usual gewesen. Ich habe jetzt alle nicht wichtigen Erweiterungen entfernt, PHP auf 5.6 geupdatet, Cache geleert und auch MM noch mal installiert (diesmal das Bundle). Tut nicht - selbes Verhalten wie gezeigt. 
Hoster ist all-inkl. Es gibt keine speziellen Einstellungen.

**Comment by zonky2** [comment]
mit der Fragestellung bist Du ggf. Im Forum besser aufgehoben - da offensichtlich kein Bug habe ich das Ticket geschlossen

**Comment by zonky2** [comment]
... hast Du Zugriff auf die Console? ggf. reicht die Laufzeit von PHP nicht aus und es wird nicht alles installiert

**Comment by zonky2** [comment]
kannst auch von hier ein "Paket" einspielen http://www.e-spin.de/contao-metamodels.html

**Comment by Olli** [comment]
Danke - klingt gut. Da gehts ggf fixer.

**Comment by zonky2** [comment]
bitte beachten: 
> Contao2go-Pakete auch ohne Contao2go
