### ISSUE TITLE
Beim Einfügen neuer Items: Call to a member function setResponse() on null

### ISSUE THREAD

**Issue by Hauge** [MetaModels/core#1029]
| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   7       |                                  |
| Contao version:                     |   3.5.14       |                                  |
| MetaModels version:                 |     MetaModels 2.0.0-alpha13     |                                  |
| Installation via composer:          | nein |                                  |
| Installed MetaModels packages:      |    manuelle installation |    |
| DCG version:                        |      2.0.0-beta37    |                                  |

Folgenden Fehler erhalte ich beim erstellen eines neuen Items:
Fatal error: Uncaught exception Error with message Call to a member function setResponse() on null thrown in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php on line 145
![1](https://cloud.githubusercontent.com/assets/1571133/17620295/9f28ac3a-608b-11e6-8e7e-cd2d50c4caf6.JPG)

**Comment by cliffparnitzky** [comment]
Gleiches Problem wie hier: https://github.com/MetaModels/core/issues/946#issuecomment-239273715

**Comment by discordier** [comment]
Follow up to contao-community-alliance/dc-general#290
