### ISSUE TITLE
RTE-enabled Attributes should make use of dbfs

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#1030]
I confirm that:
I have not tested this with the latest version available

I have a longtext attribute with TinyMCE enabled. When i link a file with the help of the TinyMCE-Link-Picker the resulting DB-Entry does store a value something like
```html
 <p>lorem <a href="files/filename.pdf">ipsum</a></p>
```

when i do the same with an ce_text element in an ordinary article
```html
 <p>lorem <a href="{{file::UUID}}">ipsum</a></p>
```
is stored - which is more convenient in terms of rearangements in the filetree.
Unfortunately this can only be observed on db-level (with phpmyadmin)

this issue affects probably other atrributes (translated ones which i never used) so i post this here.
If it's not a bug then it would be a desirable enhancement.

**Comment by zonky2** [comment]
@asaage pls fill out the issue template...

**Comment by zonky2** [comment]
I tested with DCG b38 ans MM core a13

=> I can't see differences...?

ce_text
![shot261](https://cloud.githubusercontent.com/assets/1045318/17733290/316d29c0-6476-11e6-9b90-d45e2ffcfd67.jpg)

MM
![shot262](https://cloud.githubusercontent.com/assets/1045318/17733304/3fd33e3c-6476-11e6-8b0d-823aaeadbdb9.jpg)

**Comment by asaage** [comment]
the difference occurs if you move the file to a different location.
In mm the link will break in ce_text not.
> Unfortunately this can only be observed on db-level (with phpmyadmin)

**Comment by zonky2** [comment]
ah - o.k. I`ll check it...

**Comment by asaage** [comment]
https://github.com/contao/core/issues/8213#issuecomment-189257184

**Comment by zonky2** [comment]
@asaage pls open a new ticket at DCG - the DCG schould implement this feature...

**Comment by asaage** [comment]
I always pick the wrong repository... :)
