### ISSUE TITLE
Backend-Ansicht Attribute - Icons in Header fehlen

### ISSUE THREAD

**Issue by pepesale** [MetaModels/core#1031]
In der Backend-Ansicht der Attribute fehlen im Header des MetaModels die Icons für

- Bearbeiten Sie das Attribut
- Neues Attribut nach diesem Attribut
- pasteafter.0

Das ist insbesondere dann problematisch, wenn man das erste Attribut eines Metamodels anlegen möchte. Dann ist auch das gelbe Icon pasteafter.0 nicht vorhanden, so dass man praktisch keine Attribute anlegen kann.

PHP 7.0.9
Contao 3.5.15
MM dev-hotfix/alpha-14 mit dc-general dev-hotfix/beta-38, per Composer installiert

Screenshot hier:
![mm-neues-attribut-fehlende-icons](https://cloud.githubusercontent.com/assets/1433109/17839806/010fbb54-67f4-11e6-9bf3-924d1df48ae7.GIF)

So sollte es sein (hier MM alpha10 mit DCG beta34)
![mm-neues-attribut-so-soll-es-sein](https://cloud.githubusercontent.com/assets/1433109/17839807/01129cd4-67f4-11e6-9f83-26a86d5fbf78.GIF)

(als Workaround kann ich "alle auswählen" anklicken, dann werden die Icons im Header angezeigt...)

**Comment by zonky2** [comment]
bitte die PR https://github.com/contao-community-alliance/dc-general/pull/296 und https://github.com/contao-community-alliance/dc-general/pull/298 einspielen und testen

**Comment by pepesale** [comment]
Mit PR contao-community-alliance/dc-general#296 und contao-community-alliance/dc-general#298 funktioniert es wieder.

**Comment by zonky2** [comment]
Update in Arbeit...
