### ISSUE TITLE
Page index not built correctly within multilanguage MM

### ISSUE THREAD

**Issue by design23** [MetaModels/core#1032]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    5.6.1      |                                  |
| Contao version:                     |      3.5.15    |                                  |
| MetaModels version:                 |    2.0.0      |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      | bundle_all         |                                  |
| DCG version:                        |     2.0.0-beta37     |                                  |

## Issue description

Built a MM with 2 languages (DE/EN), translated alias, translated checkbox for publishing state.
The searchable pages feature does not create correct sitemap.xml entries.
It seems to depend on the publishing state of the first (main) language of the MM.

When MM entry of DE is published, it creates sitemap entries for DE **and** EN – even if EN is NOT published at all. 
The other way round, EN won't show up in the sitemap when DE is NOT published. 

I experienced this behaviour in 2 different installations.

**Comment by zonky2** [comment]
may be it´s the same bug as
* https://github.com/MetaModels/core/issues/985
* https://github.com/MetaModels/core/issues/1008

see at https://community.contao.org/de/showthread.php?60645-Aktuell-bekannte-Bugs (Mehrsprachigkeit: Translatealias ohne ausgefüllten Namen lassen sich nicht...)

**Comment by design23** [comment]
I'm not quite sure about that.
I've read the other reports as well. All of the fields have names / translations and descriptions, so that's not the cause.

**Comment by zonky2** [comment]
o.k. tank´s for the check

**Comment by design23** [comment]
Any news on that one? I already found that bug in 2 installations and it's not that helpful for SEO ;)

**Comment by zonky2** [comment]
It´s possible to you to write a PR?

**Comment by design23** [comment]
Erh... what exactly do you mean?

**Comment by zonky2** [comment]
* seach the problem and fix it at the source 
* push up a Pull Request

**Comment by design23** [comment]
Oh... yeah, I would do that if I COULD ;)

**Comment by zonky2** [comment]
95% of our work is just for fun - If you have a project to finance the bugfixing, send a mail... on the other hand you have to wait of own projects with this feature

btw: 42€ is nearly a half hour for the most full-time programmer ;-)

**Comment by design23** [comment]
I'm fully aware of these facts. I just wanted to ask if there's already a solution in sight. If I had the possibilities to fix it on my own, I totally would do that.
So, don't get me wrong on this: I think MM is the biggest and best extension Contao ever got and I appreciate all the hard work that has been put into this project so far... I just thought it might at least be a tiny tiny help to report bugs – as long as I'm not able to fix them by myself.
I use this feature in 2 client projects - and well... the clients are not really willing to pay, so this goes from my wallet ;)

**Comment by zonky2** [comment]
> the clients are not really willing to pay, so this goes from my wallet ;)

may be you should to revise your business... ;-)

**Comment by design23** [comment]
> may be you should to revise your business... ;-)

Wow. Thank you.

**Comment by zonky2** [comment]
o.k...o.k. I see your donation and "I whirl the drumsticks..."

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/core/commit/58ec4ca31aeb280366abf53a6d48e7d0d855cc11
