### ISSUE TITLE
Frontend 'Detail-Link' (Filter, Alias, auto_item) doesn't work.

### ISSUE THREAD

**Issue by dillinja** [MetaModels/core#1037]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   5.6.23       |                                  |
| Contao version:                     |    3.5.15      |                                  |
| MetaModels version:                 |    2.0.0-alpha14      |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      | bundle_all         |                                  |
| DCG version:                        |  2.0.0-beta38        |                                  |

## Issue description

Frontend 'Detail-Link' (Filter, Alias, auto_item) doesn't work.

`[06-Sep-2016 17:29:48 Europe/Berlin] PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Could get metamodel id: 0' thrown in J:\Projekte\___Xampp\htdocs\pura\composer\vendor\metamodels\core\src\MetaModels\ItemList.php on line 361
#0 J:\Projekte\___Xampp\htdocs\pura\composer\vendor\metamodels\core\src\MetaModels\ItemList.php(270): MetaModels\ItemList->prepareMetaModel()
#1 J:\Projekte\___Xampp\htdocs\pura\composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\HybridList.php(104): MetaModels\ItemList->setMetaModel('0', '0')
#2 J:\Projekte\___Xampp\htdocs\pura\system\modules\core\classes\Hybrid.php(239): MetaModels\FrontendIntegration\HybridList->compile()
#3 J:\Projekte\___Xampp\htdocs\pura\composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\MetaModelHybrid.php(102): Contao\Hybrid->generate()
#4 J:\Projekte\___Xampp\htdocs\pura\composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\HybridList.php(54): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#5 J:\Projekte\___Xampp\htdocs\pura\system\modules\core\library\Contao\Controller.php(321): MetaModels\FrontendIntegration\HybridList->generate()
#6 J:\Projekte\___Xampp\htdocs\pura\system\modules\core\pages\PageRegular.php(137): Contao\Controller::getFrontendModule(Object(Contao\ModuleModel), 'Offer')
#7 J:\Projekte\___Xampp\htdocs\pura\system\modules\core\controllers\FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#8 J:\Projekte\___Xampp\htdocs\pura\index.php(20): Contao\FrontendIndex->run()
#9 {main}`

But there is no MM with ID 0 ... it starts by 1.

## Steps to reproduce

1. installed fresh MM via composer (bundle_all)
2. create a new MM with 'Title', 'Alias' and 'Notes' as attributes
3. a.s.o see https://de.contaowiki.org/MetaModels_Beispiel_2

## Describe the behaviour of the application

- Listview works great
- produced links are looking great
- by klicking these the fatal error occures

**Comment by zonky2** [comment]
do you work with a multilanguage metamodels?

**Comment by dillinja** [comment]
no,

normaly I check translation, choose 'German', check fallback language and thats it.

so I read about the 'alias - translation' issue and create a new without any translation box checked.

same behavior.

**Comment by zonky2** [comment]
its possible to post your filter rule(s) as screenshot

**Comment by dillinja** [comment]
here it is:
![mm-filter-detail](https://cloud.githubusercontent.com/assets/4386973/18283594/4c6d18e8-7466-11e6-89ae-5421a3379f14.jpg)

**Comment by dillinja** [comment]
checked it at home on another project (same contao, dcg and mm-versions) - can't reproduce the error.

**Comment by zonky2** [comment]
hmm... may be "make new" - https://community.contao.org/de/showthread.php?45309-Contao-2-11-x-Detailseite-zeigt-nur-noch-Fehler-nach-dem-L%F6schen-eines-Kind-Models&p=293078&viewfull=1#post293078

**Comment by dillinja** [comment]
I removed Metamodels + my mm_tables completly... but I left different modules (mm lists) on some sites. Not those that I used.

Now I cleaned up a bit better ... et voilà - it works!

**Comment by zonky2** [comment]
hmm..? magic...
