### ISSUE TITLE
every filter rule insert the ace editor - this should only add in "own SQL"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1038]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  5.6        |                                  |
| Contao version:                     |   3.5.15       |                                  |
| MetaModels version:                 |   core a14       |                                  |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      |  bundle_all        |                                  |
| DCG version:                        |  b38        |                                  |

## Issue description
* open a page with filter rule at backend and you see JS error e.g. at FireBug

```
<script>window.ace || document.write('<script src="assets/ace/1.1.8/ace.js" charset="utf-8">\x3C/script>')</script>
<script>
window.ace && window.addEvent('domready', function() {
  var ta = document.getElementById('ctrl_customsql'),
      dom = ace.require("ace/lib/dom");

  // Create a div to apply the editor to
  var div = document.createElement('div');
  div.id = 'ctrl_customsql_div';
  div.className = ta.get('class'); // <= this row: TypeError: ta is null
```

**Comment by discordier** [comment]
This is the same you reported as contao-community-alliance/dc-general#308 I suspect?

If so, we should close this one.

**Comment by zonky2** [comment]
correct - I was confused...
