### ISSUE TITLE
Save Rendersettings - values get lost / Beim Speichern der Rendereinstellungen gehen im BE Werte verloren.

### ISSUE THREAD

**Issue by dillinja** [MetaModels/core#1040]
## My environment is:

| Key | Value | Comments |
| --- | --- | --- |
| PHP version: | 5.6.23 |  |
| Contao version: | 3.5.15 |  |
| MetaModels version: | 2.0.0-alpha14 |  |
| Installation via composer: | yes |  |
| Installed MetaModels packages: | bundle_all |  |
| DCG version: | 2.0.0-beta38 |  |
## Issue description

when **creating a new render-setting** and finish this with **save** or **save & close** some information gets lost. You won't get it if you click **save & close**.
## Steps to reproduce
1. create a new render-setting
2. fill in: name, output-format, jump-to-page, filter-settings, hide empty items, hide lables
3. click **save**
4. jump-to-page and filter-settings get lost
5. Contao BE -> edit render-settings -> both fields are empty
6. choos the jump-to-page + filter-setting again -> save
7. everything is fine

Tested on Mac: Safari, Chrome + Windows: Chrome
## Screenshots

(Add some visual love or even a video if you can)
![unbenannt](https://cloud.githubusercontent.com/assets/4386973/18307754/0c9c4cac-74f2-11e6-8808-1af904814866.JPG)

**Comment by zonky2** [comment]
confirmed...

**Comment by discordier** [comment]
I suspect a problem with MCW here... @stefanheimes could you chime in?

**Comment by stefanheimes** [comment]
Confirmed one time.

Create a new one and take a look close to the MCW, there is something missing. On the Screen you see the "Deutsch" in the first column. But if you just create a new RenderSetting the first column is empty. There is no active language or the "Alle Sprachen", after saving, the first column has the right context e.g. "Deutsch" or "Alle Sprachen". 

So if you create a new RenderSetting the JumpTo has an error. After the first Saving the JumpTo display all data correct. So it seems that the callback/event which create the JumpTo has an error for new records.

**Comment by discordier** [comment]
So what is the initial value then? Empty string? I guess we need to create a proper default value on new value.

**Comment by zonky2** [comment]
tested - works fine!
