### ISSUE TITLE
After Update DC General throws errors in MetaModels

### ISSUE THREAD

**Issue by m-knorr** [MetaModels/core#1047]
## My environment is:

| Key | Value | Comments |
| --- | --- | --- |
| PHP version: | 5.6 |  |
| Contao version: | 3.5.6 |  |
| MetaModels version: | 2.0.0-alpha14 |  |
| Installation via composer: | yes |  |
| Installed MetaModels packages: | core & bundle |  |
| DCG version: | 2.0.0-beta-38 |  |
## Issue description

The Frontend works as expected.

But the Backend won't work anymore. The Listings of Metamodels work, but when I want to edit an entry the following error appears.

The Multilanguage settings aren't saved neither. I can't save the translation values in the metamodels settings, Zulu and Bangalore are configured instead of german and english...

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message 4 matching palettes found. thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Palette/PaletteCollection.php on line 138
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(709): ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\PaletteCollection->findPalette(Object(MetaModels\DcGeneral\Data\Model))
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(564): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(539): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(142): call_user_func_array(Array, Array)
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC/General.php(285): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC/General.php(345): ContaoCommunityAlliance\DcGeneral\DC_General->callAction()
#11 system/modules/core/classes/Backend.php(650): ContaoCommunityAlliance\DcGeneral\DC_General->edit()
#12 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_ar...')
#13 contao/main.php(20): Contao\BackendMain->run()
#14 {main}
```

[edit by zonky2]

**Comment by discordier** [comment]
Do you remember from which version you upgraded?

The issue is, that dc-general now finds 4 matching palette definitions where it should only find one.

What packages have additionally been updated aside from MetaModels and dc-general?

Can you provide us with more information about your setup?

**Comment by m-knorr** [comment]
I can't reproduce the additionally install modules, sorry. But here are the currently installed modules:

![bildschirmfoto 2016-11-02 um 11 27 32](https://cloud.githubusercontent.com/assets/13362483/19925263/80212da4-a0ef-11e6-89e4-886c41bf8da4.png)

Hope it helps, because the MetaModels don't work anymore... :(

My setup contains 4 MetaModels which are in some kind referenced with each other. Maybe that's the Problem why the DC-general finds 4 palette definitions...

**Comment by zonky2** [comment]
@m-knorr two notes:
* you can delete "metamodel/core" - this package is implemented in bundle_all
* if you wish to update the DCG to beta39, you should update the json file => read the manual...

**Comment by discordier** [comment]
I can not reproduce this on my system.

We would be either in need of the DB or access to your site to do (paid) debugging.

If you want to get the root cause of the problem yourself, you want to trace into `src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Palette/PaletteCollection.php` and dump the matching palettes.
Then you should get an idea why several match.

**Comment by zonky2** [comment]
@m-knorr pls check your system... if you can reproduce the error, you can re-open the issue
