### ISSUE TITLE
add checkbox "all chosen items active"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1057]
look at https://github.com/contao-community-alliance/dc-general/issues/315#issuecomment-262377542

**Comment by discordier** [comment]
*sigh* let me copy it for you...

> add checkbox "all chosen items active"

![image](https://cloud.githubusercontent.com/assets/940331/20545181/1001a5e2-b10e-11e6-804a-c457bc866f9e.png)

**Comment by zonky2** [comment]
THX!

**Comment by discordier** [comment]
Needed it just now, therefore I implemented it. :)

**Comment by zonky2** [comment]
you are my "MM fairy" ;-)

it works fine and speed up the work with MM

THX!
