### ISSUE TITLE
Manuelles Sortieren bei Kind-Elementen (mehrsprachiges Metamodel)

### ISSUE THREAD

**Issue by martonos** [MetaModels/core#1058]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    5.6.27      |                                  |
| Contao version:                     |      3.5.19    |                                  |
| MetaModels version:                 |     2.0.0-alpha14     |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |     bundle_all     |                                  |
| DCG version:                        |     2.0.0-beta38     |                                  |

## Issue description

Ich hab ein MetaModel "Projekte" welches ein weiteres MetaModel "Zeilen" als Kind-Element hat. Die Metamodels sind beide mehrsprachig. Schon beim parent kann ich nur manuell sortieren über die blauen Pfeile. Ein Javascript-Fehler tritt dabei nicht auf. Wenn ich versuche bei den Kindern die Reihenfolge über die blauen Pfeile zu verändern, kann ich die neue Position nicht auswählen.

Davon abgesehen, funktioniert das Verschieben per Drag&Drop weder bei den Eltern- noch bei den Kindelementen. In der Datenbank steht unter sorting in der Kind-Tabelle 0,128,256,384 oder 512. Bei der Eltern-Tabelle stehen "ordentliche" Werte. 

Scheint ähnlich wie hier zu sein:
https://github.com/MetaModels/core/issues/731#issuecomment-88400177

## Screenshots

![projekte_-_contao_open_source_cms_3_5](https://cloud.githubusercontent.com/assets/5220040/20713538/f49b4d4a-b648-11e6-9261-6d0056236ede.jpg)

**Comment by zonky2** [comment]
zum Thema Sortieren per Ajax: der Fix unter https://github.com/contao-community-alliance/dc-general/pull/313

**Comment by martonos** [comment]
Jope. Mit dem contao-community-alliance/dc-general#313 gibt es also einen Fix, welche DC-General-Version muss ich denn dafür über den Composer installieren? Von mir aus, muss es auch gar nicht gleich per Ajax sein, Hauptsache ich kann irgendwie die Reihenfolge ändern.

![metamodels_-_contao_open_source_cms_3_5](https://cloud.githubusercontent.com/assets/5220040/20714628/e249582c-b64c-11e6-8103-6363b49bfb16.jpg)

**Comment by martonos** [comment]
Ach verrückt, ich hab die beiden Zeilen angepasst und jetzt geht es. Das ist doch jetzt aber nicht Updatesicher oder?

Schon jetzt vielen Dank!

**Comment by discordier** [comment]
Das Problem wird in beta 38 vom DCG gefixt sein, somit ist es "updatesicher", da du die Fehlerbehebung von Hand bei dir vorgenommen hast.
Beim Update wird deine Aenderung mit unserer ueberschrieben, welche jedoch dieselbe ist.

Ich mache daher hier nun zu.

**Comment by martonos** [comment]
Alles klar. Danke!
