### ISSUE TITLE
Add column enabled at tl_metamodel_dca_sortgroup and toggle "eye" at backend

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1059]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   5.6       |                                  |
| Contao version:                     |    3.5.19      |                                  |
| MetaModels version:                 |     core a14     |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |   b38       |                                  |

## Description

Add column enabled at tl_metamodel_dca_sortgroup and toggle "eye" at backend to activate/deactivate the grouping and sorting

![shot296](https://cloud.githubusercontent.com/assets/1045318/20729071/e3f525fa-b680-11e6-8b66-f66a4cc71878.jpg)

**Comment by discordier** [comment]
What do you need this for?
I mean,what is the use case?
Why would you want to have disabled sorting settings?

I'll file this as future for the moment.

**Comment by zonky2** [comment]
> Why would you want to have disabled sorting settings?

at first: a consistent usability... the most "adjustment" we can toggle e.g. filter rules and other

**Comment by zonky2** [comment]
Fixed at MM 2.3
