### ISSUE TITLE
Change 'Unnamed legend' as default to MetaModel name

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1063]
my be its a good idea to change  'Unnamed legend' to the name of the MetaModel?

see at https://github.com/MetaModels/core/blob/master/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php#L228

```diff
        $activeLegend   = $this->translateLegend(
-            array('legendtitle' => 'Unnamed legend', 'legendhide' => false),
+            array('legendtitle' => $metaModel->getName(), 'legendhide' => false),
            $metaModel
        );
```

**Comment by discordier** [comment]
I do not see why this should be better.

**Comment by zonky2** [comment]
In my mind the metamodels name e.g. "Products", "Addresses", "Events"... looks like better than "_Unnamed legend_" ...

at this time its to much clics to add a own legend - a good way can be add the legend with the "add all" button (and checkbox to add)

**Comment by discordier** [comment]
How should this work with the addAll?

**Comment by zonky2** [comment]
> How should this work with the addAll?

I don't know... may be we can add a row with checkbox in the attribute list at first "item"

**Comment by discordier** [comment]
Well, if the others agree, I'm fine with changing this to the MetaModel-Name (@MetaModels/team, please chime in).

The addAll improvement however will need significant changes, therefore please open a new ticket for this (as feature request) if you really want this.

**Comment by zonky2** [comment]
thx https://github.com/MetaModels/core/pull/1067
