### ISSUE TITLE
readonly Date-attribute not working properly

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#1064]
Wenn in einer Eingabemaske ein Datum-Feld mit der Eigenschaft "nur lesen" auftaucht erscheint zum Einen trotzdem der Datepicker, der editierbarkeit sugeriert zum Anderen kann man die Maske nicht mehr abschicken falls das Feld befüllt ist.
![image](https://cloud.githubusercontent.com/assets/4138336/20960728/14e780d6-bc62-11e6-9703-6f64a5164b64.png)

**Comment by discordier** [comment]
Duplicate of MetaModels/attribute_timestamp#21.
