### ISSUE TITLE
readonly Attributes

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#1065]
The readonly - attribute of form-fields should probably also be get attributed **disabled**
as readonly fields are still submitted in the form wich is not the case with disabled fields.
compare: [readonly](http://www.w3schools.com/tags/att_input_readonly.asp) vs [disabled](http://www.w3schools.com/TAgs/att_input_disabled.asp)

aber das schein wohl schon die Runde gemacht zu haben...
#1064
#567
https://github.com/contao-community-alliance/dc-general/issues/67
https://github.com/contao/core/issues/7282

**Comment by zonky2** [comment]
pls use the issue template... and check

- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [ ] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue
