### ISSUE TITLE
PHP7 compatibility String/StringUtil in ItemList.php#L775 

### ISSUE THREAD

**Issue by HenryLamorski** [MetaModels/core#1079]
useage of deprecated `\Contao\String` instead of `\Contao\StringUtil` in https://github.com/MetaModels/core/blob/master/src/MetaModels/ItemList.php#L775

**Comment by zonky2** [comment]
its fixed https://github.com/JeremieConstant/core/commit/7368ff53af6b4bcb151ac2c2a3e75176bfc9309a
