### ISSUE TITLE
Provide new bundle

### ISSUE THREAD

**Issue by richardhj** [MetaModels/core#1088]
I would appreciate a new bundle. This bundle completes the bundles `attribute_translated` and `attribute_nontranslated` and includes the attributes
```json
"require": {
    "metamodels/attribute_combinedvalues": "~2.0",
    "metamodels/attribute_country": "~2.0",
    "metamodels/attribute_decimal": "~2.0",
    "metamodels/attribute_langcode": "~2.0",
    "metamodels/attribute_numeric": "~2.0",
    "metamodels/attribute_timestamp": "~2.0"
  }
```
(copy/paste from the `bundle_attributes`

Use case: Create a MetaModels installation with all the attributes but without the translated attributes.

**Comment by discordier** [comment]
I wondered lately if we should really encourage the usage of the bundles.

We should debate this.

I for myself nowadays only install the attributes I really need to omit "junk" in the installation.
This also greatly increases composer resolving time.

**Comment by zonky2** [comment]
I advice at the manual "use bundle_all" ... any user have problems to install the packages separatly e.g. https://community.contao.org/de/showthread.php?65698-Filter-Attribute-werden-nicht-angezeigt&p=432459&viewfull=1#post432459

**Comment by zonky2** [comment]
für 2.0 bleibt alles so wie es ist...
