### ISSUE TITLE
"Simple lookup" does not resolve translated attributes correct

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1092]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   5.6       |                                  |
| Contao version:                     |   3.5.24       |                                  |
| MetaModels version:                 |   2.0.0       |                                  |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      |     a15     |                                  |
| DCG version:                        |    b39      |                                  |

## Issue description

https://github.com/MetaModels/attribute_translatedalias/issues/9

## Steps to reproduce

https://github.com/MetaModels/attribute_translatedalias/issues/9

## Solution
add function like getDataFor https://github.com/MetaModels/core/blob/d47c3a638b1e6b0f3730565be582b7c6f5a2a1d2/src/MetaModels/Attribute/TranslatedReference.php#L150 in getFilterOptions
https://github.com/MetaModels/core/blob/d47c3a638b1e6b0f3730565be582b7c6f5a2a1d2/src/MetaModels/Attribute/TranslatedReference.php#L277-L294

**Comment by zonky2** [comment]
machen...

**Comment by zonky2** [comment]
any questions...
two MMs, both multilanguage and a relation per select

I found at `SimpleLookup.php` the Option `all_langs`
https://github.com/MetaModels/core/blob/master/src/MetaModels/Filter/Setting/SimpleLookup.php#L149

this option can bei set if we use filter rule `simplelookup_translated`
https://github.com/MetaModels/core/blob/master/contao/dca/tl_metamodel_filtersetting.php#L278
but I don´t found this rule...

and if the relation to a multilang MM a "normal select" is the instance of this attribute **not** `ITranslated`
see at https://github.com/MetaModels/core/blob/master/src/MetaModels/Filter/Rules/SearchAttribute.php#L76

**Comment by discordier** [comment]
The `all_langs` seems to have been not completely implemented in 09d5c2ea2a6ea534f4d3d0892e24c24e7b132954. I think we should finish the implementation by attaching a visibility condition to this field which wil match when the selected attribute implements `ITranslated`

**Comment by amenk** [comment]
Hack: adding english in \MetaModels\Attribute\TranslatedReference::searchForInLanguages 

    public function searchForInLanguages($strPattern, $arrLanguages = array())
    {
	    $arrLanguages[] = 'en';

-> now it finds the english record as well

**Comment by amenk** [comment]
What is  the problem of my hack?

**Comment by zonky2** [comment]
small workaround for translated attributes like translated_alias - add at DB `tl_metamodel_filtersetting` > `all_lang` = 1 and simple lookup found your item per fallback ... the FE filter per "static parameter" doesn´t work!

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/core/pull/1204

![screenshot_076](https://user-images.githubusercontent.com/1045318/37181125-0a61d7ba-232c-11e8-93d7-e1717e02276f.jpg)
