### ISSUE TITLE
Keine Systemnachricht mehr beim Löschen von Dateien in der Dateiverwaltung bei aktivierter MetaModels-Extension

### ISSUE THREAD

**Issue by Floxn** [MetaModels/core#1093]
| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |      5.6 cgi    |                                  |
| Contao version:                     |    3.5.24      |                                  |
| MetaModels version:                 |     2.0.0     |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |     a14     |                                  |
| DCG version:                        |    b38      |                                  |

## Issue description

In der Dateiverwaltung fehlt der Inhalt der Systemnachrichten die zum Bestätigen des Löschvorgangs erscheint.
Sobald MM in den Einstellung inaktiv gesetzt wird, erscheint beim Löschen wieder der Inhalt.
Getestet bei Chrome, Firefox, Safari auf Mac

## Screenshots
mit aktivem MM
![bildschirmfoto 2017-03-10 um 13 23 42](https://cloud.githubusercontent.com/assets/15326334/23795350/72622faa-0595-11e7-81b6-696dcf59c16b.jpg)
inaktives MM
![bildschirmfoto 2017-03-10 um 13 24 06](https://cloud.githubusercontent.com/assets/15326334/23795349/72619a40-0595-11e7-871e-7db9d3aec732.jpg)

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Floxn could you please have a final look at this and tell if your issue has been resolved?

**Comment by Floxn** [comment]
Sorry, I was not in the office for one week.
The fix works for me in two different installations.

Thanks for all!
