### ISSUE TITLE
new legend at rendering for frontend

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1094]
any "newbies" select a filter to filter the backend list...

may be its better to select this for frontend

![shot329](https://cloud.githubusercontent.com/assets/1045318/23795771/8c3f1c7e-0597-11e7-82ea-cb7606d90741.jpg)

**Comment by discordier** [comment]
You really want to add a subpalette there just for displaying the jumpTo page?
I will end up clicking that checkbox almost always just to set the jumpTo page then...

What about adding a legend instead of a subpalette checkbox instead?

**Comment by zonky2** [comment]
sorry "legend" is the keyword

**Comment by zonky2** [comment]
siehe https://community.contao.org/de/showthread.php?65999-SQL-Backend-Filter-will-nicht

**Comment by zonky2** [comment]
it`s "oversized"
