### ISSUE TITLE
new button "generate aliases" like Contao core as service

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1095]
new button "generate aliases" like Contao core as service

**Comment by discordier** [comment]
More details

**Comment by zonky2** [comment]
e.g. I have updated the composition to generate the alias values...

before <attr-1>-<attr-2>
after <attr-2>-<attr-3>

at this time I must open every item and save this - may be, in future times we can work with overrideAll/editAll

Contao have a button to generate all aliasses - I think it´s a good idea for MM ...

**Comment by discordier** [comment]
Said button is in the "edit multiple" area and hence applies to the same feature set.

Let alone, which alias do you want to regenerate? we could have a multitude of alias attributes, adding a button for each one will be overkill. :)

**Comment by zonky2** [comment]
Contao have
![shot330](https://cloud.githubusercontent.com/assets/1045318/23813580/ca9a80a6-05df-11e7-8c33-3697ba7d1053.jpg)

and yes: override all aliasses (if the checkbox "Neuerstellung des Alias erzwingen." on)

**Comment by discordier** [comment]
I know that button, I stated above where it is:
> Said button is in the "edit multiple" area [...]

Hence the statement stands, all aliases is maybe really overkill...

**Comment by zonky2** [comment]
implement per overrideAll

**Comment by baumannsven** [comment]
@zonky2 I think this must implement in the alias attribute.
