### ISSUE TITLE
API: add getMetaModel() to items interface IItems

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1100]
it´s possible to retrive the MetaModels per item - if the count of items zero, it´s not possible to ask the MetaModels and we should add this at IItems

**Comment by richardhj** [comment]
As it is an interface change and it would break semantic versioning and the correct milestone would be 2.0.0.
As I just checked, the `Items` collection does not require that the every `Item` belongs to the same MetaModel (see https://github.com/MetaModels/core/blob/2.0.0-alpha14/src/MetaModels/Items.php#L43-L51). Am I right? If so, there might be multiple MetaModel instances belonging the the `Items` collection.

**Comment by richardhj** [comment]
Is there a reasonable use case? Don't see so at first sight. `Items` is just a wrapper class, to enable iterating trough items.

**Comment by zonky2** [comment]
use case e.g. https://community.contao.org/de/showthread.php?66171-TableName-des-MM-im-Frontend-zur-Verf%C3%BCgung&p=436153&viewfull=1#post436153

```
$strTableName = $this->items->getItem()->getMetaModel()->getTableName();
```
if getItem() zero we have a error...

**Comment by richardhj** [comment]
> I think, every item of items have the same MetaModel - or not?
The code says: no
(Meaning it can not be assumed. The collection constructor must be adapted otherwise.)

**Comment by zonky2** [comment]
@discordier what do you mean...

**Comment by discordier** [comment]
IMO this is a breaking change as in #1087.
However, we have had to adjust some interfaces during the beta phase already (in DCG) and therefore we might squeeze this in also.
Yet I'd rather add the MetaModel name to the list template then rather than adding this new method which will be of no use usually.
In the end, it is just a convenience wrapper collection, as @richardhj has pointed out.

**Comment by richardhj** [comment]
Please add "up for discussion" for the point whether we should force an `IItems` collection belonging to one `MetaModel` instance.

**Comment by zonky2** [comment]
closed - see https://github.com/MetaModels/core/issues/1100#issuecomment-289375963
