### ISSUE TITLE
FE-Filter of MM-Select-Attributes returns no values when the option "Remaining values only" (only possible) is checked

### ISSUE THREAD

**Issue by davidmaack** [MetaModels/core#1101]
## Issue description

When using an FE-Filter on an select attribute which uses another MM to recieve its values, the open "only possible" will results in a filter with no filter options at all.

## Steps to reproduce

1. Configute a select attribute, using a second MM as the source table
2. Config a FE-filter for this attribute
3. Use the "Remaining values only" (only possible) options.

## Problem
When getting the filter options, the MM-Select builds an filter for the Source-MM. When the "only possible" is active, the id list of the active MM will be megred with the id of the attibute, resulting in no possible matches: https://github.com/MetaModels/attribute_select/blob/master/src/MetaModels/Attribute/Select/MetaModelSelect.php#L481

## Solution
Instead of creating a new statici id list, the existing method buildFilterRulesForUsedOnly sould be used, as it can allready handle the ids of the given items

So instead of
```php
        // Add some more filter rules.
        if ($usedOnly) {
            $this->buildFilterRulesForUsedOnly($filter, $idList ?: array());
        } elseif ($idList && is_array($idList)) {
            $filter->addFilterRule(new StaticIdList($idList));
        }
```

should be
```php// Add some more filter rules.
        if ($usedOnly || ($idList && is_array($idList))) {
            $this->buildFilterRulesForUsedOnly($filter, $idList ?: array());
        }
```

If someone can confim this, I would cerate an PR. And the Tags might have the same problem, but I haven´t checked that yet

**Comment by zonky2** [comment]
@discordier what do you mean..?

**Comment by zonky2** [comment]
it´s the same reason on https://github.com/MetaModels/core/issues/636

**Comment by zonky2** [comment]
this fixed https://github.com/MetaModels/core/issues/636
