### ISSUE TITLE
Fehlermeldung bei Integration als Kind-Tabelle (von tl_member)

### ISSUE THREAD

**Issue by dirktietze** [MetaModels/core#1104]
PHP-Version: 5.6
Contao-Version: 3.5.25
MM per Composer oder NightlyBuild: Composer
MM Version (core): dev-hotfix/alpha-15
DC-General Version: 2.0.0-beta38
spezielle Hotfix-Pakete eingespielt?: contao-frontend-editing dev-master (412516db) ? 2.0.x-de

Bei Zuweisung der Eingabemaske als Kind-Tabelle erscheint beim anschliessenden Aufruf (Klick) auf die Eingabemaske in der Eltern-Tabelle (z.B. tl_member) die Fehlermeldung:

```
Warning: Invalid argument supplied for foreach() in composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php on line 315
```

Das Anlegen einer unabhängigen Eingabemaske funktioniert sowie als Kind Tabelle, wenn das Elternelement auch ein MetaModel ist.

**Comment by zonky2** [comment]
sofern es am FEE liegt bitte bei https://github.com/MetaModels/contao-frontend-editing/issues einfügen
