### ISSUE TITLE
Filtern von Attributen (Einfache Abfrage) muss zwingend im Frontend-Modul gesetzt werden

### ISSUE THREAD

**Issue by jgrotstabel** [MetaModels/core#1109]
In der Ausgangsbasis (MetaModels Alpha 14 mit DC General 2.0.0 Beta 38) reichte es einen Filter „Einfache Abfrage“ im MetaModel unter Filtersets zu definieren und es griff somit im Frontend.

Nach Update auf (MetaModels Alpha 15 (Custom Nightly von @baumann.sven) mit DC General 2.0.0 Beta 39) muss nun zusätzlich im Modul (MetaModelListe) diese Einstellung beim Punkt Filterparameter überschreiben gesetzt werden, sonst greift die „Einfache Abfrage“ nicht.

Das macht meiner Meinung nach keinen Sinn. Entweder entfernt man dann die Vorbelegung unter den Filtereinstellungen und muss das zwingend im Modul machen. Oder der Standartfilter geht auch wird aber bei Anwendung vom Modul überschrieben.

**Comment by zonky2** [comment]
ich habe das versucht an zwei Installationen nachzuvollziehen
"Alt" DCG b31 und MMcore a9 und
"Aktuell" DCG b39 und MMcore a15 
mit gleichem Ergebnis:

* bei einfacher Abfrage reagiert eine Liste auf den GET-Wert je nach Einstellung per "auto_item" oder "Attribut-Spaltenname" und gibt das entsprechende Item aus
* Filterwidget wird im FE erst angezeigt, wenn Checkbox "Statischer Parameter" gesetzt ist
* bei Standardeinstellungen und keinem Filterwert wird in der MM-Liste kein Wert ausgegeben
* Werte werden bei keinem Filterwert ausgegeben, wenn "Leeren Wert erlauben" gesetzt ist
* ein Standardwert für die Filterung kann gesetzt werden, wenn Checkbox "Statischer Parameter" gesetzt ist und eine Auswahl in Filter-Regel oder in MM-Liste (Modul/CE) gewählt ist - der Wert kann überschrieben werden, wenn Checkbox "GET-Parameter verwenden" gesetzt

... also m.E. funktioniert alles i.O.

**Comment by jgrotstabel** [comment]
> bei einfacher Abfrage reagiert eine Liste auf den GET-Wert je nach Einstellung per "auto_item" oder "Attribut-Spaltenname" und gibt das entsprechende Item aus

Also in der Filtereinstellung hatte ich bei URL-Parameter nichts eingetragen. Wenn ich dort auto_item benutze funktioniert die Liste dann auch wenn ich im Modul nichts unter Filterparameter überschreiben eintrage. Ist das denn wirklich so selbsterklärend? Vielleicht fehlt eine kleine Info im Modul, wann diese Werte zu setzen sind?

> ein Standardwert für die Filterung kann gesetzt werden, wenn Checkbox "Statischer Parameter" gesetzt ist und eine Auswahl in Filter-Regel oder in MM-Liste (Modul/CE) gewählt ist - der Wert kann überschrieben werden, wenn Checkbox "GET-Parameter verwenden" gesetzt

Ok, dieser Punkt war mir auch nicht ganz klar, vielleicht auch hier eine kleine Erklärung im Modul?

**Comment by zonky2** [comment]
nach Besprechung per Telefon: close...
