### ISSUE TITLE
Minimodel & Transifex

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1110]
it´s not possible to found the text

```
$GLOBALS['TL_LANG']['tl_metamodel_dcasetting']['addAll_activate']            = 'Add new settings enabled.';
```

 at https://www.transifex.com/metamodels/metamodels/translate/#de/core-tl_metamodel_dcasetting??

**Comment by discordier** [comment]
It will become available as soon as we have a properly named `2.0.0-alpha16` branch.
Currently it is not available as the branch name is `alpha15`
