### ISSUE TITLE
Checkbox Filter zeigt keine Checkbox an

### ISSUE THREAD

**Issue by Shania567** [MetaModels/core#1111]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------
| PHP version:                        |   7.0       |                                  |
| Contao version:                     |   3.5.24       |                                  |
| MetaModels version:                 |    2.0.0 dev-hotfix/alpha-15     |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |    dc-general beta39      |                                  |

## Issue description

(Describe the problem you are having)
Keine Anzeige des Filters bei Checkbox Filtern (Feldern) im Frontend

## Steps to reproduce

1. Metamodel mit einem Checkbox Attribut anlegen (bei mir Liste von Volieren, die verschiedene Dinge haben oder auch nicht, - im Beipsiel eine Außenfütterungsmöglichkeit)
2. Liste im Frontend anzeigen lassen (ich nutze ein Inhaltselement), Filterset zuordne
3. Inhaltselement für den Filter anlegen und im Filterset ein Checkboxfeld wählen
4. Der Filter wird im Frontend nicht angezeigt. Der Websitebesucher kann also die Liste nicht nach dem Checkboxfeld filtern.

Auf den Bildern erkennt man, wie der Filter bei mir eingerichtet ist.
![checkbox_filter_01](https://cloud.githubusercontent.com/assets/27729619/25136107/57861a60-2454-11e7-9387-7ccbd94c3967.JPG)
![checkbox_filter_02](https://cloud.githubusercontent.com/assets/27729619/25136104/577f4af0-2454-11e7-9de1-4c93e829a713.JPG)
![inhaltselement_01](https://cloud.githubusercontent.com/assets/27729619/25136105/5781cfbe-2454-11e7-9154-6e7a5ba9df9b.JPG)

Ich habe mehrere MM in meiner Umgebung und der Filter funktioniert in keinem der Filtersets, Alle anderen funktionieren jedoch.

Hier ist noch der Beitrag zu dem Problem im Forum:
https://community.contao.org/de/showthread.php?51270-Checkbox-Filter-zeigt-keine-Checkbox-an&p=438085&viewfull=1#post438085

**Comment by zonky2** [comment]
look at https://github.com/MetaModels/filter_checkbox/issues/7
