### ISSUE TITLE
alias input field and combined-values field as readonly if set option "Force regenerating"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1126]
alias input field and combined-values field as readonly if set option "Force regenerating" ?

**Comment by richardhj** [comment]
Sounds reasonable.

**Comment by zonky2** [comment]
we can do this...

[MM-call 30.05.2017]

**Comment by zonky2** [comment]
PR #1171

**Comment by baumannsven** [comment]
Merged in 49dc3b916514e8691287622bee0a972a0cea4ae7
