### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#1128]
We have missed one String call. See: 

https://github.com/MetaModels/core/blob/master/src/MetaModels/ItemList.php#L775

**Comment by zonky2** [comment]
we collect all PHP7 issues at https://github.com/MetaModels/core/issues/988

**Comment by zonky2** [comment]
https://github.com/MetaModels/core/blob/bd9e35909f522ba461a8ea96f357679a52b2fad9/src/MetaModels/ItemList.php#L743
