### ISSUE TITLE
unvollständiges Löschen in tl_metamodel_tag_relation

### ISSUE THREAD

**Issue by wortberge** [MetaModels/core#1130]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 5.6.28 and 7.0.13         |                                  |
| Contao version:                     |  3.5.24        |                                  |
| MetaModels version:                 |    bundle_all 2.0.0      |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |     attribute_levensthein     |                                  |
| DCG version:                        |    2.0.0-beta38      |                                  |

## Issue description

Wenn Items eines Metamodels gelöscht werden, obwohl sie noch in einem anderen als Tags referenziert sind, verbleiben die Einträge in der tl_metamodel_tag_relation

Im Folge werden im FE Tags ohne Text ausgegeben und im BE kommt es bei Bearbeitung des betroffenen Datensatzes zur Fehlermeldung (siehe Screenshot) 

## Steps to reproduce

1. [First Step]
MM für Tags anlegen (z.B.Abteilungen)
Attribute: translatedtext (name), translatedalias(alias), translatedtext(description)
2. [Second Step]
referenzierendes MM anlegen (z.B. Mitarbeiter)
Abteilungen als Attribut Mehrfachauswahl einbinden 
3. [Third Step]
Items in Mitarbeitern anlegen und Abteilungen zuweisen
4. [Fourth Step]
Abteilung löschen

## Screenshots

![bildschirmfoto 2017-05-17 um 10 00 13](https://cloud.githubusercontent.com/assets/4026612/26144322/a4a68ece-3ae8-11e7-9cec-e6e57b1a68d5.png)

![bildschirmfoto 2017-05-17 um 10 15 32](https://cloud.githubusercontent.com/assets/4026612/26144667/0c5dca22-3aea-11e7-9959-fd698fe254b9.png)

**Comment by zonky2** [comment]
Hotfix https://github.com/MetaModels/attribute_tags/pull/64

**Comment by zonky2** [comment]
gefixt https://github.com/MetaModels/attribute_tags/pull/64
