### ISSUE TITLE
show id, pid, tstamp, sorting at details of item

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1131]
show id (additional to view in headline) , pid, tstamp, sorting at details of item ... may be as "system informations"

**Comment by zonky2** [comment]
we can do this...

[MM-core 30.05.2017]

**Comment by discordier** [comment]
Ref #581 and create virtual attributes.

**Comment by zonky2** [comment]
Add defaultvalues here https://github.com/contao-community-alliance/dc-general/blob/61ffe2081323104b38ad951b2fbb3cb4b0f1a025/src/Contao/View/Contao2BackendView/ActionHandler/ShowHandler.php#L158

**Comment by zonky2** [comment]
Fixed https://github.com/contao-community-alliance/dc-general/pull/597
