### ISSUE TITLE
set system row "sorting" with current number at create new item also at not manual sorting

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1132]
we should set the row "sorting" from default to "current" sorting number at we create a new item - we should set also if a not manual sorting active...

the reason is: if we create any items without a active sorting or a alphabetical sorting become all items the sorting value `0` - if we change to manual sorting and we created the items at "correct" order looks like as the right sorting (but the sorting is sero)... to set the correct sorting number we can change the row per database tool or we move every item "one down and one up"

**Comment by discordier** [comment]
Sorting should get populated at https://github.com/contao-community-alliance/dc-general/blob/11597752073c725214ae4fd3b899402285821863/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php#L593

**Comment by zonky2** [comment]
* if manual sorting activated, the new item have a number for sorting
* if we have items with sorting = 0 and add a new, have only the new item a sorting number (128)
* if we move some item, all items get a new sorting number

may be it´s a good idea to add a event to set sorting numer at all items it´s manual sorting defined and setz sorting number at 0 if we delete the manual sorting...

**Comment by zonky2** [comment]
I has checked the current manual sorting:
* if manual sorting activated, new item save the (first) sorting number
* if you activated sorting after the input of your data, it´s to sufficent to drag&drop one item... all other items keep the right sorting number
