### ISSUE TITLE
this is better to be done with a new event to sort conditions into their parents as we might have other classes in the future

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1134]
TODO: this is better to be done with a new event to sort conditions into their parents as we might have other classes in the future.

https://github.com/MetaModels/core/blob/8e61ba89a336e59996f5a5245370c2b8476efea5/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php#L337

**Comment by discordier** [comment]
Has been implemented in MM 2.1 via `MetaModels\Events\DefaultPropertyConditionCreator` and rewritten condition handling.
