### ISSUE TITLE
in here all language strings and icons are related to filters?

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1136]
FIXME: in here all language strings and icons are related to filters?

https://github.com/MetaModels/core/blob/8e61ba89a336e59996f5a5245370c2b8476efea5/src/MetaModels/DcGeneral/Events/Table/InputScreens/Subscriber.php#L127

**Comment by discordier** [comment]
Implemented in 2.1, won't fix for 2.0 as the translator is not available here.
