### ISSUE TITLE
this way of generating jump to urls is not as elegant as it could be we might want to refactor it

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1145]
@todo this way of generating jump to urls is not as elegant as it could be we might want to refactor it.

https://github.com/MetaModels/core/blob/8e61ba89a336e59996f5a5245370c2b8476efea5/src/MetaModels/Filter/Setting/ICollection.php#L78

**Comment by discordier** [comment]
As stated in a92063b, we will not alter the interfaces for V2.0 anymore.
