### ISSUE TITLE
 we might want to change the name $arrFilterUrl to $arrFilterParams or something like that

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1146]
@todo: we might want to change the name $arrFilterUrl to $arrFilterParams or something like that.

https://github.com/MetaModels/core/blob/8e61ba89a336e59996f5a5245370c2b8476efea5/src/MetaModels/Filter/Setting/ISimple.php#L56

**Comment by discordier** [comment]
As stated in a92063b8848950cb13addacf615f1e7e8d50094a, we will not alter the interfaces for V2.0 anymore.
