### ISSUE TITLE
Cache template path in Template::getTemplate()

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1149]
FIXME: this could be cached and save two calls to file_exists() in \TemplateLoader::getPath().

https://github.com/MetaModels/core/blob/8e61ba89a336e59996f5a5245370c2b8476efea5/src/MetaModels/Render/Template.php#L252

**Comment by discordier** [comment]
this could save two calls to file_exists() in \TemplateLoader::getPath().

**Comment by zonky2** [comment]
fixed in MM 2.2
