### ISSUE TITLE
Fehler bei Anzeige - BE Tabellenformat wenn Varianten aktiviert

### ISSUE THREAD

**Issue by speedweb** [MetaModels/core#1156]
I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  5.6.30  |                                  |
| Contao version:                     |  3.5.27  |  LTS                |
| MetaModels version:                 | 2.0.0 | bundle_all      |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |          |                                  |

## Issue description
Sobald "Varianten" aktiviert ist wird im Backend wenn die Tabellarische Ansicht aktiviert ist
nur noch der erste Eintrag des Datensatzes angezeigt.

## Steps to reproduce
um das ganze zu testen habe ich "mein erstes MetaModel" nach Anleitung nachgebaut.

## Screenshots
https://community.contao.org/de/showthread.php?66883-Problem-mit-Anzeige-in-Tabellenform&p=441367&viewfull=1#post441367

**Comment by zonky2** [comment]
Wie soll eine "Einrückung" einer Tabelle realisiert werden? Der Fehler liegt eher darin, dass bei Varianten die Option "Tabelle" nicht aktivierbar sein sollte...

**Comment by speedweb** [comment]
gibt es ein Beispiel mit Varianten und wie diese im Backend sinnvoll angezeigt werden?
Vielleicht habe ich das mit den Varianten falsch verstanden.
Leider habe ich keine weiteren Infos zu den Möglichkeiten mit Varianten gefunden.

**Comment by zonky2** [comment]
was wäre in "Deinem Sinne sinnvoll"...

**Comment by speedweb** [comment]
sinnvoll = Übersichtlich
wäre bei Varianten eine Lösung als Liste welche per CSS angepasst werden kann.
Daten Elternelement Horizontal formatiert (wie bei der Tabellenansicht)
Varianten eingerückt darunter...
Wie werden Varianten bisher Übersichtlich im BE ausgegeben?

**Comment by zonky2** [comment]
mal einige Infos zum Thema "Varianten":
* Varianten haben immer nur **eine** Hierarchieebene, d.h. es gibt nur "Eltern" und nur "Kinder" - also keine "Kinder-Kinder"
* die Attribute eines Items teilen sich bei Varianten in "feste Werte" - die werden nur im jeweiligen Elternelement definiert und automatisch auch in den Kindelementen aktualisiert - und "variable Werte" - die sich in in allen Items "eines Eltern-Kind-Blocks" unterscheiden
* die Anzeige sollte bei den Elternelementen ein [+] haben, sofern Kindelemente vorhanden sind
* Kindelemente **immer** über das Icon "Zauberhut" erstellen
* natürlich kann ein eigenes (BE)CSS über die Render-Einstellungen geladen werden

**Comment by zonky2** [comment]
MM-call 26.09.2017: für eine (HTML)Tabelle mit Einrückungen hatte niemand eine Idee, wie das funktionieren solle - letztendlich werden wir bei aktivieren Varianten (und Hierarchie) die Anzeige als Tabelle abschalten.

Sollte eine spezielle Form der Anzeige gewünscht werden, könnte das ggf. separat beim MM-Team angefragt/beauftragt werden mail@metamodels.me
