### ISSUE TITLE
BE List View: render a pagination menu

### ISSUE THREAD

**Issue by xchs** [MetaModels/core#1159]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  5.6.29        |                                  |
| Contao version:                     | 3.5.27         |                                  |
| MetaModels version:                 |  2.0.0-alpha15        |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |   bundle_all       |                                  |
| DCG version:                        |    2.0.0-beta39      |                                  |

## Issue description

It would be nice if we could have a pagination menu in the BE list view (see e.g. the Contao [`Pagination`](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Pagination.php) class).

## Screenshots

* MetaModels BE list view:

![BE List View](http://fs5.directupload.net/images/170608/wq8jjng7.png)

* BE System Log:

![BE System Log](http://fs5.directupload.net/images/170608/zgrf2exn.png)

**Comment by zonky2** [comment]
this is a part of DCG => https://github.com/contao-community-alliance/dc-general/issues/312
