### ISSUE TITLE
Filter "Einfache Abfrage": keine Werte zum Filtern verfügbar

### ISSUE THREAD

**Issue by LinkingYou** [MetaModels/core#1169]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.0.20        |                                  |
| Contao version:                     |   3.5.28       |                                  |
| MetaModels version:                 |     Latest NightlyBuild     |                                  |
| Installation via composer:          | no |                                 |
| Installed MetaModels packages:      |    no      |                                  |
| DCG version:                        |    2.0.0-beta39      |                                  |

## Issue description

Ein Filter ‚Einfache Abfrage’ erzeugt eine Filterung nach einem Attribut über eine Select-Liste. Gleichzeitig kann ein Standardwert für diese Liste durch Auswahl eines Attribut-Wertes gesetzt werden bzw. – wenn die Option ‚Statischer Parameter’ gesetzt ist - im FE-Modul ein Wert zur Filterung gewählt werden.
Während die Auswahl eines Attributes funktioniert, werden keine Attributs-Werte zum Setzen eines Standard-Wertes angeboten bzw. im FE-Modul bleibt die Select-Liste zur Auswahl eines Filterwertes leer.

Das Problem ist ein PHP7-Kompatibilitätsproblem. Unter PHP5.6 gab es keine Probleme.

In der MetaModels\Attribute\TranslatedReference.php in Zeile 308 steht:

`$arrReturn[$objValue->$arrOptionizer['key']] = $objValue->$arrOptionizer['value'];`

Das muss bei PHP7 wie folgt heißen:

`$arrReturn[$objValue->{$arrOptionizer['key']}] = $objValue->{$arrOptionizer['value']};`

Dokumentiert ist die Änderung des PHP-Verhaltens hier im Abschnitt "Changes to the handling of indirect variables, properties, and methods":
http://php.net/manual/de/migration70.incompatible.php

| Expression|PHP 5 interpretation|PHP 7 interpretation |
|------------|------|------|
|$foo->$bar['baz']|$foo->{$bar['baz']}|($foo->$bar)['baz']|

**Comment by zonky2** [comment]
@LinkingYou kannst Du einen PR machen?

**Comment by LinkingYou** [comment]
Gerne. Ist erledigt.

**Comment by discordier** [comment]
Closing in favor of #1170
