### ISSUE TITLE
add html node at action array

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1173]
add html node at action array e.g. to add form widgets or other html snippets

```
	<div class="actions">
		<?php foreach($arrItem['actions'] as $action): ?>
		<?php if (!empty($action['html'])): ?>
			<?= $action['html'] ?>
		<?php else: ?>
			<a href="<?= $action['href']; ?>"<?php if ($action['class']): ?> class="<?= $action['class']; ?>"<?php endif; ?><?php if ($action['title']): ?> title="<?= $action['title']; ?>"<?php endif; ?><?= $action['attribute']; ?>><?= $action['label']; ?></a>
		<?php endif; ?>
		<?php endforeach; ?>
```

**Comment by zonky2** [comment]
allet jut

**Comment by richardhj** [comment]
as @zonky2 said. With a new template "action button"

**Comment by discordier** [comment]
`metamodels_action_button`? or will this collide with the lister templates?
Should we go for `mm_actionbutton` prefix like we do with the attributes?

**Comment by richardhj** [comment]
Another thought that must be thought of:
What's about the `.text` templates?
Inserting `html` in the `text` template is contradictory. Calling the node "`raw`" will not improve this.
Just now, I come to the conclusion, to introduce the nodes `raw_html` and `raw_text` instead of `html`.

**Comment by zonky2** [comment]
https://github.com/MetaModels/core/pull/1179
