### ISSUE TITLE
Apply $GLOBALS['TL_CONFIG']['maxResultsPerPage'] in backend listings

### ISSUE THREAD

**Issue by HaraldHubinger** [MetaModels/core#1192]
## Checklist before I submit this issue report

I confirm that:
- [x ] I have tested this with the latest version available
- [x ] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [ x] I have checked the Contao community forums for references https://community.contao.org/
- [ x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    5.6 and 7.0      |                                  |
| Contao version:                     |     3.5.28     |                                  |
| MetaModels version:                 |      2.2.0    |                                  |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |          |                                  |

## Issue description
$GLOBALS['TL_CONFIG']['maxResultsPerPage'] is not applied in backend lists.

The Metamodel at issue contains ~150.000 items.
If Backend-User selects the filterAll-Option in Backend-List the configured value of maxResultsPerPage is not used, so that maximum PHP execution time can be exceeded.

If that is not the intended behaviour it would be useful to apply this setting also to MM-Backend-Lists.

## Steps to reproduce
Create a Metamodel with ~150.000 items. Define a backend listing. Select the filterAll-Option from Filter.

## Describe the behaviour of the application
After exceeding max_execution_time it displays a Server Error (even on a fast machine and minutes of time).

## Describe the expected behaviour of the application
Apply maxResultsPerPage from Settings/localconfig.php

**Comment by zonky2** [comment]
can you open a new issue at DCG https://github.com/contao-community-alliance/dc-general

**Comment by HaraldHubinger** [comment]
Thanks, issue now filed under https://github.com/contao-community-alliance/dc-general/issues/361.

**Comment by zonky2** [comment]
thx!

**Comment by HaraldHubinger** [comment]
Danke gleichfalls!

2017-09-14 12:55 GMT+02:00 zonky2 <notifications@github.com>:
