### ISSUE TITLE
Error if you add only one attribute at input mask

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1197]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |          |                                  |
| Contao version:                     |     3.5.28     |                                  |
| MetaModels version:                 |    a16      |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |     b40     |                                  |

## Issue description

Error if you add only one attribute at input mask

## Steps to reproduce

1. Input mask
2. Add one new attribute with button "new"
3. select "Attribute" at select field ... and now crashes...

## Describe the behaviour of the application

```
Fatal error: Call to a member function get() on null in \composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Events\Table\InputScreens\Subscriber.php on line 403
```

## Workaround

use the button "add all"

**Comment by MacKP** [comment]
Anmerkung: ist bei Contao 4 auch so ;-)

**Comment by zonky2** [comment]
fixed
