### ISSUE TITLE
error at permission for non-admins if tags related to tl_page

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1200]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   5.6       |                                  |
| Contao version:                     |  3.5        |                                  |
| MetaModels version:                 |    a16      |                                  |
| Installation via composer:          | (yes/no) |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |    b40      |                                  |

## Issue description

Contao send error message...

## Steps to reproduce

1. attribute tags with tl_page as related table
2. set permissions for BE users e.g. editors
3. if you open the input mask, contao send a error message and logfile `Details:  Not enough permissions to edit page ID mm_gut_employees::1 or paste after/into page ID Funktion:  tl_page::checkPermission`

as first workaround this fix https://github.com/contao-community-alliance/dc-general/tree/hotfix/core_table_permission

**Comment by zonky2** [comment]
first hotfix https://github.com/contao-community-alliance/dc-general/pull/364

**Comment by discordier** [comment]
Duplicate of #708?

**Comment by zonky2** [comment]
sieht so aus...

**Comment by zonky2** [comment]
Bug besteht weiterhin (MM 2.2) https://github.com/MetaModels/core/issues/708#issuecomment-847032776

**Comment by zonky2** [comment]
gefixt - siehe https://github.com/MetaModels/core/issues/708#issuecomment-847032776
