### ISSUE TITLE
Custom Template not found in template subfolder

### ISSUE THREAD

**Issue by Olli** [MetaModels/core#1202]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [ ] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 7.0         |                                  |
| Contao version:                     |  3.5.28        |                                  |
| MetaModels version:                 | 2.0.0alpha-15 also alpha-16         |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |  core, bundle_all        |                                  |
| DCG version:                        |   ^3.5.5       |                                  |

## Issue description

I have a custom template for rendering images in backend listing of metamodel. MM can't find the template if it's in a subfolder in the templates directory and the subfolder is assigned to a layout.
I have to copy the templatefile into the main templates folder.

## Steps to reproduce

1. make a custom template maybe of mm_attr_file
2. make a subfolder in templates and assign it to an layout
3. assign the custom template to a particular attribute in a backend renderer of a metamodel 
4. view the metamodel in the backend 

## Describe the behaviour of the application

I got 
```
Template mm_attr_file_gw not found (it is maybe within a unreachable theme folder?).
```

## Describe the expected behaviour of the application

Template should be found and display the attribute correctly

## Screenshots

How it's used to be in the attributes configuration:
![screenshot--2017-10-05-13-18-04](https://user-images.githubusercontent.com/1754/31224837-ca2b093a-a9cf-11e7-883e-ae89160d3361.png)

How it's used to be in the backend view of the metamodel:
![screenshot-2017-10-05-13-08-07](https://user-images.githubusercontent.com/1754/31224840-cd969fd0-a9cf-11e7-961e-b32da5b9eb24.png)

This is how it's actually displayed:
![screenshot-2017-10-05-13-07-11](https://user-images.githubusercontent.com/1754/31224842-cf894dce-a9cf-11e7-9b45-416129e6cc8c.png)

**Comment by zonky2** [comment]
move your BE template to the template root folder

**Comment by Olli** [comment]
That's what I've done (as described). What if I want to export the whole layout ?
This behavior is unexpected because the rest of contao doesn't work like "move it to the root".

**Comment by zonky2** [comment]
> This behavior is unexpected because the rest of contao doesn't work like "move it to the root".

The problem is Contao and not MetaModels - all templates independent of a theme for the backend(!) and cannot be found, because in BE there is a reference to the theme and thus also not to the theme template folder...
