### ISSUE TITLE
we lost $this->details; at 2.0.0-alpha16

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1206]
`$this->details` is not more set at 2.0.0-alpha16

https://github.com/MetaModels/core/commit/1cc774686c238ffeb5a0862112fb4a96a5eab36a#diff-a0d42d8bc3e6bc2cfcdf21c89b1429d5L772

**Comment by richardhj** [comment]
Hotfix kommt

**Comment by richardhj** [comment]
Closing in favor of #1207
