### ISSUE TITLE
Nightly Build should load Doctrine cache V. 1.2 for PHP ~5.5

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1210]
Nightly Build should load Doctrine cache V. 1.2 for PHP ~5.5

see https://community.contao.org/de/showthread.php?69062-FM-nach-manueller-Installation-von-MM&p=459116&viewfull=1#post459116

**Comment by discordier** [comment]
Platform for nightly packages has been restored to PHP 5.4.

PS: We should retire the nightlies some time in the near future, the won't be available for Contao 4 anyway.

**Comment by zonky2** [comment]
we kill it with the end off MM 2.0 support
