### ISSUE TITLE
Change license key to "LGPL-3.0-or-later"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1212]
Change at composer.json and all file header

```diff
-  "license": "LGPL-3.0+",
+  "license": "LGPL-3.0-or-later",
```

List at https://github.com/MetaModels/core/issues/1215

**Comment by tim-bec** [comment]
@zonky2 sind `phpcq` sowie test laufen lassen notwendig? Falls nicht, würde ich für alle PR-s erstellen.

**Comment by zonky2** [comment]
more at https://github.com/MetaModels/core/issues/1215
