### ISSUE TITLE
Grouping/Sorting lost standard if we add a new Grouping/Sorting

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1213]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [ ] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   5.6       |                                  |
| Contao version:                     |     3.3.33     |                                  |
| MetaModels version:                 |   core a17       |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |    b41      |                                  |

**Comment by zonky2** [comment]
Bug at https://github.com/contao-community-alliance/dc-general/pull/321

**Comment by discordier** [comment]
Please open a new ticket in DCG for this

**Comment by zonky2** [comment]
fixed https://github.com/contao-community-alliance/dc-general/pull/402
