### ISSUE TITLE
Updating: PHP Version, PHPUnit, transfer sql to DCA

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#1215]
Updating:

**.travis.yml - latest PHP version at first!**
```diff 
 php:
+ - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
- - "5.5"
- - "5.4"

```
**delete `travis.php.ini` and add to .travis.yml**
```diff
+before_install:
+  - echo "memory_limit = -1" > travis.php.ini && phpenv config-add travis.php.ini
```

**composer.json**
```diff
-  "license": "LGPL-3.0+",
+  "license": "LGPL-3.0-or-later",

 "require": {
-  "php": ">=5.4",
+  "php": "^5.6 || ^7.0",
```
It could be that we have  ```"php": "^5.6 | ^7.0",``` this is okay, not nice but will work, so we don't need to fix it.

**PHPUnit**
```diff
- class TranslatedTableTextTest extends \PHPUnit_Framework_TestCase
+ class TranslatedTableTextTest extends \PHPUnit\Framework\TestCase

-        $metaModel = $this->getMock(
-            'MetaModels\MetaModel',
-            array(),
-            array(array())
-        );
+        $metaModel = $this
+            ->getMockBuilder('MetaModels\MetaModel')
+            ->setMethods(array())
+            ->setConstructorArgs(array(array()))
+            ->getMock();
```

**transfer sql to DCA**
* delete sql file
* add sql parameter to field declaration

**check the file header**
see https://github.com/MetaModels/core/issues/1150

# List of repositories to apply above tasks to:
- [x] metamodels/core
- [x] metamodels/attribute_alias
- [x] metamodels/attribute_checkbox
- [x] metamodels/attribute_combinedvalues
- [x] metamodels/attribute_country
- [x] metamodels/attribute_decimal
- [x] metamodels/attribute_file
- [x] metamodels/attribute_geodistance
- [x] metamodels/attribute_langcode
- [x] metamodels/attribute_levensthein
- [x] metamodels/attribute_longtext
- [x] metamodels/attribute_numeric
- [x] metamodels/attribute_rating
- [x] metamodels/attribute_select
- [x] metamodels/attribute_tabletext
- [x] metamodels/attribute_tags
- [x] metamodels/attribute_text
- [x] metamodels/attribute_timestamp
- [x] metamodels/attribute_translatedalias
- [x] metamodels/attribute_translatedcheckbox
- [x] metamodels/attribute_translatedcombinedvalues
- [x] metamodels/attribute_translatedfile
- [x] metamodels/attribute_translatedlongtext
- [x] metamodels/attribute_translatedselect
- [x] metamodels/attribute_translatedtabletext
- [x] metamodels/attribute_translatedtags
- [x] metamodels/attribute_translatedtext
- [x] metamodels/attribute_translatedurl
- [x] metamodels/attribute_url
- [x] metamodels/filter_checkbox
- [x] metamodels/filter_fromto
- [x] metamodels/filter_perimetersearch
- [x] metamodels/filter_range
- [x] metamodels/filter_select
- [x] metamodels/filter_tags
- [x] metamodels/filter_text

# TBD:
- [ ] contao-community-alliance/composer-client
- [ ] contao-community-alliance/composer-plugin
- [x] contao-community-alliance/dc-general
- [x] contao-community-alliance/dependency-container
- [x] contao-community-alliance/event-dispatcher
- [x] contao-community-alliance/events-contao-bindings
- [x] contao-community-alliance/meta-palettes
- [x] contao-community-alliance/translator
- [x] contao-community-alliance/url-builder
- [ ] metamodels/bundle_all
- [ ] metamodels/bundle_attributes
- [ ] metamodels/bundle_filter
- [ ] metamodels/bundle_nontranslated
- [ ] metamodels/bundle_translated
- [ ] metamodels/attribute_geoprotection is alpha version R.I.P.

**Comment by stefanheimes** [comment]
Missing elements:

- metamodels/core
  - travis.yml
- metamodels/attribute_decimal
  - travis.yml
  - composer.json
  - PHPUnit
- metamodels/attribute_levensthein
  - travis.yml
  - composer.json
  - PHPUnit
- metamodels/attribute_numeric 
  - composer.json 
- metamodels/attribute_rating
  - travis.php.ini
- metamodels/attribute_timestamp
  - travis.yml
  - composer.json
  - PHPUnit
- metamodels/attribute_translatedtext
  - travis.yml
  - composer.json
  - PHPUnit
- metamodels/attribute_translatedurl
  - travis.yml
  - composer.json
  - PHPUnit
- metamodels/attribute_url
  - travis.yml
- metamodels/bundle_all
  - composer.json
- metamodels/bundle_attributes
  - composer.json
- metamodels/bundle_filter
  - composer.json
- metamodels/bundle_nontranslated
  - composer.json
- metamodels/bundle_translated
  - composer.json
- metamodels/filter_fromto
  - travis.yml
  - composer.json
- metamodels/filter_perimetersearch
  - travis.yml
  - composer.json
- metamodels/filter_range
  - travis.yml
  - composer.json
- metamodels/filter_select
  - travis.yml
  - composer.json
- metamodels/filter_tags
  - travis.php.ini
  - composer.json
- metamodels/filter_text
  - travis.yml

**Comment by discordier** [comment]
I guess this is obsolete now that we have our autofixer.

Closing therefore

**Comment by zonky2** [comment]
thx for autofixer!
