### ISSUE TITLE
Fatal Error on adding new attribute after recent update via composer

### ISSUE THREAD

**Issue by m-r-h-n** [MetaModels/core#1218]
## Checklist before I submit this issue report

I confirm that:
- \[x] I have tested this with the latest version available
- \[x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- \[x] I have checked the Contao community forums for references https://community.contao.org/
- \[x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.1.14     |                                  |
| Contao version:                     |    3.5.33      |                                  |
| MetaModels version:                 |     2.0.0-alpha17     |                                  |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      |     bundle_all     |                                  |
| DCG version:                        |      2.0.0-beta41    |                                  |

## Issue description

Right after adding a new attribute i got this error:
`Fatal error: Uncaught exception Exception with message Query error: Unknown column 'languages__langcode' in 'field list' (SELECT id, id, tstamp, sorting, name, tableName, mode, translated, languages, varsupport, languages__langcode, languages__isfallback FROM tl_metamodel WHERE id = '5') thrown in system/modules/core/library/Contao/Database/Statement.php on line 295`

## Screenshots

![screen](https://user-images.githubusercontent.com/9356986/36899908-75b35576-1e21-11e8-8e86-ccd011f74985.png)

**Comment by zonky2** [comment]
try DCG b42

**Comment by m-r-h-n** [comment]
@zonky2 
Yapp - that fixes it!
Thanx

**Comment by HaraldHubinger** [comment]
Installed dc-general dev-hotfix/beta-42 to fix the described issue. Now opening an already configured Metamodels-Backend-DC to edit data throws 

Fatal error: Declaration of MetaModels\DcGeneral\Data\Driver::save(ContaoCommunityAlliance\DcGeneral\Data\ModelInterface $objItem) must be compatible with ContaoCommunityAlliance\DcGeneral\Data\DataProviderInterface::save(ContaoCommunityAlliance\DcGeneral\Data\ModelInterface $objItem, $timestamp = 0) in /var/www/fb/public_html/composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php on line 53

My configuration is contao/core 3.5.34, metamodels/bundle_all 2.0.0 / DCG dev-hotfix/beta-42/PHP7.0.27-0deb9u1.

**Comment by m-r-h-n** [comment]
Jump to dev-hotfix/2.0.0-alpha18-translation for metamodels/core

**Comment by HaraldHubinger** [comment]
This fixed it. Had to alias the package as 2.0.0 in composer.json (for compatibility with metamodels/notelist).
Thanks for the lightning-fast solution!

**Comment by zonky2** [comment]
@HaraldHubinger: siehe http://metamodels.readthedocs.io/de/latest/manual/install.html#test-von-speziellen-paketen-via-composer

> Da MetaModels eng mit dem DC_General (DCG) verzahnt ist, muss zum Testen häufig auch hier auf eine neuere Version geupdatet werden

=> das gilt natürlich auch umgedreht :D
