### ISSUE TITLE
Saving a translation jumps back to fallback language and overrides it

### ISSUE THREAD

**Issue by m-r-h-n** [MetaModels/core#1222]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.1.15     |                                  |
| Contao version:                     |    3.5.34      |                                  |
| MetaModels version:                 |    dev-hotfix/2.0.0-alpha18-translation      |                                  |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      |   bundle_all       |                                  |
| DCG version:                        |      dev-hotfix/beta-42    |                                  |

## Issue description

While saving a translated item e.g. english it jumps back to fallback language (in my case german) and overrides all translated items with the just saved one (english).
Got a mm with 3 translations and a translatedtext attribute for testing.

**Comment by zonky2** [comment]
tested... only the fallback language is saved

**Comment by zonky2** [comment]
Fix
https://github.com/contao-community-alliance/dc-general/blob/764c356ab5e891e8ff4336248ba8c6d6ec04ed4b/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php#L112
```diff
- $session['ml_support'][$providerName][$modelId] = $currentLanguage;
+ $session['ml_support'][$providerName] = $currentLanguage;
```

**Comment by zonky2** [comment]
fixed https://github.com/contao-community-alliance/dc-general/blob/hotfix/beta-42/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php#L112
