### ISSUE TITLE
sort child table icons in the model commands at model table 'sorting'

### ISSUE THREAD

**Issue by baumannsven** [MetaModels/core#1225]
We have eg two child tables `foo => fooBar, foo => barFoo`.
The table `fooBar has id 2` and `barFoo the id 3`.

The result by the model commands is `edit ... fooBar, barFoo`.

Used the order from the base metamodel table for sort the model commands `edit ... barFoo, fooBar`.

**Comment by zonky2** [comment]
@baumannsven ist das noch aktuell? ganz verstandeen habe ich das Problem noch nicht...

**Comment by zonky2** [comment]
MM 2.2: Die Kind-Tabellen-Icons werden beim Parent in der reihenfolge angezeigt, wie die Reihenfolge der Models in der Modelliste ist-
