### ISSUE TITLE
Unsmooth update because of #1154, #1186

### ISSUE THREAD

**Issue by richardhj** [MetaModels/core#1227]
The "isdefault" checkbox of the input screen and render settings got removed in #1186.

When you made usage of this checkbox prior the removal and you haven't defined any view combinations, you get the following exception trying to access a MetaModel in the backend:

https://github.com/MetaModels/core/blob/2.0.0/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php#L451

`$this->data` is `null` in this case.

## Proposed Solution:
Somewhere, add this logic:
```php
if (null === $this->data) {
    trigger_notice('Did you forget to define the view combinations?');
}
```
Or something similar.

**Comment by zonky2** [comment]
@discordier what do you mean?

**Comment by discordier** [comment]
I did favor an exception over a trigger error and subsequently causing an exception then.

**Comment by zonky2** [comment]
@richardhj pls test it...

**Comment by richardhj** [comment]
I already updated 😬

**Comment by discordier** [comment]
So is the solution ok for you?

**Comment by richardhj** [comment]
U don't want to type hint the `$data` param in the constructor of `InputScreen`? And/or put an exception at this place?

**Comment by discordier** [comment]
If we put the type hint, you will not get the exception for null unless we default it to null which feels wrong as we then suggest that you may pass null and throw then an exception if you do so...

**Comment by richardhj** [comment]
Finally, I'm fine with that solution.
