### ISSUE TITLE
Update travis build add travis_wait for long build time

### ISSUE THREAD

**Issue by baumannsven** [MetaModels/core#1231]
Information about travis_wait can you find here:
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

Updating:

**.travis.yml - Use travis_wait for long build time!**
```diff
-   - travis_retry composer update --prefer-dist --no-interaction
+   - travis_retry travis_wait composer update --prefer-dist --no-interaction
```

# List of repositories to apply above tasks to:
- [ ] metamodels/core
- [ ] metamodels/attribute_alias
- [ ] metamodels/attribute_checkbox
- [ ] metamodels/attribute_combinedvalues
- [ ] metamodels/attribute_country
- [ ] metamodels/attribute_decimal
- [ ] metamodels/attribute_file
- [ ] metamodels/attribute_geoprotection is alpha version R.I.P.
- [x] metamodels/attribute_geodistance
- [ ] metamodels/attribute_langcode
- [ ] metamodels/attribute_levensthein
- [ ] metamodels/attribute_longtext
- [ ] metamodels/attribute_numeric
- [ ] metamodels/attribute_rating
- [ ] metamodels/attribute_select
- [ ] metamodels/attribute_tabletext
- [ ] metamodels/attribute_tags
- [ ] metamodels/attribute_text
- [ ] metamodels/attribute_timestamp
- [ ] metamodels/attribute_translatedalias
- [ ] metamodels/attribute_translatedcheckbox
- [ ] metamodels/attribute_translatedcombinedvalues
- [ ] metamodels/attribute_translatedfile
- [ ] metamodels/attribute_translatedlongtext
- [ ] metamodels/attribute_translatedselect
- [ ] metamodels/attribute_translatedtabletext
- [ ] metamodels/attribute_translatedtags
- [ ] metamodels/attribute_translatedtext
- [ ] metamodels/attribute_translatedurl
- [ ] metamodels/attribute_url
- [ ] metamodels/bundle_all
- [ ] metamodels/bundle_attributes
- [ ] metamodels/bundle_filter
- [ ] metamodels/bundle_nontranslated
- [ ] metamodels/bundle_translated
- [ ] metamodels/filter_checkbox
- [ ] metamodels/filter_fromto
- [ ] metamodels/filter_perimetersearch
- [ ] metamodels/filter_range
- [ ] metamodels/filter_select
- [ ] metamodels/filter_tags
- [ ] metamodels/filter_text

# TBD:
- [ ] contao-community-alliance/composer-client
- [ ] contao-community-alliance/composer-plugin
- [ ] contao-community-alliance/dc-general
- [ ] contao-community-alliance/dependency-container
- [ ] contao-community-alliance/event-dispatcher
- [ ] contao-community-alliance/events-contao-bindings
- [ ] contao-community-alliance/meta-palettes
- [ ] contao-community-alliance/translator
- [ ] contao-community-alliance/url-builder

**Comment by discordier** [comment]
I wonder if this is really necessary as no build is failing nor did I have this issue over the past year or so.

Removed milestone until we decided if it is really needed.

**Comment by baumannsven** [comment]
@discordier I think we can close this.
