### ISSUE TITLE
Error messages by "strict mode"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1232]
Affects in MM 2.0 and MM 2.1:

If the DB has a "strict mode", e.g. MySQL 5.7 or MariaDB, there are error messages when saving.

Please report such error messages here, including a description of how to reproduce them.

Current Fix: disable strict mode

**Comment by zonky2** [comment]
Core https://gitlab.com/metamodels/core/commit/f138a6b0f6846306fe7e427869e39aa763a66ddb

**Comment by discordier** [comment]
Does this need a backport to 2.0?

**Comment by zonky2** [comment]
not really - some things are already fixed in 2.0... if there are more bugs in 2.0, the "strict mode" should be switched off or switched to 2.1

**Comment by zonky2** [comment]
o.k.

**Comment by zonky2** [comment]
see new `schema manager` https://github.com/MetaModels/core/pull/1267
