### ISSUE TITLE
Wrong TypeHinting in CustomSql

### ISSUE THREAD

**Issue by bezin** [MetaModels/core#1235]
Continuing from here to not further flood the Core-Bundle issue tracker https://github.com/contao/core-bundle/issues/1603

Unfortunately it is not fixed yet. Event-Dispatcher works again, but now I cannot access filter configuration in the backend. I get the following error message:
```
Type error: Argument 4 passed to MetaModels\Filter\Setting\CustomSql::__construct() must be an instance of Contao\InsertTags, instance of Contao\CoreBundle\Framework\Adapter given, called in C:\dev\web\metamodels\vendor\metamodels\core\src\Filter\Setting\CustomSqlFilterSettingTypeFactory.php on line 105
```

This is due to TypeHinting in CustomSql.php:114, where Contao\InsertTags still is expected. 

Cheers

**Comment by bezin** [comment]
Hello there,

I further debugged this: The definition of the metamodels.insert_tags service needs to be fixed as well. The class name should not be escaped, because it gets escaped afterwards during container build, hence escaping it prior leads to "Contao\\\\InsertTags" being passed to the Adapter. 

However, the InsertTags classes needs do be passed in as an instance anyways, because the replace method calls $this->doReplace().

**Comment by zonky2** [comment]
@discordier can you check this?

**Comment by bezin** [comment]
It does work if you use the createInstance method of the adapter: 

```
metamodels.insert_tags:
        class: Contao\InsertTags
        factory: ['@contao.framework', 'createInstance']
        arguments: ['Contao\InsertTags']
```

And then revert the TypeHints of course.

**Comment by discordier** [comment]
Try 2f1d8db5 please

**Comment by bezin** [comment]
This does fix it 👍 Many thanks 🙌

**Comment by zonky2** [comment]
thx
