### ISSUE TITLE
Simple lookup filter: "search in all languages" checkbox disappears after saving

### ISSUE THREAD

**Issue by bezin** [MetaModels/core#1244]
## Issue description

The checkbox "search in all languages" disappears, after I saved an freshly created simple lookup filter. 

## Steps to reproduce
1. Create a simplelookup filter
2. Select a translated field, e.g. translated alias or translated text as attribute

The page will reload and you get a new checkbox "search in all languages"

3. Save

The Checkbox disappears. I expect the checkbox to still be there.

When you check the checkbox before step 3, the settings will be in effect though. So it seems to be a display issue only. 

## Versions
PHP 7.2.6
Contao 4.4.20
MetaModels 2.1

**Comment by zonky2** [comment]
same in MM 2.0 - checkbox is hidden after save

**Comment by dmolineus** [comment]
Can't reprocude it with MM 2.0. @zonky2 any details of the setup how to reproduce it under 2.0?

**Comment by zonky2** [comment]
fixed in 2.1
