### ISSUE TITLE
[2.2] Contao Shared Caching

### ISSUE THREAD

**Issue by richardhj** [MetaModels/core#1245]
I just got some insights on Contao 4's caching features.
As of Contao 4.6, it will be possible to set a caching max age of "1 year," and the caching proxy will invalidate the cache once an element changes so that the page is always up-to-date.

To follow up with the changes, we might want to add the following changes: 

## Tag the response of MetaModel content elements and modules

This change is necessary because our content elements/modules do not extend the Contao core classes.

```php

        // Tag the response
        if (($table = $this->objParent::getTable())
            && System::getContainer()->has('fos_http_cache.http.symfony_response_tagger')) {
            /** @var ResponseTagger $responseTagger */
            $responseTagger = System::getContainer()->get('fos_http_cache.http.symfony_response_tagger');
            $responseTagger->addTags(['contao.db.' . $table . '.' . $this->id]);
        }
```

## Tag a metamodel list

We should add a tag (e.g. `metamodels.mm_my_metamodel`) to the response of any metamodel list (content element or module). 
We then are able to invalidate the cache, when a MetaModel gets updated (`PostPersist`, `PostDuplicate`, `PostDelete`):

```php
/** @var CacheManager $cacheManager */
$cacheManager = System::getContainer()->get('fos_http_cache.cache_manager');
$cacheManager->invalidateTags($tags);
```

## Further notes

The cache then might not get invalidated when using custom filters (i.e. filters with start and stop date).

**Comment by zonky2** [comment]
relatet with https://github.com/contao-community-alliance/dc-general/issues/419

**Comment by zonky2** [comment]
@richardhj can you specify in any headwords what is already implemented in MM 2.2 and what is still open

**Comment by zonky2** [comment]
@baumannsven can we close this issue?

> Implement in https://github.com/contao-community-alliance/dc-general/commit/f9db5fe81dadb38dd6cae3e10d41de7e484cd66a

**Comment by zonky2** [comment]
Updated hash: https://github.com/contao-community-alliance/dc-general/commit/212801055ba246518673c2a02a484c990a00e782
