### ISSUE TITLE
[2.1] CSS und JS-Dateiauswahl unter Rendersettings mittels Filepicker,  Dir Separator Problem unter Windows

### ISSUE THREAD

**Issue by Ainschy** [MetaModels/core#1250]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   7.1.20       |                                  |
| Contao version:                     |      4.4.25    |                                  |
| MetaModels version:                 |    2.1      |                                  |
| Installation via composer:          |  yes |                                  |
| Installed MetaModels packages:      | MM2.1 |                                  |
| DCG version:                        | ~2.1@dev |                                  |

## Issue description
Windows DIRECTORY_SEPARATOR von Symfony ersetzte die Slashes unterhalb von files durch Backslashes. Dateien sind damit nicht auswählbar. Nur auf der obersten Ebene möglich. 
\MetaModels\CoreBundle\EventListener\DcGeneral\Table\RenderSettings\AddAssetListener::scanFiles

## Steps to reproduce

1. In einem MM unter Windows bei den Rendersettings eine CSS oder JS Datei auswählen die mitausgeliefert werden soll. Z.b. für die Backend Ansicht.
2. bei der Auswahl einer Dateien auf der 2. Ebene wie files/layout\backend.css wird der Directory Separator von Windows verwendet.
3. Hier wird dieses ersetzt: vendor/symfony/symfony/src/Symfony/Component/Finder/Iterator/PathFilterIterator.php

## Describe the behaviour of the application
Der Versuch einen Datei wie eben beschrieben auszuwählen führt zu einer Fehlermeldung ohne nähere Erklärung. "Ein Fehler ist aufgetreten"

Lösungsvorschlag:

MultiColumn-Auswahl durch einen Filepicker ersetzen.

**Comment by discordier** [comment]
Fixed in fbcc8b20cab586e5762713cf081d375e215b50dd

**Comment by Ainschy** [comment]
Perfekt <3
