### ISSUE TITLE
[2.0, 2.1] Bug when creating an attribute with the same column name

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1255]
Bug when creating an attribute with the same column name

we can change the attribute subscriber from Post- to PrePersistModelEvent

https://github.com/MetaModels/core/blob/ebda9ec8ccd31425f72b62cde1edda151d3f6553/src/MetaModels/DcGeneral/Events/Table/Attribute/Subscriber.php#L106

and

https://github.com/MetaModels/core/blob/ebda9ec8ccd31425f72b62cde1edda151d3f6553/src/MetaModels/DcGeneral/Events/Table/Attribute/Subscriber.php#L513

we should create a new custom validator

**Comment by discordier** [comment]
Bug is in dc-general and got introduced in https://github.com/contao-community-alliance/dc-general/commit/17446f3db18226380c11ce5166e7219b90e07654#diff-74bdf77094b9a1246f922701deacb509R732
It does store the model with implicit id "null", however, the result is ignored here https://github.com/contao-community-alliance/dc-general/commit/17446f3db18226380c11ce5166e7219b90e07654#diff-11ce102fa1c0f4cff1dfd6be4d793231R71 and therefore we will never see the error.

ping @baumannsven, as he developed it. Nothing we can do from MetaModel side.

**Comment by zonky2** [comment]
fixed https://github.com/contao-community-alliance/dc-general/issues/436
