### ISSUE TITLE
Various errors at filter rule "simple lookup" II

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1259]
various errors at filter rule "simple lookup"

    b) if the checkbox "only used" is not set and a "simple attribute" such as text is selected, the filter does not work - there are no return values; with a "complex attribute" such as select, the restriction to "only used" works (look at d62c7bb#diff-a7a3e048b8ea95100f546d5970ee6d22)

see https://github.com/MetaModels/core/issues/1234

backport from MM 2.1

**Comment by discordier** [comment]
Implemented in d6dc931c8b6fa315aa98f0bdb211301f005c2dd4

**Comment by zonky2** [comment]
look good
