### ISSUE TITLE
List of ready repositories in version 2.1

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1260]
# List of ready repositories:

## MM core
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/core/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/core/branches) [MetaModels/core](https://github.com/MetaModels/core)

## MM Attributes
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_alias/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_alias/branches) [MetaModels/attribute_alias](https://github.com/MetaModels/attribute_alias)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_checkbox/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_checkbox/branches) [MetaModels/attribute_checkbox](https://github.com/MetaModels/attribute_checkbox)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_color/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_color/branches) [MetaModels/attribute_color](https://github.com/MetaModels/attribute_color)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_combinedvalues/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_combinedvalues/branches) [MetaModels/attribute_combinedvalues](https://github.com/MetaModels/attribute_combinedvalues)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_country/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_country/branches) [MetaModels/attribute_country](https://github.com/MetaModels/attribute_country)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_decimal/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_decimal/branches) [MetaModels/attribute_decimal](https://github.com/MetaModels/attribute_decimal)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_file/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_file/branches) [MetaModels/attribute_file](https://github.com/MetaModels/attribute_file)
- [ ] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_geodistance/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_geodistance/branches) [MetaModels/attribute_geodistance](https://github.com/MetaModels/attribute_geodistance)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_langcode/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_langcode/branches) [MetaModels/attribute_langcode](https://github.com/MetaModels/attribute_langcode)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_levensthein/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_levensthein/branches) [MetaModels/attribute_levensthein](https://github.com/MetaModels/attribute_levensthein)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_longtext/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_longtext/branches) [MetaModels/attribute_longtext](https://github.com/MetaModels/attribute_longtext)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_numeric/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_numeric/branches) [MetaModels/attribute_numeric](https://github.com/MetaModels/attribute_numeric)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_rating/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_rating/branches) [MetaModels/attribute_rating](https://github.com/MetaModels/attribute_rating)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_select/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_select/branches) [MetaModels/attribute_select](https://github.com/MetaModels/attribute_select)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_tabletext/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_tabletext/branches) [MetaModels/attribute_tabletext](https://github.com/MetaModels/attribute_tabletext)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_tags/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_tags/branches) [MetaModels/attribute_tags](https://github.com/MetaModels/attribute_tags)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_text/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_text/branches) [MetaModels/attribute_text](https://github.com/MetaModels/attribute_text)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_timestamp/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_timestamp/branches) [MetaModels/attribute_timestamp](https://github.com/MetaModels/attribute_timestamp)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedalias/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedalias/branches) [MetaModels/attribute_translatedalias](https://github.com/MetaModels/attribute_translatedalias)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedcheckbox/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedcheckbox/branches) [MetaModels/attribute_translatedcheckbox](https://github.com/MetaModels/attribute_translatedcheckbox)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedcombinedvalues/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedcombinedvalues/branches) [MetaModels/attribute_translatedcombinedvalues](https://github.com/MetaModels/attribute_translatedcombinedvalues)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedfile/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedfile/branches) [MetaModels/attribute_translatedfile](https://github.com/MetaModels/attribute_translatedfile)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedlongtext/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedlongtext/branches) [MetaModels/attribute_translatedlongtext](https://github.com/MetaModels/attribute_translatedlongtext)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedselect/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedselect/branches) [MetaModels/attribute_translatedselect](https://github.com/MetaModels/attribute_translatedselect)
- [ ] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedsimpletable/master.svg?style=flat-square&label=master(2.1.0))](https://travis-ci.org/MetaModels/attribute_translatedsimpletable/branches) [MetaModels/attribute_translatedsimpletable](https://github.com/MetaModels/attribute_translatedsimpletable)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedtabletext/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedtabletext/branches) [MetaModels/attribute_translatedtabletext](https://github.com/MetaModels/attribute_translatedtabletext)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedtags/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedtags/branches) [MetaModels/attribute_translatedtags](https://github.com/MetaModels/attribute_translatedtags)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedtext/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedtext/branches) [MetaModels/attribute_translatedtext](https://github.com/MetaModels/attribute_translatedtext)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedurl/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedurl/branches) [MetaModels/attribute_translatedurl](https://github.com/MetaModels/attribute_translatedurl)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_url/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_url/branches) [MetaModels/attribute_url](https://github.com/MetaModels/attribute_url)

## MM Filter
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_checkbox/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_checkbox/branches) [MetaModels/filter_checkbox](https://github.com/MetaModels/filter_checkbox)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_fromto/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_fromto/branches) [MetaModels/filter_fromto](https://github.com/MetaModels/filter_fromto)
- [ ] [![Build Status](http://img.shields.io/travis/MetaModels/filter_perimetersearch/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_perimetersearch/branches) [MetaModels/filter_perimetersearch](https://github.com/MetaModels/filter_perimetersearch)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_range/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_range/branches) [MetaModels/filter_range](https://github.com/MetaModels/filter_range)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_register/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_register/branches) [MetaModels/filter_register](https://github.com/MetaModels/filter_register)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_select/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_select/branches) [MetaModels/filter_select](https://github.com/MetaModels/filter_select)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_tags/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_tags/branches) [MetaModels/filter_tags](https://github.com/MetaModels/filter_tags)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_text/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_text/branches) [MetaModels/filter_text](https://github.com/MetaModels/filter_text)

## Bundles
- [ ] [![Build Status](http://img.shields.io/travis/MetaModels/bundle_all/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/bundle_all/branches) [MetaModels/bundle_all](https://github.com/MetaModels/bundle_all)
- [ ] [![Build Status](http://img.shields.io/travis/MetaModels/bundle_attributes/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/bundle_attributes/branches) [MetaModels/bundle_attributes](https://github.com/MetaModels/bundle_attributes)
- [ ] [![Build Status](http://img.shields.io/travis/MetaModels/bundle_filter/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/bundle_filter/branches) [MetaModels/bundle_filter](https://github.com/MetaModels/bundle_filter)
- [ ] [![Build Status](http://img.shields.io/travis/MetaModels/bundle_nontranslated/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/bundle_nontranslated/branches) [MetaModels/bundle_nontranslated](https://github.com/MetaModels/bundle_nontranslated)
- [ ] [![Build Status](http://img.shields.io/travis/MetaModels/bundle_start/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/bundle_start/branches) [MetaModels/bundle_start](https://github.com/MetaModels/bundle_start)
- [ ] [![Build Status](http://img.shields.io/travis/MetaModels/bundle_translated/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/bundle_translated/branches) [MetaModels/bundle_translated](https://github.com/MetaModels/bundle_translated)

## FEE
- [ ] [![Build Status](http://img.shields.io/travis/contao-community-alliance/dc-general-contao-frontend/release/2.1.0.svg?style=flat-square&label=release/2.1.0)](https://travis-ci.org/contao-community-alliance/dc-general-contao-frontend/branches) [contao-community-alliance/dc-general-contao-frontend](https://github.com/contao-community-alliance/dc-general-contao-frontend)
- [ ] [![Build Status](http://img.shields.io/travis/MetaModels/contao-frontend-editing/release/2.1.0.svg?style=flat-square&label=release/2.1.0)](https://travis-ci.org/MetaModels/contao-frontend-editing/branches) [MetaModels/contao-frontend-editing](https://github.com/MetaModels/contao-frontend-editing)

## DCG
- [ ] [![Build Status](https://img.shields.io/travis/contao-community-alliance/dc-general.svg?style=flat-square&label=2.1)](https://travis-ci.org/contao-community-alliance/dc-general/branches) [contao-community-alliance/dc-general](https://github.com/contao-community-alliance/dc-general)

## Install/Test
with the following adjustment, you can test the packages - in MM 2.1 the smallest PHP version is 7.1
```
...
  "require": {
    "php": "^7.1",
    "contao-community-alliance/dc-general": "^2.1",
    "menatwork/contao-multicolumnwizard-bundle": "^3.4",
    "metamodels/core": "^2.1.0@dev",
    "metamodels/attribute_alias": "^2.1.0@dev",
    "metamodels/attribute_checkbox": "^2.1.0@dev",
....
```

or read cookbook chapter https://metamodels.readthedocs.io/de/latest/cookbook/install/install_mm2.1-alpha.html

**Comment by zonky2** [comment]
thx at @discordier for the badges

**Comment by dmolineus** [comment]
[`MetaModels/attribute_geodistance`](https://github.com/MetaModels/attribute_geodistance/commit/4d7673d3161b603c164e904b66af3782afc60f10)

- Deprecated Autoloader hinzugefügt
- Test für Deprecated Autoloader hinzugefügt

**Comment by discordier** [comment]
@dmolineus Fixed permissions in simpletable. Apparently the team assignment was forgotten when @stefanheimes added the repository. Sorry for that.

**Comment by dmolineus** [comment]
Thanks @discordier. Changes to MetaModels/attribute_translatedsimpletable are pushed now. I also added some basic tests, increased minimum required php version to 7.1 and added missing requirement statements.

**Comment by richardhj** [comment]
Can I delete the "old" branch https://github.com/contao-community-alliance/dc-general-contao-frontend/tree/feature/contao4?

**Comment by richardhj** [comment]
@discordier https://packagist.org/packages/MetaModels/contao-frontend-editing does not get auto-updated.

**Comment by discordier** [comment]
Yep, you broke it. :smile_cat:
```
This package is in a broken state and will not update anymore. 
Some branches contain invalid data and until you fix them the entire package is frozen.

Skipped branch release/2.1.0, "08c4ab0b95768b25f9313007247a89006657cbf9:composer.json" 
does not contain valid JSON
Parse error on line 72:
...2.1.x-dev"    }  },  "config": {    
--------------------^
Expected: 'EOF'
```

**Comment by richardhj** [comment]
Oh no 😿 Should have used composer-validate.

**Comment by discordier** [comment]
Which `ant` would do. :smile_cat:

**Comment by zonky2** [comment]
more at https://github.com/MetaModels/core/issues/1288
