### ISSUE TITLE
[2.2] MCW D&D obsolete at render settings

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1263]
MCW D&D obsolete at render settings

![screenshot_371](https://user-images.githubusercontent.com/1045318/51300338-d3bff780-1a2b-11e9-80bb-c14ed9e1f70d.jpg)

**Comment by discordier** [comment]
Is this related to https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/17?
I mean, what do we have to add here and where?
What has changed in MCW?

**Comment by zonky2** [comment]
D&D is default in MCW-bundle

**Comment by zonky2** [comment]
With the MCW this only has something to do indirectly - a D&D is not necessary / not useful at this point - the buttons should be hidden.

**Comment by discordier** [comment]
I agree that we do not need them, my question simply was why they are there in the first place (were they always there?) and how to get rid of them.

Both got answered just fine. ;)

**Comment by zonky2** [comment]
fixed
