### ISSUE TITLE
rename attribute column without delete+new

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1265]
rename attribute column without delete old column (with all values!) and add a new column

with "delete+new" we lost different other things e.g. filter settings

**Comment by discordier** [comment]
We should keep an eye on this one if #1267 also fixes this.

**Comment by zonky2** [comment]
with new schema manager its the same 

I change from `Test` to `Test2`

```
 * ALTER TABLE mm_test DROP Test
 * ALTER TABLE mm_test ADD Test2 VARCHAR(255) DEFAULT NULL

```
