### ISSUE TITLE
error at rename attribute column

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1266]
error at rename attribute column e.g. `Test` to `test`

```
An exception occurred while executing 'ALTER TABLE mm_employees ADD test varchar(255) NOT NULL default ''': SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'test'
```

relatet to #1265

**Comment by discordier** [comment]
We should keep an eye on this one if #1267 also fixes this.

**Comment by zonky2** [comment]
the column names are not case-sensitive - see https://dev.mysql.com/doc/refman/5.6/en/identifier-case-sensitivity.html

But in MM 2.3 (MM 2.2?) we have a human readable error message
