### ISSUE TITLE
add key display in metapalettes

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1270]
add key display in metapalettes

see https://github.com/MetaModels/attribute_country/issues/15#issuecomment-458706579

**Comment by discordier** [comment]
Do we really want to add this key or rather change it to an existing one?
I wonder how this could get rendered as `Display settings` in your screenshot in MetaModels/attribute_country#15.

**Comment by zonky2** [comment]
I can't tell you that either - YOU wrote, the key is missing

**Comment by discordier** [comment]
Was fixed in country attribute MetaModels/attribute_country#15.
