### ISSUE TITLE
[2.1] Save-Problem with readonly fields (alias)

### ISSUE THREAD

**Issue by OMOSde** [MetaModels/core#1276]
## Checklist before I submit this issue report

I confirm that:
- [ ] I have tested this with the latest version available
- [ ] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [ ] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.1.26        |                                  |
| Contao version:                     |  4.4.34        |                                  |
| MetaModels version:                 |  2.1        |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      | use json from: https://metamodels.readthedocs.io/de/latest/cookbook/install/install_mm2.1-alpha.html          |                                  |
| DCG version:                        |   "dev-feature/contao4-release as 2.1.0"       |                                  |

## Issue description

In German: Wenn ich die Option 'Neuerstellung des Alias erzwingen.' für ein Alias-Attribut nutze, dann wird in der Eingabemaske das Inputfeld 'readonly' (nicht bearbeitbar). Das führt in der Folge beim Speichern zu einem Fehler. Siehe Screenshot
![mm_error](https://user-images.githubusercontent.com/2035628/52646167-8fb4fb00-2ee2-11e9-862a-a2b39cddc84c.png)

Ich vermute das Contao bei readonly-Input-Feldern nur null zurückliefert.

Das gleiche Problem tritt bei der Option 'Nur Lesen' in den Attributseinstellungen (Eingabemaske) auf.

**Comment by zonky2** [comment]
welche DB bzw. ist `strict mode` an?

**Comment by OMOSde** [comment]
MySQL 5.7, strict mode on

**Comment by zonky2** [comment]
das Thema hatten wir doch schon im Forum!?! - und steht auch in https://metamodels.readthedocs.io/de/latest/cookbook/install/install_mm2.1-alpha.html

**Comment by zonky2** [comment]
duplicate of #1268
