### ISSUE TITLE
Metamodels with translated Elements

### ISSUE THREAD

**Issue by MacKP** [MetaModels/core#1278]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## Issue description

When you fill in the Edit-Mask for an Item with translations and you change to an other language there is no visual indication, that there is nothing written there (ok, I can see the fallback, but thats not realy intuitiv). It would be nice, to have an class at the input element to style this a litte bit in that case.

## Steps to reproduce

1. Create a new translated Item
2. Fill in the first language
3. Change to other language

## Describe the behaviour of the application

You just see the second language with the Text of the first language

## Describe the expected behaviour of the application

Different color (red) for the input element.

**Comment by zonky2** [comment]
pls see at https://github.com/contao-community-alliance/dc-general/issues/343

**Comment by MacKP** [comment]
Thx for the Info! Should have searched there also... sorry...

**Comment by zonky2** [comment]
see https://metamodels.readthedocs.io/de/latest/manual/component/multi-language.html#eingabemaske-eingabe
