### ISSUE TITLE
Feature: Indizierung Contao-Suche

### ISSUE THREAD

**Issue by Creational** [MetaModels/core#128]
Es sollte eine Einstellungsmöglichkeit geben, die Detailseiten eines MetaModels zum Contao-Suchindex hinzuzufügen.

**Comment by discordier** [comment]
Aktueller Stand: https://github.com/MetaModels/core/compare/6a793d0...2b38b7e

**Comment by jgrotstabel** [comment]
Hallo zusammen,
gibt es eine ungefähre Ansage, wann mit der Integration der MetaModels Ergebnissseiten in den Contao-Suchindex zu rechnen ist?
Da oben sind ja alle Punkte unter Workflow und Umsetzung abgehakt.
Kurze Info wäre sehr Hilfreich, wir hegen den Gedanken Euer tolles Tool für ein Projekt einzusetzen und daran auch mal ausgiebig zu testen. Die Suche wäre dafür extrem von Vorteil ;-)
Viele Grüße
Jens

**Comment by tim-bec** [comment]
Das pinge ich mal in Richtung @stefanheimes :-)

**Comment by discordier** [comment]
Neuer PR ist: #789.

**Comment by stefanheimes** [comment]
Funktion ist im Master hinterlegt und aktiv. Sollte es noch Probleme geben, sollte diese in neuen Tickets hinterlegt werden. Diese Ticket wird geschlossen, da die Funktion eingebaut wurde.
