### ISSUE TITLE
[2.1] Issues with metapalettes legends containing + sign

### ISSUE THREAD

**Issue by dmolineus** [MetaModels/core#1280]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [ x I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.2.14        |                                  |
| Contao version:                     |   4.4.35      |                                  |
| MetaModels version:                 | 2.1.x-dev          |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |  all         |                                  |
| DCG version:                        |  2.1.x-dev         |                                  |

## Issue description

See related tickets:

* [/contao-community-alliance/dc-genera#49](https://github.com/contao-community-alliance/dc-general/issues/459)
* [contao-community-alliance/meta-palettes/issues#42](https://github.com/contao-community-alliance/meta-palettes/issues/42)
* [MetaModels/attribute_file#70](https://github.com/MetaModels/attribute_file/issues/70)
* [MetaModels/attribute_translatedfile#25](https://github.com/MetaModels/attribute_translatedfile/issues/25)

Let's stop gambling with Github issues now but address the root of the issue. It's introduced with https://github.com/MetaModels/core/commit/06c9eccea1f5baf99df7adf2b0c27b95869db927#diff-036ec8758c82b25c5157a34d7553901bL144 where the checking for the `+` sign in legends got removed. The new abstraction https://github.com/MetaModels/core/commit/06c9eccea1f5baf99df7adf2b0c27b95869db927#diff-eaaa1c8727398a70154ff9f6bfd9bef9R50 doesn't contain the check. So basically the legends are created for it.

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/core/commit/3749e031a01377ffc0b66ba7a02838a4deb488c4
