### ISSUE TITLE
[2.1]filter setting multiple selection (Mehrfachauswahl) in FE does not work

### ISSUE THREAD

**Issue by bizon1** [MetaModels/core#1282]
## Checklist before I submit this issue report

I confirm that:
- [2.1@dev ] I have tested this with the latest version available
- [ x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x ] I have checked the Contao community forums for references https://community.contao.org/
- [x ] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.3       |                                  |
| Contao version:                     |  4.4.35        |                                  |
| MetaModels version:                 |  2.1.0@dev        |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |   all available       |                                  |
| DCG version:                        |   dev-feature/contao4-release as 2.1.0       |    updated on Feb, 28  |                            |

## Issue description

Filter setting multiple selection (Mehrfachauswahl) in FE does not work.
The problem occurred after a composer update on februar, 28 in which the dc-general also was updated. No other metamodel-file was affected in this update.

## Steps to reproduce

1. FE-Filter Mehrfachauswahl

## Describe the behaviour of the application

When I select one checkbox - I get a correct result.
When I select a second checkbox - I get no item found and my checkbox selections was cleared.

## Describe the expected behaviour of the application

It worked correctly before dc-general was updated.

## Screenshots
Filter-Settings
![fe-filter-mehrfachauswahl](https://user-images.githubusercontent.com/5312861/53635679-29d4ad00-3c1e-11e9-8c11-fabc1994b6cf.png)

**Comment by zonky2** [comment]
@bizon1 is it possible that you made an update of Contao?

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/core/commit/41b9a870029348923e4508d09d2ea810f065563e
