### ISSUE TITLE
List of stable tagged repositories in version 2.1

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1288]
# List of stable tagged repositories:

## MM core
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/core/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/core/branches) [MetaModels/core](https://github.com/MetaModels/core)

## MM Attributes
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_alias/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_alias/branches) [MetaModels/attribute_alias](https://github.com/MetaModels/attribute_alias)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_checkbox/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_checkbox/branches) [MetaModels/attribute_checkbox](https://github.com/MetaModels/attribute_checkbox)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_color/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_color/branches) [MetaModels/attribute_color](https://github.com/MetaModels/attribute_color)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_combinedvalues/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_combinedvalues/branches) [MetaModels/attribute_combinedvalues](https://github.com/MetaModels/attribute_combinedvalues)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_country/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_country/branches) [MetaModels/attribute_country](https://github.com/MetaModels/attribute_country)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_decimal/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_decimal/branches) [MetaModels/attribute_decimal](https://github.com/MetaModels/attribute_decimal)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_file/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_file/branches) [MetaModels/attribute_file](https://github.com/MetaModels/attribute_file)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_geodistance/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_geodistance/branches) [MetaModels/attribute_geodistance](https://github.com/MetaModels/attribute_geodistance)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_langcode/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_langcode/branches) [MetaModels/attribute_langcode](https://github.com/MetaModels/attribute_langcode)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_levensthein/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_levensthein/branches) [MetaModels/attribute_levensthein](https://github.com/MetaModels/attribute_levensthein)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_longtext/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_longtext/branches) [MetaModels/attribute_longtext](https://github.com/MetaModels/attribute_longtext)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_numeric/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_numeric/branches) [MetaModels/attribute_numeric](https://github.com/MetaModels/attribute_numeric)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_rating/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_rating/branches) [MetaModels/attribute_rating](https://github.com/MetaModels/attribute_rating)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_select/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_select/branches) [MetaModels/attribute_select](https://github.com/MetaModels/attribute_select)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_tabletext/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_tabletext/branches) [MetaModels/attribute_tabletext](https://github.com/MetaModels/attribute_tabletext)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_tags/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_tags/branches) [MetaModels/attribute_tags](https://github.com/MetaModels/attribute_tags)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_text/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_text/branches) [MetaModels/attribute_text](https://github.com/MetaModels/attribute_text)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_timestamp/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_timestamp/branches) [MetaModels/attribute_timestamp](https://github.com/MetaModels/attribute_timestamp)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedalias/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedalias/branches) [MetaModels/attribute_translatedalias](https://github.com/MetaModels/attribute_translatedalias)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedcheckbox/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedcheckbox/branches) [MetaModels/attribute_translatedcheckbox](https://github.com/MetaModels/attribute_translatedcheckbox)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedcombinedvalues/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedcombinedvalues/branches) [MetaModels/attribute_translatedcombinedvalues](https://github.com/MetaModels/attribute_translatedcombinedvalues)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedfile/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedfile/branches) [MetaModels/attribute_translatedfile](https://github.com/MetaModels/attribute_translatedfile)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedlongtext/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedlongtext/branches) [MetaModels/attribute_translatedlongtext](https://github.com/MetaModels/attribute_translatedlongtext)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedselect/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedselect/branches) [MetaModels/attribute_translatedselect](https://github.com/MetaModels/attribute_translatedselect)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedtabletext/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedtabletext/branches) [MetaModels/attribute_translatedtabletext](https://github.com/MetaModels/attribute_translatedtabletext)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedtags/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedtags/branches) [MetaModels/attribute_translatedtags](https://github.com/MetaModels/attribute_translatedtags)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedtext/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedtext/branches) [MetaModels/attribute_translatedtext](https://github.com/MetaModels/attribute_translatedtext)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_translatedurl/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_translatedurl/branches) [MetaModels/attribute_translatedurl](https://github.com/MetaModels/attribute_translatedurl)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/attribute_url/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/attribute_url/branches) [MetaModels/attribute_url](https://github.com/MetaModels/attribute_url)

## MM Filter
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_checkbox/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_checkbox/branches) [MetaModels/filter_checkbox](https://github.com/MetaModels/filter_checkbox)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_fromto/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_fromto/branches) [MetaModels/filter_fromto](https://github.com/MetaModels/filter_fromto)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_perimetersearch/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_perimetersearch/branches) [MetaModels/filter_perimetersearch](https://github.com/MetaModels/filter_perimetersearch)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_range/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_range/branches) [MetaModels/filter_range](https://github.com/MetaModels/filter_range)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_register/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_register/branches) [MetaModels/filter_register](https://github.com/MetaModels/filter_register)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_select/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_select/branches) [MetaModels/filter_select](https://github.com/MetaModels/filter_select)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_tags/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_tags/branches) [MetaModels/filter_tags](https://github.com/MetaModels/filter_tags)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/filter_text/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/filter_text/branches) [MetaModels/filter_text](https://github.com/MetaModels/filter_text)

## Bundles
- [x] [![Latest Version on Packagist](http://img.shields.io/packagist/v/MetaModels/bundle_all.svg)](https://packagist.org/packages/metamodels/bundle_all) [MetaModels/bundle_all](https://github.com/MetaModels/bundle_all)
- [x] [![Latest Version on Packagist](http://img.shields.io/packagist/v/MetaModels/bundle_attributes.svg)](https://packagist.org/packages/metamodels/bundle_attributes) [MetaModels/bundle_attributes](https://github.com/MetaModels/bundle_attributes)
- [x] [![Latest Version on Packagist](http://img.shields.io/packagist/v/MetaModels/bundle_filter.svg)](https://packagist.org/packages/metamodels/bundle_filter) [MetaModels/bundle_filter](https://github.com/MetaModels/bundle_filter)
- [x] [![Latest Version on Packagist](http://img.shields.io/packagist/v/MetaModels/bundle_nontranslated.svg)](https://packagist.org/packages/metamodels/bundle_nontranslated) [MetaModels/bundle_nontranslated](https://github.com/MetaModels/bundle_nontranslated)
- [x] [![Latest Version on Packagist](http://img.shields.io/packagist/v/MetaModels/bundle_start.svg)](https://packagist.org/packages/metamodels/bundle_start) [MetaModels/bundle_start](https://github.com/MetaModels/bundle_start)
- [x] [![Latest Version on Packagist](http://img.shields.io/packagist/v/MetaModels/bundle_translated.svg)](https://packagist.org/packages/metamodels/bundle_translated) [MetaModels/bundle_translated](https://github.com/MetaModels/bundle_translated)

## FEE
- [x] [![Build Status](http://img.shields.io/travis/contao-community-alliance/dc-general-contao-frontend/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/contao-community-alliance/dc-general-contao-frontend/branches) [contao-community-alliance/dc-general-contao-frontend](https://github.com/contao-community-alliance/dc-general-contao-frontend)
- [x] [![Build Status](http://img.shields.io/travis/MetaModels/contao-frontend-editing/2.1.0.svg?style=flat-square&label=2.1.0)](https://travis-ci.org/MetaModels/contao-frontend-editing/branches) [MetaModels/contao-frontend-editing](https://github.com/MetaModels/contao-frontend-editing)

## DCG
- [x] [![Build Status](https://img.shields.io/travis/contao-community-alliance/dc-general.svg?style=flat-square&label=2.1)](https://travis-ci.org/contao-community-alliance/dc-general/branches) [contao-community-alliance/dc-general](https://github.com/contao-community-alliance/dc-general)

## Install
with the following adjustment, you can install the packages - in MM 2.1 the smallest PHP version is 7.1
```
...
  "require": {
    "php": "^7.1",
    "contao-community-alliance/dc-general": "^2.1",
    "metamodels/core": "^2.1",
    "metamodels/attribute_alias": "^2.1",
    "metamodels/attribute_checkbox": "^2.1",
....
```

or read manual chapter https://metamodels.readthedocs.io/de/latest/manual/install.html#installation-von-mm-2-1

**Comment by zonky2** [comment]
W O W !
all ready - congratulations!!

**Comment by swinde** [comment]
MetaModels/bundle_start und MetaModels/bundle_all werden in der Paketsuche im CM 1.1.4 nicht gefunden!
Bei Suche mit MetaModels/bundle werden 4 Treffer angezeigt, es müssten aber 6 sein.
Stefen Winde

**Comment by zonky2** [comment]
@swinde see https://github.com/contao/contao-manager/issues/417
