### ISSUE TITLE
Cast slug value to string.

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1289]
see https://github.com/MetaModels/core/commit/00eb0c17ff36dedaf575896ef5b618abe7f9c834

**Comment by baumannsven** [comment]
@zonky2 What do you mean. This was made yes

**Comment by zonky2** [comment]
Fixed in https://github.com/MetaModels/core/commit/00eb0c17ff36dedaf575896ef5b618abe7f9c834
