### ISSUE TITLE
Type hint error.

### ISSUE THREAD

**Issue by richardhj** [MetaModels/core#1292]
d12d4c816bb79d3409de146ae4814f2c1e9f20cb

Sorry, I accidentily hit enter, I did not aim to commit to master ☹️

This commit fixes https://sentry.io/share/issue/aa918b2b886347e9a3aa72f3a7354025/ https://sentry.io/share/issue/d5f554df52764973a2145c083954a641/.

**Comment by discordier** [comment]
Master restored, cherry-picked in e130744ee114c458f8c9630e0cf83c17b5db0fbb and fix up in b08465bff05094b8a61cf46c8c8e92bc7e63c905

**Comment by richardhj** [comment]
You're great, thanks for your efforts!

**Comment by discordier** [comment]
No problem mate but please be more careful next time. :smile_cat:
