### ISSUE TITLE
Alias with always overwrite and unique the checkboxes for the input should be set automatically

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1296]
Alias with always overwrite and unique the checkboxes for the input should be set automatically

Hint at list view of input mask are o.k.

and "Attribute mit "Neuerstellung erzwingen" sind automatisch "nur lesend" (Einstellung nicht änderbar)." is lost

MM 2.0 http://easycaptures.com/fs/uploaded/1191/5809004744.png

**Comment by baumannsven** [comment]
MM 2.1 http://easycaptures.com/fs/uploaded/1191/4531819639.png

**Comment by discordier** [comment]
Fixed in 1a536fd and https://github.com/contao-community-alliance/dc-general/commit/7e80a2ff1747d6985d70b5057f2dfee9c9cf6123
