### ISSUE TITLE
Metamodel-Liste - Probleme mit linker Spalte im Template

### ISSUE THREAD

**Issue by Monsterdog2k** [MetaModels/core#1299]
## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.1        |                                  |
| Contao version:                     |  4.4.36        |                                  |
| MetaModels version:                 | 2.1 dev         |                                  |
| Installation via composer:          | yes |                                 |
| Installed MetaModels packages:      | alle freigegebenen Packages        |                                  |
| DCG version:                        | 2.1.3         |                                  |

## Issue description

Auf einer Seite habe ich in der linken Spalte eine MetaModel-Liste eingebaut, in der Hauptspalte habe ich eine weitere MetaModel-Liste eingebaut. Bei diesen zwei funktioniert die Anzeige.

Füge ich in der Hauptspalte ein weitere MetaModel-Liste in einen Artikel ein, wird im FE der Inhalt der MetaModel-Liste (linke Spalte) nicht mehr angezeigt.

Füge ich alle drei MetaModel-Listen in einen Artikel ein werden diese im FE problemlos angezeigt.

**Hinweis:** Jedes MetaModel-Liste greift auf ein anderes MetaModel zu.

**Comment by zonky2** [comment]
Kannst Du mich über das Forum oder die MM-Webseite kontaktieren? müsste ich mir mal ansehen...

**Comment by Monsterdog2k** [comment]
Ich habe es heute nochmal getestet. Es muss sich offenbar um einen Fehler in einem meiner Templates gehandelt haben.

Mittlerweile werden die Inhalte angezeigt, wenn auch nicht an den richtigen Stellen in der linke Spalte. Dieses Problem liegt aber mit Sicherheit immer noch in meinen Templates.
