### ISSUE TITLE
Copy action does not work

### ISSUE THREAD

**Issue by richardhj** [MetaModels/core#1300]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |      7.3    |                                  |
| Contao version:                     |      4.7    |                                  |
| MetaModels version:                 |  2.1.2        |                                  |
| Installation via composer:          | (yes/no) |      yes                            |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |      2.1.3    |                                  |

## Issue description

If I hit the copy button in the backend list (hierarchical list), an error occurs:

"Unparsable encoded id value: ''"
https://sentry.io/share/issue/83ade2e589e54167b185090a2f532292/

If you open the stack trace:  TreeEnforcingListener in process at line 78: An 'pid' parameter has to be present and is present.
ModelCollector.php in getModel at line 146: The pid parameter is `''` (empty string).

However, the copy action uri looks like:
_contao?do=metamodel_mm_ferienpass&act=copy&source=mm_ferienpass::5&rt=ERqBXMJxH8jIXCBlb3VGenfVJdzOZEIsEiOAywhn0bE&ref=QGwB_9Jy_

## Steps to reproduce

1. Click on copy

**Comment by richardhj** [comment]
> I tested in our test environment:
The URI of the copy button is http://test.metamodel.me/contao?do=metamodel_mm_test&&act=copy&source=mm_test::2&rt=_eF_flmqs07lyqBM4RJXMTGTSxvRsnBe36p-upG-1Xo&ref=WY8dlNxK
After I clicked on the button, the URI is http://test.metamodel.me/contao?do=metamodel_mm_test&table=mm_test&act=edit&id=mm_test::6&pid&rt=_eF_flmqs07lyqBM4RJXMTGTSxvRsnBe36p-upG-1Xo
So where does the pid parameter come from?

https://github.com/contao-community-alliance/dc-general/issues/484#issuecomment-480854873

**Comment by zonky2** [comment]
see https://github.com/contao-community-alliance/dc-general/issues/484

**Comment by zonky2** [comment]
works - testet in MM 2.2
