### ISSUE TITLE
Factory: Using $this when not in object context

### ISSUE THREAD

**Issue by JLNNN** [MetaModels/core#1303]
Hi,

I'm using my own Contao extension to display data based on inserttags & MetaModels. I use it like this in the template:
`{{restaurant::address}}`
and in my extension I've got a function
```php
public function restaurantReplaceInsertTags($strTag) {
  // code
}
```
which worked like a charm for older MM versions. Now I upgraded some scripts and my system is on
* PHP 7.2
* Contao 3.5.40
* MetaModels/bundle_all 2.0.0

After getting everything to work again, I ran into the error:
```
Fatal error: Uncaught exception Error with message Using $this when not in object context thrown in composer/vendor/metamodels/core/src/MetaModels/Factory.php on line 105
#0 system/modules/jsdoener/JsDoener.php(66): MetaModels\Factory::getMetaModel('mm_restaurant')
#1 system/modules/core/library/Contao/InsertTags.php(1129): JsDoener\JsDoener->restaurantReplaceInsertTags('restaurant::add...', false, '', Array, Array, Array, 0, 4)
#2 system/modules/core/library/Contao/InsertTags.php(77): Contao\InsertTags->replace('file::mm_insert...', false)
#3 system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('...', false)
#4 system/modules/core/classes/FrontendTemplate.php(100): Contao\Controller::replaceInsertTags('...', false)
#5 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#6 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#7 index.php(20): Contao\FrontendIndex->run()
#8 {main}
```

Removing the inserttags from my templates resolves this issue, but that's not what I want :) I'm getting the factory like this in my extension:
```php
public function restaurantReplaceInsertTags($strTag) {
            $objMember = \FrontendUser::getInstance();
            $arrSplit = explode('::', $strTag);

            if ($arrSplit[0] == 'restaurant') {
                if (isset($arrSplit[1])) {
                    $container = $GLOBALS['container']['metamodels-service-container'];
                    $factory = $container->getFactory();
                    $objMetaModel = $factory::getMetaModel('mm_restaurant');

            // more code ...
}
```
and that's where the error occurs.

Can you help me?

Thanks in advance,
  Julian

PS: Wir können auch gerne auf deutsch schreiben, falls das Dinge vereinfacht. Wenn alles wieder läuft, spendiere ich einen Döner 👍🥙

**Comment by zonky2** [comment]
Du solltest das Handbuch lesen https://metamodels.readthedocs.io/de/latest/reference/interfaces/metamodels.html#factory-interface und solche Fragen im Forum stellen - das sind keine Bug/Feature-Issues

kannst Dir was in meiner Amazon-Liste aussuchen => im Forum alias zonky

**Comment by JLNNN** [comment]
Ich habe das Handbuch bzgl. Factories gelesen. Wenn du den Code vergleichst, siehst du, dass ich ihn sogar von dort kopiert habe. Dennoch funktioniert es nicht. Wenn es sich letztendlich nicht um einen Bug handelt, entschuldige ich mich, aber solange ich etwas nach Anleitung abarbeite und dann eine Fehlermeldung erhalte, deren Lösung sich mir durch weiteres Googeln nicht erschließt und bei dem ich davon ausgehe, dass auch andere Entwickler darauf stoßen können, poste ich ein Issue auf github.

Folgende Links habe ich ebenfalls gefunden, helfen mir bei meinem Problem aber nicht weiter:
- https://community.contao.org/de/showthread.php?73982-Fehlermeldung-nach-update-undefined-method-MetaModels-Factory-byTableName()&highlight=factory
- https://community.contao.org/de/showthread.php?62314-byTableName-getMetaModel()&highlight=byTableName

Davon ab ist der Großteil der Dokumentation mittlerweile für MM 2.1 umgesetzt und eine andere Version als `latest` kann ich nicht auswählen.

Ihr macht mit MetaModels einen super Job und ich bin dankbar, diese Extension nutzen zu können/dürfen, doch hier komme ich leider nicht weiter. Ich kann auch nicht ausschließen, dass ich hier einen Edge-Case konstruiert habe und es einen Workaround gibt, aber es hat ja unter eine älteren MM Version schließlich funktioniert.

**Comment by JLNNN** [comment]
Tauuuuusend Dank! Dass ich statt :: hätte -> nutzen müssen, hätte ich nie gesehen.

Bei deiner Amazon-Wishlist ist es egal, welchen Artikel ich in den Warenkorb lege, ich kann ihn nur zur mir nach Hause schicken lassen. Hast du einen paypal.me Link als Alternative?

**Comment by zonky2** [comment]
E-Mail an Deine Adresse ist raus...
