### ISSUE TITLE
There are labels missing in the "Edit record" screen if the checkbox attribute is not installed

### ISSUE THREAD

**Issue by heimseiten** [MetaModels/core#1308]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_translatedcheckbox/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.3        |                                  |
| Contao version:                     |    4.7.5      |                                  |
| MetaModels version:                 |   2.1.1       |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |    core & attribute_translatedcheckbox      |                                  |

## Issue description

If only the core and the translatedcheckbox is installed, there are labels missing in the "Edit record" screen. When the checkbox attribute is installed, the label is correct.

## Steps to reproduce

1. Install only the core and the translatedcheckbox.
2. Add a new attribute.

## Screenshot
<img width="1422" alt="Bildschirmfoto 2019-05-07 um 10 08 10" src="https://user-images.githubusercontent.com/6552484/57283951-889c2400-70b0-11e9-9f1c-11aa4f739884.png">

**Comment by zonky2** [comment]
Workaround: install untranslated checkebox...

we can't solve the problem without adding unwanted dependencies :(

**Comment by zonky2** [comment]
fixed in MM 2.2
