### ISSUE TITLE
button "Add new" too much at new input mask

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1311]
button "Add new" too much at new input mask

http://easycaptures.com/fs/uploaded/1229/6638366806.png

and add new MM

http://easycaptures.com/fs/uploaded/1230/2520472416.png

**Comment by discordier** [comment]
IMO the "edit multiple" is also wrong in there... This is an issue in dcg IMO as the buttons are rendered by dcg.
They used to be not present in the edit mask @baumannsven, did you change the top button handling recently?

**Comment by baumannsven** [comment]
@zonky2 Can you open the ticket in the right repro please.

**Comment by zonky2** [comment]
done https://github.com/contao-community-alliance/dc-general/issues/486
