### ISSUE TITLE
Backend-Listenansicht Details: Bei leeren Feldern Fehlerhinweis

### ISSUE THREAD

**Issue by ThomasJanotta** [MetaModels/core#1318]
php 7.2.11/7.3.4
contao 4.4.40
mm core/bundle 2.1.3
via composer
mit mm packages 2.1.x
dcg 2.1.3
(ich habe eine Live- und Testversion, deswegen 2 Konfigs oben)

Wenn man in der Backend-Listenansicht eines MM auf das "blaue i" für Details des Datensatzes klickt, erscheint bei leeren Feldern der Hinweis:

Unexpected behaviour, attribute title text representation was not rendered. 

Diese Meldung wird erzeugt durch:
vendor\metamodels\core\src\CoreBundle\EventListener\DcGeneral\ItemRendererListener.php

![erroremptyfield](https://user-images.githubusercontent.com/8110641/60413872-a11f4b00-9bd6-11e9-9dd7-839b73388ad8.png)

**Comment by discordier** [comment]
What attribute type is this? We might have to change the text rendering for that one.

**Comment by ThomasJanotta** [comment]
Hi discodier, it affects "all" attribute types

`Title : text`
`Research interest : longtext`
`Publish Academic background : checkbox`
`Category (when empty) : select`

**Comment by zonky2** [comment]
@ThomasJanotta können wir nicht nachvollziehen - bei `MSC.photo__sort` ist das aktuell "normal" - die internal Attribute sollten hier gar nicht erscheinen...

alles aktuell?

![screenshot_629](https://user-images.githubusercontent.com/1045318/60874135-d6134980-a237-11e9-84fc-17c024e108b9.jpg)

**Comment by discordier** [comment]
photo__sort zeigt seit `8f5a455` nun auch nur noch einen Leerstring, entfernen kann ich es leider nicht ohne Eingriff im DCG. Dennoch sollte das Problem des OP nie auftreten.

**Comment by zonky2** [comment]
neues Ticket zum Thema: https://github.com/MetaModels/core/issues/1319

ich habe noch diverse Implementierungen durchgesehen, ohne diese Fehlermeldung - ich schließe das Ticket wg. "nicht nachvollziehbar"

**Comment by zonky2** [comment]
Fehlermeldung kommt dann, wenn in den Rendereinstellungen die Checkbox "Leere Einträge verbergen" checked ist - siehe https://github.com/MetaModels/core/issues/1319#issuecomment-509931339

**Comment by ThomasJanotta** [comment]
Hallo, 
I updated in the CM to 2.1.4, cleared additionally cleared Anwendungs-Cache und Composer-Cache, 
but no changes. Something else to update?
![error2](https://user-images.githubusercontent.com/8110641/61171375-02500280-a577-11e9-9d47-ba70e7a14765.png)

**Comment by zonky2** [comment]
fix in 2.1.5 - see https://github.com/MetaModels/core/commit/95c53dfbb23b76ddab595589560bc2b33382860b

try "dev-hotfix/2.1.5 as 2.1"
see https://metamodels.readthedocs.io/de/latest/manual/install.html#test-von-speziellen-paketen

**Comment by ThomasJanotta** [comment]
Hmm, - Can only install one of: metamodels/core[2.1.x-dev, dev-hotfix/2.1.5]

**Comment by zonky2** [comment]
try try "dev-hotfix/2.1.5 as 2.1.5"

**Comment by ThomasJanotta** [comment]
Hallo,
it works. Mit und ohne Checkbox keine 'Fehlermeldung'.

**Comment by ThomasJanotta** [comment]
Eine logische Sache noch, Contao macht das zwar auch, aber wenn da steht 'Leere Einträge verbegen' dürfte in der Backend-Info die jeweilige ZEILE ja gar nicht auftauchen, z.B. title'...

**Comment by zonky2** [comment]
da kann man unterschiedlicher Meinung sein - für mich hat die "i-Ausgabe" nichts mit den Rendereinstellungen zu tun und sollte (wie bei Contao) eine Komplettübersicht der Daten widerspiegeln, d.h. für mich sollten an der Stelle immer alle Daten ausgegeben werden.

**Comment by ThomasJanotta** [comment]
Agreed ;-)
