### ISSUE TITLE
decode special chars at be list rendersetting, input mask

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1320]
decode special chars at be list rendersetting, input mask

![screenshot_643](https://user-images.githubusercontent.com/1045318/61228541-c196eb80-a726-11e9-8f0e-387dba12966f.jpg)

**Comment by discordier** [comment]
I HATE this input encoding/decoding stuff... :/

**Comment by zonky2** [comment]
Contao Bockmist!

**Comment by zonky2** [comment]
tested - works fine!
