### ISSUE TITLE
change exception to error message:  No visible properties for this edit mask defined

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1322]
in BE list and new - if you forgotten to add attributes for input mask

```User Error: No visible properties for this edit mask defined!```

**Comment by discordier** [comment]
Not a Bug in MM core, message originates here:
https://github.com/contao-community-alliance/dc-general/blob/bf59fc2085cc848c564e40324dee14ef2897faa6/src/Contao/View/Contao2BackendView/EditMask.php#L508
and here:
https://github.com/contao-community-alliance/dc-general/blob/bf59fc2085cc848c564e40324dee14ef2897faa6/src/Contao/View/Contao2BackendView/EditMask.php#L789

**Comment by zonky2** [comment]
o.k.!

move to https://github.com/contao-community-alliance/dc-general/issues/499

**Comment by discordier** [comment]
Clsing here then.

**Comment by zonky2** [comment]
its not possible to render all exceptions in DCG - maybe we can change this one to a error message...

**Comment by zonky2** [comment]
see comments https://github.com/contao-community-alliance/dc-general/issues/499
