### ISSUE TITLE
Hirarchical MM should be set to manual sorting by default

### ISSUE THREAD

**Issue by MacKP** [MetaModels/core#1324]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.2      |                                  |
| Contao version:                     |   4.4       |                                  |
| MetaModels version:                 |     Version 2.1.1
(5.4.2019, 15:22:12)     |                                  |
| Installed MetaModels packages:      |   bundle_all       |                                  |
| DCG version:                        |      ?    |                                  |

## Issue description

Wenn ein hierachisches MM angelegt wird, sollte die Sortierung schon auf Manuell gestellt sei, da alles andere eh keinen Sinn macht und nicht funktioniert. Ansonsten kann man ja eh keine Items passend hierarchisch anlegen.

Viele Grüße

**Comment by zonky2** [comment]
Da ist die Frage, wie restriktiv man da vorgehen sollte:

* vorhandene Sortierungen disablen und fix manuelle Sortierung einschleusen?
* manuelle Sortierung als Sortierung in DB anlegen und auf aktiv schalten?

**Comment by MacKP** [comment]
Die Sache ist ja die: Hirarchie und andere Sortierungen gehen nicht. Von daher weiß ich nicht was daran restriktiv ist... es geht ja schon nicht. Aktuell muss man allerdings selber dran denken, was immer blöd ist ;-)

**Comment by zonky2** [comment]
Bisher haben wir bei MM relativ wenig "magic moments" eingebaut, die einfach irgendwas machen - da damit auch immer verschiedene Restriktionen einhergehen, die ggf. in unseren bisherigen usecases nicht vorgekommen sind.

In MM 2.3 habe ich eine Meldung eingebaut, wenn auf "Hierarchie" umgestellt wird, dass die Sortierung auf "Manuell" als default eingestellt werden muss.
