### ISSUE TITLE
Blob Attribut Display Error

### ISSUE THREAD

**Issue by pglidingmatth** [MetaModels/core#1325]
## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    3.5.8.1      |                                  |
| Contao version:                     |    4.4.40      |                                  |
| MetaModels version:                 |          |   Habe leider gerade kein Zugriff auf den Contao Manager, reiche ich aber nach.                               |
| Installed MetaModels packages:      |          |      Habe leider gerade kein Zugriff auf den Contao Manager, reiche ich aber nach.                            |
| DCG version:                        |         | Habe leider gerade kein Zugriff auf den Contao Manager, reiche ich aber nach.                                 |

## Issue description
Hallo zusammen, 

ich habe ein Problem bei der Anzeige einer MetaModels Seite, wenn diese eine blob-Attribut enthält.
Sobald ich dieses aus dem MetaModel entferne funktioniert die Anzeige wieder.
![grafik](https://user-images.githubusercontent.com/53228448/61800650-b2eabb80-ae2d-11e9-81af-a913e056c832.png)

Im Logfile finde ich die folgenden Hinweise:
[2019-07-02 21:10:26] http://request.INFO: Matched route "contao_catch_all". {"route":"contao_catch_all","route_parameters":{"_scope":"frontend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_url_fragment":"favicon.ico","_route":"contao_catch_all"},"request_uri":"https://www.domain.tld/favicon.ico","method":"HEAD"} [][2019-07-02 21:10:26] http://security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} [][2019-07-02 21:10:26] http://request.INFO: Matched route "contao_catch_all". {"route":"contao_catch_all","route_parameters":{"_scope":"frontend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_url_fragment":"favicon.ico","_route":"contao_catch_all"},"request_uri":"https://www.domain.tld/favicon.ico","method":"GET"} [][2019-07-02 21:10:26] http://security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} [][2019-07-02 21:10:26] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: https://www.domain.tld/favicon.ico" at /www/htdocs/userid/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found: https://www.domain.tld/favicon.ico at /www/htdocs/userid/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\\CoreBundle\\Exception\\PageNotFoundException(code: 0): Page not found: https://www.domain.tld/favicon.ico at /www/htdocs/userid/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:64)"} []

Hat jemand eine Idee woran dies liegen könnte? Ist dies ggf. ein Bug von MetaModels?

## Steps to reproduce

1. Anlage eines blob Attributs in einem MetaModel
2. Anzeige dieses blob Elements in einem Render
3. Einbinden des Renders mit dem Metamodel in einen Artikel

## Describe the behaviour of the application

Fehler bei der Anzeige des Artikels

## Describe the expected behaviour of the application

Anzeige des MetaModels im Frontend

**Comment by zonky2** [comment]
was ist den ein "BLOB Attribut" 
https://www.wwf-jugend.de/public_migrated/uploads_user/10000/9929/blogimages/title.jpg

bitte app_dev.php aktivieren und von da den Stack posten

**Comment by pglidingmatth** [comment]
![grafik](https://user-images.githubusercontent.com/53228448/61806604-488b4880-ae38-11e9-9bd4-94ba3acef217.png)

Binary Large Objects (BLOBs) sind große binäre Datenobjekte.

Die Contao-Installation läuft nicht auf einem Root-Server sondern einem Webspace. Wie kann ich hier den Debug Modus aktivieren, bzw. einen Benutzernamen und ein Passwort hinterlegen, um ihn aufzurufen?

**Comment by zonky2** [comment]
was BLOBs sind, ist mir klar...

Die Attribute haben Bezeichnungen/Namen - damit man in der Kommunikation erkennen kann, worum es geht - Du meinst offensichtlich das **Attribute File/Datei** https://github.com/MetaModels/attribute_file

Bitte wie geschieben app_dev.php verwenden und Stactrace kopieren

**Comment by zonky2** [comment]
@pglidingmatth wie siehts aus?

**Comment by pglidingmatth** [comment]
HI zonky, leider habe ich anscheinend meine letzte Nachricht an dich nicht abgeschickt, wohl aber geschrieben oO. Wir haben aktuell die Contao Version 4.4.0 LTS laufen und wollen gerne bei einer LTS Version bleiben. Leider kann ich dass app_dev.php nach der Anleitung nicht konfigurieren.

vendor/bin/contao-console contao:install-web-dir --user=[Placeholder:Username] --password=[Placeholder:Password]
PHP Fatal error:  Uncaught TypeError: Return value of Contao\ManagerPlugin\Bundle\Parser\DelegatingParser::addParser() must be an instance of Contao\ManagerPlugin\Bundle\Parser\void, none returned in /www/htdocs/[Placeholder]/vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php:25
Stack trace:
#0 /www/htdocs/[Placeholder]/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(131): Contao\ManagerPlugin\Bundle\Parser\DelegatingParser->addParser(Object(Contao\ManagerPlugin\Bundle\Parser\JsonParser))
#1 /www/htdocs/[Placeholder]/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(231): Contao\ManagerBundle\HttpKernel\ContaoKernel->getBundleLoader()
#2 /www/htdocs/[Placeholder]/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(53): Contao\ManagerBundle\HttpKernel\ContaoKernel->addBundlesFromPlugins(Array)
#3 /www/htdocs/[Placeholder]/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): Contao\ManagerBundle\HttpKernel\ContaoKernel->registerBundles()
#4 /www/htdocs/[Placeholder]/vendor/symfony/symfony/ in /www/htdocs/[Placeholder]/vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php on line 25

Fatal error: Uncaught TypeError: Return value of Contao\ManagerPlugin\Bundle\Parser\DelegatingParser::addParser() must be an instance of Contao\ManagerPlugin\Bundle\Parser\void, none returned in /www/htdocs/[Placeholder]/vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php:25
Stack trace:
#0 /www/htdocs/[Placeholder]/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(131): Contao\ManagerPlugin\Bundle\Parser\DelegatingParser->addParser(Object(Contao\ManagerPlugin\Bundle\Parser\JsonParser))
#1 /www/htdocs/[Placeholder]/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(231): Contao\ManagerBundle\HttpKernel\ContaoKernel->getBundleLoader()
#2 /www/htdocs/[Placeholder]/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(53): Contao\ManagerBundle\HttpKernel\ContaoKernel->addBundlesFromPlugins(Array)
#3 /www/htdocs/[Placeholder]/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): Contao\ManagerBundle\HttpKernel\ContaoKernel->registerBundles()
#4 /www/htdocs/[Placeholder]/vendor/symfony/symfony/ in /www/htdocs/[Placeholder]/vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php on line 25

Hast du eine Idee wie ich dies zum laufen bekomme?

**Comment by zonky2** [comment]
vor das 
```vendor/bin/contao-console contao:install-web-dir --user=[Placeholder:Username] --password=[Placeholder:Password]``` hast Du wie angegeben `php` bzw. Deinen PHP-Pfad zur eintsprechenden Binary geschrieben...?

ansonsten kannst Du die `.env` auch aus einem anderen Projekt kopieren

**Comment by pglidingmatth** [comment]
Ja habe davor php geschrieben und ich stehe auch im richtigen Verzeichnis bei der Eingabe des Befehls. Leider habe ich kein anderes Projekt aus der ich die .env nehmen könnte. Hast du noch eine andere Idee?

**Comment by zonky2** [comment]
Du kannst eine Supportanfrage bei MM machen oder im Forum unter "Bezahlte Unterstützung" - mehr fällt mir im Moment nicht ein...

**Comment by zonky2** [comment]
das Ticket ist nicht nachvollziehbar und es gab keine weiteren Auskünfte bezüglich der Fehlermeldung - wird geschlossen
