### ISSUE TITLE
Some attributes cause DCGeneral to always save an unchanged dataset

### ISSUE THREAD

**Issue by bezin** [MetaModels/core#1330]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |PHP 7.2.2|                                  |
| Contao version:                     |4.4.41|                                  |
| MetaModels version:                 |2.1.4|                                  |
| Installed MetaModels packages:      |All|                                  |
| DCG version:                        |2.1.3|                                  |

## Issue description
Some attributes will provide empty strings, if no value is set for them. These will be compared against null in https://github.com/MetaModels/core/blob/master/src/DcGeneral/Data/Model.php#L171 and hence the model will be marked as changed.

The attributes I can confirm this behaviour for are:

- Select
- File
- TranslatedLongText
- TranslatedText 

## Steps to reproduce
Have a MetaModel with (one of) these attributes, hit save with an empty value twice.
Check tstamp in database inbetween and after. You'll see it changed.

## Describe the expected behaviour of the application
The application correctly compares the given and the "new" value of the attribute and does not trigger another save.

## Fix

we must implement `serializeData()` 
e.g. see numeric https://github.com/MetaModels/attribute_numeric/commit/098a1e7cee128377bfadd18c13ca18fc754c1ad6 - set the default value depending on `getSQLDataType` https://github.com/MetaModels/attribute_numeric/blob/master/src/Attribute/Numeric.php#L37-L40

## Note

Thix fixes some errors for `strict mode` - see https://github.com/MetaModels/core/issues/1268

**Comment by zonky2** [comment]
List to check attributes

- [ ] [MetaModels/attribute_alias](https://github.com/MetaModels/attribute_alias)
- [ ] [MetaModels/attribute_checkbox](https://github.com/MetaModels/attribute_checkbox)
- [ ] [MetaModels/attribute_color](https://github.com/MetaModels/attribute_color)
- [ ] [MetaModels/attribute_combinedvalues](https://github.com/MetaModels/attribute_combinedvalues)
- [ ] [MetaModels/attribute_contentarticle](https://github.com/MetaModels/attribute_contentarticle)
- [ ] [MetaModels/attribute_country](https://github.com/MetaModels/attribute_country)
- [ ] [MetaModels/attribute_file](https://github.com/MetaModels/attribute_file)
- [ ] [MetaModels/attribute_geodistance](https://github.com/MetaModels/attribute_geodistance)
- [ ] [MetaModels/attribute_langcode](https://github.com/MetaModels/attribute_langcode)
- [ ] [MetaModels/attribute_levensthein](https://github.com/MetaModels/attribute_levensthein)
- [ ] [MetaModels/attribute_longtext](https://github.com/MetaModels/attribute_longtext)
- [ ] [MetaModels/attribute_numeric](https://github.com/MetaModels/attribute_numeric)
- [ ] [MetaModels/attribute_rating](https://github.com/MetaModels/attribute_rating)
- [ ] [MetaModels/attribute_select](https://github.com/MetaModels/attribute_select)
- [ ] [MetaModels/attribute_tablemulti](https://github.com/MetaModels/attribute_tablemulti)
- [ ] [MetaModels/attribute_tabletext](https://github.com/MetaModels/attribute_tabletext)
- [ ] [MetaModels/attribute_tags](https://github.com/MetaModels/attribute_tags)
- [ ] [MetaModels/attribute_text](https://github.com/MetaModels/attribute_text)
- [ ] [MetaModels/attribute_timestamp](https://github.com/MetaModels/attribute_timestamp)
- [ ] [MetaModels/attribute_url](https://github.com/MetaModels/attribute_url)
- [ ] [MetaModels/attribute_translatedalias](https://github.com/MetaModels/attribute_translatedalias)
- [ ] [MetaModels/attribute_translatedcheckbox](https://github.com/MetaModels/attribute_translatedcheckbox)
- [ ] [MetaModels/attribute_translatedcombinedvalues](https://github.com/MetaModels/attribute_translatedcombinedvalues)
- [ ] [MetaModels/attribute_translatedcontentarticle](https://github.com/MetaModels/attribute_translatedcontentarticle)
- [ ] [MetaModels/attribute_translatedfile](https://github.com/MetaModels/attribute_translatedfile)
- [ ] [MetaModels/attribute_translatedlongtext](https://github.com/MetaModels/attribute_translatedlongtext)
- [ ] [MetaModels/attribute_translatedselect](https://github.com/MetaModels/attribute_translatedselect)
- [ ] [MetaModels/attribute_translatedsimpletable](https://github.com/MetaModels/attribute_translatedsimpletable)
- [ ] [MetaModels/attribute_translatedtablemulti](https://github.com/MetaModels/attribute_translatedtablemulti)
- [ ] [MetaModels/attribute_translatedtabletext](https://github.com/MetaModels/attribute_translatedtabletext)
- [ ] [MetaModels/attribute_translatedtags](https://github.com/MetaModels/attribute_translatedtags)
- [ ] [MetaModels/attribute_translatedtext](https://github.com/MetaModels/attribute_translatedtext)
- [ ] [MetaModels/attribute_translatedurl](https://github.com/MetaModels/attribute_translatedurl)

**Comment by zonky2** [comment]
all Issues fixed
