### ISSUE TITLE
incorrect indexing with multilingual MM

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1332]
incorrect indexing with multilingual MM

URL ...nd.de/**en**/detail-view/kutscher-alois is correct

same result if I change my profile from de to en

![FireShot Pro Screen Capture #087 - 'Maintenance - Contao Open Source CMS' - workshop_metamodels-playground_de_contao_act=index do=maintenance rt=1rH5O](https://user-images.githubusercontent.com/1045318/63020329-1f416380-be9e-11e9-9882-91a2c369f855.png)

**Comment by discordier** [comment]
Was supposedly introduced for #1032 in 58ec4ca.

**Comment by zonky2** [comment]
works fine
