### ISSUE TITLE
Get filter options with Mysql 5.7 throws an syntax error

### ISSUE THREAD

**Issue by baumannsven** [MetaModels/core#1335]
By the list view of an metamodel. Is there set a filter option from a base simple attribute.
Then throw mysql a syntax error.

```
An exception occurred while executing 'SELECT base_simple_attribute, COUNT(base_simple_attribute) as mm_count FROM mm_table WHERE id IN (?, ?, ?, ?, ?, ?, ?, ?) GROUP BY base_simple_attribute ORDER BY FIELD(id, ?, ?, ?, ?, ?, ?, ?, ?) ASC' with params ["2", "3", "8", "6", "9", "7", "82", "122", "2", "3", "8", "6", "9", "7", "82", "122"]:
```

```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mm_table' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

https://github.com/MetaModels/core/blob/fd19337bc5c2927296d65586c0cd94d547de9567/src/Attribute/BaseSimple.php#L161-L168

**Comment by baumannsven** [comment]
I think the order by in the statement is obsolete

**Comment by zonky2** [comment]
In my opinion, it should be sufficient to have the column from GROUP_BY in the select.

```diff
             $statement = $this->connection->createQueryBuilder() 
-                 ->select($strCol . ', COUNT(' . $strCol . ') as mm_count') 
+                 ->select('id, ' . $strCol . ', COUNT(' . $strCol . ') as mm_count') 
                 ->from($this->getMetaModel()->getTableName()) 
                 ->where('id IN (:ids)') 
                 ->groupBy($strCol) 
                 ->orderBy('FIELD(id, :ids)') 
                 ->setParameter('ids', $idList, Connection::PARAM_STR_ARRAY) 
                 ->execute(); 
```

**Comment by discordier** [comment]
I think I have fixed this with @stefanheimes and @davidmaack via phone some weeks ago. They promised to file an PR or commit themselves... what's up with that?

**Comment by zonky2** [comment]
@discordier ... @stefanheimes and @davidmaack make a performance fix - see https://github.com/MetaModels/core/pull/1339

this is another bug :(

**Comment by zonky2** [comment]
@baumannsven pls check this https://github.com/MetaModels/core/issues/1335#issuecomment-529227517

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/core/pull/1356
see https://medium.com/code-kings/mysql-5-7-getting-error-when-trying-to-group-by-try-this-37ad659c1de
thx at @baumannsven for your coworking
