### ISSUE TITLE
Missing ID in PostDuplicateEvent when pasting dataset

### ISSUE THREAD

**Issue by bezin** [MetaModels/core#1336]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 7.2.2.|                                  |
| Contao version:                     |4.4.42 |                                  |
| MetaModels version:                 |2.1.5|                                  |
| Installed MetaModels packages:      |All|                                  |
| DCG version:                        |2.1.5|                                  |

## Issue description

I have a simple MetaModel with some text attributes, an alias, translatedurl, tags and a select.
It is configured in the back end with manual sorting. I listen to the PostDuplicateModel to manually track changes across several meta models. 

When I have a metamodel without manual sorting in back end, the PostDuplicateEvent has an model id. This is handled in the [CopyHandler](https://github.com/contao-community-alliance/dc-general/blob/master/src/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php#L159-L183).

When I have a metamodel with manual sorting, the PostDuplicateEvent is thrown in [default controller](https://github.com/contao-community-alliance/dc-general/blob/master/src/Controller/DefaultController.php#L708-L724) without a model id.

## Steps to reproduce

1. Create meta model with manual sorting in back end
2. Listen to PostDuplicate
3. "Duplicate" an item, actually it is copy and paste. 

## Describe the behaviour of the application
The PostDuplicateEvent is dispatched once without ID.

## Describe the expected behaviour of the application
I expect it to have an ID, because it actually is the same as with the CopyHandler (at least to the editor).

**Comment by zonky2** [comment]
see https://github.com/contao-community-alliance/dc-general/issues/507

**Comment by baumannsven** [comment]
If have test it. And in the copied model has an id.

You use the event `dc-general.model.post-duplicate` and not `dc-general.model.pre-duplicate`.
The copied model in the event `dc-general.model.post-duplicate` has not a id.
