### ISSUE TITLE
Bei einer nicht übersetzte Legend wird die Default Sprache nicht angezeigt

### ISSUE THREAD

**Issue by MacKP** [MetaModels/core#1337]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.3.9     |                                  |
| Contao version:                     |    4.4.43      |                                  |
| MetaModels version:                 |      Version 2.1.1
(5.4.2019, 15:22:12)    |                                  |
| Installed MetaModels packages:      |    metamodels/bundle_all      |                                  |
| DCG version:                        |    2.1.5      |                                  |

## Issue description

Ich habe bei der Eingabemaske, wenn ich im Backend mit einer Sprache unterwegs bin, die nicht bei der Legend übersetzt wurde nur folgendes stehen: legend1_legend / legend2_legend / legend3_legend  usw.

## Steps to reproduce

1. Mehrsprachig MM anlegen - mit EN (fallback) / NL / JP als Sprachen - nicht DE
2. Eingabemaske definieren mit einer Legend, die Übersetzungen für alle drei Sprachen hat
3. Eingabemaslke aufrufen, wenn man mit DE im Backend angemeldet ist.

## Describe the behaviour of the application

Jetzt wird eben nicht die Fallback Sprache für die Legend angezeigt. Das war bei der Seite vorher (Contao 3 und uralte MM2.0 Version) das normale verhalten.

## Describe the expected behaviour of the application

Die Fallback-Sprache sollte hier genommen werden.

**Comment by discordier** [comment]
Fixed in fee0093.

Nice ticket number btw. :smile_cat:

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@MacKP could you please have a final look at this and tell if your issue has been resolved?
