### ISSUE TITLE
perPage Moduleinstellungen per GET-Parameter überschreiben

### ISSUE THREAD

**Issue by SGehle** [MetaModels/core#1338]
Ist es möglich, die perPage Moduleinstellungen für Listen per GET-Parameter zu überschreiben?

**Comment by zonky2** [comment]
Welche Moduleinstellungen sollen das sein?

btw: der Issue-Tracker ist eigentlich nicht für allgemeine Fragen gedacht, sondern für Bugs und Features - solche Fragen bitte im MM-Forum oder Slack stellen

**Comment by zonky2** [comment]
duplicated issue https://github.com/MetaModels/core/issues/868
