### ISSUE TITLE
Symfony 4 compatibility: "templating" service

### ISSUE THREAD

**Issue by richardhj** [MetaModels/core#1342]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |      7.3    |                                  |
| Contao version:                     |       4.8   |                                  |
| MetaModels version:                 |   2.1       |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |          |                                  |

## Issue description

When updating to Symfony 4, the following error occurs:
```
The service "metamodels.controller.inputscreen.add_all" has a dependency on a non-existent service "templating".
```

the solution is to add the following to the config:
```
templating:
    engines:
        twig
```

This ticket belongs to MetaModels or Contao core?

**Comment by dmolineus** [comment]
The template service is deprecated. I propose to inject twig directly

**Comment by richardhj** [comment]
Ah, thanks for the hint, I will look into it.
