### ISSUE TITLE
Standard backend search for a longtext field

### ISSUE THREAD

**Issue by heimseiten** [MetaModels/core#1343]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   7.3       |                                  |
| Contao version:                     |      4.4.44    |                                  |
| MetaModels version:                 |     2.1.1     |                                  |
| Installed MetaModels packages:      |   MetaModels Bundle-All       |                                  |
| DCG version:                        |    2.1.x-dev      |                                  |

## Issue description

In the MetaModels input screens I can select "Searchable" in the "Backend listing, filtering and sorting" section. This will not be shown in the backend list under "Search".

## Steps to reproduce

1. Select "Searchable" for a longtext field in the "Backend listing, filtering and sorting" section in the input screens
2. try to select the logtext in the "Search" select menu

## Screenshots

![Bildschirmfoto-2019-10-18-um-10 04 23](https://user-images.githubusercontent.com/6552484/67158809-1f962900-f33d-11e9-9ea9-18748791d68c.jpg)
![Bildschirmfoto-2019-10-18-um-10 04 57](https://user-images.githubusercontent.com/6552484/67158810-215fec80-f33d-11e9-8241-0ce52b931305.jpg)

**Comment by zonky2** [comment]
but at longtext - fixed https://github.com/MetaModels/attribute_longtext/pull/16
