### ISSUE TITLE
Key "auto_item" will not be recognized at URL in detail page

### ISSUE THREAD

**Issue by marcuslelle** [MetaModels/core#1348]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.2.10        |                                  |
| Contao version:                     |  4.4        |                                  |
| MetaModels version:                 |  2.1.5        |                                  |
| Installed MetaModels packages:      |  bundle_all   |                                  |
| DCG version:                        |          |                                  |

## Issue description

I use the alias as filter for a detail page and filled in the value "auto_item" in URL-parameter.
When clicking on the detail link in list view I get a 404 at detail page, although the URL seems to be correct.
Without out auto_item everything works as expected.

**Comment by zonky2** [comment]
I can't reproduce the behavior in any of our test cases

**Comment by zonky2** [comment]
@marcuslelle you can this issue reopen, if you more information
