### ISSUE TITLE
Attribute (Listenansicht): Falscher 'title' für 'Attribut einfügen'

### ISSUE THREAD

**Issue by ThomasJanotta** [MetaModels/core#1350]
Wenn man mit der Maus über das Plus-Icon fährt, steht dort "Neue Einstellung ... " statt "Neues Attribut ...".

Contao 4.4.45
MM bundle_all 2.1.1

![falscher_title](https://user-images.githubusercontent.com/8110641/68305451-fa791880-00a7-11ea-8080-fad7180cce4b.png)

**Comment by zonky2** [comment]
in Attribut-Ansicht

**Comment by ThomasJanotta** [comment]
Übrigens bei beiden, oben (Neu ... oben) und in der Liste der Attribute (Neu ... nach ...)

**Comment by discordier** [comment]
Must be fixed in transifex.

Translation keys in `tl_metamodel_attribute`:
- `tl_metamodel_attribute.pastenew.0`
- `tl_metamodel_attribute.pastenew.1`

**Comment by zonky2** [comment]
fixed
