### ISSUE TITLE
error if the attribute name already exists

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1351]
* Creating an attribute with an existing column name
* an error message appears (as exception and not as contao message!)
* Attribute is created nevertheless (tl_attributes)
* If the attribute is deleted, the original column of the MM table is deleted => **very bad!**

**Comment by zonky2** [comment]
ist MM 2.0 - wird nicht mehr bearbeitet

**Comment by discordier** [comment]
Is 2.1 not affected?

**Comment by zonky2** [comment]
in 2.1 comes a real error message
