### ISSUE TITLE
The column name "description" is invalid

### ISSUE THREAD

**Issue by m-r-h-n** [MetaModels/core#1364]
Moin,

hat sich an den reservierten Spaltennamen etwas geändert?
Der Name "description" ist nicht mehr möglich, bspw. für Attribut Text oder Langtext.

Hab den in Projekten recht häufig in Verwendung.

Core 2.1.7
Bundle-All  2.1.1
Contao 4.4.46

**Comment by zonky2** [comment]
@m-r-h-n das ist in MySQL 8 ein reserviertes Wort - siehe https://github.com/MetaModels/core/pull/1359/files#diff-8a20844e69aab5428835ee2de5684b7bR118

@discordier wie machen wir das bei einem Update vom Provider oder Umzug einer Installation?

**Comment by zonky2** [comment]
wir werden die Spaltennamen escapen #1374

**Comment by discordier** [comment]
Closed via #1392
