### ISSUE TITLE
Attribute display setting -> can't use NOT rule

### ISSUE THREAD

**Issue by Ainschy** [MetaModels/core#1365]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.2      |                                  |
| Contao version:                     | 4.4.46      |                                  |
| MetaModels version:                 |  2.1.7     |                                  |
| Installed MetaModels packages:      | bundle-all |                                  |
| DCG version:                        |  2.1,5  |                                  |

## Issue description
To invert an rule i cant set it into a NOT Rule, like OR or AND. This option is missing.

## Steps to reproduce

1. add a rule for display a attribute
2. add rule NOT 
3. try to move display rule into NOT rule like AND or OR Rule

## Describe the behaviour of the application
i dont't like to display a attribute  when an other attribute (select) is blank. 

## Screenshot
![Anzeigeeinstellungen_NOT-NICHT](https://user-images.githubusercontent.com/1788135/73190653-9ace5e80-4126-11ea-8076-d6c37a6b3b3c.png)

**Comment by zonky2** [comment]
Change to https://github.com/contao-community-alliance/dc-general/issues/515

**Comment by zonky2** [comment]
fix https://github.com/MetaModels/core/pull/1368

**Comment by zonky2** [comment]
fixed
