### ISSUE TITLE
check natural sorting at BE panels

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1366]
check natural sorting at BE panels - this is attribute type numeric

![Zwischenablage02](https://user-images.githubusercontent.com/1045318/73430984-9af57680-433f-11ea-811b-cb6650c54c5d.jpg)

**Comment by discordier** [comment]
Does only affect `attribute_numeric`, doesn't it?

**Comment by zonky2** [comment]
mybe - but "Jahr" is correct with
```
---
2019
2020
```

and ist not the order in the database table

**Comment by discordier** [comment]
But the correct numeric order. ;)

**Comment by zonky2** [comment]
nö

**Comment by discordier** [comment]
Of course it is.
```
---
2019
2020
```
Is the correct order.

**Comment by zonky2** [comment]
fix https://github.com/MetaModels/core/pull/1367
