### ISSUE TITLE
Unnötige Funktionslinks im Formular "Neuer Datensatz"

### ISSUE THREAD

**Issue by ThomasJanotta** [MetaModels/core#1370]
Durch eine fehlende deutsche Beschriftung (in mm 2.0.0) ist mir der Fehler erst aufgefallen.

Wenn man aus der BE-Liste eines Metamodels oben auf 'Neuen Datensatz' klickt, gelangt man zum Formular "Neuer Datensatz". Dort sind oben rechts AUCH (nochmal) die Funktionslinks 'Neuer Datensatz' und 'Mehrere bearbeiten'. Die gehören da ja nicht hin. Bei 'Mehrere bearbeiten' bekommt man natürlich einen Server-Fehler (nto implemented).

cto 3.5.x
mm 2.0.0
cto 4.4.40
mm 2.1

![error_neuerdatensatz](https://user-images.githubusercontent.com/8110641/74229250-51534700-4cc2-11ea-8c16-26222f812b17.png)

**Comment by zonky2** [comment]
Fixed in MM 2.2...?? zumindest taucht das hier nicht mehr auf
