### ISSUE TITLE
Error at save with API - pid doesn´t have default value - in strict mode

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1371]
Error at save with API - pid doesn´t have default value - in strict mode e.g. MariaDB

```php
use MetaModels\Item;

$modelName = 'mm_employees';
$factory   = $this->getContainer()->get('metamodels.factory');
$model     = $factory->getMetaModel($modelName);
$objItemMa = new Item($model, []);
$objItemMa->set('name', 'Mayer');
$objItemMa->save();

echo 'Generate item id: ' . $objItemMa->get('id');
```

**Comment by discordier** [comment]
The problem is, that the values are never added in `new Item()`, nor saved in `MetaModel::createNewItem()` or `MetaModel::saveItem()`.
In fact, the latter one postpones the saving of some system columns to `MetaModels::saveBaseColumns()` which does not work in strict mode anymore.

**Comment by zonky2** [comment]
not repeatable...
