### ISSUE TITLE
fix sorting in BE navigation

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1372]
fix sorting in BE

![screenshot_841](https://user-images.githubusercontent.com/1045318/75183138-247f4500-5742-11ea-939d-ea1d33179b9c.png)

**Comment by zonky2** [comment]
Contao 4.9 resetted the alphabetical sorting

**Comment by discordier** [comment]
Can you link the commit/issue here please?

**Comment by zonky2** [comment]
I have searched - found nothing :(
