### ISSUE TITLE
 SQLSTATE[3D000]-error during installation MM 2.1.8 and C4.4.47 

### ISSUE THREAD

**Issue by Sarahsolus** [MetaModels/core#1376]
MM: v2.1.8 (but also earlier versions, that were working 2 weeks ago)
Contao: 4.4.47
Php: 7.2

During installation of current MM v2.1.8 and Contao v4.4.47 via composer, near the end the installation breaks with these errors:

```
[WARNING] Some commands could not be registered:


In AbstractMySQLDriver.php line 113:

An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'':

SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected


In PDOConnection.php line 109:

SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected


In PDOConnection.php line 107:

SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected


[WARNING] Some commands could not be registered:


In AbstractMySQLDriver.php line 113:

An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'':

SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected


In PDOConnection.php line 109:

SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected


In PDOConnection.php line 107:

SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

```
----

- changing the composer.json entries to

"metamodels/bundle_all": "< 2.1.7",
"metamodels/core": "< 2.1.7",

doesn't help.

- removing those entries fixes the error (but also removes MM)...

- error happens on the server and also on local system. (both PHP7.2, MySQL5.7)
- installation broke when trying to add metamodels to an existing and working Contao
- installation also broke during installation of an new project

**Comment by discordier** [comment]
@zonky2 Can you reproduce this?

 @Sarahsolus Is there any chance you can provide us with a stack trace?

**Comment by zonky2** [comment]
@discordier getestet - kann ich nicht nachvollziehen... weitere Diskussion hier https://community.contao.org/de/showthread.php?77369-SQLSTATE-3D000-Fehler-bei-Installation-MM-2-1-8-und-C4-4-47

@baumannsven hatt sich angeboten, dass mal anzusehen - Kontakt per PM

**Comment by baumannsven** [comment]
Das Problem liegt wahrscheinlich am Warmup vom Cache. Wenn keine Datenbank konfiguriert ist. Werde mir später das mal anschauen

**Comment by Sarahsolus** [comment]
Erst einmal Danke nochmal an den netten Hilfesteller am Telefon. @baumannsven

Der Grund für den Fehler scheint tatsächlich zu sein, dass neuerdings eine parameters.yml samt schon vorhandener Datenbank von Metamodels erwartet wird.
Bei unserem git repo, das ich zur Contao Installation auf den Server klone, ist keine parameters.yml enthalten. (die wurde dann am Schluss erst mit contao/install erzeugt) Das war bisher kein Problem, und ist es auch weiterhin nicht, wenn ich kein Metamodels mitinstalliere.

Das macht den Deployment-Vorgang natürlich in Zukunft etwas zäher, wenn ich auf dem Server erst die parameters.yml umschreiben muss, aber grundsätzlich weiß ich jetzt erstmal, wie ich das Problem umgehen kann.
Vielen Dank für's Mitüberlegen.

**Comment by discordier** [comment]
Did we introduce this with the migrations? 🤔
IMO this is the only part that might interface with the database during boot time, however this should be limited to the install tool.

**Comment by discordier** [comment]
Excellent analysis by webstar in [this posting](https://community.contao.org/de/showthread.php?77369-SQLSTATE-3D000-Fehler-bei-Installation-MM-2-1-8-und-C4-4-47&p=521282&viewfull=1#post521282).

**Comment by dmolineus** [comment]
> Excellent analysis by webstar in this posting.

Great you found it, just wanted to repeat the information here. :-)

**Comment by discordier** [comment]
Working on the fix atm. :smile_cat:

**Comment by bezin** [comment]
I just tried it with the fix provided for https://github.com/contao-community-alliance/contao-polyfill-bundle/issues/5 and it IMO solved this issue here as well. I updated the CCA Polyfill Bundle and ran the post-install-cmd script. 

@Sarahsolus Could you please run `composer update` and try again?

**Comment by zonky2** [comment]
fixed https://github.com/MetaModels/core/pull/1378

**Comment by zonky2** [comment]
see https://github.com/MetaModels/core/releases/tag/2.1.9
