### ISSUE TITLE
Panel-Layout Error

### ISSUE THREAD

**Issue by SGehle** [MetaModels/core#1400]
## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.3.13        |                                  |
| Contao version:                     |  4.9.2        |                                  |
| MetaModels version:                 |  2.1.9         |                                  |
| Installed MetaModels packages:      |  bundle_all         |                                  |
| DCG version:                        |  2.1.7        |                                  |

## Issue description

![image](https://user-images.githubusercontent.com/1748990/79634991-5b843c80-816e-11ea-8005-9dd09863e3f3.png)

## Steps to reproduce

Open Panel-Picker

## Describe the behaviour of the application

Return value of Contao\CoreBundle\Translation\Translator::getFromGlobals() must be of the type string or null, array returned

## Describe the expected behaviour of the application

Show Panel-Picker

**Comment by zonky2** [comment]
MM 2.1 in Kombi mit C4.9 unterstützen wir nicht - siehe https://metamodels.readthedocs.io/de/latest/manual/install.html

entweder C4.4 nehmen oder MM 2.2 https://now.metamodel.me/de/unterstuetzer/fundraising#metamodels_2-2

**Comment by zonky2** [comment]
btw: in MM 2.2 gibt es die Picker nicht mehr - dafür eine Explanation ("Verkehrsschild" mit Popup)

**Comment by SGehle** [comment]
Danke für das schnelle Feedback. Ich habe nur das bundle_all installiert, dies ist bis jetzt nur in 2.1 verfügbar, daher wurde auch MM 2.1 installiert.

**Comment by zonky2** [comment]
ja, "wir" haben verpasst, MM 2.1 auf Contao 4.4 fest zu nageln - MM 2.2 ist ja über das EAP gegen einen Obolus von 350€ (sofort) einsetzbar
