### ISSUE TITLE
only the first entry of input masks is being applied

### ISSUE THREAD

**Issue by UB3RL33T** [MetaModels/core#1407]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.2      |                                  |
| Contao version:                     |     4.9     |                                  |
| MetaModels version:                 |     2.2.x-dev     |            core, the rest is a mix of 2.1 and 2.2.x-dev based on your default-composer.json (private repo)                     |
| Installed MetaModels packages:      |          |  metamodels/bundle_all + metamodels/contao-frontend-editing   |
| DCG version:                        |     2.1.7     |                                  |

## Issue description

I've defined two input screens via Metamodels, one where the administrator can see and edit records and another one for the FEE package so users can create records.

When defining multiple input screens it seems like only the first one in the list is being used, for FE & BE.

## Steps to reproduce

1. Create a simple metamodel setup with one table and some colums: [name],[comment]
2. Define two different input screens
~~3. Do not assign a backend group to the first input mask, like so:~~
![image](https://user-images.githubusercontent.com/21123031/82668049-413ff180-9c39-11ea-85bd-0215bc934d68.png)

EDIT: I've applied the workaround proposed by zonky2
My setup now looks like this: ![image](https://user-images.githubusercontent.com/21123031/83001535-2f30cb00-a00c-11ea-8ee8-e75ed6ae2a48.png)

I've assigned the BE input screen to be displayed in the BE Content section, the FE input screen is not assigned any BE section as it's only supposed to be used in FE for frontend editing.

## Describe the behaviour of the application

With this setup the Metamodel is displayed below all Sections:
![image](https://user-images.githubusercontent.com/21123031/82669480-ce844580-9c3b-11ea-8372-cca6bbeb3c4b.png)
and is actually using the FE input mask.

Same goes for the Frontend-editing module, it's using the FE input screen even though it's not assigned a frontend group.

When swapping the list entries so that the BE input screen is the first entry. The Metamodel is displayed in the correct section (so backend is working fine then) but FEE is then using the BE input mask even though it's not assigned a FE group.

~~Basically Metamodels is always using the first input mask in the list without respecting assigned groups.~~

EDIT: If either of the group assignments is left empty, the input mask will be applied in the respective mode regardless of other definitions following afterwards
So for this setup
![image](https://user-images.githubusercontent.com/21123031/83004077-79677b80-a00f-11ea-93af-d963169f0ff9.png)

The BE List will be applied in the frontend even though there is another input mask defined afterwards.
When assigning a different FE group to both entries in the list then it works.

## Describe the expected behaviour of the application

I'd expect, when creating multiple input masks, that the configuration is applied, e.g. the input mask assigned to a backend group and not a frontend group will not be applied in frontend and vice versa.

**Comment by zonky2** [comment]
pls use Contao 4.4 or upgrade to MM 2.2 - Contao 4.9 with MM 2.1 is not supportet

see https://community.contao.org/de/showthread.php?77886-F%C3%BCr-alle-die-MM-2-1-unter-CONTAO-gt-4-4-probieren-bitte-lesen!

**Comment by UB3RL33T** [comment]
@zonky2 I've upgraded to dev-2.2, I can still reproduce the bug :)

Should I edit my initial report or is it fine as is?

**Comment by zonky2** [comment]
I have assigned the ticket to MM 2.2 - but an update of the information would still be good

I can vaguely remember the problem - I think i created a "dead" usergroup without rights and chose this instead of "-"

**Comment by UB3RL33T** [comment]
I've updated the issue with the version numbers. 

Your proposed workaround works, I created an empty user group and assigned it to the backend section like so: 
![image](https://user-images.githubusercontent.com/21123031/83001535-2f30cb00-a00c-11ea-8ee8-e75ed6ae2a48.png)

Now my input screens work for the backend as well as the frontend. 

Thank you @zonky2

**Comment by zonky2** [comment]
I'll look for a better solution...

**Comment by zonky2** [comment]
@UB3RL33T
We discussed this in the MM cal: the selection "-" means, take all those who have not yet been on as a group - as "catch all" so to speak.
I will adapt the - as * and the documentation if necessary.

**Comment by zonky2** [comment]
fixed in MM 2.2 and manual https://metamodels.readthedocs.io/de/latest/manual/component/dca-combine.html#einleitung
