### ISSUE TITLE
Add filter and search in BE at list of attributes in attributes, render settings and input mask

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1410]
Add filter and search in BE at list of attributes in attributes, render settings and input mask

* Filter: type
* Search: name, column name, type

**Comment by zonky2** [comment]
add filter and search in attribute list

@baumannsven pls check filter - options are empty

**Comment by baumannsven** [comment]
https://github.com/contao-community-alliance/dc-general/issues/539

**Comment by baumannsven** [comment]
The filter options now available.

**Comment by zonky2** [comment]
works fine
