### ISSUE TITLE
Additional CSS/JS for Render Setting is not included when there are no items

### ISSUE THREAD

**Issue by cliffparnitzky** [MetaModels/core#1421]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 7.3.21 |                                  |
| Contao version:                     |4.4.51 |                                  |
| MetaModels version:                 | 2.1.9 |                                  |
| Installed MetaModels packages:      | - | variouse attributes |
| DCG version:                        | 2.1.7 |                                  |

## Issue description

Additional CSS/JS for Render Settings is not included in the backend when there are no items (empty list).

## Steps to reproduce

1. Define some CSS for the backend list (e.g. to define the width of the filter selects)
2. Set the CSS file in the render setting
3. Open the list and use the search with a value that delivers no results

## Describe the behaviour of the application

The additional defined CSS/JS for Render Setting is not included in the backend when there are no items (empty list).

## Describe the expected behaviour of the application

The additional defined CSS/JS for Render Setting should also be included in the backend when there are no items (empty list).

### At least 30 items ... the CSS for the filter is inclued
![s1](https://user-images.githubusercontent.com/1247552/90188350-9bc19780-ddbb-11ea-982b-7e6b1b9e845a.png)

### No items ... no CSS
![s2](https://user-images.githubusercontent.com/1247552/90188359-a0864b80-ddbb-11ea-82d8-0fed40b5e6e2.png)

**Comment by zonky2** [comment]
thx

**Comment by zonky2** [comment]
The CSS and Javascript is only for the items and not for the "environment". This is called in Item.php at parseValue.
For the BE please use the conventional way...

https://de.contaowiki.org/Stylesheet_f%C3%BCr_Backend-Theme_erg%C3%A4nzen

**Comment by cliffparnitzky** [comment]
Yeah, you're right ... "i saw the wood not bevore the trees" ... That is the easiest solution. And if i have both, styling the items and the list view parts, I can put them into the same CSS file.

In my opinion, we have to describe this in the manual. This should be enough.

**Comment by zonky2** [comment]
> In my opinion, we have to describe this in the manual. 

manual it´s OpenSource ;-)

**Comment by zonky2** [comment]
done https://metamodels.readthedocs.io/de/latest/manual/component/rendersettings.html#optionen
