### ISSUE TITLE
Bug with DBAL 2.11.0

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1425]
see https://github.com/doctrine/dbal/issues/4282

If we click at attribute icon or rendersetting... we have the follow error

```An exception occurred while executing 'SELECT id FROM tl_metamodel_attribute WHERE (pid = ?) AND () ORDER BY sorting ASC' with params ["1"]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY sorting ASC' at line 1```

see https://community.contao.org/de/showthread.php?78918-Nach-MM-Installation-Attibute-nicht-aufrufbar-SQL-Syntax-Error

Workaround:
set in your composer.json
`"doctrine/dbal": "~2.10.4"`

**Comment by discordier** [comment]
Tracked in https://github.com/contao-community-alliance/dc-general/issues/549
