### ISSUE TITLE
MM name show in BE ( to &#40; and ) to &#41;

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1429]
MM name show in BE ( to `&#40;` and ) to `&#41;`

MM 2.2 / C 4.9

**Comment by discordier** [comment]
Excuse me but... what?

**Comment by zonky2** [comment]
see https://easycaptures.com/fs/uploaded/1508/3504293507.png

**Comment by zonky2** [comment]
in MM 2.1 and C 4.4: `Mitarbeiter (öäüß)`

**Comment by zonky2** [comment]
fixed in MM 2.2
