### ISSUE TITLE
Add ordering of sort options for backend list view

### ISSUE THREAD

**Issue by cliffparnitzky** [MetaModels/core#1430]
Currently the sort options of a backend list view are ordered by ID (I suppose). The easiest and most Contao like improvement will be sorting alphabetically. But I think in some cases a custom manual order will be nice.

**Comment by zonky2** [comment]
@cliffparnitzky you mean the same like this? https://github.com/MetaModels/core/issues/74#issuecomment-14895886

**Comment by cliffparnitzky** [comment]
Sorry. I corrected the titel an description.

Meant was the backend view 
![image](https://user-images.githubusercontent.com/1247552/98669167-49a7f800-2351-11eb-8483-1cbc329a251c.png)

**Comment by zonky2** [comment]
may be this is a part of DCG ... @baumannsven ?

**Comment by cliffparnitzky** [comment]
> may be this is a part of DCG ... @baumannsven ?

Generally yes ... but if we want a manual ordering, we need it the MM view, where the sortings a displayed. Maybe we need a separate field in the rendering mask, to define the sorting.

**Comment by zonky2** [comment]
O.K. - I skipped that it's about sorting - you could make the items of the sorting sortable and use this order for the dropdown

**Comment by cliffparnitzky** [comment]
> ... you could make the items of the sorting sortable and use this order for the dropdown

Yes, that's the feature request 😀

**Comment by zonky2** [comment]
dca_metamodels_sortgroup.php

```php
    'list'                  => [
        'sorting'           => [
            'mode'         => 4,
            'fields'       => ['sorting'],
            'panelLayout'  => 'limit',
            'headerFields' => ['name'],
            //'flag'         => 1,
        ],
```

thats all

**Comment by zonky2** [comment]
fixed
