### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by Olli** [MetaModels/core#1433]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |          |           7.4                       |
| Contao version:                     |          |               4.9.10                   |
| MetaModels version:                 |          |                     2.2@dev             |
| DCG version:                        |          |              2.2@dev                    |
| Installed MetaModels packages:      |          |    folgende  |
```
 "metamodels/attribute_alias": "^2.2@dev",
    "metamodels/attribute_checkbox": "^2.2@dev",
    "metamodels/attribute_file": "^2.2@dev",
    "metamodels/attribute_longtext": "^2.2@dev",
    "metamodels/attribute_numeric": "^2.2@dev",
    "metamodels/attribute_select": "^2.2@dev",
    "metamodels/attribute_text": "^2.2@dev",
    "metamodels/attribute_timestamp": "^2.2@dev",
    "metamodels/attribute_url": "^2.2@dev",
    "metamodels/contao-frontend-editing": "^2.2@dev",
    "metamodels/core": "^2.2@dev",
    "metamodels/filter_checkbox": "^2.2@dev",
    "metamodels/filter_select": "^2.2@dev",
    "metamodels/filter_text": "^2.2@dev",                                
```

## Issue description

Ich habe eine Installation mit Firmeneinträgen. Alle haben eine Aliasfeld, was aus Firmenname und PLZ zusammengebaut wird.
Aliase werden korrekt erzeugt und in der Datenbank abgelegt.
Auf einer Seite im FE wird lediglich die Liste der Firmen ausgegeben (Seiten-ID 40*) . In den Rendereinstellungen wird bei "Frontend jump-to settings" auf die Listingseite(!) verlinkt (also {{link_url::40}}). 
Es werden aber keine Detailansichten von mir benutzt (war vorgesehen aber nicht umgesetzt). Es werden auch keine Links erzeugt die auf eine Detailseite zeigen könnten.
Das hat in MM 2.1 auf Contao 4.4 ohne Probleme funktioniert. Nach dem Update wird die Seite nicht mehr ausgegeben. Folgende Meldung kommt wenn man die Seite aufrufen will: 
```
[2020-12-29 07:47:11] request.CRITICAL: Uncaught PHP Exception
Symfony\Component\Routing\Exception\InvalidParameterException:
"Parameter "alias" for route "contao_frontend" must match ".+"
("firmenuebersichten/name/Bürobedarf,Verbrauchsmaterialien,Büro-%2FKommunikationstechnik,Mobilfunk
u. Zubehör,Büroausstattung,  Copy-Center,  Farbkopieren bis A3,Binden,Laminieren,Stempel  Webdesign u. Hosting/ortsteil/<*schnipp*>"
given) to generate a corresponding URL." at /var/www/vhosts/<*schnipp*>/vendor/symfony/routing/Generator/UrlGenerator.php
line 193 {"exception":"[object]
(Symfony\\Component\\Routing\\Exception\\InvalidParameterException(code:
0): Parameter \"alias\" for route \"contao_frontend\" must match \".+\"
(\"firmenuebersichten/name/Bürobedarf,Verbrauchsmaterialien,Büro-%2FKommunikationstechnik,Mobilfunk
. Zubehör,Büroausstattung,  Copy-Center,\n Farbkopieren bis A3,Binden,Laminieren,Stempel  Webdesign u.
Hosting/ortsteil/<*schnipp*>\" given) to generate a corresponding URL.
at
var/www/vhosts/<*schnipp*>/vendor/symfony/routing/Generator/UrlGenerator.php:193)"}
[]
```
Das Problem ist behoben, wenn ich anstelle von  {{link_url::40}}  den Link zu {{link_url::}} ändere.
Ich kann nicht sagen ob das Problem aufgetreten wäre, wenn man eine Seite mit Detailansicht verlinkt. 
In dem Log sieht man außerdem Inhalte eines kompletten Datensatzes mit Inhalt von verbundenen Tabellen.

## Steps to reproduce
siehe oben

mit diesen Einstellungen funtkioniert es und wenn {{link_url::40}} drin steht geht es nicht.

![Screenshot_2020-12-29 MetaModels c49](https://user-images.githubusercontent.com/1754/103276614-f2bcb780-49be-11eb-913b-207db1961618.png)

**Comment by zonky2** [comment]
kannst Du mal Updaten und das checken - irgendwie kann ich das nicht nachstellen...

**Comment by Olli** [comment]
Ich denke das Ticket kann zugemacht werden. Ich habe keine Möglichkeit das weiter zu testen damir die Daten fehlen und das Projekt sich anderweitig geholfen hat.

**Comment by zonky2** [comment]
ok
