### ISSUE TITLE
Manuelle Sortierung über "Burger"-Menu nicht möglich - JS Fehler

### ISSUE THREAD

**Issue by Ainschy** [MetaModels/core#1436]
## Checklist before I submit this issue report

I confirm that:
- [X ] I have tested this with the latest version available
- [X ] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X ] I have checked the Contao community forums for references https://community.contao.org/
- [X ] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.4      |                                  |
| Contao version:                     |    4.9.12      |                                  |
| MetaModels version:                 |    2.2      |                                  |
| Installed MetaModels packages:      |    2.2 dev      |                                  |
| DCG version:                        |   dev-release 2.2.0       |                                  |

## Issue description

Manuelle Sortierung über der "Burger" icon nicht möglich. Laut Console ein JS Fehler: 
Uncaught TypeError: Cannot read property 'tBodies' of null at GeneralTableDnD.init (vanillaGeneral.js?v=b9a07193:119)

## Steps to reproduce

1. Manuelle Sortierung bei einem MM auswählen
2. Das Burger Menu erscheint in der MM Listen Ansicht aber es zeigt keinen Funktion

## Describe the behaviour of the application

s.o.

## Describe the expected behaviour of the application

s.o.

## Screenshots

(Add some visual love or even a video if you can)

**Comment by zonky2** [comment]
Fixed: https://github.com/contao-community-alliance/dc-general/pull/566

**Comment by zonky2** [comment]
fixed in DCG
