### ISSUE TITLE
FE-Filter jumpTo-Page

### ISSUE THREAD

**Issue by cogizz** [MetaModels/core#144]
Ich nutze das FE-Filter ContentElement wie folgt:

Das CE-Filter ist auf der Home eingebunden und die Weiterleitung ist auf meine Lister-Seite gesetzt. Wenn ich jetzt das Formular abschicke, lande ich zwar auf der Lister-Seite, aber die URL ist ohne Filter gesetzt.

Ich vermute es liegt an der Zeile: https://github.com/MetaModels/core/blob/master/src/system/modules/metamodels/MetaModelFrontendFilter.php#L235
Dadurch wird die Action-Url auf die Lister-Seite gesetzt, was dazu führt das die Filter-Verarbeitung nicht ausgeführt wird.

Meiner Ansicht nach müsste das ganze wie folgt aussehen, durch diese Änderung wird al Action-Url immer die aktuelle Seite verwendet.

```php
global $objPage;
			
		// return filter data
		return array(
			'action'     => $this->generateFrontendUrl($objPage->row(), $this->getJumpToUrl($arrParams['other'])),
			'formid'     => $this->formId,
			'filters'    => $arrRendered,
			'submit'     => ($blnAutoSubmit ? '' : $GLOBALS['TL_LANG']['metamodels_frontendfilter']['submit'])
		);
```

**Comment by cboelter** [comment]
@discordier it looks like that is fixed?!

**Comment by discordier** [comment]
Is it? Have you tested?

**Comment by cboelter** [comment]
This part looks as the same as my fix
https://github.com/MetaModels/core/blob/c134bccc8e936ac8379fd19ca981e2fa856414e8/src/MetaModels/FrontendIntegration/FrontendFilter.php#L305-L318

I tested it with my testing movie database for tng. There it works if I go from the homepage to the and-filter-me page.

**Comment by discordier** [comment]
No, it does not look exactly the same as your fix used the global `$objPage` where the current code is still using the pqassed jumpTo page information.

**Comment by tim-bec** [comment]
is it fixed, or not?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cogizz could you please have a final look at this and tell if your issue has been resolved?

**Comment by xantippe** [comment]
Aktuelles Verhalten mit **Version 2.0.0-alpha6**

Um auf Seite A einen Filter zu haben, der auf Seite B eine Liste filtert, **muss** man auf **beiden Seiten** den selben Filter als **Modul** eingebunden haben - nur dann funktioniert die Filterung.

Die Kombinationen
A: CE-Filter => B: CE-Filter
A: CE-Filter => B: Modul-Filter
A: Modul-Filter => B: CE-Filter

funktionieren **nicht** :-(

btw: mir ist nicht so recht klar, warum auf Seite B der Filter "nochmal" eingebunden sein muss - es macht zwar in den meisten Fällen sicher Sinn, aber wahrscheinlich nicht immer...

**Comment by zonky2** [comment]
siehe https://metamodels.readthedocs.io/de/latest/cookbook/filter/filter-with-forwarding.html
