### ISSUE TITLE
Switch to github-actions

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1449]
Switch to github-actions - see e.g. https://github.com/MetaModels/core/pull/1448/files

1. [x] delete `.travis.yml`
2. [x] add `.github/workflows/diagnostics.yml` and change the first line
3. [x] fix `readme.md`
4. [x] fix `composer.json` with PHP 7.4, MM core 2.2, DCG 2.2, http**s** etc.
5. [x] fix unittests

Last update: 21.11.2022

## MM core
- [x] [x] MetaModels/core https://github.com/MetaModels/core/tree/master

## MM Attributes
- [x] [x] MetaModels/attribute_alias https://github.com/MetaModels/attribute_alias/tree/master
- [x] [x] MetaModels/attribute_checkbox https://github.com/MetaModels/attribute_checkbox/tree/master
- [x] [x] MetaModels/attribute_color https://github.com/MetaModels/attribute_color/tree/master
- [x] [x] MetaModels/attribute_combinedvalues https://github.com/MetaModels/attribute_combinedvalues/tree/master
- [x] [x] MetaModels/attribute_contentarticle https://github.com/MetaModels/attribute_contentarticle/tree/master
- [x] [x] MetaModels/attribute_country https://github.com/MetaModels/attribute_country/tree/master
- [x] [x] MetaModels/attribute_decimal https://github.com/MetaModels/attribute_decimal/tree/master
- [x] [x] MetaModels/attribute_file https://github.com/MetaModels/attribute_file/tree/master
- [x] [x] MetaModels/attribute_geodistance https://github.com/MetaModels/attribute_geodistance/tree/feature/2.2.0
- [x] [x] MetaModels/attribute_langcode https://github.com/MetaModels/attribute_langcode/tree/master
- [x] [x] MetaModels/attribute_levenshtein https://github.com/MetaModels/attribute_levenshtein/tree/master
- [x] [x] MetaModels/attribute_longtext https://github.com/MetaModels/attribute_longtext/tree/master
- [x] [x] MetaModels/attribute_numeric https://github.com/MetaModels/attribute_numeric/tree/master
- [x] [x] MetaModels/attribute_rating https://github.com/MetaModels/attribute_rating/tree/master
- [x] [x] MetaModels/attribute_select https://github.com/MetaModels/attribute_select/tree/master
- [x] [x] MetaModels/attribute_tablemulti https://github.com/MetaModels/attribute_tablemulti/tree/master
- [x] [x] MetaModels/attribute_tabletext https://github.com/MetaModels/attribute_tabletext/tree/master
- [x] [x] MetaModels/attribute_tags https://github.com/MetaModels/attribute_tags/tree/master
- [x] [x] MetaModels/attribute_text https://github.com/MetaModels/attribute_text/tree/master
- [x] [x] MetaModels/attribute_timestamp https://github.com/MetaModels/attribute_timestamp/tree/master
- [x] [x] MetaModels/attribute_translatedalias https://github.com/MetaModels/attribute_translatedalias/tree/master
- [x] [x] MetaModels/attribute_translatedcheckbox https://github.com/MetaModels/attribute_translatedcheckbox/tree/master
- [x] [x] MetaModels/attribute_translatedcombinedvalues https://github.com/MetaModels/attribute_translatedcombinedvalues/tree/master
- [x] [x] MetaModels/attribute_translatedcontentarticle https://github.com/MetaModels/attribute_translatedcontentarticle/tree/master
- [x] [x] MetaModels/attribute_translatedfile https://github.com/MetaModels/attribute_translatedfile/tree/feature/2.2.0
- [x] [x] MetaModels/attribute_translatedlongtext https://github.com/MetaModels/attribute_translatedlongtext/tree/feature/2.2.0
- [x] [x] MetaModels/attribute_translatedselect https://github.com/MetaModels/attribute_translatedselect/tree/feature/2.2.0
- [x] [x] MetaModels/attribute_translatedtablemulti https://github.com/MetaModels/attribute_translatedtablemulti/tree/feature/2.2.0
- [x] [x] MetaModels/attribute_translatedtabletext https://github.com/MetaModels/attribute_translatedtabletext/tree/feature/2.2.0
- [x] [x] MetaModels/attribute_translatedtags https://github.com/MetaModels/attribute_translatedtags/tree/master
- [x] [x] MetaModels/attribute_translatedtext https://github.com/MetaModels/attribute_translatedtext/tree/master
- [x] [x] MetaModels/attribute_translatedurl https://github.com/MetaModels/attribute_translatedurl/tree/master
- [x] [x] MetaModels/attribute_url https://github.com/MetaModels/attribute_url/tree/master

## MM Filter
- [x] [x] MetaModels/filter_checkbox https://github.com/MetaModels/filter_checkbox/tree/master
- [x] [x] MetaModels/filter_fromto https://github.com/MetaModels/filter_fromto/tree/master
- [x] [x] MetaModels/filter_perimetersearch https://github.com/MetaModels/filter_perimetersearch/tree/master
- [x] [x] MetaModels/filter_range https://github.com/MetaModels/filter_range/tree/master
- [x] [x] MetaModels/filter_register https://github.com/MetaModels/filter_register/tree/master
- [x] [x] MetaModels/filter_select https://github.com/MetaModels/filter_select/tree/master
- [x] [x] MetaModels/filter_tags https://github.com/MetaModels/filter_tags/tree/master
- [x] [x] MetaModels/filter_text https://github.com/MetaModels/filter_text/tree/master

## MM FEE
- [x] [x] MetaModels/contao-frontend-editing https://github.com/MetaModels/contao-frontend-editing/tree/feature/2.2.0
- [x] [x] MetaModels/dropzone_file_upload https://github.com/MetaModels/dropzone_file_upload

**Comment by baumannsven** [comment]
https://github.com/MetaModels/dropzone_file_upload

@zonky2 @discordier change the default branch to master please

**Comment by zonky2** [comment]
> @zonky2 @discordier change the default branch to master please

done

**Comment by zonky2** [comment]
all released...
