### ISSUE TITLE
Implement lightboxSize in tl_layout for files

### ISSUE THREAD

**Issue by MacKP** [MetaModels/core#1457]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   7.4.x       |                                  |
| Contao version:                     |  4.9.x        |                                  |
| MetaModels version:                 |   2.2.0       |                                  |

## Issue description

lightboxSize in the tl_layout is not used for the Lightbox Images at the Moment.

**Comment by zonky2** [comment]
How can I check this?

**Comment by MacKP** [comment]
1. Set lightboxSize in the PageLayout
2. Goto Rendersettings -> Check Link or Lightbox in file Attribute 
3. Goto Frontend and klick on Image for the Lightbox-View.

**Comment by MacKP** [comment]
The Size is in -> unserialize($GLOBALS['objPage']->getRelated('layout')->lightboxSize))

[2] -> width
[2] -> height
[2] -> ID of ImageSize

with and height are only set if you set it in the PageLayout.

**Comment by zonky2** [comment]
MM 2.2 implemented
