### ISSUE TITLE
[MM 2.2] Doppel-Länderkürzel (z.B. en-US oder en-CA) liefern Fallbacksprache DE statt EN zurück

### ISSUE THREAD

**Issue by leycommediasolutions** [MetaModels/core#1458]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.4        |                                  |
| Contao version:                     |  4.9        |                                  |
| MetaModels version:                 |  2.2        |                                  |
| Installed MetaModels packages:      |  all        |                                  |
| DCG version:                        |  2.2        |                                  |

## Issue description
Doppel-Länderkürzel (z.B. en-US oder en-CA) liefern Fallbacksprache DE statt EN zurück.

**Comment by zonky2** [comment]
@discordier: Das Verhalten kann ich in unserem Testcase nachvollziehen :(

**Comment by zonky2** [comment]
related with https://github.com/MetaModels/core/issues/739

**Comment by zonky2** [comment]
@leycommediasolutions wir arbeiten an dem Feature

**Comment by zonky2** [comment]
Add in MM 2.2

see "Change languages to use country code like en-US"
