### ISSUE TITLE
it is not possible to filter on the home page if the alias is index

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1460]
it is not possible to filter on the home page if the alias is `index`

Tested in MM 2.2

**Comment by discordier** [comment]
Need more details of the setup and data.

**Comment by zonky2** [comment]
I have MM-Filter at start page - if the alias e.g. home and I click the filter button, we rederect to URL

`domain.tld/home/filterkey/filtervalue`

o.k. - works fine, but I change the alias to index and I click the button we rederect to

`domain.tld`

without slug parameters...

`domain.tld/filterkey/filtervalue`

retrun a 404

**Comment by zonky2** [comment]
I have tested this in the Contao demo with the news and set the reader to the start page and changed the redirection accordingly - in the URL `index` is then added e.g.

`https://demo.contao.org/en/index/new-contao-versions-in-short-intervalls.html`

**Comment by zonky2** [comment]
hmm - at testcase works...

**Comment by zonky2** [comment]
apparently the problem only exists with certain providers and then also not in every directory/project ... hmmm???
The main problem is probably the `MultiViews` parameter - if this is switched off, it works fine.

```
<IfModule mod_rewrite.c>
# Needed on All-Inkl.
Options +FollowSymLinks -MultiViews -Indexes
...

```

Thanks at @discordier for your Knobelei :D
