### ISSUE TITLE
Problem with symfony/filesystem 

### ISSUE THREAD

**Issue by Misco** [MetaModels/core#1470]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                7.4        |          |                                  |
| Contao version:            4.9.34         |          |                                  |
| MetaModels version:    2.1             |          |                                  |
| Installed MetaModels packages:  starter    |          |                                  |
| DCG version:                        |          |                                  |

## Issue description

require symfony/filesystem ^3.3 || ^4.0 should be require symfony/filesystem ^3.3 || ^5.0
to avoid problem like this: https://community.contao.org/de/showthread.php?83789-ClassNotFoundError-unter-C4-9-34

## Steps to reproduce

1. create a new template

## Describe the behaviour of the application

Attempted to load class "Path" from namespace "Symfony\Component\Filesystem". Did you forget a "use" statement for e.g. "Webmozart\PathUtil\Path", "ScssPhp\ScssPhp\Util\Path" or "BaconQrCode\Renderer\Path\Path"?

## Describe the expected behaviour of the application

template selection

## Screenshots

(Add some visual love or even a video if you can)

**Comment by zonky2** [comment]
Wait for fix at Contao or use workaround https://github.com/contao/contao/pull/5298
