### ISSUE TITLE
Indexierung bei mehreren Domains

### ISSUE THREAD

**Issue by falkrussow** [MetaModels/core#1478]
| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.4     |                                  |
| Contao version:                     |    4      |                                  |
| MetaModels version:                 |     2.2     |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |          |                                  |

## Issue description

Ich habe in Contao mehrere Webseiten angelegt welche auf ein MetaModel zugreifen. In den unterschiedlichen Webseiten lass ich die Einträge gefiltert ausgeben. So erscheint unter Webseite A nur das was unter Webseite A erscheinen soll usw.

Nun möchte ich aber auch, dass die Url's in die Sitemap kommen. Leider ist es so, dass wenn ich die Indexierung anlege alle Url's in die Sitemap kommen und somit auch in der Sitemap von der Webseite A die Einträge von der Webseite B aufgenommen werden. Allerdings mit der Domain der Webseite A.

Ich kann das natürlich Filtern, dass nur die URL's von Webseite A indexiert werden doch dann gelangen die URL's von Webseite A in die Seitemap von Webseite B.

Somit werden dann in Google Adressen indexiert die es eigentlich gar nicht geben darf.

Ist es irgendwie möglich, dass man bei der Indexierung sagen kann in welche Sitemap oder für welche Domain / Startpunk das ganze sein soll?

siehe https://community.contao.org/de/showthread.php?84209-Indexierung-bei-mehreren-Domains

**Comment by zonky2** [comment]
pls check https://community.contao.org/de/showthread.php?84209-Indexierung-bei-mehreren-Domains&p=567041&viewfull=1#post567041
