### ISSUE TITLE
contao 4.13 and 5?

### ISSUE THREAD

**Issue by leon1995** [MetaModels/core#1482]
Hi,
can you give an estimation on when a MM version for contao 4.13 will be released?
Will there be a version for contao 5?

I have seen, that a beta for 4.13 is ready, but I havent found a way to download and install it. Can you give me a hint, please?

**Comment by zonky2** [comment]
MM 2.3 can only be obtained as early adopter against a donation until the release. More about this in the manual (unfortunately only in German).

https://metamodels.readthedocs.io/de/latest/manual/install.html#installation-von-mm-2-3-fur-contao-4-13-und-php-8

For Contao 5 there will also be a MM - whether as version 2.x or 3.x is not yet clear. We generally only support the LTS versions of Contao.

**Comment by leon1995** [comment]
Okay, but can you give an estimation about the release? Will it be published in the next weeks or in some months?

**Comment by zonky2** [comment]
We wait of round 85% of donations - See https://now.metamodel.me/de/unterstuetzer/fundraising

I'm afraid there won't be a release before Christmas....

But the current version runs stable and is in use in about 30 projects.

With a donation you can also use the 2.3...
