### ISSUE TITLE
Veröffentlichter Übersetzungsstatus greift nicht im Filter

### ISSUE THREAD

**Issue by k-webdesign** [MetaModels/core#1489]
Das Feld "Translated checkbox" ist zum Veröffentlichen von Elementen gesetzt und wird aber im Filterwidget Einzel- und Mehrfachauswahl ignoriert. Die Produktliste blendet den Eintrag aus, der Filter aber nicht.

MM 2.2

**Comment by zonky2** [comment]
Woher soll die Filterregel wissen, dass es auf eine Checkbox des Models, welches mit einer Relation verbunden ist, reagieren soll?

Ich sehe da aktuell zwei Möglichkeiten:

a) bei Attribut Select/Tags einen Filter einbauen, der die Checkbox prüft - das wird in MM 2.2 auch in FE-Ausgabe weiter gereicht
b) https://github.com/MetaModels/core/issues/1099

**Comment by k-webdesign** [comment]
Fix: Im Filter in der "Mehrfachauswahl" der Haken bei _Diesen Filter für verbleibende Werte ignorieren_ setzen
