### ISSUE TITLE
Ansichtsbedingungen des Eingabefeldes über einen Filter ansprechen

### ISSUE THREAD

**Issue by tognit** [MetaModels/core#1503]
Wäre es möglich die Ansichtsbedingungen eines Eingabefeldes über einen Filter anzusteuern?

z.B. Zeige das Feld A nur an wenn die Bedingungen des Filter (SQL usw.) erfüllt sind.

**Comment by zonky2** [comment]
bezieht sich die Frage auf das? https://community.contao.org/de/showthread.php?85943-Verschiedene-Eingabemasken

**Comment by tognit** [comment]
Ja das ist so!

**Comment by zonky2** [comment]
dann dort: https://community.contao.org/de/showthread.php?85943-Verschiedene-Eingabemasken&p=577721&viewfull=1#post577721
