### ISSUE TITLE
[MM 2.3] Issue with unique field validation after recent Contao update (4.13.40)

### ISSUE THREAD

**Issue by Webstylerin** [MetaModels/core#1506]
Hello,

today, I updated several installations to Contao 4.13.40, and I've encountered an issue where I can no longer edit records with unique fields. When attempting to save changes, I receive the following message:

"The property 'alias' is already in the database and not unique."

This issue also occurs with text fields marked as unique, even though the alias or text field values are indeed unique, as I am merely attempting to edit an existing record.

I have confirmed this behavior on two separate installations. Another installation still on Contao 4.13.39 does not exhibit this problem.

Best regards,
Nicole

**Comment by zonky2** [comment]
the problem is already on the operating table

**Comment by zonky2** [comment]
Alias should fixed - I check all other filter rules

**Comment by Webstylerin** [comment]
Thank you! Alias and text fields now work again with "unique".
