### ISSUE TITLE
API change MetaModelAttribute::prepareTemplate() - remove default value from $objSettings

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#163]
The default value for `$objSettings` of `null` should be removed from `MetaModelAttribute::prepareTemplate()` as we are generating the default RenderSettings if none has been supplied inline in `parseValue()` and we are using the settings object everywhere which is effectively resulting in an Exception when using the default value of `null`.

**Comment by xantippe** [comment]
noch aktuell?

**Comment by zonky2** [comment]
changed https://github.com/MetaModels/core/commit/c134bccc8e936ac8379fd19ca981e2fa856414e8
