### ISSUE TITLE
Sortieren im Frontend

### ISSUE THREAD

**Issue by guay** [MetaModels/core#167]
Derzeit lässt sich nur im FE-Modul der MetaModel-Liste bestimmen, wie die Sortierung (Sortieren nach... und Sortierreihenfolge) aussieht. Wäre es möglich eine Art Sort-Filter zu haben, der im Frontend die Sortierung der dargestellen Liste erlaubt?... Z.B. Sortieren anhand der gezeigten Attribute (oder einem Teil davon)

**Comment by xantippe** [comment]
+1

**Comment by xantippe** [comment]
m.E. kann das Issue damit erstmal geschlossen werden

**Comment by xantippe** [comment]
siehe https://github.com/MetaModels/core/issues/167#issuecomment-153660516
