### ISSUE TITLE
FR: Optional Eltern-Element in Variante darstellen

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#178]
Wenn man eine Variante eines Eintrags erstellt, wäre es toll oberhalb dieser über eine eigene Rendereinstellung gewisse Daten ausgeben zu lassen (z.b. Name, Bild, Beschreibung, ...) um die Variante eleganter anlegen / bearbeiten zu können.

**Comment by zonky2** [comment]
MM call 25.05.2021: eine Möglichkeit wäre, dass die Widgets aus dem Hauptdatensatz im Variantendatensatz als Readonly dargestellt werden
