### ISSUE TITLE
Titel bei Kind-Tabelle

### ISSUE THREAD

**Issue by tognit** [MetaModels/core#184]
Wenn man eine MM als Kind-Tabelle verwendet, steht im Kopfbereich (tl_label) "tstamp".
Schöner wäre der Titel der Kind-Tabelle.
![tl_label](https://f.cloud.github.com/assets/1794459/594976/bf0fa9be-cac9-11e2-8f1a-66adf8040631.jpg)

Oder habe ich da was übersehen?

Grüessli
Steven

**Comment by cboelter** [comment]
@discordier kannst du mir hier vllt. einen Schubser in die richtung geben, wo man das einbauen müsste?
Wir brauchen dieses Feature relativ dringend für ein Projekt.

**Comment by discordier** [comment]
Implement an listener for `ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetParentHeaderEvent`.
https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Event/GetParentHeaderEvent.php#L43

**Comment by cboelter** [comment]
thanks, I will have a look on it.

**Comment by dmolineus** [comment]
@discordier Can be closed. Got fixed with the referenced pull requests above.
