### ISSUE TITLE
Filter als Content-Element: Weiterleitung funktioniert nicht

### ISSUE THREAD

**Issue by MaryLou1** [MetaModels/core#207]
Wenn ein Filter als Content-Element (MetaModel_Frontendfilter) eingebunden wird, funktioniert die Ausgabe des Filters auf eine Weiterleitungsseite nicht. Es werden dann, ohne Fehlermeldung, alle Datensätze ausgebeben, Filterparameter ist "futsch".

Wenn der gleiche Filter mit den gleichen Einstellungen als MODUL in die Seite eingebunden wird, funktioniert alles einwandfrei.

Ich konnte das auch mit/bei der "Movie Database" nachbauen. Filtertyp "Einzelauswahl". Aktuelle Nightly-stable (15.6.2013).

**Comment by xantippe** [comment]
https://github.com/MetaModels/core/issues/144#issuecomment-159545304
