### ISSUE TITLE
translated-Select-Optionen in aktuell zu bearbeitender Sprache?

### ISSUE THREAD

**Issue by Hendriks** [MetaModels/core#232]
Weiss nicht, ob das in den Core gehört... Ich versuche es aber auf jeden Fall *einfach* und *verständlich* zu illustrieren:

#### SOLL-Zustand (meiner Meinung nach):

__1)__ Benutzersprache __DE__ ; Eingabemaske für __DE__ :

__Hersteller:__ Hugendubel _[ nicht-übersetztes Select ]_
__Artikelnummer:__ "365" _[ nicht-übersetztes Text-Feld ]_
__Haupt-Farbe: Schwarz__ _[ übersetztes Select ]_
__Beschreibung:__ "Dieses Produkt besteht aus..." _[ übersetztes Text-Feld ]_

__2)__ Benutzersprache __DE__ ; Eingabemaske für __EN__ :

__Hersteller:__ Hugendubel
__Artikelnummer:__ "365"
__Haupt-Farbe: Black__
__Beschreibung:__ "This product is made of..."

__3)__ Benutzersprache __EN__ ; Eingabemaske für __DE__ :

__Manufacturer:__ Hugendubel
__Article number:__ "365"
__Main Color: Schwarz__
__Description:__ "Dieses Produkt besteht aus..."

__4)__ Benutzersprache __EN__ ; Eingabemaske für __EN__ :

__Manufacturer:__ Hugendubel
__Article number:__ "365"
__Main Color: Black__
__Description:__ "This product is made of..."

Hier in diesem Beispiel lege ich zu Grunde, dass DE die Standard-Fallback-Sprache ist; und EN eine "Übersetzung".

Besonderes Augenmerk liegt hier auf dem __übersetzten Select__. Dessen Optionen (hier aktiv: "Schwarz" bzw. "Black") sollten sich —meiner Meinung nach— doch immer nach der Sprache der (aktuell aktiven) Eingabemaske richten. Im Moment ist dies jedoch nicht der Fall. Daher dieses Ticket.

Alternative Regelung: Alle Labels, alle übersetzten Select-Optionen und alle sonstigen übersetzten Werte (Felder) richten sich immer / ausschließlich nach der BE-Benutzersprache (unabhängig von der aktiven Sprache der Eingabemaske). Am hiesigen Beispiel würde das den Konstellationen 1 und 4 entsprechen.

Im Moment ist es des weiteren so, dass wenn für das übersetzte Select keine Übersetzung (EN) hinterlegt ist und in der Eingabemaske DE bereits eine Option ausgewählt/gespeichert wurde, dann in der entsprechenden Eingabemaske EN die Option aber nicht (mehr/auch) eingeloggt ist, sondern auf "leer" steht. Das soll sicherlich nicht so sein, oder?

...getestet unter der DEV vom 29.06.13...

**Comment by xantippe** [comment]
@cogizz & @tim-bec 
im aktuellen MM (core 2.0.0-alpha8) sehe ich die Angaben und Übersetzungen so wie in "SOLL" beschrieben - ist die Sache noch aktuell oder kann Ticket geschlossen werden?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Hendriks could you please have a final look at this and tell if your issue has been resolved?
