### ISSUE TITLE
MetaModels API?

### ISSUE THREAD

**Issue by der-On** [MetaModels/core#236]
It would be great to have an API so other extensions can interactive with metamodels.

Possible usecases:

- CRUD existing metamodels
- Retrieve attribute-definitions
- programaticly create metamodels + filters + views (usefull for deployment as metamodel definitions are in-code)

**Comment by xantippe** [comment]
Hallo "der-On",
ich nehme an, Du möchtest mit den CRUD-Aktionen nicht das MetaModels als solches bearbeiten/beeinflussen, sondern die Inhalte bei einem angelegten MM - richtig?

Eine REST- oder SOAP- o.ä. Schnittstelle gibt es (noch) nicht - jedoch ist über die Interfaces vieles schon so gekapselt, dass man damit sicher gut seine eigene Schnittstelle bauen kann.

Siehe Handbuch unter "Interfaces" (noch im Aufbau!) http://metamodels.readthedocs.org/de/latest/reference/api.html

**Comment by xantippe** [comment]
@der-On kann das Issue mit dem Hinweis auf Quelltext + Handbuch geschlossen werden?

**Comment by der-On** [comment]
Ja gern

**Comment by xantippe** [comment]
dann mach es doch bitte...
