### ISSUE TITLE
Frontendfilter mit weiterleitung auf Seite mit Liste + Frontendfilter

### ISSUE THREAD

**Issue by der-On** [MetaModels/core#242]
Ich habe folgende Konstelation:

Auf Seite A befindet sich ein Frontendfilter, welcher Filtereinstellung A benutzt aber nur einen Teil der Felder der Filtereinstellung verwendet. Der Frontendfilter leiter hier auf Seite B weiter.

Auf Seite B befindet sich ebenfalls ein Frontendfilter, welcher auch Filtereinstellung A benutzt, hier aber alle Felder verwendet. Zusätzlich befindet sich hier noch eine Liste, welche ebenfalls die Filtereinstellung A verwendet.

Bei der Weiterleitung von Seite A auf Seite B werden die Filterwerte via POST übertragen und dann nicht in die URL, also die GET-Parameter übernommen.

Der Grund liegt in ModuleMetaModelFrontendFilter->getParams()
https://github.com/MetaModels/core/blob/master/src/system/modules/metamodels/MetaModelFrontendFilter.php#L156

und in ModuleMetaModelFrontendFilter->getFilters()
https://github.com/MetaModels/core/blob/master/src/system/modules/metamodels/MetaModelFrontendFilter.php#L202

Hierbei wird die formId im POST verglichen, welche natürlich nicht übereinstimmt, weil es zwei verschiedene Formulare sind (die aber die gleichen Filtereinstellungen verwenden).

Mögliche Lösung wäre:
Den Formularen die id der Filtereinstellung mitgeben und darauf vergleichen, statt auf die formId.

Verwandte Issues sind: #144 und #207

Bei den beiden kommt aber noch folgendes Problem hinzu:
https://github.com/MetaModels/core/blob/master/src/system/modules/metamodels/ModuleMetaModelList.php#L73

Das Listen-Modul wertet nur die GET-Parameter aus, nicht aber die POST parameter. Ein kurzer Test hat gezeigt, dass man hier auch schreiben könnte:

```
->setFilterParam($this->metamodel_filtering, deserialize($this->metamodel_filterparams, true), array_replace($_GET, $_POST))
```

**Comment by xantippe** [comment]
Bug oder Feature
https://github.com/MetaModels/core/issues/144#issuecomment-159545304

**Comment by xantippe** [comment]
ungetestet:
* Seite A mit Filter A -> leitet auf Seite B
* Seite B mit Filter A (per CSS versteckt) + Filter B

Filter A sollte aus den POST-Parametern die URL erzeugen und an die Ausgabeseite zurückleiten - sofern die Attribute aus Filter A in Filter B enthalten sind, sollten diese auch die Werte aus der URL übernehmen - z.B. als Select

**Comment by zonky2** [comment]
siehe https://github.com/MetaModels/core/issues/144#issuecomment-159545304 "Nachtrag"

Filter als Modul in beide Seiten einbinden - Contao-Limitierung wg. Form-ID-Check

**Comment by zonky2** [comment]
oder https://metamodels.readthedocs.io/de/latest/cookbook/filter/filter-with-forwarding.html
