### ISSUE TITLE
Header panel: Filter

### ISSUE THREAD

**Issue by daniel-nemeth** [MetaModels/core#247]
Hallo.
Wenn man ein Attribut 'timestamp' hat, und dieses als Filter für das Header-Panel nutzen möchte, wird nicht das formatierte Datum angezeigt, sondern der Timestamp selbst.

![screen shot 2013-07-31 at 13 09 42](https://f.cloud.github.com/assets/5083254/885540/bcbeae94-f9d1-11e2-95ca-8cfa88b288e2.png)

**Comment by dmolineus** [comment]
Gonna be fixed by https://github.com/MetaModels/attribute_timestamp/pull/17
