### ISSUE TITLE
Kleiner Bug bei Sortierung der Rendereinstellungen

### ISSUE THREAD

**Issue by Hauge** [MetaModels/core#259]
Das Drag&Drop beim sortieren der Rendereinstellungen funktioniert lediglich von oben nach unten - alles was man von unten nach oben schiebt wird wieder zurück gesetzt.

**Comment by xantippe** [comment]
getestet in dev-master (5e3248c7) [04.11.2015]
=> D&D an erste Stelle bei Rendering funktioniert

**Comment by stefanheimes** [comment]
Info oder Fehler ? @xantippe

**Comment by xantippe** [comment]
Info, dass es **funktioniert**
