### ISSUE TITLE
Insert tag to details view

### ISSUE THREAD

**Issue by tristanlins** [MetaModels/core#284]
I would propose an insert tag to the details view, I know it require more than the record id, but it would be realy handy.

**Comment by zonky2** [comment]
MM call 25.05.2021: macht Ainschy

**Comment by Ainschy** [comment]
Jupp

**Comment by zonky2** [comment]
@Ainschy wie weit bist du in dem Jahr gekommen? :D

**Comment by zonky2** [comment]
@discordier I check the current inserttags... we have the "jump to"-tag as generate the link, or not?

see https://github.com/MetaModels/core/blob/ffbf7e27ca2c91096aa9ecbe813409347184dcfc/src/FrontendIntegration/InsertTags.php#L53

`mm::jumpTo::[MM Name|ID]::[Item ID]::[ID render setting](::[Parameter (Default:url)|label|page|params.attname])`

**Comment by zonky2** [comment]
see https://github.com/MetaModels/core/issues/284#issuecomment-1015137548

**Comment by discordier** [comment]
@zonky2 How can one use this insert tag? Do you have a working example? I do not get it.
