### ISSUE TITLE
Umlaute CSS OpenSansLight

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [MetaModels/core#288]
Mir ist aufgefallen das der Umlaut 'ü' in der Fallbackschrift angezeigt wird.

Der Fehler ist zu beheben, wenn man die Schrift als Google-Font einbinded.
Müssen natürlich nichtt alle Schriftschnitte sein.

<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

Im style.css Zeile 54 hab ich es behoben für die Lightvariante.
  aside div[class^="ce_"],
  aside .widget, 
  .clearall,
  div[class^="ce_"] p, 
  div[class^="ce_"] li {
    font-family: 'Open Sans', sans-serif;
    font-weight:300 ;
  }

**Comment by hella-schu** [comment]
Ist zwar ein altes Ticket, kann aber das Problem bestätigen für die aktuellen Versionen von Firefox und Chrome sowie für IE11.

**Comment by zonky2** [comment]
> Ist zwar ein altes Ticket, kann aber das Problem bestätigen für die aktuellen Versionen von Firefox und Chrome sowie für IE11.

* Welche Seite (URL)
* was muss ich tun?

**Comment by hella-schu** [comment]
z.B.: https://now.metamodel.me/a-movie-database/de/15/departed-unter-feinden.html
Rechte Leiste, 'Zurück zur Übersicht'

**Comment by Floxn** [comment]
Dieses Phänomen mit dem "Ü" ist mir auch schon mehrfach untergekommen. Bisher aber immer nur in Firefox.
Hier besteht das "ü" dann immer aus zwei zwischen, einmal das u und dann noch die beiden Punkte als neues Zeichen.
Meine Theorie: Beim Einfügen eines Textes aus einem anderen Programm wird das Ü irgendwie falsch interpretiert. Bearbeitet man den Text dann im RTE müssen erst beiden Zeichen gelöscht werden und eine manuelle Eingabe des "ü" behebt dann den Fehler.

Bin mal gespannt was ihr noch so heraus findet.

**Comment by zonky2** [comment]
auch wenn ich im Firebug ein ü Ü einfüge, sieht es "unschön" aus... m.E. werden statische Font-Dateien verwendet - ggf. sind die etwas alt

**Comment by zonky2** [comment]
... per Google: keine einheitliche Lösungsstrategie gefunden... 

* machmal hilft es wohl, die Umlaute neu einzugeben - ggf. ist was an UTL8 "verdreht"
* oder wir nehmen eine andere Schrift https://superdevresources.com/open-sans-alternatives/
