### ISSUE TITLE
[feature] Einträge in Eingabemaske direkt in Subpalette sortieren / verschieben

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#292]
Es wäre toll, Einträge direkt in eine Subpalette hinein verschieben zu können.

Also ungefähr so:
![mm-palettensortierung](https://f.cloud.github.com/assets/1793396/1191677/e783f7c0-2455-11e3-8a50-33cba74ab158.png)

**Comment by xantippe** [comment]
@tim-bec wie sieht man in der Auflistung wo bzw. was eine Subpalette bildet? das müsste in der Anzeige auf alle Fälle mit rein...

**Comment by tim-bec** [comment]
@xantippe hab grad keine installation mit aktuellem mm und subpalette zur hand, würde aber entweder hinter dem attributstyp ein [subpalette] (in grün) ergänzen oder die ganze zeile entsprechend formatieren.

**Comment by xantippe** [comment]
Hmmm... habe mir das nochmal angesehen - ich kann mir nicht vorstellen, wie man aus dem möglichen Regelwerk a) eine grafische Anzeige hin bekommt noch b) eine Zu-/ bzw. Einordnung per Klemmmappe...

**Comment by zonky2** [comment]
we close this after discussion
