### ISSUE TITLE
Attribut "behält" seine Eigenschaft wenn es geändert wird (date to text)

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#296]
MM Stable
Contao 2.11.11

Ich hatte ursprünglich ein Datums-Attribut angelegt und dieses später in ein Text Attribut umgewandelt. 
Wenn ich hier nun z.b. 2011/2012 eingeben will speichert das attribut nur 2011. Ebenso bei 2011-2012. Aber auch 01.02.2012 verwirft es und speichert nur 01...

**Comment by xantippe** [comment]
getestet mit Contao 3.5.6 und MM core 2.0.0-alpha8

* Attribut "Datum" angelegt und mit Daten befüllt (2015-12-30)
* Typ von Datum auf Text geändert (Daten wurden gelöscht)
* neuer Wert 205/2016 eingetragen => wurde anstandslos angenommen

m.E. besteht das Problem nicht mehr und das Ticket kann geschlossen werden...
