### ISSUE TITLE
Neues Attribut: MultiColumnWizard

### ISSUE THREAD

**Issue by andreasisaak** [MetaModels/core#30]
Wir brauchen wirklich mal den MCW für die MetaModels

**Comment by xantippe** [comment]
1+

**Comment by MoniqueHahnefeld** [comment]
1+

**Comment by MoniqueHahnefeld** [comment]
Könnte man hier nicht für ein Select als Ersatz den TableLookUPWizard anknüpfen?
Das wäre vielleicht am einfachsten, oder?
https://github.com/terminal42/contao-tablelookupwizard

**Comment by xantippe** [comment]
Hallo Monique,
ich sehe auf den ersten Blick keine großartigen Unterschiede zwischen dem TLupW und dem bestehenden Attribut "Auswahl/Mehrfachauswahl" - für mich ist die Anfrage eher wie

https://community.contao.org/de/showthread.php?51895-FR-Element-mehrfach-eingeben-k%F6nnen-wie-bei-MultiColumnWizard

https://community.contao.org/de/showthread.php?21986-MultiColumnWizard-DCA-Felder-kombinieren

**Comment by MoniqueHahnefeld** [comment]
@xantippe Ich glaube Du hast mich nicht verstanden :D
https://github.com/MetaModels/attribute_tabletext  + TLUW meinte ich....

**Comment by xantippe** [comment]
hmmm... kann auch sein...

m.E. geht es um ein "Attribut" bei dem man 
a) mehrere Spalten definieren kann und
b) in den "Zellen" der Spalten verschiedene Möglichkeiten wie Text, Select-Auswahl, File-Auswahl, Link usw. hat sowie
c) in der Eingabemaske mehrere gleichartige Zeilen befüllen kann

Ein Attribut Select ist im MM doch enthalten - warum sollte man das austauschen?

**Comment by MoniqueHahnefeld** [comment]
@xantippe das Problem ist das der MultiColumnWizard  bzw der Aufbau ein serialisiertes Array übergibt, was nicht gut ist. Zu Gunsten der Normalisierung der Datenbank-Struktur habe ich daher den Gedanken gehabt, dass man einen Mittelweg vorerst finden kann. 

Bsp:
Textfeld was im Attr Table Select schon geht könnte also reichen wenn ich den Redakteur mit dem TLUW unterstütze.

Das waren so in etwa meine Gedanken dazu. Die Schwierigkeit bei dem Ganzen ist ja unter anderen die Kompatibilität mit den Einstellmöglichkeiten der Filter.

**Comment by xantippe** [comment]
o.k. ...

**Comment by MoniqueHahnefeld** [comment]
@xantippe ja, ich glaube das hängt hier vom Einzelfall und von den Anforderungen ab... muss man einfach mal programmieren und Testen xD.

**Comment by xantippe** [comment]
"muss *man* einfach" => oder Frau ;-)

**Comment by Aybee** [comment]
> "muss man einfach" => oder Frau ;-)

Das ist nicht witzig, da hättest du genauso gut schreiben können

*"MutliColumnWizard" => oder Fahrrad ;-)*

http://www.duden.de/rechtschreibung/man_jemand_irgendeiner_irgendeine

**Comment by xantippe** [comment]
ich glaube zwar nicht, dass Monique mir beim nächsten Stammtisch den Kopf abreißt, aber Du sollt Deinen Seelenfrieden haben

**Comment by MoniqueHahnefeld** [comment]
lol, doch das mach ich :D

**Comment by xantippe** [comment]
o.k. dann komme ich gleich ohne ;-)

**Comment by MoniqueHahnefeld** [comment]
+1

**Comment by zonky2** [comment]
s.u.A.
http://metamodels.readthedocs.io/de/latest/manual/extended/attribute_mcw.html

**Comment by zonky2** [comment]
work with
* https://github.com/MetaModels/attribute_tablemulti
* https://github.com/MetaModels/attribute_translatedtablemulti
