### ISSUE TITLE
[Contao3] Class 'MetaModels\Helper\UpgradeHandler' not found

### ISSUE THREAD

**Issue by HellPat** [MetaModels/core#303]
`Fatal error: Class 'MetaModels\Helper\UpgradeHandler' not found in /system/modules/metamodels/config/runonce.php on line 18`

=> Contao3 Nightly

**Comment by JanMalte** [comment]
Beim ersten Durchlauf der Installation von MM wird versucht der Wert von der einen Spalte in die andere zu kopieren. Dies wird zum Beispiel durch folgenden Code ausgelöst:
https://github.com/MetaModels/core/blob/tng/src/MetaModels/Helper/UpgradeHandler.php#L56

**Comment by Zeromax** [comment]
Habe das Problem auch.
Jeweils via Install tool upgrade und die Dateien nicht via Composer sondern aus der Zip Datei.

Folgender Workflow
* unter Contao 3.2 Upgrade MM1 auf MM2
* Contao 3.2 mit MM2 upgrade auf Contao 3.5.4
* DB Update Schritt auf 3.3 kein Problem
* DB Update Schritt auf 3.5 den folgenden Fehler
```
( ! ) Fatal error: Class 'MetaModels\Helper\UpgradeHandler' not found in /var/www/htdocs/projekt/system/modules/!metamodels-tng-branch/config/runonce_0.php on line 23
Call Stack
#	Time	Memory	Function	Location
1	0.0009	231608	{main}( )	.../install.php:0
2	0.1913	939552	Contao\BackendInstall->run( )	.../install.php:24
3	0.2188	1606168	Contao\BackendInstall->adjustDatabaseTables( )	.../BackendInstall.php:177
4	0.2189	1606304	Contao\Backend->handleRunOnce( )	.../BackendInstall.php:628
5	0.2467	1652256	include( '/var/www/htdocs/projekt/system/modules/!metamodels-tng-branch/config/runonce.php' )	.../Backend.php:273
6	0.2468	1653136	runonce_be4b5be1a9dece4d55082b9dd868885d->run( )	.../runonce.php:36
7	0.2505	1654192	require_once( '/var/www/htdocs/projekt/system/modules/!metamodels-tng-branch/config/runonce_0.php' )	.../runonce.php:14
```

Datei unter `system\modules\!metamodels-tng-branch\config\runonce_0.php` Zeile 23 auskommentiert dann lief es durch.

So wie es aussieht geht die runonce unter C3.5 nicht.
