### ISSUE TITLE
Fallback languages problem.

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#311]
Ich hab mir die Core Klasse vom MM eben angeschaut. Siehe hierzu https://github.com/MetaModels/core/blob/contao3/src/system/modules/metamodels/MetaModels/MetaModel.php#L282.

Durch diesen umbau haben wir das System zu grob eingestellt. Es wird nun nicht mehr für jedes Attribute geprüft ob ein Wert in der Zielsprache vorhanden ist, sondern nur noch ob allgemein Daten vorhanden sind. 

Damit haben wir die Feinheit, dass ein Attribute, wenn es keine bzw. nur teil Daten in der Zielsprache hat die Fallbacksprache benutzt, entfernt. Was eigentlich ein Rückschritt ist von dem was MM mal konnte. 

Hier muss eigentlich wieder ein Workflow eingerichtet werden, dass jedes complexe/translated Attribute nach seinen Daten gefragt wird und dieses entscheiden kann ob nun die Zielsprache oder die Fallbacksprache zurück gegeben wird oder ein mix aus beiden.

**Comment by discordier** [comment]
No feedback from @stefanheimes and @davidmaack, closing therefore as assumed to be fixed.
