### ISSUE TITLE
Allgemein Filter - Count Funktion

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#312]
Ich habe mir die Filter mal angeschaut. Es gibt die Möglichkeit die Anzahl für jede Filter Option auszugeben. 

Nun haben wir aber das Problem das die Filter nacheinander Aufgerufen werden, Ihre Liste mit den ID zurück geben und dann gleich den Count berechnen. 
Allerdings wenn der 1. Filter die Values berechnet hat und der letzte Filter fertig ist, hat sich unter Umständen die Anzahl der Items geändert. Somit wäre das Ergebnis vom 1. Filter nicht mehr richtig. Da sich die Anzahl der sichtbaren Items geändert hat. 

Damit bekommen wir immer falsche Count Werte im Filter, für eine Option.

Meiner Meinung nach müsste im 1. Durchgang alles gefiltert werden und in einem 2. Durchgang die Filter nach den richtigen Count Values befragt werden, weil wir dann die fertige Liste mit den ID`s haben.

Oder sehe ich das falsch ?

Zusatz:

Ich hab das Problem auch das die Filter den Count berechnen, aber andere Filter wie Veröffentlicht nicht mit einbeziehen. Somit hab ich immer all Werte auch von den Elementen die nicht angezeigt werden sollten.

**Comment by tim-bec** [comment]
@stefanheimes ist das noch valid?

**Comment by discordier** [comment]
Er antwortet nicht, also mach ich zu.

**Comment by Aybee** [comment]
Ich denke ich habe hier mehr oder weniger das Gleiche. Vorab eine Frage: Welchen Wert soll **count** anzeigen, den allgemeinen (total) oder den **nach** der Filterung?

Beispiel mit **multiselect**:
- **trader A**
  - apples
  - pears
- **trader B**
  - apples
  - plums
- **not filtered**
  - apples 2
  - pears  1
  - plums  1
- **filtered by pears** (current solution)
  - apples **2**
  - pears  1 (selected)
- **filtered by pears** (expected)
  - apples **1**
  - pears  1 (selected)

Ich wäre dafür, dass hier die zweite Version (expected) genommen werden soll. Die momentane Situation ist nur sinnvoll für single select, oder?

_Ich habe hier erst mit **einem** Filter getestet. Mal sehen, was sich ergibt, wenn mehrere Filter vorhanden sind. Dann wirds wahrscheinlich noch komplizierter._

**Comment by MacKP** [comment]
So war es und so sollte es eigentlich auch wieder sein : Es wird immer das gezählt, was NACH der Filterung raus kommt (sonst wäre es nutzlos, da ja auch Items gezählt werden würde, die nicht im Frontend ausgegeben werden sollen).

Viele Grüße

**Comment by Aybee** [comment]
Hallo Marc, das ist fein, dann kann ich dem Kunden sagen, dass das irgendwann korrigiert wird.

Muss natürlich drauf geachtet werden, dass das nur bei multiselect ist (checkboxes). Bei singleselect (radios) würde bei Auswahl eines anderen radios das momentane radio ja wieder deaktiviert.

Kann jemand das Ticket dann bitte wieder öffnen?

**Comment by zonky2** [comment]
Info vom MM-Call "Februar 2016":

> Welche "Strategie" soll es beim Zählen (count) von Items beim Filter geben?
>
> => Es sollte so sein, das immer das ausgegeben wird, was dann als Anzahl raus kommt, wenn man den Filter benutzt (also z.B. den jeweils einzelnen Tag). Grundlage müßte also immer die aktuell gefilterte Liste sein.
>
> Für eine spätere Beta vorgesehen.

**Comment by zonky2** [comment]
Info vom MM call 03.09.2020:

Um bei mehreren Filterwidget vorauszuberechnen, was eine Einstellung für eine Ausgabeanzahl hervorbringt, müsste man alle Filtermöglichkeiten voraus ausführen und berechnen. Die aktuellen Zahlen sind wie oben beschrieben "mit Vorsicht zu genießen" und stimmen nur bei sehr einfachen Filteraufbauten.

Zudem macht die aktuelle Implementierung Probleme mit dem `strict mode`, so dass die Option in MM 2.2 abgeschaltet wird.

Ggf. kann das als separate Funktion eingebaut werden - aber nicht wie aktuell bei den allemeinen Queries.

**Comment by zonky2** [comment]
Fixed in MM 2.2
Templates angepasst
