### ISSUE TITLE
FR: Attribute nach anlegen sperren

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#334]
Wenn ein Attribut angelegt wurde, sollte es hinsichtlich seiner "Attributart" gesperrt werden, also das nachträgliche wechseln von z.b. text auf translatedtext nicht mehr möglich sein.

**Comment by xantippe** [comment]
@tim-bec 

m.E. kann das Ticket geschlossen werden weil

* Warnung vorhanden (Screenshot)
* in Handbuch http://metamodels.readthedocs.org/de/latest/manual/component/attribute.html#einleitung
* zu dem Thema kaum (noch) Postings im Forum

![shot35](https://cloud.githubusercontent.com/assets/1045318/12086391/171ff9e8-b2ca-11e5-8093-accca818f3dc.jpg)

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@tim-bec could you please have a final look at this and tell if your issue has been resolved?
