### ISSUE TITLE
Data Provider - resetFallback

### ISSUE THREAD

**Issue by andreasisaak** [MetaModels/core#35]
ResetFallback 

Vorgaben:
Tabele X hat ein Feld isDefault. Diese ist markiert als Fallback.

Funktionsweise:
1. Eintrag im Datensatz A das isDefault aktive ist.
2. Eintrag im Datensatz B, hier wird auch angeben das isDefault aktiv ist.

Nun werden alle Felder isDefault in der DB zurückgesetzt, anschließend wird isDefault für Datensatz B aktiviert.

Siehe im Seitenbaum für languageFallback.

_--- Originally created by stefanheimes_

**Comment by xantippe** [comment]
@andreasisaak: was??..

**Comment by discordier** [comment]
Das geht eher an @stefanheimes. Siehe den Nachsatz von Andreas.

**Comment by zonky2** [comment]
siehe https://github.com/contao-community-alliance/dc-general/issues/303

**Comment by discordier** [comment]
Meanwhile implemented - however still suffers from #1018. Closing here therefore.
