### ISSUE TITLE
Filter with GET and POST elements.

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#358]
If we use selects and simple linklist we got the problem that after a submit all values for the linklist are lost. 

At a short view in der MetaModelFrontendFilter i found the main problem. See 
https://github.com/MetaModels/core/blob/master/src/system/modules/metamodels/MetaModelFrontendFilter.php#L241

In my opinion the `$arrParams['other']` isn't right. We should use the  `$arrParams['all']` because we want all current params.

@discordier What do you think about this ? Should we change this or do we get some bad side effects.

**Comment by xantippe** [comment]
@discordier ist das nun Bug oder Feature?

**Comment by zonky2** [comment]
obsolete...
