### ISSUE TITLE
Invalid Markup Validation HTML5 [Filter Widget]

### ISSUE THREAD

**Issue by UlrichHolland** [MetaModels/core#374]
Validator:

Line 1, Column 6509: The for attribute of the label element must refer to a form control.

…submitonchange">  label for="value"  /label <fieldset id="value" c…

**Comment by xantippe** [comment]
Meiner Meinung nach, wäre ein "HTML-Conformer" Umbau relativ leicht zu bewerkstelligen - dazu müssten die folgenden Sachen umgebaut werden

1.) in mm_filter_default.html5 muss
```
<div class="widget <?php echo $filter['class']; ?>">
	<?php echo $filter['label']; ?>
	<?php echo $filter['value']; ?>
</div>
```
zu
```
<div class="widget <?php echo $filter['class']; ?>">
	<?php echo $filter['value']; ?>
</div>
```
und die Anzeige Label oder Legend wird dem "Sub-Template" filteritem überlassen

2.) Filter\Simple.php sollte eine Generierung des Legend erhalten - siehe https://github.com/MetaModels/core/blob/fa305c9d3ce55fa0a7c92b37599e09b5c46161a1/src/MetaModels/Filter/Setting/Simple.php#L408
```
            'label'      => $objWidget->generateLabel(),
           'legend'    => generateLegend($arrWidget);
....
function generateLegend($arrWidget) {
    return '<legend>'.$arrWidget['raw']['label'][0].'</legend>';
}
```

3.) in den Templates mm_filteritem_NN kann anschließend je nach HTML-Markup ein Legend oder Label eingebaut werden

Da die vorhanden Templates weiter funktionieren, sollte der Umbau keine Probleme bereiten...

**Comment by zonky2** [comment]
o.k. Problem wurde besprochen - PR wird vorbereitet

**Comment by zonky2** [comment]
Fixed in MM 2.2
