### ISSUE TITLE
getFilterOptions - Return all values, but "onlypossible" is active

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#379]
If you have no result anymore, all filters return as filter otpions all values they have. I think this is totally wrong when we are using "onlypossible".

The main problem is that in all attributes the "getFilterOptions" use a simple if($arrIds), but a `array()` is returned on this condition a FALSE. So in my opionion we have to add a check at the beginning.

``` php
if(is_array($arrIds) && empty($arrIds))
{
    return array();
}
```

If we have an array the "onlypossible" is active and if this array is empty we have no id's. So the only possible value is ... nothing or better say an empty array() as is it defined in MetaModels.  

@discordier The question is should we add this in each attribute or in each filter because if we have an empty array and want all possible values, the return is an empty array everytime. So if i have nothing why should i get something more than nothing.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@stefanheimes could you please have a final look at this and tell if your issue has been resolved?
