### ISSUE TITLE
Icon in der MetaModels Übersicht für die direkte Bearbeitung

### ISSUE THREAD

**Issue by andreasisaak** [MetaModels/core#382]
Wir haben zwar schon viele Icons aber ich würde noch eins hinzufügen. Und zwar würde ich den allgemeinen Stift neu verlinken das du direkt in do=mm_exampletable ankommst und die beiden gekreuzten Stifte (neu in Contao 3.2) für die Bearbeitung der MetaModels Settings.

Dann wäre es auch konform zu den News und Events.

**Comment by xantippe** [comment]
@andreasisaak: was meinst Du mit "gekreuzte Stifte"? das Icon
system/themes/default/images/header.gif

das wäre "Schraubendreher+Maulschlüssel"

**Comment by xantippe** [comment]
@andreasisaak: ich kann  nicht recht nachvollziehen wo du das meinst - auf der "MM-BE-Hauptseite" haben alle Icons als GET ...do=metamodels...

**Comment by discordier** [comment]
Das geht btw. nur bei stand alone MetaModels... ich glaube wir lassen es daher lieber.
Die Backend integration hat man so ja eigentlich schon sauber, oder?

**Comment by xantippe** [comment]
ich habe immer noch keinen Plan, wo, welches Icon erscheinen soll - da nach 2 Jahren niemand weiter an dem Problem sich "gerieben" hat, kann das Ticket auch erstmal zu...
