### ISSUE TITLE
Icons in Kindtabellen tauschen

### ISSUE THREAD

**Issue by andreasisaak** [MetaModels/core#383]
Dort sollten wir unser eigenes MM Icon durch die beiden gekreuzten Stifte ersetzen die in Contao 3 hinzugekommen sind. Als Fallback in Contao 2 kann man ja immer noch die das eigene Icon dafür nehmen.

**Comment by xantippe** [comment]
in der aktuellen Version core 2.0.0-alpha8 sehe ich als "Kind-Icon" das hier

![shot36](https://cloud.githubusercontent.com/assets/1045318/12138705/1e5eda34-b45b-11e5-9c6f-32e30c0c35a7.jpg)

meinst Du das? und willst

![shot37](https://cloud.githubusercontent.com/assets/1045318/12138714/346892ca-b45b-11e5-875c-7b42470605ab.jpg)

das?

Da man bei den Eingabemasken inzwischen ein **eigenes Icon** angeben kann, würde ich vorschlagen, das einzublenden (wenn vorhanden) - als Default finde ich das aktuelle nicht so unpassend... ggf. das hier als Alternative

![shot38](https://cloud.githubusercontent.com/assets/1045318/12138741/7efb4c4c-b45b-11e5-93ea-d3a5271b4a0d.jpg)

das Icon "Maulschlüssel+Schraubendreher" steht für mich eher für "Eigenschafts-Einstellungen" und nicht für bearbeiten...

**Comment by zonky2** [comment]
nicht mehr aktuell
