### ISSUE TITLE
Filter mit allen Definitionen kopieren

### ISSUE THREAD

**Issue by AgentCT** [MetaModels/core#385]
Es wäre schön, wenn man einen Filter mit allen gemachten Einstellungen kopieren könnte. Braucht man einen Filter mit leichten Abwandlungen häufig wäre das eine riesen Erleichterung.

**Comment by xantippe** [comment]
getestet /core 2.0.0-alpha8:

* ein komplettes Filterset kann über die Funktion "Mehrere bearbeiten" (scheinbar) kopiert werden - es wird aber nur ein "leeres" neues Filterset erzeugt...
* ... jedoch kann man die Filterregeln des "Filtersets A" über "Mehrere Bearbeiten" + "Kopieren" in "Filterset B" übertragen/duplizieren

**Comment by xantippe** [comment]
beim Kopieren sollte das neue Filterset den Zusatz "Kopie" erhalten - siehe https://github.com/contao-community-alliance/dc-general/issues/109

**Comment by zonky2** [comment]
Beim Kopieren über die Funktion "Mehrere bearbeiten" werden vorhandene Hierarchien nicht mit übertragen

Quelle:
![shot180](https://cloud.githubusercontent.com/assets/1045318/14133186/57e0ac04-f64d-11e5-88b2-76feca9b09b3.jpg)

Ziel:
![shot181](https://cloud.githubusercontent.com/assets/1045318/14133187/57e54a98-f64d-11e5-9bc5-a64a666209de.jpg)

**Comment by baumannsven** [comment]
Das Problem liegt am Clipboard selbst. Dieses lässt nur ein Element. Bei mehrere kopieren wird dann Effektiv das letzte selektierte Element kopiert.

**Comment by zonky2** [comment]
es werden alle vier kopiert - aber ohne die Hierarchie, so dass Einfache Abfrage + SQL "Kinder" von ODER sind...

**Comment by zonky2** [comment]
Problem besteht bei MM 2.4 immer noch...

**Comment by zonky2** [comment]
ist im DCG und MM 2.3 gefixt - neuer Button für "Deep-Copy"

![grafik](https://github.com/user-attachments/assets/f5f5d43e-c903-4898-97d6-a1eaba65ad76)
