### ISSUE TITLE
Feature: Inserttags Redakteursfreundlich erweitern

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#398]
Redakteure die in einem mm einen anderen mm Eintrag verlinken wollen (z.B. Newseintrag mit verweis auf Projekt) müssen dazu aktuell das lange jumpTo Konstrukt verwenden: {{mm::jumpTo::mm_projects::1::6}}

Problem: Die Rendersettingsid bekommt der Redakteur eigentlich nicht raus.

Lösung: 
- Erweiterung der Rendersettings um ein Input für einen "inserttagAlias"
- jumpTo erweitern das man was wie mm::shortJumpTo::projectDetail::1 bauen kann - also den "inserttagAlias" übergibt. Das Rendersetting wiederum kennt sich ja selbst (z.b. id 6) und auch das metamodel ( z.b. id 2)

**Comment by xantippe** [comment]
@tim-bec Hallo Tim, ich glaube, wenn jemand die "MM-Tabelle" als "mm_projects" und die Item-ID (1) raus bekommt, bekommt auch die Render-Einstellung-ID (6) heraus.

An der Stelle wäre die Frage, ob man nicht ein Inserttag mit {{mm:jumpTo:mein_alias}} die "redakteursfreundlichere Wahl/Variante" wäre... wenn ja, sollte das eher in eigenes Modul

Ich sehe hier (noch) keinen allgemeinen Bedarf.

**Comment by zonky2** [comment]
better way https://now.metamodel.me/de/unterstuetzer/fundraising#redakteurmodul
