### ISSUE TITLE
[Contao 3.2.9] Nicht-sichtbare Attribute im Template als Wert abfragbar / Subpaletten und Template

### ISSUE THREAD

**Issue by cyberlussi** [MetaModels/core#402]
Bezugnehmend auf https://community.contao.org/de/showthread.php?49584-gel%F6st-Stand-MM-Subpaletten ein Feature- oder Optimierungs-Request:

In einem (FE) Template sind die Attribute verfügbar, die per Rendersettings "sichtbar" geschaltet wurden. Möchte man im Template aber auf "nicht sichtbare" Attribute zugreifen, so geht dies nicht, da diese im Array der Daten NULL sind. Es müsste eine Möglichkeit geben, im Template auf bestimmte oder alle Daten eines Eintrages zugreifen zu können, ohne dass diese angezeigt werden und die vorgefertigten Templates weitestgehend verwendet werdet können.

**Während die Anfrage oben ganz allgemein ist, könnte man auch alternativ den Umgang mit Subpaletten im Speziellen verfeinern**: nämlich dadurch, daß MM im Template automatisch Subpaletten und deren Sub-Attribute nach Belegung in- bzw. exkludiert werden. Das Attribut, welches die Subpaletten aktiviert, darf dann aber auch nicht ausgeben werden (z.B. "1"). Dies würde zumindest meinem Anwendungsfall vollständig genügen.

Beispiel (Subpalette "Galerie hinzufügen")
* Subpalette "Galerie hinzufügen" aktiviert im BE ein "Galerie" File-Attribut. Die Galerie soll nur dann angezeigt werden, wenn dies durch den Nutzer per Checkbox "Galerie hinzufügen" gewünscht ist.
* im FE Template z.B. metamodel_prerendered.html5 kann man zwar auf $this->data[] zugreifen, aber das Feld für "Galerie hinzufügen", welches im Template die Anzeige steuern soll ist NULL (egal ob 1oder 0 in DB gesetzt), da es nicht zur Anzeige (würde "1" ausgeben) gedacht ist und in den Rendersettings als nicht-sichbar geschaltet ist. 
* Als workaround muss man ein Template für die Subpaletten aktivierende Checkbox erstellen, das nichts ausgibt und das Attribut in den Rendereinstellungen sichtbar schalten, dann wird es in das $this->data[] array eingefügt und kann abgefragt werden, um die Galerie anzuzeigen oder auch auszublenden. Dies hat den Nachteil, dass 2 MM Templates manuell angepasst werden müssen.

**Hinweis**: alles unter der Annahme, dass im Modul "Keine Datensätze parsen" inaktiv ist (Verhalten von mir dann nicht geprüft)

**Comment by xantippe** [comment]
Aktueller Stand: Contao 3.5.6 MM core 2.0.0-alpha8

Die raw-Daten werden immer ausgegeben - dazu können die Attribute ausgeblendet sein bzw. müssen nichtmal in der FE-Render-Ausgabe aufgefüht bzw. eingeladen sein

Siehe #484 

wenn das die Frage war - Ticket bitte schließen...

**Comment by cyberlussi** [comment]
Hi, nein das stimmt so glaube ich nicht. Ich habe auch den letzten Stand mit CTO 3.5.6 installiert (metamodels/core dev-master (900dbda5)).

Wenn ich in den Rendersettings eines MM einzelne Attribute im FE ausblende (Auge mit Kreuz), erscheinenen diese nicht im [raw] Teil von $this->data - nur die sichbaren Attribute sind dort gelistet. Beispiel siehe unten: mal mit Bild, mal ohne.

Somit ist für mich dieses Ticket und #484 nicht gelöst (inhaltlich gleichwertig): Ich finde es sinnvoll, dass das $this->data[..][raw] Segment alle Elemente aus der Datenbank beinhaltet. 

Im Moment gibt es doch schon eine MM-List Einstellung unter "MetaModel Render-Einstellung > Keine geparsten Items über "$data" ausgeben", könnte man da nicht noch eine Einstellung "Alle Attribute eines Items über "$data" ausgeben" hinzufügen, die entweder den aktuellen Zustand "raw = nur sichtbare" oder "raw = alle" darstellt?


![2016-01-04_12_34_28_-_metamodels_-_contao_open_source_cms_3_5](https://cloud.githubusercontent.com/assets/4976687/12088895/91fffc7a-b2df-11e5-87cd-c8e71e41818f.png)
```
Array
(
    [0] => Array
        (
            [raw] => Array
                (
                    [id] => 3
                    [pid] => 0
                    [sorting] => 128
                    [tstamp] => 1451409283
                    [title] => Sed auctor neque eu tellus rhoncus ut eleifend
                    [image] => Array
                        (
                            [bin] => Array
                                (
                                    [0] => 5�b
З�I��e�O
                                )

                            [value] => Array
                                (
                                    [0] => 35cc620d-d097-11e4-b849-f6950765e54f
                                )

                            [path] => Array
                                (
                                    [0] => files/upload/photo-1426443177319-df7c639993c8.jpg
                                )

                        )

                    [attachments] => Array
                        (
                            [bin] => Array
                                (
                                )

                            [value] => Array
                                (
                                )

                            [path] => Array
                                (
                                )

                        )

                    [detailed_text] => Vivamus hendrerit arcu sed erat molestie vehicula. 
```
![2016-01-04_12_35_31_-_metamodels_-_contao_open_source_cms_3_5](https://cloud.githubusercontent.com/assets/4976687/12088902/ab3d3590-b2df-11e5-94e6-73491dad3672.png)
```
Array
(
    [0] => Array
        (
            [raw] => Array
                (
                    [id] => 3
                    [pid] => 0
                    [sorting] => 128
                    [tstamp] => 1451409283
                    [title] => Sed auctor neque eu tellus rhoncus ut eleifend
                    [attachments] => Array
                        (
                            [bin] => Array
                                (
                                )

                            [value] => Array
                                (
                                )

                            [path] => Array
                                (
                                )

                        )

                    [detailed_text] => Vivamus hendrerit arcu sed erat molestie vehicula.
```

**Comment by MacKP** [comment]
Wenn, dann sollte das konfigurierbar sein. Pauschal immer alles Ausgeben ist nicht gut, da man ja mehrere Listen auf einer Seite ausgeben kann mit jeweils unterschiedlichen Attributen (um das Layout besser hin zu bekommen). Wenn da immer alles drinn wäre, dann würde das recht lahm werden.

Viele Grüße

**Comment by xantippe** [comment]
@cyberlussi 
Ich habe nochmal mit dem selben dev-master (900dbda) die Sache getestet - wie gesagt, ich kann die Attribute in der Render-Einstellung löschen und es werden (trotzdem) bei raw alle Attribute angezeigt - kannst Du bitte prüfen, ob Du irgendwelche Caches an hast?

**Comment by cyberlussi** [comment]
@xantippe 
In meiner lokale MAMP Umgebung (PHP 5.6.10) habe ich den Cache auf "aus". Ich habe in CTO "Internen Cache umgehen" aktiv und Komprimierungen aus. "MetaModels Cache" hat angeblich 0 Dateien.  Habe unter Systemwartung alle "Daten bereinigt" und in der Paketverwaltung mal aus releases gestellt.
contao-community-alliance/dc-general 	2.0.0-beta31
metamodels/core 	2.0.0-alpha8
Meine Ausgabe erfolgt direkt im Artikel-Baum als "MetaModel-Liste", ich bin in einer Detailansicht mit eigenem Template, Ausgabe erfolgt per "dump($this->data);"
Ich wüsste jetzt nicht, wo ich da noch einen Cache habe. --> Gleiches Verhalten wie von mir oben beschrieben!

Wie gibst du denn die RAW Werte aus? Per Modul?

**Comment by cyberlussi** [comment]
Moment ... du sagst "in den Rendereinstellungen löschen" .... kurz probiert: auch ein gelöschtes Attribut in den Render-Einstellungen wird nicht als RAW angezeigt.

**Comment by xantippe** [comment]
ich habe im Template ein "print_r" und gabe das per CE-MM-Liste aus
bitte sende mir mal Deine E-Mail per PN im Forum (zonky) - ich kann Dir einen Snapshot von mir zusenden

**Comment by cyberlussi** [comment]
Mit der Umgebung von Xantippe konnte ich folgendes, ich denke auffälliges Verhalten nachvollziehen - **ist das so gewollt?**

Render-Einstellungen vollständig ohne Attribute
-> alle Attributwerte im RAW array gelistet

Ich habe dann alle Attribute durch "alle hinzufügen" hinzugefügt - aber alle noch unsichtbar gelassen
-> alle Attributwerte im RAW array gelistet

Dann habe ich das erste Attribut sichtbar gemacht (Name) 
-> Ausgabe in RAW array enthält nur noch "name"!!!!

```
    [0] => Array
        (
            [raw] => Array
                (
                    [id] => 93
                    [pid] => 0
                    [sorting] => 0
                    [tstamp] => 1451566598
                    [name] => Avery
                )

            [text] => Array
                (
                    [name] => Avery
                )

            [attributes] => Array
                (
                    [name] => Name
                )

            [html5] => Array
                (
                    [name] => <span class="text">Avery</span>
                )

            [class] => first even
            [jumpTo] => Array
                (
                )
        )
```
Wenn also wenigstens ein Element sichtbar ist, werden nur die sichtbaren ins RAW array hinzugefügt ....

**Comment by xantippe** [comment]
Interessanter Effekt

* Einmal alle Attribute hinzufügen
* Alle auf Sichtbar schalten
* Anschließend unsichtbar schalten oder löschen

=> Nachdem ein Attribut einmal auf sichtbar geschaltet wurde, ist es offensichtlich in raw enthalten... und kann dann aber wieder entfernt werden

... ob das so gewollt war??

**Comment by discordier** [comment]
Nein war es nicht. Das ist definitiv falsch.

**Comment by xantippe** [comment]
o.k. - vielleicht wäre ein guter Kompromiss, wenn in raw immer dann angezeigt wird, wenn das Attribut in der Render-Liste als Attribut auftaucht - egal ob sichtbar oder nicht.

somit könnte man alle "drei Zustände" 
* gar keine Ausgabe
* in raw
* in raw und HTML5 bzw. Text

recht leicht bewerkstelligen

**Comment by cyberlussi** [comment]
+1

**Comment by zonky2** [comment]
I'll check, has the current version the same phenomenon?

**Comment by zonky2** [comment]
Test mit MM core a13 und DCG beta38

MM mit "Mitarbeiterliste" (siehe Handbuch) mit einigen Textfeldern und einem Select auf MM "Abteilung"

Rendering für FE angelegt und MM-CE-Liste - keine Filter oder sonstige Einstellungen - Standardtemplate mit Debugausgabe (siehe Handbuch)

Start: 
1.) **Render-Einstellungen OHNE Attribute**
![shot268](https://cloud.githubusercontent.com/assets/1045318/18026908/66f1e086-6c55-11e6-9b83-f7e4816669fa.jpg)

=> im Ausgabearray ist für jedes Daten-Item ein Knoten vorhanden, raw ist vollständig gefüllt
![shot269](https://cloud.githubusercontent.com/assets/1045318/18026916/a685751e-6c55-11e6-917b-427f850a5193.jpg)

=> das hat zur Folge, dass in dem Template die Ausgabeschleife durchlaufen wird - zwar ohne Ausgabe, da HTML- bzw. Text-Knoten leer - aber die umschließenden HTML-Divs ausgegeben werden
![shot270](https://cloud.githubusercontent.com/assets/1045318/18026928/d6e4aef0-6c55-11e6-9405-d6381dd8c20f.jpg)

**2.) Attribut "Name" in Render-Einstellung als Attribut + aktiv**

=> dann wird die Ausgabe im raw-Knoten gekürzt auf die "Standard-Attribute" und dem gewählten Attribut "Name"
![shot271](https://cloud.githubusercontent.com/assets/1045318/18026934/44065c7c-6c56-11e6-86ca-60eaa6b54f3d.jpg)

3.) Attribut "Name" in Render-Einstellung als Attribut aber deaktiviert**

=> nun ist wieder der komplette raw-Knoten zu sehen

4.) Attribut "Vorname"in Render-Einstellung als Attribut aktiviert - "Name" bleibt deaktiviert**

=> Ansicht wie bei 2.) aber Vorname wird ausgegeben

**Comment by zonky2** [comment]
@cyberlussi - ich habe das Thema mit @discordier durchgesprochen und es ist, so wie es ist, genau "richtig" - was, wann passiert, sieht man an meinem letztem Kommentar.

Es kommt auf Deine Anforderungen an, aber man kann über den raw-Knoten und einem eigenen Template alle gewünschten Ausgaben erzeugen.

Das Ticket wird somit geschlossen...
