### ISSUE TITLE
Translated Frontend-Filters random language options

### ISSUE THREAD

**Issue by xat** [MetaModels/core#418]
Benutzt man TranslatedSelect oder TranslatedTags in einem Frontend Filter-Menue so werden die Options in der korrekten Sprache angezeigt wenn die Aktive Sprache der Fallback Sprache entspricht.

Wenn man allerdings im Frontend die Sprache wechselt auf eine Sprache die nicht die Fallback Sprache ist so sind die Options values in zufaelliger Sprache.

Ich hab versucht dem Problem auf die Schliche zu kommen und bin schliesslich in der "getFilterOptions" Methode der TranslatedSelect Klasse gelandet gelandet.

Dort wird ein SQL-Statement dieser art hier erzeugt:

```SQL
SELECT COUNT(mm_job_function.vargroup) as mm_count, mm_job_function.*
					FROM mm_job_function
					WHERE lang IN ('en','de')
					
					GROUP BY mm_job_function.vargroup
					ORDER BY  title
```

was dann zu einem result fuehrt indem die rows unterschiedliche sprache haben  weil _vor_ der gruppierung eigentlich schon mal nach primaer / fallback sprache sortiert werden muesste.

Mit einem Subselect in dieser Art, bekommt man die richtige Sprachen:

```SQL
SELECT COUNT(virt.vargroup) as mm_count, virt.*
					FROM (SELECT vargroup FROM mm_job_function ORDER BY FIELD(lang, 'en', 'de')) as virt
					WHERE virt.lang IN ('en','de')
					
					GROUP BY virt.vargroup
					ORDER BY  virt.title
```

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@xat could you please have a final look at this and tell if your issue has been resolved?
