### ISSUE TITLE
Mehrsprachigkeit der Eingabemaske im Backend

### ISSUE THREAD

**Issue by klauswagner** [MetaModels/core#420]
Folgendes Vorgehen:
Ich lege in meinem mehrsprachigen (Deutsch, Französisch, Englisch) MetaModel "Produkte" eine Eingabemaske "BE Produkt Erfassung" an. In den Einstellungen zur Eingabemaske ist "Übersetzung" aktiviert und die entsprechenden Sprachen sind angelegt. Als Fallback-Sprache ist "Englisch" ausgewählt.
In den Einstellungen der einzelnen Attribute des MetaModels "Produkte" sind alle Übersetzungen eingetragen:

![image](https://cloud.githubusercontent.com/assets/7679272/3103606/530a9b96-e659-11e3-8fba-f10647986447.png)

Problem:
Wenn ich nun in die Eingabemaske wechsle (in diesem Fall BE-Bereich "Inhalte" > "Produkte") und einen neuen Datensatz anlege, werden die Labels und Erklärungen der definierten Eingabefelder auf englisch angezeigt.
Das passiert unabhängig davon, welche Sprache ich für diesen Datensatz gerade bearbeite (Sprachauswahl oben rechts). Und unabhängig davon welche Standardsprache im Browser eingestellt ist, bzw. welche Sprache für das Contao-Backend eingestellt wurde.
Die Ausgabe der Labels und Erklärungen bezieht sich **immer** auf die festgelegte Fallback-Sprache. Ändere ich die Fallback-Sprache auf "deutsch", werden die Labels auf deutsch angezeigt...

Wenn ich nun den Fall habe, dass mehrere Personen aus unterschiedlichen Ländern auf der Welt die Produkte pflegen, bekommt eine Person aus China die Labels auf deutsch angezeigt und kann damit dann wenig anfangen.
Wäre es da nicht sinnvoll, bei der Ausgabe der Labels zu prüfen, welche Contao-Backend-Sprache der Benutzer momentan eingestellt hat und wenn diese Sprache bei den Attributs-Namen und den Attributs-Beschreibungen eingetragen ist, diese auszugeben. Falls die Sprache nicht vorhanden ist, kann man dann die Fallback-Sprache nutzen.

**Comment by Kreativsoehne** [comment]
Wir stehen hier vor einem ähnlichen Problem:

Es gibt eine Seite mit zwei Inhaltszweigen für Deutschland und die Schweiz. Die Sprache ist jeweils deutsch, aber je nach gewählter Domain springt Contao auf den jeweiligen Inhaltsteil; *.de landet im Zweig de_de, *.ch in de_ch.
Alle Inhalte, die von MetaModels stammen, sind in deutscher Sprache hinterlegt, sind aber pro Land unterschiedlich. Surft man die Website nun auf der .ch-Domain an, dann kommen auf den Seiten, auf denen Inhalte aus den MetaModels gezeigt werden sollen, keine Inhalte mit der Meldung, dass nichts gefunden wurde ("Ihre Suche lieferte keine passenden Ergebnisse.")

Offenbar ist dieses Problem ebenfalls auf das hier diskutierte Thema zurück zu führen.

Hat sich da etwas getan? Gibt es vielleicht einen Workaround?

**Comment by zonky2** [comment]
nein, da hat sich nichts getan bzw. es wurde "hart" auf zwei Zeichen begrenzt

...und wie schon im Forum zu Deiner Anfrage geschrieben, ist das Posting https://github.com/MetaModels/core/issues/420#issuecomment-44397988 der "letzte Stand", d.h. selbst programmieren und PR einreichen oder programmieren lassen...

**Comment by zonky2** [comment]
Fixed in MM 2.2 - see https://github.com/MetaModels/core/issues/1458
