### ISSUE TITLE
[TNG] Links in the breadcrumbs don't contain $_GET ref

### ISSUE THREAD

**Issue by LeoUnglaub** [MetaModels/core#430]
Hey,
the links in the Meta Models breadcrumbs don't contain the new and needed ref param. This can cause some problems if you have multiple tabs open on the same time.

![selection_026](https://cloud.githubusercontent.com/assets/734684/3131211/00139474-e802-11e3-848f-00fcfff87496.jpg)
The normal contao function for generating links in the backend should fix that problem.
Greetings
Leo

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@LeoUnglaub could you please have a final look at this and tell if your issue has been resolved?
