### ISSUE TITLE
[TNG] edit multiple in the meta models list causes empty backend screen

### ISSUE THREAD

**Issue by LeoUnglaub** [MetaModels/core#431]
Hey,
if you use the edit multiple global option in the meta models list, you get an empty (no 500, it's 200) backend view.

![selection_025](https://cloud.githubusercontent.com/assets/734684/3131386/f74b5b54-e803-11e3-9102-9e41e3c6e8f0.jpg)
![selection_026](https://cloud.githubusercontent.com/assets/734684/3131389/fa02bf18-e803-11e3-89c0-23a3aebe2da5.jpg)

Greetings
Leo

**Comment by xantippe** [comment]
core 2.0.0-alpha8

ein "leeres BE" kommt bei mehrere bearbeiten nicht (mehr) aber die Funktionen zum Bearbeiten stehen nicht zur Verfügung

**Comment by zonky2** [comment]
siehe https://github.com/contao-community-alliance/dc-general/issues/281

**Comment by zonky2** [comment]
pls observe contao-community-alliance/dc-general#281

**Comment by zonky2** [comment]
test https://github.com/contao-community-alliance/dc-general/tree/feature/override_edit_all
