### ISSUE TITLE
Split up event handler for renaming a MetaModel.

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#440]
`MetaModels\DcGeneral\Events\Table\MetaModels\UpdateMetaModel::handle()` must be splitted up into only the real labor work of renaming the table.

We need to fix the check in `MetaModels\DcGeneral\Events\Table\MetaModels\Subscriber::ensureTableNamePrefix()` to only check the new table name and error out if it does not exist.

**Comment by zonky2** [comment]
MM check the prefix of table name at renaming
