### ISSUE TITLE
[TNG] Contao 2.11 nightly kein ClassLoading

### ISSUE THREAD

**Issue by cogizz** [MetaModels/core#444]
Ich habe gerade einmal die aktuelle TNG nightly auf einer Contao 2.11 installiert.
Leider scheint es dort kein ClassLoading zu geben. Ich erhalte folgende Fehlermeldung:

```
Fatal error: Could not load class MetaModels\Dca\MetaModelDcaBuilder in …/system/functions.php on line 105 
```

**Comment by discordier** [comment]
2.11 is unsupported.
