### ISSUE TITLE
Contao 3.3.1 / Nightly  - Cannot make static method

### ISSUE THREAD

**Issue by ghost** [MetaModels/core#464]
Beim Aufruf von MetaModels im Backend bekomme ich folgenden Fehler:
Installiert habe ich die Nightly für C3 von der MM Seite.

```
Fatal error: Cannot make static method Contao\Controller::loadDataContainer() non static in class DcGeneral\Contao\BackendBindingInternal in /home/hostiane/public_html/kunden/hirnpuls/system/modules/generalDriver/DcGeneral/Contao/BackendBindings.php on line 71
```

**Comment by luger95** [comment]
What's that TNG ?

**Comment by Zeromax** [comment]
@luger95 tng = The next Generation
> MetaModels 2.x kann unter Contao 2.11 und Contao 3.x eingesetzt werden. Unter Github ist sie als Version 2.x oder in den Git Branches "tng" verfügbar. Unter Composer muss man für die Nutzung dieser Version "2.x-dev" auswählen. Der Begriff "tng" steht für "The next generation".

Only in german available.https://now.metamodel.me/de/ressourcen/nightly-builds#version-2x
