### ISSUE TITLE
[TNG] Error nach Installation

### ISSUE THREAD

**Issue by ghost** [MetaModels/core#465]
Folgender Error kommt nach der TNG Installation unter Contao 3.3.2, wenn man ein neues MetaModel erstellen möchte

```
Fatal error: Call to a member function hasErrors() on a non-object in /home/test2/public_html/kunden/contao/system/modules/generalDriver/templates/dcbe_general_field.html5 on line 17
```

**Comment by wwwebgainss** [comment]
Habe das gleiche Problem. GIbt es eine Liste der Dateien welche ich löschen soll von der NIghtly-Contao 3 Verison???

**Comment by MacKP** [comment]
@wwwebgainss so eine Liste gibt es nicht. Du könntest dir eine Nightly runter laden und dann da nachschauen, was da alles drinn ist. Oder du hast noch das alte Paket von dir und guckst da direkt nach. Beim nächsten mal bitte besser im Forum fragen. Dafür ist das besser geeignet.

**Comment by wwwebgainss** [comment]
ich habe alle ordner die in der nightly waren auf meinem Webspace gelöscht und zusätzlich noch die !metamodels-contao3-branch und ich bekomme diese Fehlermeldung "Fatal error: Call to a member function hasErrors() on a non-object in" wenn ich die Eingabemaske BE eines MetaModels bearbeiten möchte. Versuche seit 6 Stunden verzweifelt diesen Fehler zu beheben :(

**Comment by MacKP** [comment]
@wwwebgainss bitte melde dich doch erst mal im Forum! Das hier ist ein Ticket System und kein Helpdesk.
Ansonsten musst du wirklich alle Ordner und Dateien entfernen vor dem Update, die in der Nightly waren.
Im Forum dann bitte noch ein paar mehr Infos: Welche Contao Version. Wie bist du genau vorgegangen und wann genau kommt der Fehler.
