### ISSUE TITLE
MetaModul-FilterReset wird auf HP nicht angezeigt wenn über Modul eingebunden

### ISSUE THREAD

**Issue by kein-nickname** [MetaModels/core#477]
Contao 3.3.3 / MM Dev-TNG
Wenn man den Modultyp "MetaModul-FilterReset" per Modul einbindet wird dieser nicht aktiviert.
Im HTML-Code erfolgt dann:
```
<section class="mod_metamodels_frontendclearall block">
    <form method="post">
        <input type="hidden" value="...." name="REQUEST_TOKEN"></input>
        <input type="hidden" value="" name="FORM_SUBMIT"></input>
        <div class="formbody">
        </div>
    </form>
</section>
```
Wenn man jedoch im Inhaltselement den Elementtyp "Zurücksetzen" nutzt wird es angezeigt.
```
<div class="clearall">
    <a href="index.php/abcd.html" title="Alle Filter zurücksetzen">
        Alle Filter zurücksetzen
    </a>
</div>
```

Ein BUG oder ist die Nutzung über das Modul nicht mehr vorgesehen?
Hat in der Demo von MetaModuls damals so fuktioniert!

**Comment by xantippe** [comment]
inzwischen ist das Verhalten ofensichtlich "invers": #888

**Comment by stefanheimes** [comment]
The module works, now the CE-Elements has a bug so we could close this ticket, because we have the other one for the CE-Element.
