### ISSUE TITLE
Checkbox SubmitOnchange in BE Eingabe leert andere (!) Subpaletten Inhalte

### ISSUE THREAD

**Issue by cyberlussi** [MetaModels/core#493]
Hi,

ich habe mit "DC General Tree BackendView Ultimate" in einem BE Formular eines MM mehrere Checkboxen und Felder abhängig gemacht (im Detail: Checkbox::Option1 + File::Galerie; Checkbox::Option2 + File::Anlagen -> "Property value is for attribute Option1 (Parameter: 1)" und "Property value is for attribute Option2 (Parameter: 1)") und die checkboxen auch jeweils mit "SubmitOnChange" konfiguriert. Das klappt im Formular erstmal so wie gedacht. Ich beobachte aber den folgenden Effekt:

Neuer MM-Eintrag (oder einen bestehenden bearbeiten) -> CB-Option1 aktivieren -> Fileauswahl erscheint, Galeriebilder auswählen, Bilder erscheinen (wie von Contao gewohnt) -> CB-Option2 aktivieren -> Galeriebilder verschwinden (File Auswahl button ist aber noch sichtbar). 

Ich habe das auch mal nur mit Textfeldern anstatt File-Auswahl gemacht, dort leert sich der "andere" Wert einfach bzw. fällt auf den Wert aus der DB zurück (Eintrag bearbeiten). Der Event "SubmitOnChange" zeigt und versteckt zwar zuverlässig abhängige Felder, leider speichert es die neuen Daten anderer (!) Felder anscheinend aber nicht. Anmerkung: Felder, die keine Abhängigkeiten definiert haben, werden beim SubmitOnchange allerdings korrekt mit den letzten Eingaben versorgt.

Ob das jetzt ein Problem von MM, DC General Tree BackendView Ultimate oder Contao ist, weiß ich nicht.

**Comment by xantippe** [comment]
aktuelle Test: Contao 3.5.6 mit MM 2.0.0-alpha8

Ich habe zum Test zwei Subpaletten per Checkbox definiert Sub1 (Meine Daten) mit einigen Textfeldern und Sub2 (Meine Bilder) mit einer Mehrfachauswahl von Bildern. Bei beiden Subpaletten werden die Elemente über eine Checkbox per 
* Typ: Eigenschaftswert ist
* Attribut: Meine Daten bzw. Meine Bilder (Checkbox)
* Wert: Aktiv

sowie bei den Checkboxen "Absenden bei Änderungen"

Beide Subpaletten können unabhängig ein- und ausgeschaltet werden ohne dass was "verschwindet" (siehe Screenshots) - das nur die Inhalte der Subpaletten gespeichert werden, die sichtbar sind, ist sicher die gewollte Funktionalität.

m.E. funktioniert alles wie gewünscht und das Ticket kann geschlossen werden

![shot24](https://cloud.githubusercontent.com/assets/1045318/12064608/d92450b2-afc7-11e5-8bcd-3b0bda0b733c.jpg)

:::::::::::::::::::

![shot25](https://cloud.githubusercontent.com/assets/1045318/12064612/df71ca3a-afc7-11e5-8631-68491ebb0dfd.jpg)

**Comment by cyberlussi** [comment]
Ich denke, der heutige Zustand erlaubt das Ticket zu schließen.

**Comment by xantippe** [comment]
Interessanter Effekt

* Einmal alle Attribute hinzufügen
* Alle auf Sichtbar schalten
* Anschließend unsichtbar schalten oder löschen

=> Nachdem ein Attribut einmal auf sichtbar geschaltet wurde, ist es offensichtlich in raw enthalten... und kann dann aber wieder entfernt werden

... ob das so gewollt war??

**Comment by cyberlussi** [comment]
@xantippe Sicher, dass dieser Kommentar https://github.com/MetaModels/core/issues/493#issuecomment-168780269 für dieses Ticket gedacht war?
