### ISSUE TITLE
[TNG] Keine Auswahl von Attributen bei Einzel- und Mehrfachauswahl Filter möglich

### ISSUE THREAD

**Issue by jgrotstabel** [MetaModels/core#496]
Sowohl beim Filter Einfachauswahl als auch Mehrfachauswahl ist es mir in der MetaModels 2.x auf Contao 3.2.12 nicht möglich, ein zu filterndes Attribute in den Filtereinstellungen zu hinterlegen.
Ich kann immer ein Attribute auswählen (welches ich dafür hinterlegt habe), sobald ich jedoch auf speichern klicke wird die Attribute Auswahl in den Filtereinstellungen geleert. 
Deswegen kann ich dann auch im Modul Filter keine Attribute auswählen.

Habe auch versucht den Cache zu leeren. Leider nix gebracht.

**Comment by dmolineus** [comment]
Any solution ideas here @discordier? I would fix it, if we agree on a solid solution. I would suggest to use an dot or two underscores as separator between table and property. The huge drawback would be the backwards compatibility.

**Comment by discordier** [comment]
@dmolineus Swap:
```
$value = str_replace($metaModel->getTableName() . '_', '', $value);
```
with
```
$value = substr($value, strlen($metaModel->getTableName() . '_'));
```
And we should be all set, sorry that I totally forgot about this issue.

**Comment by dmolineus** [comment]
I applied the changes in https://github.com/MetaModels/core/issues/823. It's not merged into tng yet. Would be nice if someone with this issue would conform this fixes the bug because I couldn't reproduce it (propably missed something of the special configuration where it occurs).
