### ISSUE TITLE
Reload after Select / Radio for Subpalettes

### ISSUE THREAD

**Issue by emkayy** [MetaModels/core#498]
A 'Submid on Change' option for subpalette triggering fields like select or radio buttons would be nice - just like the checkbox already has!

**Comment by discordier** [comment]
@tim-bec isn't this working already?

**Comment by xantippe** [comment]
aktuell getestet in core 2.0.0-alpha8 

=> für ein "Submit on Change" muss in den Eigenschaften des Attributs in der Eingabemaske "Absenden bei Änderungen" aktiviert sein

funktioniert somit und m.E. kann das Ticket geschlossen werden
