### ISSUE TITLE
Subpalettes: Hide Legends with all Containing Fields

### ISSUE THREAD

**Issue by emkayy** [MetaModels/core#499]
Working with complex forms would be much easier if you could apply subpalette options to all elements within one legend area. Means defining subpalette conditions to a legend element affects it's "children".

**Comment by xantippe** [comment]
@tim-bec: wenn ich das richtig verstehe, soll die Legende (das "grüne Ding") ausgeblendet werden, wenn alle zur legende zugehörigen Attribute unsichtbar sind - korrekt?

wenn ja, sollte die Konfiguration mit in die Einstellungen der Legende - z.B. als Option "Legende ausblenden, wenn kein Attribut sichtbar"

**Comment by zonky2** [comment]
* die Legende soll triggern können und wenn die ausgeblendet wird, werden auch "Kinder" nicht mit angezeigt

**Comment by zonky2** [comment]
Test in MM 2.1 und 2.2: wenn Legende ausgeblendet wird werden auch alle Widgets der Section der legende ausgeblendet
