### ISSUE TITLE
Feature: Render settings, Ein-Klick: "alle aktiv"

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#50]
Momentan muss man in den Render-Settings für jeden Eintrag (Attribut) das Auge einzeln bestätigen.
Schön wäre es wenn man das in der Meta Navigation mit einem klick für alle erledigen kann.   (Ähnlich wie alle markieren)

**Comment by discordier** [comment]
@xantippe Wohnt nun hier: https://github.com/MetaModels/core/blob/tng/src/MetaModels/DcGeneral/Events/Table/InputScreens/Subscriber.php#L308

**Comment by zonky2** [comment]
siehe auch https://github.com/MetaModels/core/issues/1057

**Comment by zonky2** [comment]
implemented with https://github.com/MetaModels/core/issues/1057
