### ISSUE TITLE
[TNG] Sortierreihenfolge der Metamodels in umgekehrter Reihenfolge

### ISSUE THREAD

**Issue by mosesontheweb** [MetaModels/core#501]
Mir ist grade aufgefallen, dass die Namen der Metamodels, die ich angelegt haben, in umgekehrter Reihenfolge angezeigt werden. Also Z -> A anstatt A->Z.

Gruß, Thomas

metamodels/core - dev-tng @ 2e73b7

**Comment by tim-bec** [comment]
@discordier dürfte das nicht mittlerweile erledigt sein?

**Comment by discordier** [comment]
Weiss ich nicht mehr, aber bei @cboelter haben wir zumindest noch ein Problem im dcg hinsichtlich Sortierung ohne Gruppierung.

**Comment by xantippe** [comment]
aktuelle Version core 2.0.0-alpha8

die MM-Einträge können über den "blauen Pfeil" oder über den "grünen Hamburger" nach eigenem Gusto sortiert werden

m.E. kann der Issue geschlossen werden
