### ISSUE TITLE
Fatal Error After Renaming MM Database Table

### ISSUE THREAD

**Issue by emkayy** [MetaModels/core#511]
After I renamed a DB table of a MetaModel (that I used as a select option) I get a system error. Deleting cache doesn't help. I can't log into contao anymore because I get a fatal error.

I have to change the name of the database table in the tl_metamodel_attribute table -> select_table column manually.

**Comment by xantippe** [comment]
getestet in core 2.0.0-alpha8

* referenziertes MM umbenannt (Tabellenname)
* in Attribut select mussten die Auswahlen bei "Anzeigeeinstellungen" neu gesetzt werden

=> alle Anzeigen im BE und FE wieder vorhanden und keine Fehler

das Issue kann m.E. geschlossen werden
