### ISSUE TITLE
[tng] get Templates for basename

### ISSUE THREAD

**Issue by Zeromax** [MetaModels/core#521]
This method `getTemplatesForBase` gets the templates by basename and missed my templates...
https://github.com/MetaModels/core/blob/tng/src/system/modules/metamodels/MetaModels/Dca/Helper.php#L261

I put them into a subfolder. Added them via `TemplateLoader`.

```php
TemplateLoader::addFiles(array
(
	'mod_metamodel_category'			=> 'templates/modules',
));
```
But metamodels ignores them, because I have not put it into the root from the templates Folder.

Please check the Contao `TemplateLoader` as well like in this line:
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Controller.php#L90

Thanks ;)

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Zeromax could you please have a final look at this and tell if your issue has been resolved?
