### ISSUE TITLE
TNG Keine Sortierung im Backend

### ISSUE THREAD

**Issue by tschero** [MetaModels/core#526]
Hallo,

bei dem Versuch die Sortierung im Backend zu nutzen wird leider keine Aktion durchgeführt.
Das MetaModel und die Einstellungen wurden gemäß Contao Wiki Beispielprojekt abgelegt.

Einen zugehörigen Thread im Contao Forum findet Ihr hier:
https://community.contao.org/de/showthread.php?51969-Backend-Sortierung-Ansicht-ver%E4ndern

Gruß
tschero

**Comment by lucdesign** [comment]
@felixxxxx: Finde ich keine gute Idee! Will man da später was einfügen, dann muss mann alle Zahlen neu eingeben!

**Comment by xantippe** [comment]
Mit der "neuen" Funktion der Sortierungsdefinition - siehe http://metamodels.readthedocs.org/de/latest/manual/component/dca.html#ablauf

```
Anschließend können in der Listenansicht der Eingabemasken über das Icon “Sortierung und Gruppierung” verschiedene Einträge für die Sortierung und Gruppierung der gespeicherten Items angelegt werden.
```

funktioniert die Sortierung sowohl im BE - z.B. Name aufsteigend, Name absteigend, Manuell sowohl im BE als auch im FE-Element Liste z.B. per "Sortierung" die manuelle Sortierung

getestet: 
Contao 3.5.6
MM bundle_al 2.0.0 mit core 2.0.0-alpha8

kann m.E. geschlossen werden

**Comment by discordier** [comment]
Dann tu dies. :)
