### ISSUE TITLE
[contao3] Kopierbutton bei Variationen funktioniert nicht

### ISSUE THREAD

**Issue by JT-007** [MetaModels/core#539]
Bei den Varianten eines MM Eintrags steht zwar der Kopierbutton zur Verfügung aber beim Klick darauf passiert nichts.

Laut xtra kann der Kopierbutton gar nicht funktionieren und sollte entfernt werden.

**Comment by tim-bec** [comment]
Kopieren von Varianten funktioniert in 2.0.0
