### ISSUE TITLE
Tooltips bei Icons der Rendereinstellungen, Attributen usw. falsch

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#546]
Hier erscheint "Filtereinstellungen" statt "Rendereinstellungen" bei: Bearbeiten, Kopieren, Details

bei Verschieben: "Cut render settings id <id>"

bei Toggle: "id <id>"

**Comment by discordier** [comment]
Scheint mir ein translation Problem zu sein, damit dann definitiv auch Core betroffen und nicht nur DCG.

**Comment by zonky2** [comment]
einige ToolTips (TT) sind hinzu gekommen - folgende fehlen noch:

* alle "Augen" veröffentlichen haben bei MM keinen TT

* Render-Einstellungen
![shot325](https://cloud.githubusercontent.com/assets/1045318/23739778/dd456a80-04a0-11e7-97d2-d295ce9878d1.jpg)

* Eingabemasken
![shot326](https://cloud.githubusercontent.com/assets/1045318/23739785/ea6723f2-04a0-11e7-9c5b-dac6557a0add.jpg)

![shot328](https://cloud.githubusercontent.com/assets/1045318/23739811/013a716a-04a1-11e7-8c4d-73a0c109914b.jpg)

* Ansichtsbedingungen
![shot327](https://cloud.githubusercontent.com/assets/1045318/23739799/f7998f7e-04a0-11e7-9718-87aa0ca8a46e.jpg)

**Comment by johannes-bittner** [comment]
Fehler bei Übersicht Eingabemasken, Tooltip für letztes Icon: Fehler/unpräzise: 
"Bearbeiten Sie **ein** Einstellungen der Eingabemaske" 
Besser vielleicht: 
"Bearbeiten Sie die anzuzeigenden Felder der Eingabemaske" 

![grafik](https://cloud.githubusercontent.com/assets/1597697/23759392/f929e400-04ec-11e7-8723-01b8ca18c9c4.png)

**Comment by discordier** [comment]
Die Ybersetzungen kann jeder auf Transifex verbessern.
Hierzu ist jeder gerne eingelade.

**Comment by zonky2** [comment]
leider sind die Übersetzungen - ggf. auch schon die Originaltexte - nicht immer konsistent :-(

**Comment by discordier** [comment]
Sollte sich nun dank MiniModelv2 erledigen, leider beim core nocht nicht (da der branch aktuell alpha15 heisst und nicht 2.0.0-alpha15)

**Comment by zonky2** [comment]
@discordier die Änderung zu

> "Bearbeiten Sie die anzuzeigenden Felder der Eingabemaske"

hat @johannes-bittner am 9 März in Transifex gemacht - weshalb erscheint das nicht? Test in dev-hotfix/2.0.0-alpha16 (e7c679eb)

**Comment by baumannsven** [comment]
I have merged in 3c8b7f45ba5a05f958673810107fe76db8d2fc32 the translations.

**Comment by zonky2** [comment]
[x] Render-Einstellungen
[x] Übersicht Eingabemasken, Tooltip für letztes Icon
[x] Eingabemasken
[ ] alle "Augen" veröffentlichen
[ ] alle Verschieben-Pfeile

**Comment by zonky2** [comment]
fixed https://github.com/MetaModels/core/pull/1183
