### ISSUE TITLE
[TNG] NB 21.08.14: Checkbox Varianten speichert nur bei "Speichern und neu"

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#551]
der Status der Checkbox "Varianten" ändert sich nur bei "Speichern und neu" bei Speichern oder Speichern und schließen ändert sich zwar in der Anzeige die Checkbox, wird die Seite aber neu geladen ist der alte Zustand wieder da.

bei Speichern und zurück kommt "The function/view "Save and go back" is not implemented. "

**Comment by discordier** [comment]
Save & go back should be implemented with https://github.com/contao-community-alliance/dc-general/commit/581c9c76c79c742143a3d4a101239e81961c5f30
@xantippe is the other issue still present?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@xantippe could you please have a final look at this and tell if your issue has been resolved?

**Comment by xantippe** [comment]
ich sehe zu, das so schnell wie möglich zu testen...
