### ISSUE TITLE
CE-Element "METAMODEL LIST" MM-Name mit anzeigen

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#555]
Hallo,

ich fänd es prima, wenn bei den CE "METAMODEL LIST" zusätzlich das MetaModel angegeben wird z.B. so

```
### METAMODEL LIST ###
Fahrzeuge
```

bei mehreren MM-Lists in einem Artikel muss man sonst immer erst nachsehen wer welcher ist...

**Comment by zonky2** [comment]
ggf. ist ein freies Eingabefeld besser oder zus. zu Model-Name und ggf. Filterset-Name

**Comment by discordier** [comment]
Wie bereits diskutiert, ein "Kommentar" Freitextfeld macht hier vermutlich am Meisten Sinn.

**Comment by zonky2** [comment]
mehr Infos im BE: siehe https://github.com/MetaModels/core/pull/1182
