### ISSUE TITLE
Listen unabhängig voneinander Sortieren können (auf einer Seite)

### ISSUE THREAD

**Issue by MacKP** [MetaModels/core#556]
Beispiel:
Eine Seite wo 2 Listen Module vorhanden sind.
z.B. Bücherplattform

```
Liste 1 = komplett alle (mit Paginierung)
Liste 2 = Featured Einträge (5 Stück)
```

Liste 1 möchte man eventuell nach Verlag / Preis / Alphabet sortieren
Liste 2 soll natürlich immer so bleiben wie die ist. Oder noch besser selbst wieder ganz anders sortiert werden können, nach Erscheinungsdatum

Es wäre also gut, wenn man (vllt per Parameter sorting1 = Sortiern für Liste 1 / sorting2 = Sortieren für Liste 2) angeben könnte, was wie sortiert werden kann/darf.

Viele Grüße

Original -> https://github.com/MetaModels/DC_General/issues/35#issuecomment-52843294

**Comment by xantippe** [comment]
@MacKP: ich sehe das Problem bei der aktuellen Version (alpha8) nicht - oder meinst Du das Feature mit dem Überschreiben der Sortierung?

**Comment by MacKP** [comment]
Puh.. lange her.. Ich meine, das es aktuell eben noch nicht in der Art geht, da die Sortierung immer noch nicht per Parameter geregelt ist. Spätestens bei einer Paginierung ist das nicht drinn.

**Comment by xantippe** [comment]
ahhh ich glaube, dass Problem ist "zwei Listen auf einer Seite"...

**Comment by xantippe** [comment]
getestet:

* zwei Listen mit unterschiedlich eingestellter Sortierung geht
* eine der beiden Listen kann auch eine dynamische Sortierung per "Sortierung überschreiben" haben

siehe Screenshot...

die dyn. Sortierung würde sich auf beide Listen auswirken, wenn beide den gleichen Alias haben - ähnliches Problem besteht ja auch bei der Paginierung von zwei Listen auf einer Seite

zu umgehen wäre das z.B. durch das Aktualisieren per AJAX

![shot24](https://cloud.githubusercontent.com/assets/1045318/12036353/895e4246-ae45-11e5-85e1-2fe823928769.jpg)

**Comment by zonky2** [comment]
siehe #1455
