### ISSUE TITLE
[TNG] Kein Icon für manuelles Sortieren im BE bei MM mit Varianten(?)

### ISSUE THREAD

**Issue by design23** [MetaModels/core#559]
Hi,

bin mir nicht sicher, ob hier ein Bedienfehler meinerseits oder wirklich ein Issue vorliegt – aber sicherheitshalber melde ich das mal.

Ich habe aktuell das Problem, dass in der BE Listenansicht der MM kein Icon (bzw. kein "Anfasser") für manuelles Sortieren mit Drag & Drop angezeigt wird. Die Sortiermodi habe ich schon alle durchprobiert.
![bildschirmfoto 2014-08-25 um 00 17 49](https://cloud.githubusercontent.com/assets/6112308/4024881/dc34a528-2bdd-11e4-9cd8-86e8f062a59f.png)

**Comment by zonky2** [comment]
>Bei Varianten muss man die normalen cut und paste Pfeile nehmen, da Varianten implizit als Baum dargestellt werden.
In Baeumen kann man jedoch nicht per Drag&Drop sortieren (das ist in ganz Contao so).

daher obsolet
