### ISSUE TITLE
FR: Checkboxen der Mehrfachauswahl im Item sortierbar

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#565]
Könnten die Checkboxen zus./alternativ zur eingestellten Standardsortierung auch individuell in jedem Item sortierbar gemacht werden - Analog z.B. CSS-Auswahl im Layoutbuilder

Der Contao-Core sollte das ja soweit in petto haben...

Dank & Gruss
![screenshot2](https://cloud.githubusercontent.com/assets/1045318/4075858/c83fda5e-2eb4-11e4-8492-a4bc3792dbf8.jpg)

**Comment by Kreativsoehne** [comment]
Gibt es hier bereits eine Lösung für die Sortierung im "Checkbox Wizard"?

**Comment by zonky2** [comment]
implementiert https://github.com/MetaModels/attribute_tags/pull/60
