### ISSUE TITLE
[TNG] FR: Verschachtelungstiefe von MM mehr als zwei Ebenen

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#566]
Bei einer Verschachtelungstiefe von Metamodels von mehr als zwei Ebenen werdendie folgenen Ebenen nicht oder nur rudimentär in das Ausgebearray eingepflegt.

z.B. MM1 --> bezieht Werte aus MM2 --> bezieht Werte aus MM3

Macht man eine Ausgabeliste für MM1 gibt es für Werte aus MM3 folgende Effekte:
* Referenzierung per Auswahl: nur ein Item wird im Array angebenen mit Wert der ID des Datensatzes (auch wenn andere Spalte ausgewählt)
* Referenzierung per Mehrfachauswahl: das Item erscheint gar nicht

Es wäre schön, wenn die Verschachtelungstiefe angehoben werden könnte - muss ja nicht "unendlich" werden ;-)

Gruss & Dank!

TNG vom 28.08.14 unter Contao 3.2.12

siehe auch https://community.contao.org/de/showthread.php?52464-MM-3-Verschachtelung-Mehrfachauswahl-wird-in-raw-Array-nicht-%FCbernommen&p=338385#post338385

**Comment by discordier** [comment]
Sollte eigentlich inzwischen funktionieren, oder?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@xantippe could you please have a final look at this and tell if your issue has been resolved?
