### ISSUE TITLE
[TNG] NB 20.09.14 Fehler für "Angepasstes Template für die Ausgabe" bei Anzeige im BE und eigenem Template

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#579]
wenn ich ein eigens Template  mm_attr_checkbox_be anlege und auswähle, kommt in der Listenansicht
```
Fatal error: Uncaught exception Exception with message Could not find template "mm_attr_checkbox_be" thrown in system/modules/core/library/Contao/TemplateLoader.php on line 127

#0 system/modules/metamodels/MetaModels/Render/Template.php(235): Contao\TemplateLoader::getPath('mm_attr_checkbo...', 'html5')
#1 system/modules/metamodels/MetaModels/Render/Template.php(353): MetaModels\Render\Template->getTemplate('mm_attr_checkbo...', 'html5', false)
#2 system/modules/metamodels/MetaModels/Attribute/Base.php(409): MetaModels\Render\Template->parse('html5', false)
...
```

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@xantippe could you please have a final look at this and tell if your issue has been resolved?

**Comment by xantippe** [comment]
I´ll do was ich machen kann...

**Comment by tim-bec** [comment]
@cboelter bist du hier noch an einem WIP dran, sonst schauen wir uns das mal an.

**Comment by cboelter** [comment]
@tim-bec nope, könntet Ihr gerne übernehmen :)

**Comment by xantippe** [comment]
aktueller Test: bei Auswahl eines Templates, weches in einem /template/unterordner sitzt, kommt in der Listenansicht
```Template not found (it is maybe within a unreachable theme folder?).```
also alles o.k. für mich
