### ISSUE TITLE
[TNG] FR: Eingabemaske > Legende eine Option für hide bzw. collapse des Panels

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#580]
Es wäre schön, wenn es wie bei den DCA-Einstellungen der Legend eine Option für das ":hide" gibt, um ein Panel in der Detailanzeige im Standardmodus zusammengeklappt anzuzeigen.

Aktuell wird das Auf/Zu eines Panels (auch) nicht in der Session mit abgespeichert.

siehe auch: https://community.contao.org/de/showthread.php?52704-Frage-zu-quot-Legende-verbergen-quot-bei-Paneleinstellungen&p=340033#post340033

**Comment by xantippe** [comment]
* Eingabe/Aktivierung von "Hide" gibt es inzwischen - siehe #729 
=> leider funktioniert diese nicht und wird auch bisher nicht in der Session gespeichert..

**Comment by discordier** [comment]
Ja, kann der dcg leider immer noch nicht. MM seitig ist jedoch alles getan

**Comment by xantippe** [comment]
gibt es ein passendes Ticket beim DCG?

**Comment by discordier** [comment]
S.o. 69

**Comment by discordier** [comment]
@xantippe should be fixed in dcg, shouldn't it?

**Comment by discordier** [comment]
Ref #550

**Comment by xantippe** [comment]
getestet mit
* DCG dev-hotfix/2.0.0-beta34 (bb67abb3)
* MM core dev-hotfix-2.0.0-alpha10 (759c9997)

=> o.k.
