### ISSUE TITLE
[TNG] Parent-ID wird nicht gespeichert

### ISSUE THREAD

**Issue by tognit** [MetaModels/core#583]
Der Zugriff auf die Kindtabelle funktioniert ja wieder, aber leider wird in der Datenbank die Parent-ID nicht gespeichert. Jetzt sind alle Kindelemente in jedem Elternelement sichtbar.

Contao 3.3.4
MM 11.09.2014

**Comment by xantippe** [comment]
@psren kannst du das mit dem aktuellen Stand von MM prüfen und ggf. das Ticket schließen?

**Comment by psren** [comment]
Geht inzwischen

**Comment by xantippe** [comment]
o.k.! - ich mach zu
