### ISSUE TITLE
[MM-1.1.x-nightly] Hochgeladene Dateien mit Klammern verursachen Problem

### ISSUE THREAD

**Issue by mosesontheweb** [MetaModels/core#584]
Hallo,

ich habe eine Plattform, bei der Vereine Turnierausschreibungen hochladen können. Dies wird mittels EFG realisiert. Jetzt kann es vorkommen, dass ein Verein eine Aussendung mit einer Klammer ")" oder "(" hochlädt. Möchte man nun im Metamodel bei einem Attribut des Typs File auf diese Datei verweisen, kommt ein Fenster mit dem Hinweis "Die Daten werden geladen", verläuft sich aber ins Endlose und blockiert den ganzen Schirm. Einzige Möglichkeit, dies zu verhindern, ist die Datei vor umzubennen.

Nachdem aber EFG den Upload mit Sonderzeichen erlaubt (und dadurch eigentlich vom System her erlaubt), liegt hier scheinbar eine Fehlbehandlung des Filenamens vor.

![datei_verweis_metamodel](https://cloud.githubusercontent.com/assets/6360498/4263638/358c5298-3bf5-11e4-8bda-19ee61f3db52.png)

**Comment by xantippe** [comment]
getestet Contao 3.5.6 + MM core 2.0.0-alpha8

hat ohne Fehler funktioniert - siehe Screenshot

Ticket kann m.E. geschlossen werden

![shot31](https://cloud.githubusercontent.com/assets/1045318/12074706/7e859336-b162-11e5-9691-62cc11f77440.jpg)
