### ISSUE TITLE
Rework factories and introduce them into attributes

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#606]
Next collective ticket.
We need to alter the factories some more as discussed with @stefanheimes and introduce them into all attributes.
- [X] https://github.com/MetaModels/core
- [X] https://github.com/MetaModels/attribute_alias
- [X] https://github.com/MetaModels/attribute_checkbox
- [X] https://github.com/MetaModels/attribute_color
- [X] https://github.com/MetaModels/attribute_combinedvalues
- [X] https://github.com/MetaModels/attribute_country
- [X] https://github.com/MetaModels/attribute_decimal
- [X] https://github.com/MetaModels/attribute_file
- [X] https://github.com/MetaModels/attribute_geoprotection
- [X] https://github.com/MetaModels/attribute_langcode
- [X] https://github.com/MetaModels/attribute_longtext
- [X] https://github.com/MetaModels/attribute_numeric
- [X] https://github.com/MetaModels/attribute_rating
- [X] https://github.com/MetaModels/attribute_select
- [X] https://github.com/MetaModels/attribute_tabletext
- [X] https://github.com/MetaModels/attribute_tags
- [X] https://github.com/MetaModels/attribute_text (Thanks to @cboelter MetaModels/attribute_text#7)
- [X] https://github.com/MetaModels/attribute_timestamp
- [X] https://github.com/MetaModels/attribute_translatedalias
- [X] https://github.com/MetaModels/attribute_translatedcheckbox
- [X] https://github.com/MetaModels/attribute_translatedcombinedvalues
- [X] https://github.com/MetaModels/attribute_translatedfile
- [X] https://github.com/MetaModels/attribute_translatedlongtext
- [X] https://github.com/MetaModels/attribute_translatedselect
- [X] https://github.com/MetaModels/attribute_translatedtabletext
- [X] https://github.com/MetaModels/attribute_translatedtags
- [X] https://github.com/MetaModels/attribute_translatedtext
- [X] https://github.com/MetaModels/attribute_translatedurl
- [X] https://github.com/MetaModels/attribute_url

**Comment by cboelter** [comment]
@discordier willst du das attribute_url gleich mit machen? Ich schaffe das wohl nicht vor sonntag :(

**Comment by discordier** [comment]
Ich hangel mich grad durch alle durch.
Und Marathon kann man gut sagen, hab bald alle factories und build system changes durch.

**Comment by discordier** [comment]
All done!
