### ISSUE TITLE
Panel-Layout fehlerhaft?

### ISSUE THREAD

**Issue by jabadoo** [MetaModels/core#618]
Gestern mit aktuellem nightly auf Contao 3.2.14 das Beispiel aus dem Wiki nachgebaut und dabei folgenden Fehler (?) entdeckt: 
1. Im BE Panel taucht das Label "Filtern:" für jeden Filter separat auf. Sollte das nicht nur einmal dargestellt werden? 
2. Search übernimmt die deutschen Label, der Filter listet nur die Spaltenbezeichnung auf.

![bildschirmfoto 2014-10-23 um 18 37 26](https://cloud.githubusercontent.com/assets/1890981/4767169/ec0d90b6-5b5a-11e4-8cd6-75b4376c886d.png)

**Comment by xantippe** [comment]
MM core 2.0.0-alpha8  noch aktuell

Ticket bei DCG: https://github.com/contao-community-alliance/dc-general/issues/170

**Comment by xantippe** [comment]
MM core alpha9

zu 1: ist soweit noch aktuell - ggf. Workaround wie https://github.com/contao-community-alliance/dc-general/issues/170#issuecomment-174184667

zu 2: dürfte sich erledigt haben - siehe Screenshots

**Comment by xantippe** [comment]
als Hinweis zur Vervollständigung des Tickets: https://github.com/contao-community-alliance/dc-general/issues/170#issuecomment-187676056

**Comment by discordier** [comment]
Der wurde ja angenommen, daher hier zu. :)
