### ISSUE TITLE
Sortierung anhand von mehreren Feldern ermöglichen

### ISSUE THREAD

**Issue by JT-007** [MetaModels/core#620]
Hallo zusammen,

es wäre sehr gut wenn man in Zukunft bei den Frontend MetaModel Listen nicht nur ein sondern gleich mehrere Feld für die Sortierung auswählen kann. Vielleicht könnte man dies ähnlich wie beim Catalog umsetzen wo man ja die ORDER BY Angaben in eine Textarea eintragen konnte.

Liebe Grüße,
JT-007

**Comment by discordier** [comment]
Dupe of #405
