### ISSUE TITLE
Filter OHNE "Nur verbleibende Tags" filtert zu viel

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#636]
siehe https://community.contao.org/de/showthread.php?53387-Frage-zu-Filter-Auswahl-Filter-Ausgabe-aller-Items-des-refer-MM&p=346475&viewfull=1#post346475

Ist der Filter "Nur verbleibende Tags" nicht gesetzt werden trotzdem nicht alle Items ausgegeben.

Beispiel:
- Filter-Set im BE für Filterung der Events
  filter_be.jpg
  ![filter_be](https://cloud.githubusercontent.com/assets/1045318/4934574/e0a306d2-65a2-11e4-9bf5-aa0932d8a950.jpg)
- Filter "Trainings" im BE => alles "deaktiviert"
  filter_be_alles_deaktiviert.jpg
  ![filter_be_alles_deaktiviert](https://cloud.githubusercontent.com/assets/1045318/4934589/f37606ba-65a2-11e4-988e-f7e8061cec93.jpg)
- Filter "Trainings im FE => alle Trainings werden aufgelistet (wie gewünscht) - auch die, die noch mit keinem Event verknüpft sind
  filter_fe_alles_deaktiviert.jpg
  ![filter_fe_alles_deaktiviert](https://cloud.githubusercontent.com/assets/1045318/4934597/fe2c8282-65a2-11e4-9696-3bf825849afb.jpg)
- Filter "Trainings" im BE => alles "Nur verbleibende Tags" ist "aktiviert" => nun müssten immer noch alle Trainings aufgelistet werden, solange kein anderer Filter gesetzt ist
  filter_be_nur_verbleibende_aktiviert.jpg
  ![filter_be_nur_verbleibende_aktiviert](https://cloud.githubusercontent.com/assets/1045318/4934599/062162d2-65a3-11e4-8c50-a85d63043d3d.jpg)
- Filter "Trainings" im BE => alles "Nur verbleibende Tags" ist "aktiviert" => es werden nur die zugeordneten Trainings ausgegeben :-( - das dürfte m.E. nur der Fall sein, wenn auch "Nur zugeordnete Tags" gesetzt ist
  filter_fe_nur_verbleibende_aktiviert.jpg
  ![filter_fe_nur_verbleibende_aktiviert](https://cloud.githubusercontent.com/assets/1045318/4934605/0e5c3da0-65a3-11e4-8285-713f84b2788e.jpg)

**Comment by discordier** [comment]
I suspect the published filter in the first screenshot forces this behavior (which is correct).

Therefore I fail to see the bug here, @zonky2 please test again by disabling the published filter temporarily.

**Comment by zonky2** [comment]
Abteilung besteht aus
* Einkauf
* GF
* Kundendienst
* Marketing
* Personal
* Test1
* Test2
* Verkauf

Test 1 und 2 sind nicht zugeordnet

**A: [_] Nur zugeordnete Tags
A 1: [_] Nur verbleibende Tags**
336

**A 1: [x] Nur verbleibende Tags**
337

nach Filterung nach Kundendienst
338

**B: [B] Nur zugeordnete Tags
B 1: [_] Nur verbleibende Tags**
339

**B 2: [x] Nur verbleibende Tags**
340

nach Filterung nach Einkauf
341

=> ergo: ohne die Filter-Option "Nur zugeordnete Tags" stimmt die Filterung nach "Nur zugeordnete Tags" nicht

**Comment by zonky2** [comment]
with Fix from #https://github.com/MetaModels/core/issues/1101#issue-217312116 works fine!

![shot344](https://cloud.githubusercontent.com/assets/1045318/25396631/7d726210-29e5-11e7-8e00-4c66a20a1a2a.jpg)

![shot345](https://cloud.githubusercontent.com/assets/1045318/25396636/816dec4a-29e5-11e7-8488-4607e380d15f.jpg)
