### ISSUE TITLE
Artefacts in templates

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#644]
We have some artefacts from older versions. 
I think we can remove this.

https://github.com/MetaModels/core/blob/tng/contao/templates/metamodel_prerendered.html5#L1

**Comment by xantippe** [comment]
@stefanheimes & @discordier - noch aktuell oder kann geschlossen werden?

**Comment by discordier** [comment]
@stefanheimes can we safely remove them from the templates?

**Comment by zonky2** [comment]
@stefanheimes pls update your linky at https://github.com/MetaModels/core/issues/644#issue-48574726

**Comment by discordier** [comment]
He is referring to [this](https://github.com/MetaModels/core/blob/fede5af4a2affbe4e97dd5b2c3f7bd59f957ece5/contao/templates/metamodel_prerendered.html5#L1)

**Comment by richardhj** [comment]
In the `ItemList` class, no `settings` property is added to the template. And as the `RenderItemListEvent` is brand-new, no other core component adds the `settings` property to the template.
I'm going to remove this legacy within #1082.

**Comment by discordier** [comment]
closing in favor of #1082.
