### ISSUE TITLE
inconsistent return value for function "getFieldDefinition" of attributes

### ISSUE THREAD

**Issue by MrTool** [MetaModels/core#645]
The function getFieldDefinition returns depending of the underlying data table different values for the attributes select/tags.

If the data table is an metamodels table the function returns the dca array with the options key=>value pair.

If the data table is not an metamodels table the options key is missing.

**Comment by discordier** [comment]
The method `getFieldDefinition()`should be phased out.
The retrieval of options at build time is way too expensive as all entries are being retrieved and held in memory.
The methods should be replaced with proper registration of:
* `MetaModels\DcGeneral\Events\MetaModel\PopulateAttributeEvent`
* `ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetPropertyOptionsEvent`
* `ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ManipulateWidgetEvent`
* `ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent`

**Comment by discordier** [comment]
This has been fixed in tags and select.
