### ISSUE TITLE
Position of the "Back"-Link

### ISSUE THREAD

**Issue by harry-boldt** [MetaModels/core#649]
In Contao, the "Back"-Link is always positioned on the left side, whereas in MetaModels, it is placed on the right side. This is confusing. In order to be Contao conform, the "Back"-Link should always be the first link.

**Comment by xantippe** [comment]
ist das eine Sache vom DCG oder MM direkt?

**Comment by discordier** [comment]
dcg

**Comment by xantippe** [comment]
Alt:
![shot140](https://cloud.githubusercontent.com/assets/1045318/13491838/09afebf8-e135-11e5-8a0e-e70d6a1268ac.jpg)

NEU:
![shot141](https://cloud.githubusercontent.com/assets/1045318/13491846/11789c7c-e135-11e5-999c-e08d36d30b19.jpg)

=> gefixt
