### ISSUE TITLE
Mehrfachauswahl Bezeichnung/Name und translated-Attribute

### ISSUE THREAD

**Issue by Wagnerwagner** [MetaModels/core#652]
Model1 hat ein translated_text-Attribut mit der Bezeichnung "Name". Im Model2 ist ein Mehrfachauswahl-Attribut angelegt. Dort wähle ich als Datenbanktabelle die Tabelle von Model1 aus. Im Dropdown von "Tabellenspalte für Bezeichnung/Name" erscheinen nun alle Attribute von Model1, außer die translated-Attribute, also auch nicht das Attribut "Name". Dieses wäre aber nötig um in der Backend-Eingabemaske von Model2 die benötigten Bezeichnungen hinter den Checkboxen anzeigen zu können.
Stelle ich das translated_text-Attribut auf ein normales text-Attribut um, kann ich als Bezeichnung/Name dieses auswählen.

Getestet mit Contao 3.3.6 und dem nightly tng vom 12.11.2014.

**Comment by cboelter** [comment]
@tim-bec wie ist denn hier der aktuelle stand? hänge gerade an dem Problem.

**Comment by tim-bec** [comment]
@cboelter wenn ich mich recht entsinne lösen wir doch genau das problem mit dem umbau auf factories bei metamodel eigenen attributen. translated_text scheint aber noch nicht umgebaut zu sein? cc @discordier

**Comment by discordier** [comment]
Du meinst mit dem umbau der Tags und Select auf MetaModels aware.
Habe das Setup bei mir am Laufen, ich hab tags auf translated MetaModels und kann dort den translated title als select/tag value nehmen.
Was genau klappt nicht?

**Comment by cboelter** [comment]
Also ich habe jetzt konkret ein MetaModel (translated) Kategorien (Translated Text und Translated Alias) und ein MetaModel (translated) Referenzen. Und innerhalb des MetaModels Referenzen habe ich ein AttributeTranslated-Tags wo ich dann auf das übersetzte MM referenziere. Das erzeugt bei mir folgende Meldung:

```Fatal error: Uncaught exception Exception with message Query error: Unknown column 'mm_category.alias' in 'field list' (SELECT COUNT(mm_category.id) as mm_count, mm_category.id, mm_category.alias FROM mm_category GROUP BY mm_category.id ORDER BY sorting) thrown in system/modules/core/library/Contao/Database/Statement.php on line 283 ```

**Comment by discordier** [comment]
Da darfst du nun keine translated tags mehr verwenden sondern musst "normale" tags verwenden.
Die translated tags wollen ja pro Sprache eigene Datensaetze referenzieren.
Du willst aber ja nicht in deutsch eine andere Kategorie haben als auf Englisch.

Abgesehen davon ist es dennoch wohl noch ein bug, dass er da den fallback auf ein SQL query macht.

**Comment by cboelter** [comment]
Ok, mein Fehler :( ... mit dem nontranslated tags funktioniert es einwandfrei. Besten Dank!

**Comment by discordier** [comment]
Sollte alles tun.
