### ISSUE TITLE
Mehrsprachige Einträge werden nicht gespeichert

### ISSUE THREAD

**Issue by tniebergall** [MetaModels/core#662]
Ich habe in der aktuellen MM TNG Version unter Contao 3.3 und 3.4 den Fehler, dass bei einem mehrsprachigem MM die Übersetzungen den Standardwert überschreiben.

Beispiel:

Ich habe ein MM in deutsch und englisch. Pflege ich nun bei einem mehrsprachigem Text-Attribut z.B. den Wert "Auto" speichere das ganze, passt es.
Möchte ich nun die englische Übersetzung pflegen (Oben recht Englisch gewählt und auf bearbeiten geklickt) z.B. Car überschreibt diese den deutschen Wert.
Die englische Übersetzung wird in die Datenbank mit dem Sprachkürzel de anstelle von en gespeichert.

Ich hoffe das ganze ist so nachvollziehbar.

Danke schon einmal vorab.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@tniebergall could you please have a final look at this and tell if your issue has been resolved?
