### ISSUE TITLE
Documentation: #404-Error after clicking Detail-Link

### ISSUE THREAD

**Issue by hansen-pansen** [MetaModels/core#664]
I just came across a thing in the documentation I'd like to request to be added to the "Beispiele".

In the very last step, when you register the modules on the pages, there is no information about the fact, that the detailpage needs to be a direct childpage of the listpage. Otherwise you will always get a "404" error.
It took me quite some time to figure out where the source of the problem was laying. It might be obvious to most advance MM-Users but for someone who sets it up for the first time, it is not too obvious.

**Comment by discordier** [comment]
No feedback, closing therefore.
