### ISSUE TITLE
Filter SingleSelections mit Tags

### ISSUE THREAD

**Issue by reneaye** [MetaModels/core#665]
Nach einem Update im Composer (weil Aliase jetzt ja wieder gehen)  habe ich nun ein Problem bei den Filtern. Wenn ich dort einen Single Selection erstelle und dann ein Tags Attribut auswähle kommt folgender Fehler:

Fatal error: Uncaught exception Exception with message Query error: Unknown column 'tag' in 'field list' (SELECT tag FROM mm_assets GROUP BY tag) thrown in system/modules/core/library/Contao/Database/Statement.php on line 283

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@reneaye could you please have a final look at this and tell if your issue has been resolved?
