### ISSUE TITLE
TNG: Baumansicht im Backend klappt falsch auf

### ISSUE THREAD

**Issue by psren** [MetaModels/core#667]
Wenn man das oberste Element in der Baumansicht ausklappt kommt das Dropdown nicht an der dafür vorgesehenen Stelle.

![bug_tagsystem](https://cloud.githubusercontent.com/assets/1016798/5390638/35e46744-810f-11e4-98d3-dcd9edecb26e.jpg)

**Comment by xantippe** [comment]
aktueller Workaround: Seite neu laden (reload)

**Comment by xantippe** [comment]
mit MM 2.0.0a10 und DCG 2.0.0b34 tritt das Verhalten nicht mehr auf
