### ISSUE TITLE
TNG: Baumansicht lässt sich nicht sortieren

### ISSUE THREAD

**Issue by psren** [MetaModels/core#668]
Die Pfeile sind zwar da, aber es lässt sich nicht sortieren.
Ist das ein Problem des DC_Generals?

**Comment by dmolineus** [comment]
Gerade getestet. Paste top, paste into, paste after funktionieren inzwischen einwandfrei.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@psren could you please have a final look at this and tell if your issue has been resolved?
