### ISSUE TITLE
Metamodel List - Listen-Offset

### ISSUE THREAD

**Issue by tniebergall** [MetaModels/core#669]
Ich habe 2 Metamodel-List-Elemente untereinander plaziert. Diese sind beide gleich konfiguriert, bis auf das beim ersten ein Limit von 3 eingestellt ist und bei dem zweiten ein offset von 3.

Im ersten Element werden die ersten 3 Einträge ausgegeben, das zweite Element sagt jedoch "Keine Einträge vorhanden"

Kann das jemand bestätigen oder habe ich einen Fehler in der Konfiguration?

Danke

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@tniebergall could you please have a final look at this and tell if your issue has been resolved?
