### ISSUE TITLE
[TNG] Clear cache on changes (WAS: Globaler Hinweis das der Cache aktiviert ist).

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#675]
Ich hatte das Problem, das Änderungen an den DCA-Combinations nicht übernommen werden. Nach etwas suchen, bin ich darüber gestolpert, das diese Daten jetzt gecached werden.

Eine gute sache, aber es wäre gut einen Hinweis zu haben das dieser Cache aktiviert ist. Ist ja ein neues Feature und bestimmt nicht jedem bekannt.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cboelter could you please have a final look at this and tell if your issue has been resolved?

**Comment by discordier** [comment]
Der Cache wird da in der Tat nicht geleert.

**Comment by discordier** [comment]
@zonky2 der Cache wird doch inzwischen geleert wenn man mit dem Auge toggled, oder?

**Comment by zonky2** [comment]
doch tüt
