### ISSUE TITLE
[TNG] Template not found im Backend

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#676]
Ich habe bei einer Testinstallation (Basierend auf der Movie-Database) das Problem, das ich immer folgende Fehlermeldung erhalte:

```
Fatal error: Uncaught exception Exception with message Could not find template "mm_attr_text_asin_image" thrown in system/modules/core/library/Contao/TemplateLoader.php on line 127 
```

Der fehler entsteht dadurch, das hier https://github.com/MetaModels/core/blob/93ef0b9748d7eb89a79bdbebe8a8a6b06f4ceaf7/src/MetaModels/DcGeneral/Events/MetaModel/RenderItem.php#L139 nur Text-Templates geladen werden. Das oben genannte Template ist jedoch nur in HTML5 vorhanden. Natürlich kann ich jetzt die Templates auch als TEXT-Template hinzufügen, aber das wäre irgendwie doppelte Arbeit. Besser wäre es, wenn es hier einen Fallback auf die Standardtemplates des Attributes geben würde.

**Comment by discordier** [comment]
@MetaModels/team @MetaModels/contributors Wie verfahren wir hier?

**Comment by MacKP** [comment]
Ich glaub da wäre es dann einfacher zu verstehen, wenn als Default das html5 Template (also das vorhandene Custom Template) genommen wird. Ist dann zwar erst mal nicht schön, aber da erkennt man dann wenigstens einen Zusammenhang. Wenn ein komplett anderes Template genommen wird, dann muss man das erst mal wissen (also in den Code gucken) warum da was ganz anderes raus kommt. Und das finde ich dann nicht so glücklich.

Viele Grüße

**Comment by cboelter** [comment]
Da es an der Stelle ja eigentlich um unformatierte Werte für den GroupHeader geht, wäre es nicht sinnvoll man greift dort auf RAW-Werte des Attributes zu, ganz ohne Templates? Dann hätten wir das Problem nicht.

**Comment by MrTool** [comment]
Die Idee mit den RAW Werten klingt für mich auch sinnvoller da es in diesem context doch auch zu Problemen kommen könnte wenn man dort html5 Templates parsed oder?

**Comment by MacKP** [comment]
Ja, gefällt mir bisher auch am besten. War erst mal nur ein Schnellschuss von mir, da mir die alternativen bisher noch gar nicht zugesagt haben ;-)

**Comment by discordier** [comment]
Raw geht nicht, da bei select und Tags usw da ein Array drin steht Deshalb gibt es Text als Format,  welches diese als plaintext rendert

**Comment by cboelter** [comment]
@discordier könnte man das nicht abfangen und per implode() einen String draus machen?

**Comment by discordier** [comment]
Klar, aber ich bezweifle dass saß was bringen wird die Datenzeile imploded zu haben.

**Comment by cboelter** [comment]
Naja ich wollte ja nicht die ganze Zeile sondern nur das Array mit den Werten des Attributes zusammenfügen, was anderes machen die Templates für die Tags ja auch nicht.

**Comment by xantippe** [comment]
@cboelter & @discordier 

ist die Sache noch aktuell oder kann Ticket geschlossen werden?

**Comment by discordier** [comment]
Shouldn't this have been fixed a long time ago? I mean, this reads like a duplicate of #47 which has been closed in f7d2bd9bdb65783b7dcd9f6f227944ab4c3a4788

> Fix issue #47 - fallback to default template for .text rendering if the template has been renamed and is not available in .text format.

**Comment by xantippe** [comment]
nach Test: FE und BE zeigen unterschiedliches Verhalten
es wurde ein eigenes Template gewählt, welches nur als HTML5 angelegt wurde (metamodels_pr_my_template.html5) und als Ausgabe wurde Text gewält...

* FE: kommt "Template not found (it is maybe...).
* BE: wechselt automatisch zum HTML5-Template

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cboelter could you please have a final look at this and tell if your issue has been resolved?

**Comment by discordier** [comment]
@xantippe Was ist denn bitte `metamodels_pr_my_template.html5` fyr ein Template? Und wo hast du es ausgewaehlt und wo wird es angezeigt?
Das passt in kein Namensschema:
* `metamodel_` fyr die pre und unrendered listen,
* `ce_metamodel_` fyr die content elemente
* `mod_metamodel_` fyr die module.
* `mm_filter_` fyr die clearall und filter container
* `mm_filteritem_` fyr die einzelnen Filter.

**Comment by xantippe** [comment]
das ist ein "Ableger" von ```metamodels_prerendered.*``` aus dem "prerendered" wird bei mir ein "pr" da mir sonst die Bezeichnungen zu lang werden (siehe #661)

Ausgewählt ist das in den Render-Einstellungen (Template*) - zum Test einmal im/für BE und einmal im/für FE

**Comment by discordier** [comment]
Das kann nicht sein, in then template options der render settings ist die Basis als `metamodel_` definiert, du hast jedoch ein suffix `s` dran, welches eigentlich allgemein NIE auswaehlbar und somit ladbar sein dyrfte. Da scheint also noch irgend ein anderes Problem zu bestehen.

**Comment by xantippe** [comment]
sorry - Schreibfehler => ```metamodel_prerendered.*```

**Comment by discordier** [comment]
Ok, allgemein ist es so, dass im Backend nur html5 verfygbar ist, siehe [hier](https://github.com/MetaModels/core/blob/1b40b02efbe9015768f21967d2e368a23304bc0d/src/MetaModels/DcGeneral/Events/MetaModel/RenderItem.php#L105) und [hier](https://github.com/MetaModels/core/blob/1b40b02efbe9015768f21967d2e368a23304bc0d/src/MetaModels/DcGeneral/Events/MetaModel/RenderItem.php#L125).

Das hat den Grund, dass Contao im Backend auch ausschliesslich html5 supported.

Ich weiss nun nicht genau wie wir hiermit umgehen sollen, siehe auch #47 wo wir das Problem "umgekehrt" hatten.

**Comment by xantippe** [comment]
ich denke auch, das ist eher eine "philosophische Fragestellung" - im Prinzip kann ich mit der Fehlermeldung im FE leben... man könnte, um es "rund" zu machen, die Ausgabe der Fehler-Meldung an die Contao Systemeinstellung "Fehlermeldungen ausgeben" koppeln...
