### ISSUE TITLE
MM und Composer: Extrem lange Verzeichnispfade

### ISSUE THREAD

**Issue by Wagnerwagner** [MetaModels/core#683]
Mir ist aufgefallen, dass die Verzeichnispfade bei einer MM-Installation mit Composer im Composer-Verzeichnis extrem lang sind.
z.B.
composer/vendor/metamodels/attribute_translatedcombinedvalues/src/system/modules/metamodelsattribute_translatedcombinedvalues/MetaModels/Attribute/TranslatedCombinedValues/TranslatedCombinedValues.php

Wenn man auf einem Windows-System mit NTFS arbeitet liegt die maximale Zeichenanzahl für einen Verzeichnispfad bei 256 Zeichen.
Das betrifft z.B. xampp-Installationen auf Windows, die dann zusätzlich noch das Laufwerk und diverse vorangestellte Verzeichnisse (wie z.B. die Verzeichnissturktur von xampp) beinhalten.
Genau so wenn ich mir z.B. ein Backup der kompletten Verzeichnisstruktur vom FTP auf meinen Windows-Rechner (NTFS) ziehen möchte. Das ist bei so langen Pfaden nicht möglich, da Windows dann eine Fehlermeldung "Zielpfad ist zu lang" anzeigt und die Verzeichnisse/Dateien nicht anlegt.

Habe nicht weiter nachgeforscht, kann mir aber vorstellen, dass es auch mit anderen Dateisystemen Probleme geben könnte.
Ist für mich persönlich kein Beinbruch, wollte es aber hier mal gesagt haben, damit ihr das auf dem Plan habt.

**Comment by discordier** [comment]
Das Problem sollte sich weitestgehend erledigt haben, oder?

**Comment by discordier** [comment]
Considering this now fixed.
