### ISSUE TITLE
Backend-Integration: Sortierung in der Backend-Navigation

### ISSUE THREAD

**Issue by Wagnerwagner** [MetaModels/core#684]
Wenn ich eine Eingabemaske für ein MetaModel anlege und diese in das Backend integriere, wird die Backend-Navigation umsortiert.

Als Integrationstyp habe ich "Unabhängig" eingestellt und die Backend-Hilfetexte eingetragen.
Wenn man als Backend-Bereich "Inhalte" wählt, fällt das nicht weiter auf. Wählt man aber als Backendbereich z.B. "System" rutscht in der Backendnavigation die komplette Navigationsgruppe "System" nach oben, vor die Gruppe "Inhalte".
Der Navigationspunkt der Eingabemaske wird nun auch nicht mehr am Ende der ausgewählten Gruppe eingefügt, sondern ganz oben in der Gruppe, als ersten Navigationspunkt.

In den Einstellungen zur Eingabemaske hat sich in letzter Zeit einiges getan (z.B. Bereich "Data manipulation permissions"). Entweder da ist was schief gelaufen, oder das ist ein Anwenderfehler meinerseits. 

Getestet mit dem aktuellen nightly tng (composer) und Contao 3.3.7.

**Comment by ways2web** [comment]
gibt es schon was neues zu dieser problematik mit der Backend-Menü Sortierung?

**Comment by discordier** [comment]
Bitte mit 1310b43 probieren.

**Comment by ways2web** [comment]
funktioniert :+1:
