### ISSUE TITLE
Broken jumpTo link

### ISSUE THREAD

**Issue by MrTool** [MetaModels/core#687]
In the new TNG the jumpTo generation is broken if you are using a non multilang MetaModels and enables the feature "add language to url".

Here is an example:
```php
False:
xx/partner-netzwerk/detail/team-sisu-gmbh.html

Right:
de/partner-netzwerk/detail/team-sisu-gmbh.html
```

It could be that this issue is in any way related to my PR #679 
If i got some time I could dive into it

**Comment by discordier** [comment]
Where is this `xx` originating from? Could you elaborate some more?

**Comment by MrTool** [comment]
The only thing i figured out was that if i create an metamodel render setting and directly fill out the redirect part (link url / filter)(non multilang mm) and save the item, exactly this values got lost and i had to fill it out again.

Also the xx stands in the serialized array in the database after an successful 2nd save.

**Comment by discordier** [comment]
Ok, found the problem.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@MrTool could you please have a final look at this and tell if your issue has been resolved?
