### ISSUE TITLE
[TNG] FilterSetting-Subscriber Fehlermeldung

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#690]
Ich kriege auf meinem aktuellen TNG folgende Fehlermeldung:

```
Warning: Invalid argument supplied for foreach() in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/FilterSetting/Subscriber.php on line 105 
```
Diese Meldung entsteht daraus, das hier das ```$GLOBALS['METAMODELS']['filters']```durchlaufen werden soll. Dieses existiert jedoch in einem TNG ohne zusätzliche Filter-Pakete nicht. Es müss hier noch eine Abfrage rein, ob das ganze existiert oder nicht.

```
if(!isset($GLOBALS['METAMODELS']['filters'])) {
    return;
}
```

Ich mache dazu am Montag einen entsprechenden PR.

**Comment by discordier** [comment]
Fixed with #691.
