### ISSUE TITLE
[TNG] Condition funktionieren nicht mit den Tags

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#692]
Ich versuche gerade die Conditions mit dem Tags-Attribute zu verwenden, leider klappt das nicht. Das SubmitOnChange habe ich bei mir lokal ergänzt, aber trotzdem werden die Conditions nicht ausgeführt.

**Comment by discordier** [comment]
Let's continue this in https://github.com/MetaModels/attribute_tags/issues/31
