### ISSUE TITLE
[TNG] Verschachtelte MetaModels sehr unübersichtlich

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#693]
Ich habe folgende Konstellation ...

MM: Person
   - MM: Interview-Basis-Daten
    - MM: Interview Fragen / Antworten

im moment ist es für den User nicht wirklich erkennbar, auf welcher ebene er aktuell ist, weil es im Sortinmode nur so aussieht:

![bildschirmfoto 2014-12-27 um 13 38 54](https://cloud.githubusercontent.com/assets/550207/5561287/bba12532-8dcd-11e4-93e4-e06a896f5fed.png)

Hier bräuchte man entweder im Sort-Header mehr Information als nur tstamp oder ideal wäre ein Breadcrumb + erweiterter Sortheader.

**Comment by tim-bec** [comment]
https://github.com/MetaModels/core/issues/184

**Comment by xantippe** [comment]
@tim-bec & @cboelter 

da #184 geschlossen ist, sollte das Ticket auch geschlossen werden können, da als "*duplicate*" gekennzeichnet

**Comment by xantippe** [comment]
=> keine Reaktion - geschlossen siehe #184
