### ISSUE TITLE
What are the tech specs to use Metamodels nightly ?

### ISSUE THREAD

**Issue by septentrio** [MetaModels/core#694]
Hello,

I'm trying to install manually Metamodels (Metamodels 2.X nightly build) on a contao 3.2.9 installation but i've got several error messages although i instelled it correctly.

Am I using the right version ?

Which version of php , json are required ?

My website is hosted by 1and1

**Comment by cboelter** [comment]
Can you post the error messages?

**Comment by septentrio** [comment]
This is the message i get when i click on the "define input/output combination for metamodel ID1" : 

Fatal error: Call to a member function hasErrors() on a non-object in /homepages/31/d351005431/htdocs/clients/archeopole/system/modules/generalDriver/templates/dcbe_general_field.html5 on line 17

**Comment by septentrio** [comment]
Sorry that was because i had an outdated version of Metamodels remaining. everything seems to be fine right now
