### ISSUE TITLE
[TNG] Parented Listenansicht wird falsch dargestellt bei fixem sorting

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#695]
Ich habe ein MetaModel angelegt und dem DCA-Setting folgende Sorting-Konfiguration zugewiesen.
![bildschirmfoto 2015-01-04 um 18 06 36](https://cloud.githubusercontent.com/assets/550207/5606730/bde92270-943c-11e4-9a8d-92fa17500894.png)

Die Listenansicht sieht dann wie folgt aus.

![bildschirmfoto 2015-01-04 um 18 09 25](https://cloud.githubusercontent.com/assets/550207/5606731/d89f5896-943c-11e4-9433-231bd6ac409c.png)

Wenn ich das ganze auf enable manual sorting umstelle, sieht die Listenansicht richtig aus.

**Comment by xantippe** [comment]
Test mit MM core 2.0.0-alpha9 => sieht o.k. aus

![shot62](https://cloud.githubusercontent.com/assets/1045318/12276651/3762b55c-b977-11e5-9afc-fc5c60a119ae.jpg)

![shot63](https://cloud.githubusercontent.com/assets/1045318/12276655/3bf23390-b977-11e5-9b5c-b3cd156b8699.jpg)
