### ISSUE TITLE
Rework factories and introduce them into filters

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#698]
- [X] https://github.com/MetaModels/attribute_checkbox
- [X] https://github.com/MetaModels/attribute_translatedcheckbox
- [X] https://github.com/MetaModels/filter_checkbox
- [X] https://github.com/MetaModels/filter_select
- [X] https://github.com/MetaModels/filter_fromto
- [X] https://github.com/MetaModels/filter_tags
- [X] https://github.com/MetaModels/filter_text (Thanks to @cboelter)
- [X] https://github.com/MetaModels/filter_register
- [X] https://github.com/MetaModels/filter_range
- [x] https://github.com/MetaModels/filter_perimetersearch

**Comment by cboelter** [comment]
I'm working on filter_text.
