### ISSUE TITLE
Hunt down all occurences of \Database::getInstance().

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#699]
All of those should be replaced with the proper database from the service container.

**Comment by zonky2** [comment]
noch aktuell?

**Comment by discordier** [comment]
yop

**Comment by cliffparnitzky** [comment]
This is what I found:

**Core**

- [ ] *core/tests/MetaModels/Test/ServicesTest.php:42:* `$container['database.connection'] = \Database::getInstance();`
- [ ] *core/src/MetaModels/DcGeneral/DataDefinition/Palette/Condition/Palette/RenderSettingAttributeIs.php:93:* `self::$attributeTypes[$value] = \Database::getInstance()`
- [ ] *core/src/MetaModels/DcGeneral/DataDefinition/Palette/Condition/Property/InputScreenAttributeIs.php:92:* `self::$attributeTypes[$value] = \Database::getInstance()`
- [ ] *core/src/MetaModels/DcGeneral/DataDefinition/Palette/Condition/Property/InputScreenRenderModeIs.php:92:* `self::$stateBuffer[$value] = \Database::getInstance()`
- [ ] *core/src/MetaModels/DcGeneral/DataDefinition/Palette/Condition/Property/RenderSettingAttributeIs.php:92:* `self::$attributeTypes[$value] = \Database::getInstance()`
- [ ] *core/src/MetaModels/Events/DatabaseBackedListener.php:233:* `$objData = \Database::getInstance()->prepare('SELECT * FROM tl_metamodel WHERE tableName=?')`
- [ ] *core/src/MetaModels/Filter/Rules/SimpleQuery.php:75:* `$dataBase = \Database::getInstance();`
- [ ] *core/src/MetaModels/Helper/TableManipulation.php:130:* `return \Database::getInstance();`
- [ ] *core/src/MetaModels/Helper/TableManipulation.php:151:* `return \Database::getInstance();`
- [ ] *core/src/MetaModels/Helper/UpgradeHandler.php:39:* `return \Database::getInstance();`

**Attributes**

- [ ] *attribute_timestamp/runonce/runonce.php:24:* `$handler = new MetaModels\Attribute\Timestamp\Helper\UpgradeHandler(\Database::getInstance());`
- [ ] *attribute_combinedvalues/runonce/runonce.php:24:* `$handler = new MetaModels\Attribute\CombinedValues\Helper\UpgradeHandler(\Database::getInstance());`
- [ ] *attribute_tags/src/MetaModels/DcGeneral/Events/Table/Attribute/Tags/Subscriber.php:509:* `$objDB = \Database::getInstance();`
- [ ] *attribute_select/src/MetaModels/DcGeneral/Events/Table/Attribute/Select/Subscriber.php:508:* `$objDB = \Database::getInstance();`
- [ ] *attribute_file/src/MetaModels/Attribute/File/File.php:47:* `$objQuery = \Database::getInstance()`
- [ ] *attribute_translatedurl/runonce/runonce.php:25:* `$handler = new MetaModels\Attribute\TranslatedUrl\Helper\UpgradeHandler(\Contao\Database::getInstance());`

**Comment by cliffparnitzky** [comment]
Wie mit @discordier besprochen sind alle Dateien markiert, die nicht angepasst werden können.

**Comment by zonky2** [comment]
gefixt
