### ISSUE TITLE
PHP minimum requirement in composer.json

### ISSUE THREAD

**Issue by fritzmg** [MetaModels/core#704]
Line 117 in BackendModuleBuilder.php and line 181 in ViewCombinations.php require the `json_encode` option JSON_PRETTY_PRINT, which is only available in PHP 5.4 and onwards. However, the composer.json still lists php >=5.3 as the minimum requirement.

**Comment by discordier** [comment]
Thanks for notifying us, will be fixed.
The option is only added for cosmetics and we might drop the json encoding altogether as doctrine-cache does encode just fine on it's own.

**Comment by dmolineus** [comment]
Run into that issue today as well. For a fallback the constants value is `128`. If you want to set it for PHP < 5.4

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@fritzmg could you please have a final look at this and tell if your issue has been resolved?

**Comment by fritzmg** [comment]
Uh, I only reported it because someone else on the german contao forum ran into this problem. I don't have any MM installations running on a PHP 5.3 server. Discordier's fix only regards the ViewCombinations.php . What's the BackendModuleBuilder.php part of? I can't find it in any repository.

**Comment by discordier** [comment]
You are right, has been fixed as well now.
