### ISSUE TITLE
Select für Sprache wird nicht angezeigt - Mehrsprachiges MM

### ISSUE THREAD

**Issue by poutvie** [MetaModels/core#705]
Contao 3.2.14 und 3.2.16
metamodels/core dev-tng (584c886d)
metamodels/bundle_all 1.0.1
contao-community-alliance/dc-general 	dev-develop (c3b7ee2d)

Nach MM Update sehe ich den Selectinput für die Sprache nicht mehr. Kann also beim Anlegen eines neuen Datensatzes die Sprache nicht mehr wechseln. 
Cache habe ich diesmal geleert.
(nur zur Info: Nach Update auf Contao 3.4 (Konflikt gekennzeichnet) geht die Sprachauswahl, aber der Filepicker nicht)

**Comment by discordier** [comment]
Eben weil der filepicker nicht geht wurde der conflict gekennzeichnet. :)
Das ist eben das issue im 3.4.0 welcher mit 3.4.1 behoben wird.

**Comment by discordier** [comment]
Dev TODO: Checken warum der DCG nicht im mehrsprachigen Modus konfiguriert wird.

**Comment by poutvie** [comment]
Mit dev-tng (9f78f80f) funktioniert die Sprachauswahl unter Contao 3.2.16 wieder. Danke!
