### ISSUE TITLE
Move contents of database.sql to dca files.

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#706]
As we are Contao3+ now, we can move the contents of database.sql to the dca files and get rid of the database.sql file.

# List of repositories to apply above tasks to:
- [x] metamodels/core
- [x] metamodels/attribute_alias => https://github.com/MetaModels/attribute_alias/pull/24
- [x] metamodels/attribute_checkbox => https://github.com/MetaModels/attribute_checkbox/pull/20
- [x] metamodels/attribute_color
- [x] metamodels/attribute_combinedvalues => https://github.com/MetaModels/attribute_combinedvalues/pull/19
- [x] metamodels/attribute_country => https://github.com/MetaModels/attribute_country/pull/14
- [x] metamodels/attribute_decimal
- [x] metamodels/attribute_file => https://github.com/MetaModels/attribute_file/pull/67
- [ ]  metamodels/attribute_geoprotection is alpha version R.I.P.
- [x] metamodels/attribute_langcode => https://github.com/MetaModels/attribute_langcode/pull/8
- [x] metamodels/attribute_longtext
- [x] metamodels/attribute_numeric
- [x] metamodels/attribute_rating => https://github.com/MetaModels/attribute_rating/commit/d8e422448525f3f013e939ecac4a9e126613f018
- [x] metamodels/attribute_select => https://github.com/MetaModels/attribute_select/pull/61
- [x] metamodels/attribute_tabletext => https://github.com/MetaModels/attribute_tabletext/commit/96eb1076eff83e377eccdc1efd89b8bf899e9ac7
- [x] metamodels/attribute_tags => https://github.com/MetaModels/attribute_tags/commit/bb60aa32c71e7e11d6233edab12a2be3b1ad8864
- [x] metamodels/attribute_text => https://github.com/MetaModels/attribute_text/pull/15
- [x] metamodels/attribute_timestamp =>https://github.com/MetaModels/attribute_timestamp/pull/30
- [x] metamodels/attribute_url =>https://github.com/MetaModels/attribute_url/pull/25
- [x] metamodels/attribute_translatedalias => https://github.com/MetaModels/attribute_translatedalias/commit/b58b1e3a8077389736163aebcf4e42b8bbb4616f
- [x] metamodels/attribute_translatedcheckbox => https://github.com/MetaModels/attribute_translatedcheckbox/commit/60eac0569e088d07b447a38b40c981b3d77aa2b0
- [x] metamodels/attribute_translatedcombinedvalues => https://github.com/MetaModels/attribute_translatedcombinedvalues/commit/680b93019397973962137b2d64b1a3e109945494
- [x] metamodels/attribute_translatedfile => https://github.com/MetaModels/attribute_translatedfile/commit/1b35410abbf7b9f7f61a529b26064f195c44f765
- [x] metamodels/attribute_translatedlongtext => https://github.com/MetaModels/attribute_translatedlongtext/commit/9af29e9b800f41220ae9a1ebda33b47ae65d8ce4
- [x] metamodels/attribute_translatedselect => https://github.com/MetaModels/attribute_translatedselect/commit/7d96b2c128f0c0659863561c96d911d8348db063
- [x] metamodels/attribute_translatedtabletext => https://github.com/MetaModels/attribute_translatedtabletext/commit/29bc6c904c42707e617a224eda58857303c20f7c
- [x] metamodels/attribute_translatedtags => https://github.com/MetaModels/attribute_translatedtags/commit/18688b129dda51457a5cd863670358f22f992ec3
- [x] metamodels/attribute_translatedtext => https://github.com/MetaModels/attribute_translatedtext/commit/51f35b949aaa005add8b0e62679af76aa8def242
- [x] metamodels/attribute_translatedurl
- [x] metamodels/filter_checkbox => https://github.com/MetaModels/filter_checkbox/pull/12
- [x] metamodels/filter_fromto => https://github.com/MetaModels/filter_fromto/pull/21
- [x] metamodels/filter_perimetersearch => https://github.com/MetaModels/filter_perimetersearch/commit/3a801b5a504b92d01a0574383504f0e99c06ccd8
- [x] metamodels/filter_range => https://github.com/MetaModels/filter_range/pull/11
- [x] metamodels/filter_register => https://github.com/MetaModels/filter_register/commit/4b23c528477dbed6cd892b3134f748009de2785e
- [x] metamodels/filter_select
- [x] metamodels/filter_tags => https://github.com/MetaModels/filter_tags/pull/22
- [x] metamodels/filter_text => https://github.com/MetaModels/filter_text/pull/34

e.g.
```
'sql' => 'char(1) NOT NULL default \'\'',
'sql' => 'char(1) NOT NULL default \'0\'',
'sql' => 'char(5) NOT NULL default \'\'',
'sql' => 'varchar(10) NOT NULL default \'\'',
'sql' => 'varchar(32) NOT NULL default \'\'',
'sql' => 'varchar(255) NOT NULL default \'\'',
'sql' => 'int(10) unsigned NOT NULL default \'0\'',
'sql' => 'blob NULL',
'sql' => 'text NULL',
```

**Comment by richardhj** [comment]
Should I go about it?
I ask because some attributes are released as stable version and use the database.sql yet.

**Comment by discordier** [comment]
Would be nice, we can safely change this in patch level releases as the results are compatible.

**Comment by zonky2** [comment]
@richardhj we can close this ticket?

**Comment by richardhj** [comment]
Definitely.

**Comment by zonky2** [comment]
finish
