### ISSUE TITLE
[TNG] Mode4 Ablage buttons werden falsch dargestellt

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#707]
Ich seit neuestem das Problem, das mir wenn ich bei den FilterSetting-Attribute etwas über das Plus im Datensatz einfügen möchte, mir die Buttons für Ablage leeren etc. falsch dargestellt werden.

![bildschirmfoto 2015-01-15 um 09 26 25](https://cloud.githubusercontent.com/assets/550207/5754418/c73eaf52-9c98-11e4-8fad-640858ec3014.png)

**Comment by discordier** [comment]
aeh, was treibt denn der "Neu" Button da unten?

Evtl. CSS Problem durchs neue clipboard? @tristanlins, hast du eine Idee?

**Comment by tristanlins** [comment]
Mh, das HTML wäre Interessant, ich vermute eher dass das kaputt ist und weniger an ein CSS Problem (ausschließen kann ich es aber nicht).

**Comment by cboelter** [comment]
Nicht schön aber selten ... https://gist.github.com/c4631157288417ec0d4e.git

**Comment by tristanlins** [comment]
Mh, der "Neu" Button hängt wirklich in dem Clipboard Container ... stammt der Auszug das aus dem Source oder den Entwicklertools?

**Comment by cboelter** [comment]
Das war aus Firebug. Soll ich nochmal den Firefox Source kopieren?

**Comment by discordier** [comment]
Waere super.

**Comment by cboelter** [comment]
Habe euch einmal den kompletten output eingefügt: https://gist.github.com/cboelter/20c6cbe282b83e82eea6#file-dcg_clipboard_source-html

**Comment by xantippe** [comment]
@cboelter: ist das ein Schreibfehler? im Ticket steht "*FilterSetting-Attribute*" - im Screenshot geht es aber um die Attribute einer Render-Einstellung..?

Aktueller Test: MM core 2.0.0-alpha8 für Render-Einstellung - siehe Screenshot - funktioniert und sieht i.O. aus

=> Ticket kann m.E. damit geschlossen werden

![shot34](https://cloud.githubusercontent.com/assets/1045318/12085724/3dc3a416-b2c3-11e5-84ea-5920acfe0d51.jpg)

zur Info: https://github.com/contao-community-alliance/dc-general/issues/166

**Comment by xantippe** [comment]
letzte CSS "Bugs" sind im DCG als PR vorhanden
