### ISSUE TITLE
PageID was not mounted

### ISSUE THREAD

**Issue by HellPat** [MetaModels/core#708]
Siehe auch: https://community.contao.org/de/showthread.php?54989-Metamodels-was-not-mounted

Ich habe ein Problem mit Benutzerkonten die keine Admins sind.
Bei bearbeiten eines Eintrags in der Metamodels-Tabelle bekomme ich mit dem eingeschränkten Nutzer folgende Meldung:

```
[2015-01-14 09:51] Not enough permissions to edit page ID mm_references::5 or paste after/into page ID
Löschen Anzeigen
[2015-01-14 09:51] Page ID mm_references::5 was not mounted
Jetzt habe ich ihm aber über die Gruppenberechtigungen die Berechtigung für die Tabelle schon gegeben.
```

Und wieso steht da "Page ID"?

Hat jemand eine Ahnung woran das liegen kann?

(Der Benutzer ist der Gruppe auch zugeordnet, das Metamodel heißt "Kunden" und die Tabelle `mm_references`)

Die Zugriffrechte bei "Definieren sie die ein- ausgabe Optionen" stimmen.

**Comment by tim-bec** [comment]
Ist dein MetaModel ein Kind von tl_page ?

**Comment by psren** [comment]
Nein, hat aber eine Verknüpfung zu Page mittels einen Select-Felds (Select Attribut).
Also quasi eine normale Seite (weil die Seiten komplizierter sind als ich es mit einer normalen Detailseite hinbekommen hätte)

![bildschirmfoto 2015-01-15 um 17 46 49](https://cloud.githubusercontent.com/assets/1016798/5761867/97930afa-9cde-11e4-9688-bea129efa219.png)

**Comment by discordier** [comment]
Aaaaaaaaaah

**Comment by psren** [comment]
Aaaaaaaaaah?
Bin ich zu doof?
Fieser Bug?
Kann ich irgendwie weiter helfen?

**Comment by psren** [comment]
@tim-bec wenn du das mit Kind meintest dann ist es eines. Aber halt nicht über pid.

**Comment by tim-bec** [comment]
Hat der eingeschränkte Nutzer den Zugriff auf tl_page ? Wenn nicht... setz dort an, denn wenn Du ein MetaModels irgendwo anders dranhängst müssen auch dort rechte vorhanden sein.

**Comment by psren** [comment]
Mhhh, also der Benutzer hat folgende Berechtigungen auf tl_page.

In den Pagemounts ist der Root ausgewählt, daran kann es also nicht liegen.
Und dann ist noch das hier ausgewählt.

![bildschirmfoto 2015-01-19 um 11 26 36](https://cloud.githubusercontent.com/assets/1016798/5799063/443b68f0-9fce-11e4-8e58-da44d6c577fe.png)
![bildschirmfoto 2015-01-19 um 11 26 58](https://cloud.githubusercontent.com/assets/1016798/5799065/443d8108-9fce-11e4-8096-83ceb246ac45.png)
![bildschirmfoto 2015-01-19 um 11 27 19](https://cloud.githubusercontent.com/assets/1016798/5799064/443d168c-9fce-11e4-8189-77173a0e42cb.png)

Ahnunglos geraten: Kann es vielleicht sein dass irgendwie die ID eine Berechtigung braucht? Eigentlich ja nicht. Sollten soch alle relevanten Felder freigegeben sein?!?

**Comment by discordier** [comment]
Bug im Contao Core.
Habe mit @leofeyer daryber gesprochen. Ich werde versuchen einen Patch zu basteln, jedoch ist noch unklar wo der dann yberall rein kommt.

Als Workaround kann man leider momentan nur einen user als admin setzen, da den DCA Dateien des Core egal ist welchen page mount man hat, da die id des aktuellen Datensatzes (in diesem Falle: `mm_references::5`) in den dca Dateien des Core als id von `tl_page` angesehen wird.
Das Verhalten kommt aus den `checkPermission()` Methoden welche aus dem loadCallback HOOKs getriggert wird.

**Comment by tim-bec** [comment]
Fuuuh. Da renn ich nun auch rein :(

**Comment by psren** [comment]
Hast du dazu auch ein Ticket aufgemacht im Contao Core und hast eine Referenz dazu, dass wir das beobachten können?

**Comment by discordier** [comment]
As discussed in contao/core#7585 this will be implemented in Contao 3.5 and therefore in the next LTS of Contao.
We will think if we can implement a 60% working workaround that deactivates the checkPermission hooks from within DC_General.

**Comment by xantippe** [comment]
noch aktuell?

**Comment by psren** [comment]
Ich weiß es leider nicht, aber vielleicht weiß der @discordier mehr. Das referenzierte Ticket ist aber noch offen.

**Comment by xantippe** [comment]
@tim-bec kannst Du das prüfen?

**Comment by tim-bec** [comment]
@xantippe da das core-ticket noch offen ist tippe ich mal auf noch aktuell, meine "damalige" installation kann ich aktuell leider nicht zum testen hochziehen.

**Comment by xantippe** [comment]
o.k. - dann warten wir mal auf Core

**Comment by discordier** [comment]
Core wird es da auch nix geben, da es einfach zu unhandlich ist... Man mysste da einen bugfixing listener bauen... :(

**Comment by xantippe** [comment]
o.k. - lassen wir das Ticket a) als 'enhancement' stehen oder b) ganz zu? ich wäre für a

**Comment by discordier** [comment]
Wir lassen es als bug stehen wie es ist, denn es ist ein bug und kein enhancement

**Comment by xantippe** [comment]
o.k.

**Comment by zonky2** [comment]
Test in MM 2.2:

* Als Admin läuft die Auswahl
* Als eingeschränkter Benutzer:

```
Symfony\Component\HttpKernel\Exception\NotFoundHttpException:
No route found for "GET /de/5,4" (from "https://mydomain.tld/")

  at vendor/symfony/http-kernel/EventListener/RouterListener.php:136
  at Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest()
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:126)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:264)
  at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:239)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:73)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:168)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (vendor/symfony/http-kernel/HttpKernel.php:134)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:31)
```

**Comment by zonky2** [comment]
mit den richtigen Benutzerberechtigungen funktioniert
