### ISSUE TITLE
Bei jedem Filter lässt sich nur eine Filterregel anlegen

### ISSUE THREAD

**Issue by AgentCT** [MetaModels/core#710]
Jeder Filter lässt sich nur noch mit einer Filterregel anlegen, bei jeder weiteren erscheint sofort eine Fehlermeldung.

<code> Fatal error: Class 'ContaoCommunityAlliance\DcGeneral\Clipboard\Filter' not found in /www/htdocs/wxxxxxx/xxxxxxxxx.de/composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/FilterSetting/Subscriber.php on line 158</code>

Metamodel-Version: dev-tng (69a6d3d3)

**Comment by cboelter** [comment]
Welche version vom DcGeneral hast du installiert?

**Comment by AgentCT** [comment]
Das Update von DC 1.6.1. auf DC 1.7.0 hat die Lage noch verschlimmert, jetzt erhalte ich noch mehr Fehlermeldungen.

**Comment by cboelter** [comment]
äääh DcGeneral 1.X? Der TNG nutzt DcGeneral 2.X bzw. den dev-develop.

**Comment by AgentCT** [comment]
Ich meinte dc-general 2.0.0-beta21

**Comment by cboelter** [comment]
Ok, wechsel doch mal auf den dev-develop, der funktioniert bei mir ohne Probleme.

**Comment by AgentCT** [comment]
Der Wechsel hilft leider auch nicht, ich habe weiter die gleichen Probleme. Außerdem bekomme ich noch folgende Meldung:
<code>
Warning: array_merge(): Argument #2 is not an array in composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php on line 289
#0 [internal function]: __error(2, 'array_merge(): ...', '/www/htdocs/w01...', 289, Array)
#1 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(289): array_merge(Array, NULL)
#2 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(333): DependencyInjection\Container\ContainerInitializer->provideSingletons(Object(Pimple))
#3 system/initialize.php(233): DependencyInjection\Container\ContainerInitializer->init()
#4 contao/main.php(24): require_once('/www/htdocs/w01...')
#5 {main}
</code>

**Comment by cboelter** [comment]
Das ganze ist über composer installiert? Ist das ein upgrade vin dev-contao3 auf dev-tng?

**Comment by AgentCT** [comment]
Die Installation läuft von Anfang auf Contao 3 mit Composer. Vielleicht wird das Problem ja durch ein Upsate eines anderen Fehlers beseitigt. Ich warte einfach mal ein paar Tage.

**Comment by cboelter** [comment]
ja aber hast irgendwann zwischendurch mal vom dev-contao3 branch auf dev-tng / 2.0 aktualisiert?

**Comment by tim-bec** [comment]
Selbiges Problem hier, ein Filter Attribut lässt sich anlegen, ein weiteres nicht mehr und bestehende lassen sich auch nicht bearbeiten, sobald man einmal versucht hat ein weiteres zu erstellen.

```

( ! ) Fatal error: Class 'ContaoCommunityAlliance\DcGeneral\Clipboard\Filter' not found in /Users/timbec/WEB/xxx-website/composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/FilterSetting/Subscriber.php on line 158
Call Stack
#	Time	Memory	Function	Location
1	0.0000	242712	{main}( )	../main.php:0
2	0.0699	3932568	Main->run( )	../main.php:293
3	0.0702	4071184	Contao\Backend->getBackendModule( )	../main.php:142
4	0.1056	5783512	MetaModels\BackendIntegration\Module->generate( )	../Backend.php:409
5	0.1056	5787592	ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle( )	../Module.php:77
6	0.1058	5800808	ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch( )	../DefaultController.php:129
7	0.1058	5800808	Symfony\Component\EventDispatcher\EventDispatcher->dispatch( )	../EventPropagator.php:119
8	0.1058	5801072	Symfony\Component\EventDispatcher\EventDispatcher->doDispatch( )	../EventDispatcher.php:53
9	0.1058	5803616	call_user_func ( )	../EventDispatcher.php:164
10	0.1058	5804008	ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction( )	../EventDispatcher.php:164
11	0.1058	5804680	call_user_func_array ( )	../BaseView.php:155
12	0.1058	5805048	ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->paste( )	../BaseView.php:155
13	0.1059	5806200	ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->showAll( )	../TreeView.php:725
14	0.1099	5930200	ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->viewTree( )	../TreeView.php:766
15	0.1106	6000040	ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->generateTreeView( )	../TreeView.php:649
16	0.1106	6001520	ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->parseModel( )	../TreeView.php:501
17	0.1107	6003000	ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->generateButtons( )	../TreeView.php:439
18	0.1132	6017424	ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch( )	../BaseView.php:2117
19	0.1132	6017424	Symfony\Component\EventDispatcher\EventDispatcher->dispatch( )	../EventPropagator.php:119
20	0.1132	6017600	Symfony\Component\EventDispatcher\EventDispatcher->doDispatch( )	../EventDispatcher.php:53
21	0.1133	6018472	call_user_func ( )	../EventDispatcher.php:164
22	0.1133	6018896	MetaModels\DcGeneral\Events\Table\FilterSetting\Subscriber->generatePasteButton( )	../EventDispatcher.php:164

**Comment by tim-bec** [comment]
Keine Probleme jedoch mit DC-General "dev-develop"

**Comment by discordier** [comment]
Neues tag im dcg folgt diese Woche.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@AgentCT could you please have a final look at this and tell if your issue has been resolved?
