### ISSUE TITLE
Status Inaktive bei Sichtbarkeitseinstellung der Backend Eingabefeldern greift nicht bei Checkboxen

### ISSUE THREAD

**Issue by JT-007** [MetaModels/core#711]
Hallo zusammen,

wenn man bei den Sichtbarkeitseinstellungen eines Backend Eingeabefeldes als Attribut eine Checkbox angibt und beim Wert "Aktive" verwendet greift die Sichbarkeitseinstellung. Stellt man den Wert auf "Inaktive" funktioniert die Abfrage jedoch nicht.

Ich habe es nun vorübergehend mit NOT gelöst aber der Wert "Inaktive" sollte auch funktionieren.

MM Core: dev-tng (69a6d3d3)
Contao 3.3.7

Lg,
JT

**Comment by discordier** [comment]
Das ist mir auch schon aufgefallen. Das Problem liegt daran, dass hier der Vergleich auf `string (0) "" == string(1) "0"` v orgenommen wird. Da muss man im building der condition checken ob das value numeric ist.

**Comment by xantippe** [comment]
ein ein "Fehler" im DCG - hier wird "nix" '' bei $value mit Null '0' von $this->propertyValue verglichen

https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Palette/Condition/Property/PropertyValueCondition.php#L158

https://github.com/contao-community-alliance/dc-general/issues/169
