### ISSUE TITLE
submitOnChange bei Checkbox verursacht Fehler bei Datei mit Mehrfachauswahl

### ISSUE THREAD

**Issue by JT-007** [MetaModels/core#712]
Hallo Zusammen,

ich habe bei einer MM Backend Eingabemaske verschiedenste Felder und unter anderem eine Checkbox (mit der Option submitOnChange) und ein Dateifeld (mit den Optionen Pflichtfeld, Passen Sie den Dateibaum an, Gültige Dateitypen, Nur Dateien erlauben und Mehrfachauswahl),

Wenn ich nun Bilder beim Dateifeld auswähle werden diese problemlos gespeichert. Wenn man den MM Eintrag bearbeitet und dich Checkbox mit submitOnChange verändert wird die Seite ja neu geladen und beim Dateifeld sind keine Bilder ausgewählt.

Wenn man zurück geht ohne zu speichert und den Datensatz nochmals bearbeitet sind die Anfangs gewählten Dateien wieder da.

MM Core: dev-tng (69a6d3d)
Contao 3.3.7

Lg,
JT

**Comment by discordier** [comment]
This is a blocker bug partially addressed with 99a988a3a46ac3fa45bbeac8c860c3ba65580d86 but really evil.

**Comment by xantippe** [comment]
aktuelle Test: Contao 3.5.6 mit MM 2.0.0-alpha8

siehe #493 und https://github.com/contao-community-alliance/dc-general/issues/96

m.E. kann das Ticket geschlossen werden
