### ISSUE TITLE
Bug Paste-Button bei Einträgen in einem MeteModel

### ISSUE THREAD

**Issue by markknochen1** [MetaModels/core#718]
ich kann nach dem letzten Nighly keine Einträge für ein MM mehr erstellen.
Erst bekam ich die schon erstellten Einträge zu sehen und wollte ein vorhandenes kopieren (was auch schon funktionierte). Danach bekam ich eine Seite mit der Fehlermeldung:

Fatal error: Uncaught exception RuntimeException with message Paste multiple is not supported at the moment, sorry. thrown in system/modules/metamodels/classes/src/MetaModels/DcGeneral/Events/MetaModel/PasteButton.php on line 52

Und nun lässt sich auch die BE-Liste mit den schon erstellten Einträgen eines MM nicht mehr anzeigen.

------
Quick & Dirty ...

ich habe in der Datei system/modules/metamodels/classes/src/MetaModels/DcGeneral/Events/MetaModel/PasteButton.php

mal innerhalb der

public static function handle(GetPasteButtonEvent $event)
{
/*
.....
*/
}

alles auskommentiert -> dann funktionert alles auch das Kopieren eines Eintrages ....
Ist sicher nicht die feine Art, mich würde trotzdem interessieren, was der eigentliche Bug war

**Comment by xantippe** [comment]
Mit aktuellem MM (core 2.0.0-alpha8) nicht (mehr) nachvollziehbar und sollte somit behoben sein
