### ISSUE TITLE
[TNG] Moving item to first Position does not work

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#719]
I think there is a bug in the new sorting. If move an Item to the first position it does not work. The second position works fine, but not the first.

**Comment by tim-bec** [comment]
Same here. Thought that these error got fixed long time ago... @discordier  ?

**Comment by discordier** [comment]
It was fixed... may be we reintroduced it by merging the new clipboard handling by @TristanLins?

**Comment by cboelter** [comment]
Works now fine for me :)

**Comment by tim-bec** [comment]
works for me 2
