### ISSUE TITLE
[TNG] Using the blue arrows for sorting throws an error

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#720]
If I want to use the blue arrows I get the message, that paste multiple is currently not supported. But if I want to go back, I get the message again because this is stored in the session. I think the best way is to remove the arrows  for the moment.

**Comment by xantippe** [comment]
@cboelter was möchtest Du sortieren? eigentlich funktioniert das inzwischen gut...

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cboelter could you please have a final look at this and tell if your issue has been resolved?
