### ISSUE TITLE
Deprecated notice: bei den Filtereinstellungen

### ISSUE THREAD

**Issue by markknochen1** [MetaModels/core#721]
Deprecated notice: The Symfony\Component\EventDispatcher\Event::getDispatcher method is deprecated since version 2.4 and will be removed in 3.0. The event dispatcher instance can be received in the listener call instead. in system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/Event.php on line 100

Funktion ist davon nicht eingeschränkt - sieht nur so eher mittel aus.

**Comment by tim-bec** [comment]
Das erscheint aber nur, wenn Du Fehlermeldungen aktiviert hast. 
Wir werden die Abhängigkeit aber ändern.

**Comment by xantippe** [comment]
aktueller Test mit MM core 2.0.0-alpha8

ich sehe nirgends eine solche Meldung!? 

@markknochen1 bitte mal prüfen und ggf. Ticket schließen
