### ISSUE TITLE
[TNG] Fatal error when editing MetaModel

### ISSUE THREAD

**Issue by wangaz** [MetaModels/core#722]
After updating to Contao 3.4.1 and the current TNG via Composer, I receive the following error message when editing a MetaModel:
```
Fatal error:  Call to undefined method ContaoCommunityAlliance\DcGeneral\Data\DefaultModel::isCurrent() in composer/vendor/contao-community-alliance/dc-general/contao/templates/dcbe_general_edit.html5 on line 10
```
Any idea?

**Comment by discordier** [comment]
Please update dc-general also to tng. Should be fixed in there.

**Comment by wangaz** [comment]
Hm, I just can find the [_develop_](https://github.com/contao-community-alliance/dc-general/tree/develop) branch and have installed the latest commit (24db36b4). Where's my mistake?

**Comment by tim-bec** [comment]
please try dcg dev-develop

**Comment by wangaz** [comment]
Thanks, it works!
