### ISSUE TITLE
[TNG] fehlende Bezeichnungen und Übersetzung bei Sortierung+Gruppierung

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#723]
in /language/nn/tl_metamodel_dca_sortgroup.php fehlen zwei Arrayeinträge mit den Bezeichnungen

m.E.
* $GLOBALS['TL_LANG']['tl_metamodel_dca_sortgroup']['rendersortattr']
* $GLOBALS['TL_LANG']['tl_metamodel_dca_sortgroup']['rendersort']

... irgendwie finde ich die ganze Datei bzw. die Übersetzung bei Transifex nicht?

**Comment by discordier** [comment]
Ja, die Ybersetzungen auf transifex sind auf dem master stand, nicht auf tng.

**Comment by xantippe** [comment]
o.k....

**Comment by xantippe** [comment]
im Master kann ich die Einträge auch nicht finden..
https://github.com/MetaModels/core/blob/master/contao/languages/en/tl_metamodel_dca_sortgroup.php

**Comment by xantippe** [comment]
getestet => o.k.

Übersetzungen fehlen noch...

![shot155](https://cloud.githubusercontent.com/assets/1045318/13527436/35fc3cae-e20f-11e5-99e9-e85d5b693fe5.jpg)
