### ISSUE TITLE
[FR] - Meta Title/Description

### ISSUE THREAD

**Issue by Munsio** [MetaModels/core#724]
Wenn man im Modul/CE die Felder Meta Title/Description auswählt werden diese nur gesetzt wenn die ausgewählten Attribute in der Rendersetting eingebunden und aktiviert wurden.

Wie im IRC mit @discordier und @MacKP besprochen wäre folgende Möglichkeit am schönsten:
- Die Felder die man im Modul/CE als Title/Description festlegt müssen weiterhin in der Rendersetting angelegt werden.
- Es gibt beim Toggle (Auge) noch einen zusätzlichen Zustand - "Nicht ausgeben aber als Variable verfügbar machen."
- Dieser 3 Zustand wird vorzugsweise mit einem Schwarzen Auge Symbol dargestellt.

**Comment by tim-bec** [comment]
Wieso zeigen wir in der Auswahl für Meta Title/Desc nicht einfach nur die Attribute an, die in dem Rendersetting eingebunden und aktiv sind?
Ich möchte eigentlich noch ein Auge / Option für das verfügbar machen vermeiden. cc @cogizz

**Comment by MacKP** [comment]
Geht ja nicht nur um die Meta-Angaben. Ist ja oft so, das man bestimmte Werte an anderer Stelle braucht und diese nicht anzeigen möchte. Aktuell muss man dafür dann immer im Template dafür sorgen, das es nicht ausgegeben wird. Damit das ganze nicht noch ein extra Symbol hat wäre da ein dritter Zuständ für das Auge schon praktisch finde ich. Das wird sonst viel zu voll... und in der Übersicht direkt sehen ob das so eingestellt ist fände ich schon ganz gut.

**Comment by tim-bec** [comment]
Aber Du hast doch nach wie vor alles (und jetzt auch noch referenzierte Werte) in den RAW Ausgaben. Wo kommt das denn so häufig bei dir vor? Ich bin kein Fan davon "Spezialfälle" in der GUI zu lösen.

**Comment by MacKP** [comment]
Hm? Wenn man in den Rendersttings ein Attribut nicht ausgeben lässt, dann hat man das aktuell doch gar nicht zur Verfügung? Oder bekommt man die Werte trotzdem in der RAW Ausgabe? Ich nutz sowas schon öfter. Ist jetzt nicht unbedingt ein Spezialfall bei mir. Sonst würde ich nicht positiv dafür stimmen ;-)

**Comment by cboelter** [comment]
Aber wenn man die Werte an einer anderen Stelle nutzen möchte, muss man doch sowieso ein eigenes Template bauen. Das lässt sich doch mit dem prerendered eh nicht machen?!

Bezüglich der Meta Title/Description wäre es da nicht sinnvoller man baut die Generierung der MetaTags so um, das diese ohne Rendersetting arbeiten und direkt die RAW-Values nutzt?
Das würde uns einen weiteren Status beim Toggle sparen oder ein weiteres Auge-Icon.

**Comment by MacKP** [comment]
@cboelter das stimmt schon, das man dann eh an einem Template rum schraubt. Aber dann würde man sich das andere Template sparen, was dann dafür da ist, das es eben nicht ausgegeben wird. Sind also theoretisch 50% Templates weniger ;-)
Vor allem finde ich ein Template für das nicht Anzeigen von etwas immer etwas strange...

**Comment by cboelter** [comment]
ok, das hängt natürlich stark von der arbeitsweise ab ... ich weiche da glaube ich recht stark vom normalen weg ab. Ich lasse mir im Haupttemplate immer alle Attribute in ein array rendern und positioniere die Attribute dann selbst im Template. Ohne schleife oder so.

**Comment by MacKP** [comment]
@cboelter ja, das kann man auch machen. MM ist allerdings mit den einzel Templates so angelegt, das man das gar nicht mehr so machen muss (meist wird sogar empfohlen, das eben nicht so zu machen um den Aufwand bei Änderungen möglichst gering zu halten).

**Comment by cboelter** [comment]
ja die einzeltemplates nutze ich auch, bei mir sieht das render template wie folgt aus:

```
<?php if ($this->items->getCount()): ?>
<div class="layout_reference_list simple_listing">
	<?php foreach ($this->items->parseAll($this->getFormat(), $this->view) as $arrItem): ?>
	<?php $arrHtml5 = $arrItem['html5']; $arrText = $arrItem['text']; $arrJumpTo = $this->view->getJumpTo(); ?>
	<div id="<?php echo $arrText['alias']; ?>" class="item <?php echo $arrItem['class']; ?>">
		<?php echo $arrHtml5['logo']; ?>
		<?php echo $arrHtml5['title']?>
		<?php echo $arrHtml5['description']; ?>
		<div class="linkButton"><a href="#"><span class="off">mehr</span><span class="on">zuklappen</span></a></div>

		<?php if($arrJumpTo['url']): ?>
		<!--<a class="more" href="<?php echo $arrJumpTo['url']; ?>#<?php echo $arrText['alias']; ?>"><?php echo $this->details; ?></a>-->
		<?php endif; ?>
	</div>
	<?php endforeach; ?>
</div>
<?php else: ?>
<p class="info"><?php echo $this->noItemsMsg; ?></p>
<?php endif; ?>
```

**Comment by xantippe** [comment]
siehe https://github.com/MetaModels/core/issues/402#issuecomment-168914578

d.h.
vielleicht wäre ein guter Kompromiss, wenn in raw immer dann angezeigt wird, wenn das Attribut in der Render-Liste als Attribut auftaucht - egal ob sichtbar oder nicht.

somit könnte man alle "drei Zustände"

    gar keine Ausgabe
    in raw
    in raw und HTML5 bzw. Text

recht leicht bewerkstelligen

**Comment by JLNNN** [comment]
Gibt es eine Möglichkeit, mehrere Felder zu kombinieren, damit man nicht nur ein Feld auswählen kann?
https://twitter.com/JLNSTCK/status/827078438083235840
![multiple-fields](https://pbs.twimg.com/media/C3pfY-WWQAAtAvA.jpg)

**Comment by richardhj** [comment]
@JLNNN Ein Attribut "combinedvalues" erstellen und dieses dann als Meta-Titel auswählen, sollte gehen.

**Comment by JLNNN** [comment]
@richardhj Funktioniert grundsätzlich, danke :) Allerdings muss das Feld sichtbar sein - bzgl. Topic. Habe es vorerst auch über eine Abfrage im Template geregelt.

**Comment by zonky2** [comment]
combined values und eigenes Template ist die Lösung
