### ISSUE TITLE
Integration: Kindtabelle

### ISSUE THREAD

**Issue by psren** [MetaModels/core#726]
Ich habe ein Problem mit Kindtabellen / Eingabemasken im Backend.
Und zwar habe ich 2 Eingabemasken als Kinder von "Kunden" integriert.

Neuerdings ist die PID aber bei den Datensätzen immer ```0```.
Muss ich da inzwischen irgendwas anders einstellen oder ist das ein bug?

![bildschirmfoto 2015-01-29 um 11 40 36](https://cloud.githubusercontent.com/assets/1016798/5956229/e25e4aae-a7ab-11e4-9fe6-0294fecba24a.png)

**Comment by tim-bec** [comment]
Wie sind denn deine Einstellungen? Bei mir klappt es so astrein: 
![image](https://cloud.githubusercontent.com/assets/1793396/5964558/7373dd94-a7f5-11e4-9d5f-13bbf6c848d2.png)

**Comment by psren** [comment]
Rendermode Parented gab es früher nicht glaube ich :-)
Hatte ich beim Update übersehen.
