### ISSUE TITLE
Legend hide does not work

### ISSUE THREAD

**Issue by psren** [MetaModels/core#729]
In my Backend form i defined legends which should be hidden by default.
However they aren't.

![bildschirmfoto 2015-01-29 um 15 12 51](https://cloud.githubusercontent.com/assets/1016798/5958877/881ede32-a7c9-11e4-8892-882d9193ad7c.png)

![bildschirmfoto 2015-01-29 um 15 12 59](https://cloud.githubusercontent.com/assets/1016798/5958881/9d6df4c6-a7c9-11e4-905c-6065b5ff30cd.png)

**Comment by cboelter** [comment]
Same here

**Comment by discordier** [comment]
https://github.com/contao-community-alliance/dc-general/issues/69
#550

**Comment by xantippe** [comment]
Issue ist noch aktuell: getestet in core 2.0.0-alpha8

**Comment by discordier** [comment]
@xantippe should be fixed in dcg, shouldn't it?

**Comment by xantippe** [comment]
gefixt in DCG beta 34
