### ISSUE TITLE
Sprache wird bei Weiterleitungsseite nicht angezeigt.

### ISSUE THREAD

**Issue by psren** [MetaModels/core#730]
Bei der Einstellung für die Weiterleitung im Rendersetting ist es somit ein ziemlicher Blindflug

![bildschirmfoto 2015-01-29 um 15 35 17](https://cloud.githubusercontent.com/assets/1016798/5959249/f8471b36-a7cc-11e4-8783-d4e656ee3c30.png)
![bildschirmfoto 2015-01-29 um 15 38 36](https://cloud.githubusercontent.com/assets/1016798/5959250/f84a8488-a7cc-11e4-9805-c6550c615f4f.png)

**Comment by tim-bec** [comment]
@discordier kann es sein das die ganzen probleme mit dem alten dcg tag / alter dcg in den nighlies zusammenhängt? auf meinen installationen kann ich das bisher nämlich nicht nachvollziehen...

**Comment by discordier** [comment]
Oeh, also das ist mir noch nichtmal im alten unter gekommen... O.o

Was steht denn im HTML Quelltext des obigen MCW?

**Comment by psren** [comment]
Zur Info hier meine Versionen:
https://gist.github.com/psren/7e1c35e9e0df77acd740

Dieses HTML kommt für die Sprachenspalte ganz links im Orignalquelltext an:
```html
<td valign="center" class="hidelabel mcwUpdateFields">
   <h3>
      <label>Sprache</label>
   </h3>
</td>
```

**Comment by discordier** [comment]
Ich meine die Zeilen darunter, welche mit JS erzeugt werden.
Musst du mit den developer-tools inspecten.

**Comment by psren** [comment]
Habe gerade ein wegen eines anderen Tickets dcg manuell auf dev gesetzt (davor wurde mir als abhängigkeit beta21 installiert).

Jetzt klappt es.
