### ISSUE TITLE
Neu angelegte MetaModels können nicht mehr editiert werden

### ISSUE THREAD

**Issue by ae69** [MetaModels/core#732]
Fehlermeldung:
   <b>Fatal error</b>:  Call to undefined method ContaoCommunityAlliance\DcGeneral\Data\DefaultModel::isCurrent() in <b>C:\xampp\htdocs\system\modules\dc-general\templates\dcbe_general_edit.html5</b> on line <b>13</b><br />

Vor einiger Zeit angelegte Metamodels können jedoch editiert werden

![unbenannt](https://cloud.githubusercontent.com/assets/8656733/5962662/acdd1376-a7e5-11e4-9592-226037917919.JPG)

Nightly vom 29-01-15 18:04
Contao 3.4.2

**Comment by tim-bec** [comment]
Kannst Du den kompletten Stack-Trace / Fehlermeldung ergänzen?

**Comment by ae69** [comment]
Sorry, aber da kommen sonst keine Fehlermeldungen, auch nicht im error-logfile

**Comment by discordier** [comment]
Sollte im tng vom dcg eigentlich tun.

**Comment by design23** [comment]
Gleiches Problem hier.
Contao 3.2.17
Nightly vom 30-01-15 14:02


Fatal error:  Call to undefined method ContaoCommunityAlliance\DcGeneral\Data\DefaultModel::isCurrent() in /Applications/MAMP/htdocs/abc/system/modules/dc-general/templates/dcbe_general_edit.html5 on line 13

**Comment by tim-bec** [comment]
@design23 kannst Du mit Composer anstatt den nightlys arbeiten?

**Comment by design23** [comment]
@tim-bec Nachdem ich bisher 4x absolut erfolglos versucht habe, mit Composer zu arbeiten, hält sich meine Begeisterung dafür ziemlich in Grenzen. Holt der sich denn andere Files bei der Installation?

**Comment by tim-bec** [comment]
Ja, das tut er, wenn man ihm das sagt. Der neue DCG ist aktuell nicht in den nightlies drin.
Wer mit MetaModels arbeitet, sollte auch auf Composer setzen. Ich kann die Probleme hier auch verstehen - wir betreiben über 20 Installationen damit weitestgehend problemlos.

Zu den Paketen: Ich weiß, das da auch viel Chaos bei uns drin ist, aber das lässt sich aktuell leider nicht vermeiden...

**Comment by design23** [comment]
Ah, okay. Gibt es denn irgendwo eine idiotensichere Anleitung für den Composer?

**Comment by tim-bec** [comment]
Schau mit dem https://github.com/contao/check ob dein System Composer-Ready ist und installiere anschließend Composer über die Erweiterungsverwaltung ( composer client) der Migrationsassistent führt dich durch die Installation. Danach sollte alles erledigt sein.

**Comment by wangaz** [comment]
siehe auch #722

**Comment by design23** [comment]
Okay, ich versuche das jetzt mal. Composer läuft schonmal. Aber wie läuft nun eine korrekte Installation von MM? Welche Pakete in welcher Reihenfolge?

**Comment by design23** [comment]
Absolut nicht machbar... Was soll mir denn diese Meldung überhaupt sagen? Habe dazu nichts gefunden:

Package contao/php-diff is abandoned, you should avoid using it. Use phpspec/php-diff instead.

**Comment by tim-bec** [comment]
Metamodels/core + metamodels/bundle_all

Ignorier die abonded Meldung einfach vorerst.
Am 31.01.2015 13:08 schrieb "design23" <notifications@github.com>:

**Comment by design23** [comment]
Hab ich gemacht, aber weder im BE noch im Ordner system/modules taucht MM auf...

Loading composer repositories with package information
Updating dependencies
  - Installing metamodels/attribute_url (dev-tng ffd05a9)
    Cloning ffd05a9698f75dc7ccc4a88d040e0de99d7eaf09

  - created 1 links
  - Installing metamodels/attribute_numeric (dev-tng bec96de)
    Cloning bec96deb5ecea547f85bdde8501c0fd6b43cf365

  - created 1 links
  - Installing metamodels/attribute_timestamp (dev-tng 6f13f23)
    Cloning 6f13f23b55a1fc08b82690d6e67377d47fc26acd

  - created 1 links
  - Installing metamodels/attribute_langcode (dev-tng 1334587)
    Cloning 13345874c0518851825bec4543f330d7f835f100

  - created 1 links
  - Installing metamodels/attribute_decimal (dev-tng 439c582)
    Cloning 439c582ae5d4dc7a67d352ee77476e40378c6ae6

  - created 1 links
  - Installing metamodels/attribute_country (dev-tng b7bb7fc)
    Cloning b7bb7fc60a6fdb12b04ed3c56c7b9834cee867a5

  - created 1 links
  - Installing metamodels/attribute_combinedvalues (dev-tng c1aac35)
    Cloning c1aac351b89c38aad37199f358ed11bf7302fd75

  - created 1 links
  - Installing metamodels/attribute_checkbox (dev-tng e8cd5c6)
    Cloning e8cd5c6e7421ef6f9c288d14863a49ff7b8ccc25

  - created 1 links
  - Installing metamodels/attribute_text (dev-tng 3023cd9)
    Cloning 3023cd9f502ffa55f785af740bb5a82068b6a506

  - created 1 links
  - Installing metamodels/attribute_select (dev-tng 477d53d)
    Cloning 477d53d49e35ca1aac9ac9cc8931ebe3b0b5b0c9

  - created 1 links
  - Installing metamodels/attribute_tags (dev-tng c2bdce3)
    Cloning c2bdce3a485d9ab0014e32cfdc3f268c609d949e

  - created 1 links
  - Installing metamodels/attribute_tabletext (dev-tng 9fe3507)
    Cloning 9fe35079f5255cc3c0a3fc561c9e97aef9fba2fc

  - created 1 links
  - Installing metamodels/attribute_longtext (dev-tng c9e7d26)
    Cloning c9e7d26ed34d57b5e626e96cbb6076565f191f5d

  - created 1 links
  - Installing metamodels/attribute_file (dev-tng 3ccf3a5)
    Cloning 3ccf3a53d15b648cb269dfa7050870671b805c19

  - created 1 links
  - Installing metamodels/attribute_alias (dev-tng 8ceb316)
    Cloning 8ceb31698a499d132b3248b26026ec4c240e5979

  - created 1 links
  - Installing metamodels/attribute_translatedcombinedvalues (dev-tng 9a8544f)
    Cloning 9a8544f97975d32eb31a96d831bea220c10494ca

  - created 1 links
  - Installing metamodels/attribute_translatedcheckbox (dev-tng 3813e42)
    Cloning 3813e42444a156224c23feab536d470e1d704a32

  - created 1 links
  - Installing metamodels/attribute_translatedtext (dev-tng f2ad30f)
    Cloning f2ad30f1dea402221a685ae97d084f35a8cfd90a

  - created 1 links
  - Installing metamodels/attribute_translatedtags (dev-tng 5ec0eef)
    Cloning 5ec0eef7112fd67e6ee7451bb536a78ddf73ef02

  - created 1 links
  - Installing metamodels/attribute_translatedtabletext (dev-tng e136f28)
    Cloning e136f281ea77db74416c81fce605ab931342d7c8

  - created 1 links
  - Installing metamodels/attribute_translatedselect (dev-tng 46e336f)
    Cloning 46e336fbe02832601574205c914f013fc373fced

  - created 1 links
  - Installing metamodels/attribute_translatedlongtext (dev-tng fb21fb0)
    Cloning fb21fb0ad0b59d89ade26cc1191e3559493395b2

  - created 1 links
  - Installing metamodels/attribute_translatedfile (dev-tng ec28cc6)
    Cloning ec28cc6aa56477e9652be3e3e723602238f0e4da

  - created 1 links
  - Installing metamodels/attribute_translatedalias (dev-tng 3f68cd8)
    Cloning 3f68cd8d7be8adc601f6a56d2ada9fbf87c8de18

  - created 1 links
  - Installing metamodels/filter_text (dev-tng 6df9de1)
    Cloning 6df9de1f2e7429455a7c270bcc511fedaae8fc04

  - created 1 links
  - Installing metamodels/filter_tags (dev-tng b97cb28)
    Cloning b97cb28a29aedae4e9bfc9c9730482838e2ac9ff

  - created 1 links
  - Installing metamodels/filter_select (dev-tng 5978066)
    Cloning 5978066d167c991c6bd0dd26f28dbcf9a5e6e792

  - created 1 links
  - Installing metamodels/filter_range (dev-tng bf0103b)
    Cloning bf0103be773ba78413e2fa1934672c7f1a96666b

  - created 1 links
  - Installing metamodels/filter_fromto (dev-tng db880c2)
    Cloning db880c2208fc6a5993e4af16ac265e60b846d785

  - created 1 links
  - Installing metamodels/filter_checkbox (dev-tng 230a0e0)
    Cloning 230a0e09bef18429a090d7c2b38ba812fcfa29e0

  - created 1 links
Package contao/php-diff is abandoned, you should avoid using it. Use phpspec/php-diff instead.
Writing lock file
Generating autoload files

**Comment by design23** [comment]
![bildschirmfoto 2015-01-31 um 13 33 29](https://cloud.githubusercontent.com/assets/6112308/5988038/cca27552-a94d-11e4-94e7-f2d1bd1485fa.png)
![bildschirmfoto 2015-01-31 um 13 33 35](https://cloud.githubusercontent.com/assets/6112308/5988040/cef8d846-a94d-11e4-893a-eec88993a37e.png)

**Comment by cyberlussi** [comment]
contao/core 	3.2.18
contao-community-alliance/dc-general 	dev-develop (fdd43c2a)
metamodels/core 	dev-tng (5eaeb7d8)

Metamodels -> Edit:
Interessanterweise erscheint das bei mir in einem SELECT:

```
<select name="version" class="tl_select">
	<option value="3" <br="">

( ! ) Fatal error: Call to undefined method ContaoCommunityAlliance\DcGeneral\Data\DefaultModel::isCurrent() in /Users/htdocs/system/modules/dc-general/templates/dcbe_general_edit.html5 on line 13
Call Stack
#TimeMemoryFunctionLocation
10.0007317776{main}(  )../main.php:0
20.197010351848Main-&gt;run(  )../main.php:288
30.198310550216Contao\Backend-&gt;getBackendModule(  )../main.php:137
40.388714686120MetaModels\BackendIntegration\Module-&gt;generate(  )../Backend.php:262
50.388914692880ContaoCommunityAlliance\DcGeneral\Controller\DefaultController-&gt;handle(  )../Module.php:77
60.389414711648Symfony\Component\EventDispatcher\EventDispatcher-&gt;dispatch(  )../DefaultController.php:115
70.389414712480Symfony\Component\EventDispatcher\EventDispatcher-&gt;doDispatch(  )../EventDispatcher.php:53
80.390114748800call_user_func:{/Users/htdocs/composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164}
(  )../EventDispatcher.php:164
90.390114749200ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView-&gt;handleAction(  )../EventDispatcher.php:164
100.390114750216call_user_func_array:{/Users/htdocs/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php:138}
(  )../BaseView.php:138
110.390114750600ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView-&gt;edit(  )../BaseView.php:138
120.391914876960ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView-&gt;createEditMask(  )../BaseView.php:750
130.393415066848ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask-&gt;execute(  )../BaseView.php:775
140.414516681376Contao\BackendTemplate-&gt;parse(  )../EditMask.php:714
150.414516681376Contao\Template-&gt;parse(  )../BackendTemplate.php:28
160.415116739120include( '/Users/htdocs/system/modules/dc-general/templates/dcbe_general_edit.html5' )../Template.php:272

</option></select>
```

**Comment by stefanheimes** [comment]
Ich kennen den Fehler auch. Es hat hier etwas mit der Versionierung vom DCG zu tun. Dabei wird das falsche Model übergeben. Es gibt ein spezielles, was die Funktion hat, aber irgendwie wird hierbei dann das Default geladen. Die schnellste Lösung hierfür ist im Template vom DCG etwas zu ändern. 

https://github.com/contao-community-alliance/dc-general/blob/develop/contao/templates/dcbe_general_edit.html5#L5 
Das Template ist unter ```TL_ROOT\system\modules\dc-general\templates\dcbe_general_edit.html5``` zu finden.

Hier einfach ein ```<?php if(false && $this->versions): ?> ``` setzten und damit ist die Versionierung erstmal im Template aus. Das Template kann dann auch in das Template-Verzeichnis hinterlegt werden. Damit sollte das System dann auch erstmal update sicher sein, bis wir das Probleme behoben haben.

**Comment by stefanheimes** [comment]
Wir haben die Versionierung von MetaModels deaktiviert. Siehe hierzu den Commit b3f0f430baaf51cf7bd550bc93612c0c31ae3bb9 Das sollte erst einmal das Problem beheben.

**Comment by cyberlussi** [comment]
Works for me +1

**Comment by ae69** [comment]
@tim-bec 

Ich bin begeistert !!!

Habe mir die Anregung zur Verwendung des Composers zu Herzen genommen und es scheint, als würde alles wieder funktionieren :smiley:
Herzlichen Dank und Grüße aus Wien!

Contao 3.4.2

**Comment by wangaz** [comment]
simple and effective solution +1, thanks

**Comment by design23** [comment]
Nachdem ich den Composer und alles was dazugehört mit dem Vorschlaghammer aus dem System geprügelt und ihn anschließend neu installiert habe, scheint nun alles zu funktionieren. Keine Ahnung was initial schiefgelaufen ist...
Trotzdem danke für den Tip und den Commit.
