### ISSUE TITLE
Attribute Text-Tabelle verschwunden

### ISSUE THREAD

**Issue by design23** [MetaModels/core#734]
Das Attribut Text-Tabelle taucht im Dropdown gar nicht mehr auf. Installiert ist die Erweiterung aber.

Contao 3.2.17
Nightly vom 30-01-15 14:02

**Comment by cboelter** [comment]
Kann ich bestätigen, gehört aber eigentlich in das entsprechende Repository.

**Comment by tim-bec** [comment]
fixed with https://github.com/MetaModels/attribute_tabletext/commit/212e4c32d8efc252eb7b605c684192446a5f43f8
