### ISSUE TITLE
Language select in Backend

### ISSUE THREAD

**Issue by EDsolution** [MetaModels/core#735]
Hi.
There is a CSS or HTML structure bug in IE browser. When you go to "item input mask" and if you have multilanguage in IE you can't switch language (select doesn't work) and also the select is on the left side insted on the right as in firefox and chrome.

**Comment by stefanheimes** [comment]
Hi, 

this bug should be solved with this commit https://github.com/contao-community-alliance/dc-general/commit/9b9bfe45e79d295ccf74362bb7416d8d1a2a5a33 

Can you pleas test it again.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@EDsolution could you please have a final look at this and tell if your issue has been resolved?

**Comment by Zeromax** [comment]
@stefanheimes check ;) Works on Win 8.1 IE 11
