### ISSUE TITLE
Manuelles Sortieren führt zu Datenverlust bei translatedfile

### ISSUE THREAD

**Issue by design23** [MetaModels/core#740]
Contao 3.2.18
metamodels/core -> dev-tng (b257c40b) → 2.0.x-dev
metamodels/bundle_all -> dev-master (f5892747)

Sobald im BE per Drag & Drop ein MM verschoben wird (Sortierung der Reihenfolge), verliert das MM seine eingetragenen Werte im Attribut translatedfile.

**Comment by discordier** [comment]
@tim-bec Kannst du das verifizieren/nachbauen?

**Comment by poutvie** [comment]
Contao 3.2.16
DC-General (d36a7925)
metamodels/core dev-tng (6a793d02)

Könnte zusammen hängen: Habe eine MM Liste im BE mit manueller Sortierung. Nach Sortierung und Seitenrefresh hat der verschobene Eintrag den Wert des Attributs mit id=1. 

1.) Sortierung ändern
2.) Seite refreshen
3.) verschobenes Element erhält Wert des Elements mit id=1
übersetzte Werte und die, die nicht in der Liste stehen bleiben erhalten.

(Screenshot zeigt nur 2 Einträge, ist aber auch bei 3 Einträgen so)
![vor-sortierung](https://cloud.githubusercontent.com/assets/8960545/6123703/30feb3b6-b106-11e4-9cde-5cfb6fb0c7d2.jpg)
![nach-sortierung](https://cloud.githubusercontent.com/assets/8960545/6123705/3389cf08-b106-11e4-96dc-c0b857e90599.jpg)

**Comment by design23** [comment]
Nachtrag: 
Habe eben festgestellt, dass der Effekt zusätzlich auftritt, wenn das MM manuell sortierbar ist und man einfach nur einen neuen Eintrag erstellt. Dieser wird an die erste Stelle gesetzt und sofort verlieren alle bereits existierenden Einträge ihre gespeicherten Werte bei den Mehrfachauswahlen (translatedtags).

**Comment by design23** [comment]
Nachtrag zum Nachtrag:
Der Effekt beschränkt sich interessanterweise auf die Fallback-Sprache. Bei den zusätzlichen Sprachversionen der Einträge sind die gespeicherten Werte noch vorhanden.

**Comment by tim-bec** [comment]
@design23 welche version des dcg nutzt du?

**Comment by design23** [comment]
@tim-bec Gute Frage. Wo genau steht denn die Info? Habe alles über Composer installiert. Beim dcg steht nur ">=3.2,<3.5". MM core ist dev-tng (d374dba4)

**Comment by tim-bec** [comment]
schau mal bei 	contao-community-alliance/dc-general und stell den dort manuell auf dev-develop oder 2.0.x-dev und teste das problem bitte noch mal damit.

**Comment by design23** [comment]
Ah, vorhin glatt übersehen. contao-community-alliance/dc-general ist aktuell auf dev-develop (a7b84c37)

**Comment by tim-bec** [comment]
okay, dann bitte noch mal folgendes schauen: passiert das nur wenn du elemente auf die erste position oder von der ersten position umsortierst?

**Comment by design23** [comment]
Nein, passiert auch auf anderen Positionen.

**Comment by discordier** [comment]
@tim-bec bitte mal nachbauen... irgendwie kommt mir das arg spanisch vor.
Betrifft das wirklich nur file attribute oder auch andere?
Wenn 1. dann muss man im file attribut suchen, wenn 2. dann eher dc-g.

**Comment by tim-bec** [comment]
@discordier ich will den exporter ;-) - versuche das mal nachzustellen. 
@design23  kannst du deine konfiguration noch etwas näher beleuchten?

**Comment by design23** [comment]
@tim-bec Meine Konfiguration ist mittlerweile recht umfangreich, also was genau möchtest du wissen?

- Ausgangspunkt ist ein MM "Produkte", Übersetzungen vorhanden, keine Varianten
- über 30 Attribute, davon 3x translatedfile mit aktivierter Option für Mehrfachauswahl

**Comment by design23** [comment]
So, jetzt hab ich spaßeshalber mal eine komplett neue Installation (3.2.19) aufgesetzt, MM via Composer installiert (core: dev-tng (8f3a486f), bundle-all: dev-master (f5892747)) und ein MM mit folgenden 3 Attributen erstellt: 
- Text (text)
- Datei (file, Mehrfachauswahl)
- Übersetzte Datei (translatedfile, Mehrfachauswahl)

Jetzt verweigert das translatedfile in der Eingabemaske direkt den Dienst mit folgender Meldung:
![bildschirmfoto 2015-03-24 um 14 57 28](https://cloud.githubusercontent.com/assets/6112308/6803175/27e27be0-d236-11e4-8301-8a90ca0e6059.png)

**Comment by discordier** [comment]
Sollte inzwischen behoben sein, siehe hierzu auch #784, MetaModels/attribute_file#45.

**Comment by design23** [comment]
Wurde das innerhalb der letzten 5 Stunden gefixed?

**Comment by poutvie** [comment]
Verschieben funktioniert bei mir jetzt. Danke!

**Comment by design23** [comment]
Nach Update tut sich beim Auswählen von Dateien gar nichts mehr...
![bildschirmfoto 2015-03-27 um 13 57 06](https://cloud.githubusercontent.com/assets/6112308/6868140/33d8e90c-d489-11e4-96a9-234fa89c3ab7.png)

Mehr passiert nicht.

metamodels/core: dev-tng (435456af) → 2.0.x-dev
metamodels/bundle_all: dev-master (f5892747)
contao-community-alliance/dc-general: dev-develop (02c33c05)

**Comment by discordier** [comment]
Schau dir bitte mit firebug mal den xhr request an und was da als response kommt.
Da sollte eine Fehlermeldung drin stehen, diese brauchen wir.

**Comment by design23** [comment]
Meinst Du das hier? Ich sehe da keine Fehlermeldung.
![bildschirmfoto 2015-04-07 um 18 46 30](https://cloud.githubusercontent.com/assets/6112308/7028505/7fb8c97a-dd56-11e4-8c2b-f9726b501b65.png)

**Comment by design23** [comment]
Mal in FF mit Firebug geprüft. Als Antwort kommt das:

<br><strong>Fatal error</strong>: Uncaught exception <strong>LogicException</strong> with message <strong>Property files (translatedfile) did not accept the value (The values differ. Encountered type NULL expected array (Found NULL, expected array (
  0 => '+>äÒ,ä¡Î|­ï¥o',
))).</strong> thrown in <strong>composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Model.php</strong> on line <strong>178</strong>
<pre style="margin:11px 0 0">
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(74): MetaModels\DcGeneral\Data\Model->setProperty('files', Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(231): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->getWidget('files', 'mm_test::5', 'files/Contao_3....')
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(250): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadTree()
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(249): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadFiletree(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(466): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(128): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(84): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#7 system/modules/core/classes/Backend.php(249): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('mm_test', Array)
#8 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_te...')
#9 contao/main.php(288): Main->run()
#10 {main}
</pre>

**Comment by discordier** [comment]
Which contao version are you on?

**Comment by design23** [comment]
3.2.19

**Comment by design23** [comment]
Changed filenames now, because the original files had some "-" and "." 
Full path now: files/testfiles/testfile_4.pdf

**Comment by design23** [comment]
Tested with 3.2.20, error still exists.

**Comment by design23** [comment]
Made a new installation (3.5.2) and installed everything via composer -> seems to work now.

**Comment by discordier** [comment]
O.o
We did not change anything in the relevant sections...

**Comment by design23** [comment]
Oh, my bad... tried the normal file attribute, not the translated file... 
I'll try the translated version asap and give feedback again.

**Comment by xantippe** [comment]
@design23: we can close the ticket?!?

**Comment by design23** [comment]
Sorry, had no time for testing. Just close this ticket. If the issue occurs again, I'll come back ;)

**Comment by xantippe** [comment]
@discordier: na dann zu das Ding ;-)

**Comment by design23** [comment]
Finally found the time for detailed tests... and... it works like charm! Thank you very much!
