### ISSUE TITLE
[TNG] error_unknown_attribute / error_unknown_id / error_unknown_column bei gelöschten Attributen

### ISSUE THREAD

**Issue by cyberlussi** [MetaModels/core#742]
Hi,

wenn ich ein Attribut lösche, dann bleibt in den Rendereinstellungen und Eingabemasken ein "error" stehen (Filter habe ich nicht geprüft). Sollten bei einem Löschen von Attributen nicht eher alle Abhängigkeiten (Rendereinstellung, Filter, etc) gelöscht werden?

![2015-02-04_19_59_59_-_metamodels_-_contao_open_source_cms_3_2](https://cloud.githubusercontent.com/assets/4976687/6047213/92922660-aca8-11e4-9523-81b4c2e880f9.png)

![2015-02-04_20_01_44_-_metamodels_-_contao_open_source_cms_3_2](https://cloud.githubusercontent.com/assets/4976687/6047228/b012458a-aca8-11e4-91af-6c1fd759b2bc.png)

**Comment by discordier** [comment]
Sollten schon, ist aber noch nicht implementiert.

**Comment by xantippe** [comment]
noch aktuell => Test: Contao 3.5.6 mit MM 2.0.0-alpha8

**Comment by zonky2** [comment]
mit PR https://github.com/MetaModels/core/pull/1017 gefixt

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cyberlussi could you please have a final look at this and tell if your issue has been resolved?
