### ISSUE TITLE
Pagination on MMItem - List not working

### ISSUE THREAD

**Issue by MrTool** [MetaModels/core#744]
MM: dev-tng (ab17f59)

Cause of the last commit where the Pagination was moved to an explicit helper file the pagination is not working anymore

**Comment by johannes-bittner** [comment]
+1

**Comment by design23** [comment]
Agree

**Comment by Olli** [comment]
+1

**Comment by fabian-ibr** [comment]
+1

**Comment by Olli** [comment]
This issue should get closed because in tng it's fixed.

**Comment by tim-bec** [comment]
thx for the hin.

**Comment by design23** [comment]
Still got the problem.

**Comment by discordier** [comment]
@design23 Can you shed some light on your configuration and which combination of settings is producing what (undesired) result.

**Comment by design23** [comment]
A few days ago I saw this: https://github.com/MetaModels/core/commit/ad5f102ed8fd194dcf26812f79bc808cdd943240

So I added the new lines to that file and now it works. Before that I just had updated MM via composer, so I have no idea why that fix wasn't updated too.

**Comment by discordier** [comment]
Can you check your `installed.json` what has is currently installled?

**Comment by design23** [comment]
What exactly do you need? That file has 4770 lines ^^

**Comment by design23** [comment]
After update via composer the pagination seems to work fine.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@MrTool could you please have a final look at this and tell if your issue has been resolved?
