### ISSUE TITLE
BE Eingabe - Alle hinzufügen - attribute werden nicht angezeigt

### ISSUE THREAD

**Issue by MrTool** [MetaModels/core#746]
Contao: 3.3.7
MM: dev-tng (6a793d02)
DCG: 2.0.0-beta22

Wenn man eine neue Eingabemaske definiert und man über [Alle hinzufügen] die Attribute anlegen lässt und danach per Auge aktiviert wird beim erstellen eines neuem Items kein Attribut angezeigt.

Wenn Ich dann jedoch ein Attribut editiere und aus [Speichern] klicke sind plötzlich alle Attribute bei der Item eingabe vorhanden.

Getestet mit Multilang Attributen

**Comment by MrTool** [comment]
Das gleiche passiert auch wenn Ich eine Legende anlege und in der BE-Ansicht dann mit dem Auge aktiviere - man muss dann immer wieder ein bereits aktives Attribut bearbeiten und speichern

**Comment by discordier** [comment]
Stimmt,  der Cache wird hierbei noch nicht geleert.

**Comment by xantippe** [comment]
noch aktuell?

**Comment by MrTool** [comment]
Ich benutze schon seit fast einem Jahr kein Contao mehr und daher auch kein MM ich kann es leider nicht sagen. Bitte mal selbst ausprobieren und closen.

**Comment by xantippe** [comment]
o.k. getestet - zumindest versucht nach obigen Angaben: ist anscheinend nicht mehr so, d.h. die Attribute werden gleich angezeigt...

kann m.E. geschlossen werden
