### ISSUE TITLE
FR: Bei Einzelbild Bildgröße und Cropmode in Eingabemaske auswählen

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#747]
Wie im IRC kurz angerissen, wäre es gut bei Datei-Attributen ohne Multi-Select je Eintrag die Bildgröße und den Crop-Mode bestimmen zu können.
Bei Implementierung sollte die Änderungen aus 3.4 berücksichtigt werden.

**Comment by MacKP** [comment]
Warum nicht auch bei Mehrfachauswahl? Ist da ja im Grunde genau wie bei Galerien von Contao? (Es sei denn man will Dateien.. aber das ist ja bei Einzelauswahl auch genau so).

**Comment by zonky2** [comment]
Hallo @tim-bec ,

ich verstehe die Sache nicht... ggf. auch schon nicht mehr aktuell - aktuell kann doch der crop-Mode ausgewählt werden und beim nächsten Update kommt die Unterstützung für picture mit hinzu...

close?

**Comment by tim-bec** [comment]
@zonky2 yes das kann zu.
