### ISSUE TITLE
Fatal error: InvalidArgumentException bei cleaner Installation (TNG, nightly)

### ISSUE THREAD

**Issue by sebuck** [MetaModels/core#749]
Hallo zusammen,

ich habe eben mal eine frische Contao (3.2.18) mit der neusten Nightly aufgesetzt und kriege leider schon beim Anlegen des ersten Attributes einen Fehler:

```
Fatal error: Uncaught exception InvalidArgumentException with message 
Could not retrieve MetaModel thrown in [...]\system\modules\metamodels\classes\src\MetaModels\DcGeneral\Events\Table\Attribute\Subscriber.php on line 474
```

Ich konnte problemlos den Typ "Text" auswählen und dann die notwendigen Felder füllen --> Speichern & Schließen wirft obigen Fehler aus. Nach Neuladen ist er weg, das Feld wurde angelegt. "Nur" Speichern, wirft den selben Fehler aus.

Ich gucke mal, ob das ganze weitere Fehler hervorruft an anderen Stellen, so ein Attribut ist ja schon recht wichtig.

**Comment by sebuck** [comment]
#### Weitere Erkenntnis:

Anscheinend tritt dieser Fehler nur beim ersten Attribut auf, das ich hinzufüge. Beim zweiten, dritten, xten... klappt es ohne Fehlermeldung.

**Comment by sebuck** [comment]
#### Noch ein Fehler

Vermutlich steht dieser im Zusammenhang, daher im selben Thema:
Die anderen Einstellungen für dieses MetaModel klappen alle. Sobald ich dann über die erzeugte BE-Eingabemaske ein neuen Datensatz anlegen möchte, kommt diese Fehlermeldung:

```
Fatal error: Uncaught exception Exception with message Query error: Unknown column
'feld_vorname' in 'field list' (UPDATE mm_test SET feld_vorname='asd' WHERE id=1) thrown
in [...]\system\modules\core\library\Contao\Database\Statement.php on line 279
```

Habe dann versucht, von den zwei angelegten Attributen, nur das andere "feld_nachname" in der Eingabemaske zu haben, um zu gucken, ob es auch diesen Fehler ausgibt. Aber es bleibt bei dem gleichen Fehler mit dem Feld "feld_vorname", obwohl es nicht in der Eingabemaske angezeigt wird.

Wenn ich dann über die URL wieder ins Backend und dann zum MetaModel navigiere, ist ein neuer Datensatz angelegt, aber ohne Inhalt. Bearbeiten und speichern bringt den gleichen Fehler wie oben. Löschen funktioniert.

Ich hoffe, das hilft irgendwie den Fehler zu finden. Werde erstmal nicht weiter machen an dieser Stelle mit der Einrichtung meiner Test-Seite. Kann ja testen, wenn ihr was gefunden habt oder nochmal andere Dinge ausprobieren.

Würde mich freuen, wenn ihr das hinkriegt und ich helfen konnte.
Danke für eure investierte Zeit für MetaModels! Tolle Sache!

**Comment by uagga** [comment]
dito genau gleiches Problem...

**Comment by tim-bec** [comment]
Kannst Du uns einen vollständigen Stack-Trace dazu liefern (das was noch unter der Fehlermeldung kommt)?

**Comment by sebuck** [comment]
Ich leider nicht, habe diese Version wieder gelöscht und seither kein MM mehr genutzt. Wird aber in nächster Zeit wieder kommen und wenn der Fehler noch auftritt würde ich hier posten.
