### ISSUE TITLE
Speichern mehrsprachigen Items klappt nicht

### ISSUE THREAD

**Issue by psren** [MetaModels/core#751]
Ich habe ein Mehrsprachiges MetaModel
Aktuell nur die Sprache "Deutsch" (also das richtige Deutsch) angelegt.
(Später werden es mehrere werden)

Hier habe ich ein Attribut welches per Picker eine Seite wählbar macht.

Das Auswählen funktioniert.
![bildschirmfoto 2015-02-10 um 10 25 19](https://cloud.githubusercontent.com/assets/1016798/6124693/e4b5b68a-b10f-11e4-853b-a589c8557c85.png)

Wenn ich jetzt aber "Speichern" drücke ist das Feld wieder leer.
![bildschirmfoto 2015-02-10 um 10 25 32](https://cloud.githubusercontent.com/assets/1016798/6124699/f1aa9478-b10f-11e4-8825-1995a43398f2.png)

In die Datenbank wurde an der Stelle ```0``` geschrieben statt der ID des gewählten Items.

Woran kann das liegen?

**Comment by psren** [comment]
Eventuell Bezug zu #739

**Comment by xantippe** [comment]
@psren kannst Du bitte genauer beschreiben, **welches Attribut mit welchen Einstellungen** Du verwendet hast - ich kann die Sache so nicht nachstellen

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@psren could you please have a final look at this and tell if your issue has been resolved?
