### ISSUE TITLE
Tabellenspalte für Bezeichnung/Name für Mehrfachauswahl ist kombinierter Eintrag => nur ein Datensatz für Auswahl

### ISSUE THREAD

**Issue by poutvie** [MetaModels/core#752]
Contao 3.2.16
metamodels/core 	dev-tng (6a793d02)

Wenn ich in einer Mehrfachauswahl einen kombinierten Eintrag für "Tabellenspalte für Bezeichnung/Name" verwende, wird nur ein Datensatz zur Auswahl gegeben. Ändere ich die Bezeichnung/Name auf ein numerisches Feld oder Textfeld => normale Funktion.

**Comment by xantippe** [comment]
@poutvie: sorry - auch nach mehrmaligem Lesen komme ich nicht recht dahinter was das Problem ist bzw. man das nachvollziehen kann 

ggf. helfen auch ein paar Screenshots, um mich vom "Schlauch zu holen" ;-)

**Comment by poutvie** [comment]
Kann ich verstehen. Ich weiß auch nicht mehr genau worum es da ging. Ich glaube, ich hatte in einer Mehrfachauswahl als Bezeichner einen Alias des anderen MM verwendet und dann wurde nur ein Datensatz zur Auswahl angezeigt, statt aller möglicher.
Aber es scheint sich mittlerweile erledigt zu haben. Ich kann es nicht mehr nachvollziehen. Es funktioniert mittlerweile wie gewünscht.
