### ISSUE TITLE
Filter Mehrfachauswahl

### ISSUE THREAD

**Issue by rittler** [MetaModels/core#754]
Bei der Verwendung eines Mehrfachauswahl erhalte ich eine Fehlermeldung. MM Version ist aktuell.

```
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''6','7','8','9','10','11','15' GROUP BY item_id' at line 4 (SELECT value_id, COUNT(value_id) as mm_count FROM tl_metamodel_tag_relation WHERE att_id='36' AND value_id IN '6','7','8','9','10','11','15' GROUP BY item_id) thrown in system/modules/core/library/Contao/Database/Statement.php on line 283
```

Fehlerfrei mit Klammern:
```
... AND value_id IN ('6','7','8','9','10','11','15') GROUP ...
```

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@rittler could you please have a final look at this and tell if your issue has been resolved?

**Comment by valentin-** [comment]
Thanks the problem does not occur anymore
