### ISSUE TITLE
langcode SQL field to short

### ISSUE THREAD

**Issue by Zeromax** [MetaModels/core#755]
There is a bug in some language attributes:

![lancode](https://cloud.githubusercontent.com/assets/1867177/6165854/6901778e-b2ab-11e4-8b1b-4e61e7c7f408.PNG)

The field is to short:

``` SQL
`langcode` varchar(2) NOT NULL default '',
```

Fine for `de` but not `de_DE`
Should have a length of 5 min.

``` SQL
`langcode` varchar(5) NOT NULL default '',
```

**Comment by Zeromax** [comment]
So finished all attributes. Would be cool to have the as soon as possible in the tng branch ;)

With this fix it is possible to use location based language codes

**Comment by discordier** [comment]
Have you read #420?
Especially the part about the language fallback.

**Comment by Zeromax** [comment]
Puh. That's a lot of stuff ;)
I only now the function in the front end. With my PR's this is given. I have no idea if it works in the CMS... Will test it later next week if I do not Forget it...

**Comment by discordier** [comment]
That's the point of mentioned issue. The Frontend.  With your fix, there is no fallback from de-de to de. Or the other way around.
Therefore we labeled it future but as you already are at it, you might want to finish it up. :)

**Comment by Zeromax** [comment]
I see the Problem. I can have allok into it. Maybe ist already there. I have seen some methods which get the language for one Metamodel.

Maybe I can have a closer look next week.

**Comment by discordier** [comment]
As attributes are finished I'll close this in favor of  #420 now.
