### ISSUE TITLE
Could not retrieve MetaModel

### ISSUE THREAD

**Issue by psren** [MetaModels/core#758]
```php
Fatal error: Uncaught exception InvalidArgumentException with message Could not retrieve MetaModel thrown in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/Attribute/Subscriber.php on line 474
#0 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/Attribute/Subscriber.php(495): MetaModels\DcGeneral\Events\Table\Attribute\Subscriber->createAttributeInstance(Array)
#1 [internal function]: MetaModels\DcGeneral\Events\Table\Attribute\Subscriber->handleUpdateAttribute(Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(284): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(614): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->handlePostPersist()
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(668): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, NULL)
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#16 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#17 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodels')
#18 contao/main.php(20): Contao\BackendMain->run()
#19 {main}
```

https://github.com/contao-community-alliance/dc-general/issues/94#issuecomment-74594954

**Comment by memikeandi** [comment]
This happens to my every time I try to add an attribute. Any leads on how to fix it or is there some older version where this does not happen? Kind of makes it impossible to use without beeing able to add attributes :)
I tested a lot of times and sometimes the error doesn´t occurs. If you for example create a new metamodel and starts by adding a file attribute. Then you can add other attributes without getting any error. Maby this was just by chance though..

**Comment by dtomasi** [comment]
@memikeandi I tried what you told about first add a attribute_file. In my case the error occurs also. Which version of metamodels/core and contao/core did you use?

**Comment by memikeandi** [comment]
Contao 3.4.4 and metamodels/core dev-tng @ 6a793d. 

It has to be a completely new metamodel. If you create at new metamodel and add for example a text attribute and the error occurs. You need to delete the whole metamodel.

But if you create a new metamodel and the first attribute you add is a file attribtue. Then I can start add other attributes without problem. I can even delete the file attribute and continue to add other attributes without getting error.

**Comment by psren** [comment]
I got the same versions ad @memikeandi 
The error seems to occur before updating the database with the newly created attribute.

If a add the column to the table manually everything works fine from then.

**Comment by psren** [comment]
Do you have a plan when to fix this? This bug is really annoying and prevents me from testing further.

**Comment by psren** [comment]
Or is there any Contao/MM-Combination that is working properly?

**Comment by psren** [comment]
```
$metaModel        = $this->getMetaModelById($information['pid']);
```

```$information['pid']``` der Key existiert nicht.

**Comment by cboelter** [comment]
same here. i will have a look on it to fix it

**Comment by memikeandi** [comment]
Donwloaded the latest nightly, and the problem seems to be gone? However I can not add the Tags attribute. When you add a Tags attribute I don´t get any error messages but no database table is created... Don´t now if this is the same issue or a separate one

**Comment by cboelter** [comment]
@discordier I provided a PullRequest could check this as soon as possible?

**Comment by cboelter** [comment]
It will be fixed after composer update.

**Comment by denunv** [comment]
For me it works again with normal attributes, but not with translated attributes.

**Comment by memikeandi** [comment]
@cboelter great! @denunv did you get the tags attribute to work as well?

**Comment by cboelter** [comment]
Is there the same error message on translated attributes, or another?

**Comment by denunv** [comment]
@memikeandi @cboelter No database fields are created for tags and translated attributes. There is also no error message.

**Comment by psren** [comment]
After a temporary fix on my installation translated attributes worked nice.
they wirk with the PR, too. I havn't tried tags for now.

**Comment by denunv** [comment]
@psren Which Contao version are you using? I need a Contao/MM-Combination where "translated attributes" are working. I have 3.4.4 installed.

**Comment by discordier** [comment]
@denunv Please ensure that you have *deleted* the problematic attribute an *recreated* it.
The fix will not scan the Table for missing columns.

**Comment by psren** [comment]
I use Contao 3.2.19 and 3.4

**Comment by memikeandi** [comment]
I use Contao 3.4.4. And the exact same problem as @denuv. No database fields are created for tags and translated attributes. But there are no error messages.

**Comment by cboelter** [comment]
For tags and translated attributes will be no fields created because they will be stored in separate value tables.

**Comment by xantippe** [comment]
ist das Ticket noch aktuell oder kann es geschlossen werden?

**Comment by psren** [comment]
Kann ich leider nicht sagen, das Projekt wurde inzwischen anders umgesetzt.
