### ISSUE TITLE
LoadDataContainerEvent not found 

### ISSUE THREAD

**Issue by psren** [MetaModels/core#759]
Bein Aufruf von MetaModels im Backend:

```php
Fatal error: Class 'ContaoCommunityAlliance\Contao\Bindings\Events\Controller\LoadDataContainerEvent' not found in /kunden/302047_70174/kunden/wacg/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Boot.php on line 77
```

**Comment by discordier** [comment]
This class is part of https://github.com/contao-community-alliance/events-contao-bindings.
Is it installed? If not, I wonder where the dependency got lost.

**Comment by psren** [comment]
Hat sich inzwischen erledigt.
Da muss es irgendwas mit den Abhängigkeiten verkackt haben beim letzten Update.
Obwohl keine Fehlermeldung kam...

Jetzt geht es wieder

```php
- Installing contao-community-alliance/events-contao-bindings (dev-master 4f9f928)
```
