### ISSUE TITLE
Weiße Seite nach Update 

### ISSUE THREAD

**Issue by sevenfour66** [MetaModels/core#760]
MM-Installation mit dem aktuellen nightly build upgedated.

Wenn man jetzt ein MM bearbeiten bearbeiten/ erstellen will, bekommt man eine weiße Seite. Offensichtlich wird beim Update die "events-contao-bindings" und "backports-initialize-system" entfernt, was zu diesem Fehler führt. Installiert man über den Composer die "events-contao-bindings" händisch nach dem Update wieder, geht auch MM wieder. Gleiches passiert, wenn man MM neu aufsetzt. Dort muss man ebenfalls die "events-contao-bindings" nachinstallieren um MetaModels zum Laufen zu bringen.

Nightly vom 18-02-15
Contao 3.4.3

![screenshot_mm_fehler](https://cloud.githubusercontent.com/assets/11057674/6245025/9e3479ac-b75a-11e4-889e-a6948667f2a6.jpg)

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@sevenfour66 could you please have a final look at this and tell if your issue has been resolved?

**Comment by sevenfour66** [comment]
Issue resolved. Thanks.
