### ISSUE TITLE
Multiple selections in checkbox menu

### ISSUE THREAD

**Issue by basisbyte** [MetaModels/core#761]
So this is not a bug (i think), it's a question or feature request. 
When I create a checkbox select menu in the frontend,
![2015-02-20_08h19_40](https://cloud.githubusercontent.com/assets/3695269/6282693/3dab00a8-b8d9-11e4-8fbf-07c1259b520e.png)
 i can select one item and it works as expected,
![2015-02-20_08h20_28](https://cloud.githubusercontent.com/assets/3695269/6282698/5c18d8bc-b8d9-11e4-98fc-92ccde90d60e.png)

but not multiple items. When selecting multiple items, after the auto-reload (i activated that as i need it) it does not find anything and the checkboxes are all unchecked then. 

![2015-02-20_08h20_56](https://cloud.githubusercontent.com/assets/3695269/6282774/53fde8ba-b8da-11e4-96f4-9a935d2e0949.png)

As far as i can see the second selection appears in the url as there is the encoded version of a semicolon separating the two items. So my question is if its a future feature and not working as of now, or if this feature is not on the raodmap. If this was already dicussed i am sorry for the double posting, but I couldn' find anything related.  

Thanks guys :)

**Comment by tim-bec** [comment]
So you are creating a checkbox-filter on a select attribute?
Instead you can create a multiselect on a tag attribute, this should work - also with multiselect.

**Comment by basisbyte** [comment]
Sorry for my late answer but was ill and then had to work on another project. 
Just wanted say thanks, 'cause it worked.
