### ISSUE TITLE
Ausblenden von Attributen über Auge funktioniert nicht

### ISSUE THREAD

**Issue by Schnubl** [MetaModels/core#762]
Das Ausblenden von Attributen funktioniert nicht aufgrund vom Caching.
Wenn man anschliessend das Komplette Metamodel öffnet und nochmal Speichert wird event. Cache geleert und somit ie änderung übernommen.

**Comment by haendersonfox** [comment]
das problem besteht mit dem aktuellen TNG von heute immer noch…

lg.

**Comment by xantippe** [comment]
@Schnubl: kannst Du zu der Aussage "*Das Ausblenden von Attributen funktioniert nicht aufgrund vom Caching.*" noch mehr Infos zum Nachbauen geben, welche Caches Du wie aktiv hast?

**Comment by discordier** [comment]
Das bezog sich auf den MM cache, welcher aber seit 9440e31 geleert werden sollte... kannst du das Problem wirklich noch reproduzieren?

**Comment by xantippe** [comment]
@Schnubl bitte testen

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Schnubl could you please have a final look at this and tell if your issue has been resolved?
