### ISSUE TITLE
Could not create a Variant-MetaModel as Child-Table

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#770]
I've tried to use a Variant-MetaModel as an Child-Table but it does not work. ListView is fine, but my added entry is not shown :(

@discordier is it currently not possible to use it in this usecase?

**Comment by discordier** [comment]
Apparently not completely, I thought the Builder would now correctly created a parented tree view.
Might also a bug in dcg when filtering the tree collection (from level 2 on as level 1 is the variant base elements).

What type of entry exactly is not shown? The base or only the variant?

**Comment by cboelter** [comment]
Nothing is shown not the base not the variant. Only a blank ListView.
Is it possible to fix it quickly or is it a complex bug?

**Comment by cboelter** [comment]
@discordier If you want, I can send you login data for the project, so you can have a closer look on it.

**Comment by cboelter** [comment]
I had a closer look on it, the problem is in this lines: https://github.com/MetaModels/core/blob/e750d21b26bf9a05f46c9d4e70fb3902a7fe8473/src/MetaModels/DcGeneral/Dca/Builder/Builder.php#L735-L741

There is the RootCondition called, which is not checking for a given PID. So it sets the pid condition every time to 0. If I override the array there, the child table works fine.

@discordier Any idea where I can fix it for working as a child table?

**Comment by tim-bec** [comment]
fixed
