### ISSUE TITLE
Variante zeigt im Titel nichts an wenn ein Select-Feld das Variantenfeld ist.

### ISSUE THREAD

**Issue by psren** [MetaModels/core#771]
Problem:
![bildschirmfoto 2015-03-03 um 17 18 27](https://cloud.githubusercontent.com/assets/1016798/6466639/6c2b27d4-c1c9-11e4-8bf3-83a4dc614227.png)

Variantenattribute:
![bildschirmfoto 2015-03-03 um 17 19 26](https://cloud.githubusercontent.com/assets/1016798/6466650/80a6867c-c1c9-11e4-95a4-bd581851f254.png)

Rendersetting:
![bildschirmfoto 2015-03-03 um 17 20 10](https://cloud.githubusercontent.com/assets/1016798/6466674/a453a8ca-c1c9-11e4-9a1e-56d03ad79529.png)

Alle Komponenten sind auf dem aktuellsten Stand.

**Comment by markus151173** [comment]
![mm-variante](https://cloud.githubusercontent.com/assets/5483797/6484686/3d5a8e80-c27e-11e4-9ca1-2e22ac11cb3b.jpg)

Ich habe leider auch das gleiche Problem mit der Version von metamodel.me (nightly-builds ZIP).

Zum Einsatz kommt Contao 3.2.18 unter WIN 7 Pro, XAMPP 1.8.2, PHP: 5.4.16.
MM habe ich mir von der Seite metamodel.me MetaModels 2.x als ZIP gezogen.

**Comment by cboelter** [comment]
Bei mir geht es auch mit einem Select im Titel.

**Comment by psren** [comment]
Scheint inzwischen zu gehen. Ich weiß nicht woran das lag.
Wie sieht es bei dir aus @markus151173 ?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@psren could you please have a final look at this and tell if your issue has been resolved?

**Comment by psren** [comment]
Testing positive
