### ISSUE TITLE
Can't create input screen or view

### ISSUE THREAD

**Issue by 360fusionBen** [MetaModels/core#773]
I have installed the nightly today (06-03-2015) on a Contao 3.2.16 set up and built my metamodel. However when I try to set up a view so I can add items to it I can't.

there are groups for users and members and I have also set up the render settings and input screens but none o these are available for selection. Not even the Administrator is showing as an option. 

![screenshot_1](https://cloud.githubusercontent.com/assets/1401397/6525139/be1e9fd0-c3f9-11e4-9622-af0ee87e52ec.jpg)

**Comment by stefanheimes** [comment]
I test it with a contao 3.2.16, too. But i have no problems. I have all Groups for FE/BE and the settings from MetaModels. I test it with the core version e750d21b and the DCG version 2.0.0-beta 22 and the version 5db9787e.

Maybe you have a problem with the cache?

**Comment by tim-bec** [comment]
cleanup. please reopen if problem still occure.
