### ISSUE TITLE
Fehler bei Attributen (Listenansicht)

### ISSUE THREAD

**Issue by dazzle89** [MetaModels/core#775]
Hallo,
mir ist in der Listenansicht der Attribute ein kleiner Fehler aufgefallen: Wenn man mit der Maus über das Plus-Icon fährt, steht dort "pastenew.1"

Außerdem:
Wenn ich bei einem Attribut auf das Plus klicke, muss ich auswählen, an welcher Stelle ich das neue Attribut einfügen möchte. Dabei müsste es, wie es in Contao typisch ist, automatisch hinter dem geklickten Attribut eingefügt werden, also ohne eine Position festzulegen.
Zudem hat das Einfügen-Icon auch einen falschen Tooltip "pasteafter.1"

Achja, und die Möglichkeit "Ablage leeren" gibt es bei mir ebenfalls nicht...

Contao Version 3.4.4

**Comment by xantippe** [comment]
aktueller Test: MM core 2.0.0-alpha8

* bei dem Plus in der Liste wird sofort die Bearbeitungsmaske geöffnet und das neue Attribut nach demjenigen mit dem geklickten Button eingefügt
* Ablage leeren ist nun vorhanden ("oben links" per [x])
* Tooltip ist ein DCG-"Problem" ... wird sich noch ändern

=> schließe das Ticket
