### ISSUE TITLE
FE breadcrumb shows wrong path

### ISSUE THREAD

**Issue by septentrio** [MetaModels/core#778]
Hello,

Here's a little issue.

I have set a MM catalog with two FE views. The first is a grid view of several items, and when you click on "show more details" it shows a detailed view.

The fact is that my breadcrumb doesn't show the name of the item when i am on detailed view

Recherche archéologique >  Les chantiers archéologiques >  item1

Is it possible to do ?

Thanks

**Comment by discordier** [comment]
You have two way of solving this.
First is editing your breadcrumb template and set the value accordingly when on the "reader page".
This is pretty easy and suggested.

The second solution is to implement a `$GLOBALS['TL_HOOKS']['generateBreadcrumb']` for this and alter the title of the last element in there.

As MetaModels does not have a "detail page" there is no way to determine what exactly shall be shown in there and how the breadcrumb shall get updated.
