### ISSUE TITLE
Fehler bei Varianten-Erstellung

### ISSUE THREAD

**Issue by cptshit** [MetaModels/core#780]
Hallo,
von bestehenden Datensätzen kann ich problemlos Varianten erzeugen. Alles gut so weit.

Wenn ich aber einen neuen Datensatz erzeugen will (es steht nur das Zwischenablagen-Logo zur Verfügung, siehe Grafik ![schnellsuche 2 mymusic - contao open source cms 3](https://cloud.githubusercontent.com/assets/4488060/6646265/82c2fce0-c9c3-11e4-8359-25399e243ea2.png)), erhalte ich folgende Fehlermeldung:

Fatal error: Uncaught exception RuntimeException with message No sorting property defined for mm_mymusic thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/SortingManager.php on line 357
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/SortingManager.php(175): ContaoCommunityAlliance\DcGeneral\Controller\SortingManager->calculate()
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(1066): ContaoCommunityAlliance\DcGeneral\Controller\SortingManager->getResults()
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(941): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->pasteTop(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), NULL, NULL)
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(766): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->sortAndPersistModels(Array, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(642): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doActions(Array, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(505): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyClipboardActions(NULL, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, NULL, Array)
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(546): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#14 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#15 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_my...')
#16 contao/main.php(20): Contao\BackendMain->run()
#17 {main}

Mach ich was flasch? Und wieso erhalte ich nicht den button "Datensatz erzeugen"?

Ich arbeite mit Contao 3.4.4 und MM Version e750d21b.

Danke euch,

Henrik

**Comment by cptshit** [comment]
Ticket https://github.com/MetaModels/core/issues/736 scheint das gleiche Problem zu beschreiben.

Wird an dem Ticket noch gearbeitet?

Henrik

**Comment by tim-bec** [comment]
should be fixed with https://github.com/MetaModels/core/pull/768

**Comment by cptshit** [comment]
`
dfgb
`
