### ISSUE TITLE
MetaModels werden nicht gelöscht

### ISSUE THREAD

**Issue by dazzle89** [MetaModels/core#781]
Hallo,

mir ist folgendes aufgefallen:

Wenn ich meine MetaModels lösche, bleiben die erstellten Metamodels in der Navigation unter "Inhalte", wo ich sie eingeordnet hatte, bestehen. Wenn ich sie anklicke, bekomme ich natürlich eine Fehlermeldung, weil die MetaModels an sich gelöscht werden, bloß die Menüpunkte nicht.

Sie verschwinden erst, wenn ich in der Systemwartung den entsprechenden Job durchführe.

Contao Version 3.4.4

**Comment by tim-bec** [comment]
Bitte leere mal den Contao Cache.

**Comment by discordier** [comment]
MetaModels cache problem.
Es fehlt die Behandlung des delete event vom DCG.

**Comment by xantippe** [comment]
Test per Contao 3.5.6 und MM core 2.0.0-alpha8
in Einstellungen > Internen Cache umgehen NICHT checked

=> beim Löschen eines MM ist das Icon sofort im BE weg...

somit m.E. obsolet

**Comment by dazzle89** [comment]
Sehr geehrte Damen und Herren, 

vielen Dank für Ihre E-Mail. Gerne beantworte ich Ihr Anliegen nach meiner Rückkehr am 04.01.2016.
Bitte beachten Sie, dass Ihre E-Mail während meiner Abwesenheit nicht automatisch weitergeleitet und auch nicht bearbeitet wird.
Vielen Dank für Ihr Verständnis. Ich wünsche Ihnen und Ihrer Familie eine besinnliche Weihnachtszeit und einen charmanten Jahreswechsel.

Mit freundlichen Grüßen 
Mirko Pawlik

---
BrandOrange.de
Werbeagentur in Lübeck

Brockesstraße 69 - 23554 Lübeck
Fon:		+49 (0)451 300 96 09-0
Fax:		+49 (0)451 300 96 09-22
Mail:		m.pawlik@brandorange.de
Web:	        www.brandorange.de

Rechtshinweise:
USt-IdNr.: DE248482801
Rechtsform: Gesellschaft bürgerlichen Rechts
Vertretungsberechtigte Personen: Sebastian Franz, Catharina Schreiber & Sascha Wons

Diese E-Mail kann vertrauliche und/oder rechtlich geschützte Informationen enthalten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
 
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
