### ISSUE TITLE
Darstellungsprobleme in Eingabemaske (Contao 3.4.4)

### ISSUE THREAD

**Issue by mrs4ndm4n** [MetaModels/core#782]
Felder laufen zu breit, bei Feldern mit Tiny fällt es auf. 

![venues_-_contao_open_source_cms_3_4](https://cloud.githubusercontent.com/assets/3496645/6687080/a34641fc-cca7-11e4-8916-273028788e1a.png)

**Comment by discordier** [comment]
anscheinend hast du dem veroeffentlicht ein w50 gegeben, dem Name jedoch nicht?
Probier mal dem namen ein clr zu verpassen, dann sollte alles wieder klappen.

**Comment by mrs4ndm4n** [comment]
nope, alle Felder sind ohne Backen-Klassen

**Comment by mrs4ndm4n** [comment]
bzw., in dem Screenshot schon.. aber der Fehler tritt trotzdem auf, auch ohne Backend-Klassen

![image](https://cloud.githubusercontent.com/assets/3496645/6780060/22c419fe-d162-11e4-9cb9-7bc9f9ddd2a3.png)

**Comment by MacKP** [comment]
Hallo mrs4ndm4n,
gib uns doch mal bitte einen Backend Login zu der Install, damit man mal direkt schauen kann. Das wäre einfacher ;-)
Schicks mir einfach an die please.marc@metamodel.me

Viele Grüße

**Comment by mrs4ndm4n** [comment]
Hallo Marc,

vielen Dank, habe am WE noch mal ein composer update gemacht. Jetzt passt's alles wieder.

**Comment by MacKP** [comment]
Na, wunderbar :)
