### ISSUE TITLE
InvalidArgumentException with message Invalid file array

### ISSUE THREAD

**Issue by Hauge** [MetaModels/core#784]
Beim anlegen eines Kinddatensatzes:
![1](https://cloud.githubusercontent.com/assets/1571133/6770681/f2240ef2-d0c7-11e4-9565-25c32166ec25.JPG)
erhalte ich:
```
Fatal error: Uncaught exception InvalidArgumentException with message Invalid file array thrown in system/modules/metamodels/classes/src/MetaModels/Helper/ToolboxFile.php on line 709
```
Der Datensatz wird aber dennoch angelegt. Wenn ich auf "zurück" klicke sieht es so aus:
![2](https://cloud.githubusercontent.com/assets/1571133/6770694/49c14ae4-d0c8-11e4-88c6-55225cade780.JPG)
Soweit so gut.
Sobald ich in diesem Datensatz ein Bild wählen möchte, erhalte ich folgenden Fehler:
```
Fatal error: Uncaught exception LogicException with message Property picture_1 (file) did not accept the value (The values differ. Encountered type string expected array (Found '����Л䨒' . "\0" . 'p0�� ', expected array ( 0 => '����Л䨒' . "\0" . 'p0�� ', ))). thrown in system/modules/metamodels/classes/src/MetaModels/DcGeneral/Data/Model.php on line 178
```
Bereits bestehende Datensätze bleiben unberührt, kann die aber dennoch nicht ändern.

Versionsinfo:
contao 3.4.4
```
Name                                             Version                 Last modification
============================================================================================
http://c-c-a.org/
contao-community-alliance/dc-general             dev-develop @ c21c7f    2015-03-21 08:05:33
contao-community-alliance/dependency-container   dev-develop @ 47f03a    2015-02-05 17:53:34
contao-community-alliance/event-dispatcher       dev-develop @ d2da54    2014-11-28 14:49:59
contao-community-alliance/events-contao-bindings dev-contao-3.2 @ 36eee0 2014-11-08 18:39:45
contao-community-alliance/translator             dev-develop @ 02feca    2014-06-05 08:57:37
--------------------------------------------------------------------------------------------

http://bit3.de
contao-community-alliance/meta-palettes          dev-master @ 13117d     2015-01-26 17:37:38
--------------------------------------------------------------------------------------------

https://www.cyberspectrum.de
discordier/justtextwidgets                       0.5.4                   2014-02-05 22:52:54
--------------------------------------------------------------------------------------------

http://www.doctrine-project.org
doctrine/cache                                   dev-master @ 6c5c32     2015-02-16 12:24:01
--------------------------------------------------------------------------------------------

http://www.leo-unglaub.net
leounglaub/contao-simple-ajax                    1.0.2                   2014-02-07 22:35:55
--------------------------------------------------------------------------------------------

http://www.men-at-work.de
menatwork/contao-multicolumnwizard               dev-dev @ ae91b5        2014-11-20 11:57:11
--------------------------------------------------------------------------------------------

http://now.metamodel.me/
metamodels/attribute_alias                       dev-tng @ 8ceb31        2015-01-29 17:36:33
metamodels/attribute_checkbox                    dev-tng @ e8cd5c        2015-01-30 09:07:10
metamodels/attribute_combinedvalues              dev-tng @ 6cc84e        2015-03-20 23:44:28
metamodels/attribute_country                     dev-tng @ b7bb7f        2015-01-29 18:01:21
metamodels/attribute_decimal                     dev-tng @ 439c58        2015-01-29 18:04:31
metamodels/attribute_file                        dev-tng @ 9b3cb6        2015-03-21 08:13:34
metamodels/attribute_langcode                    dev-tng @ 133458        2015-01-29 20:13:11
metamodels/attribute_longtext                    dev-tng @ c9e7d2        2015-01-29 20:59:06
metamodels/attribute_numeric                     dev-tng @ bec96d        2015-01-29 21:43:58
metamodels/attribute_rating                      dev-tng @ 741381        2015-01-30 00:22:15
metamodels/attribute_select                      dev-tng @ 31de9c        2015-03-21 06:26:52
metamodels/attribute_tabletext                   dev-tng @ 212e4c        2015-02-02 11:06:58
metamodels/attribute_tags                        dev-tng @ edc7cc        2015-03-21 05:21:10
metamodels/attribute_text                        dev-tng @ 3023cd        2015-01-30 05:34:20
metamodels/attribute_timestamp                   dev-tng @ 5e957a        2015-03-21 01:11:48
metamodels/attribute_translatedalias             dev-tng @ 3f68cd        2015-01-30 06:35:53
metamodels/attribute_translatedcheckbox          dev-tng @ 3813e4        2015-01-30 09:30:26
metamodels/attribute_translatedcombinedvalues    dev-tng @ 310be8        2015-02-03 17:59:19
metamodels/attribute_translatedfile              dev-tng @ 839494        2015-03-21 09:27:46
metamodels/attribute_translatedlongtext          dev-tng @ 52a3b7        2015-02-05 21:51:54
metamodels/attribute_translatedselect            dev-tng @ 575303        2015-02-18 02:05:09
metamodels/attribute_translatedtabletext         dev-tng @ e936db        2015-02-17 18:10:52
metamodels/attribute_translatedtags              dev-tng @ 10ec35        2015-02-18 01:41:47
metamodels/attribute_translatedtext              dev-tng @ 574459        2015-02-17 19:34:56
metamodels/attribute_url                         dev-tng @ 6e4d7b        2015-02-17 21:12:53
metamodels/bundle_all                            dev-master @ f58927     2013-10-01 20:03:31
metamodels/bundle_attributes                     dev-master @ 058e26     2014-02-03 14:19:34
metamodels/bundle_filter                         dev-master @ 45d9cf     2013-05-03 07:16:44
metamodels/bundle_nontranslated                  dev-master @ 5f2b3f     2014-02-17 14:37:26
metamodels/bundle_translated                     dev-master @ 4bc0c1     2014-02-17 14:34:39
metamodels/core                                  dev-tng @ fbb686        2015-03-21 17:51:37
metamodels/filter_checkbox                       dev-tng @ 7d06b8        2015-02-17 21:46:24
metamodels/filter_fromto                         dev-tng @ d84ea1        2015-03-19 08:13:52
metamodels/filter_range                          dev-tng @ 3516f5        2015-03-20 02:53:17
metamodels/filter_select                         dev-tng @ 597806        2015-01-10 05:37:20
metamodels/filter_tags                           dev-tng @ 1127e5        2015-02-18 01:59:32
metamodels/filter_text                           dev-tng @ 6df9de        2015-01-13 04:37:56
--------------------------------------------------------------------------------------------

http://pimple.sensiolabs.org
pimple/pimple                                    1.1.x-dev @ bc2fc1      2014-04-20 07:24:09
--------------------------------------------------------------------------------------------

http://symfony.com
symfony/event-dispatcher                         2.7.x-dev @ 186349      2015-03-13 17:50:01
symfony/expression-language                      2.7.x-dev @ 1ec5b5      2015-03-17 12:50:07
--------------------------------------------------------------------------------------------

other
contao-community-alliance/url-builder            dev-develop @ 5f8997    2014-09-20 03:38:06
```

**Comment by Hauge** [comment]
Nachtrag:
Ich kann den Datensatz auch nicht aus dem Zwischenspeicher schmeißen:
![3](https://cloud.githubusercontent.com/assets/1571133/6770725/9a06ee5e-d0c9-11e4-9927-76a28333c1f6.JPG)
Dazu muss ich den Cache in der Benutzerverwaltung leeren.

**Comment by discordier** [comment]
Wie genau ist dein File Attribut konfiguriert? Ich muss da was ybersehen haben.

**Comment by Hauge** [comment]
Guten Morgen, 
hier das Attribut:
![5](https://cloud.githubusercontent.com/assets/1571133/6774483/93795182-d121-11e4-84a9-c3e92d702e0f.JPG)
Hier die Konfiguration der Eingabemaske:
![6](https://cloud.githubusercontent.com/assets/1571133/6774529/499d09a4-d122-11e4-8eec-c76d8385af5b.JPG)
Und hier zur Sicherzeit noch das Sorting:
![7](https://cloud.githubusercontent.com/assets/1571133/6774535/5b6aa11e-d122-11e4-9d17-e00637c9881b.JPG)

**Comment by Hauge** [comment]
Der Fehler kommt auch, wenn das mm nicht als Kindtabelle angelegt ist.

**Comment by discordier** [comment]
Ref to MetaModels/attribute_file#45.

**Comment by Hauge** [comment]
Thanx

**Comment by cboelter** [comment]
@discordier the error is still there :( ...

```Fatal error: Uncaught exception InvalidArgumentException with message Invalid file array thrown in composer/vendor/metamodels/core/src/MetaModels/Helper/ToolboxFile.php on line 709 ```

**Comment by discordier** [comment]
siehe 0b2f1642b3703ebd4df1a77ce454b7bbc004a1c5.

**Comment by pju-** [comment]
Using the current nightly and Contao LTS (3.2.20), I still get this error.
Same behaviour as Hauge described: entries are saved, but error message is thrown. Can't clear the new entry from the cache. Emptying the backend/metamodels cache doesn't help either.

**Comment by discordier** [comment]
Can you provide details on your configuration and maybe also a screengrab of how to reproduce this?
I fixed it together with @cboelter 8 days ago and therefore we thought it would be fixed.

**Comment by pju-** [comment]
Just did some further testing and it seems connected to visibility conditions.

First off, this is the exact error message:
`Fatal error: Uncaught exception InvalidArgumentException with message Invalid file array thrown in system/modules/metamodels/classes/src/MetaModels/Helper/ToolboxFile.php on line 714`

To reproduce:
3 Models:
- model 2 (slides) with image field - is child of model 1 (but I think that's irrelevant)
- model 3 acts is only for the select

The file/image field is set so only a certain folder and it's subfolders can be accessed and only images can be selected.

The problem arises when I create the condition that the image/file field is only shown when the select field has a certain value.
It's not set to obligatory, but if I don't set an image I get the error message. 
Additionally, I can't choose to de-select - nothing happens when I update after choosing the de-select radio in the dialog.

No idea how to post the nice version details that hauge posted I'm afraid.
Hope that helps.

![bildschirmfoto 2015-04-02 um 22 16 17](https://cloud.githubusercontent.com/assets/5202770/6972715/eaa43cee-d985-11e4-8227-5a0cd661f7b8.png)
![bildschirmfoto 2015-04-02 um 22 13 15](https://cloud.githubusercontent.com/assets/5202770/6972651/83f0b41e-d985-11e4-9b44-382236b3356f.png)
![bildschirmfoto 2015-04-02 um 22 12 44](https://cloud.githubusercontent.com/assets/5202770/6972649/83e64ace-d985-11e4-9c27-18d2794f8109.png)
![bildschirmfoto 2015-04-02 um 22 12 55](https://cloud.githubusercontent.com/assets/5202770/6972650/83ecf9c8-d985-11e4-94a3-ee70d6fe2698.png)

**Comment by discordier** [comment]
Could you post the whole stack trace instead of only the top message?

**Comment by pju-** [comment]
Danke für deinen Einsatz!
I just updated the post with a more general test case.

Here is the stack trace, sorry:
```
Fatal error: Uncaught exception InvalidArgumentException with message Invalid file array thrown in system/modules/metamodels/classes/src/MetaModels/Helper/ToolboxFile.php on line 714

#0 system/modules/metamodelsattribute_file/classes/src/MetaModels/Attribute/File/File.php(115): MetaModels\Helper\ToolboxFile::convertValuesToDatabase(NULL)
#1 system/modules/metamodels/classes/src/MetaModels/MetaModel.php(873): MetaModels\Attribute\File\File->serializeData(NULL)
#2 system/modules/metamodels/classes/src/MetaModels/MetaModel.php(923): MetaModels\MetaModel->saveAttribute(Object(MetaModels\Attribute\File\File), Array, NULL, NULL)
#3 system/modules/metamodels/classes/src/MetaModels/MetaModel.php(1003): MetaModels\MetaModel->updateVariants(Object(MetaModels\Item), NULL, Array)
#4 system/modules/metamodels/classes/src/MetaModels/Item.php(299): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#5 system/modules/metamodels/classes/src/MetaModels/DcGeneral/Data/Driver.php(562): MetaModels\Item->save()
#6 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(622): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#7 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(679): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#8 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(777): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#9 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(752): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#11 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#17 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#18 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_te...')
#19 contao/main.php(288): Main->run()
#20 {main}
```

**Comment by netdrag** [comment]
I get the same error. I have a metamodel with 2 Image fields and I get this error also when I leave this fields empty.

**Comment by Creational** [comment]
Same here ...

```
Fatal error: Uncaught exception InvalidArgumentException with message Invalid file array thrown in composer/vendor/metamodels/core/src/MetaModels/Helper/ToolboxFile.php on line 714
#0 composer/vendor/metamodels/attribute_file/src/MetaModels/Attribute/File/File.php(115): MetaModels\Helper\ToolboxFile::convertValuesToDatabase(NULL)
#1 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(873): MetaModels\Attribute\File\File->serializeData(NULL)
#2 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(923): MetaModels\MetaModel->saveAttribute(Object(MetaModels\Attribute\File\File), Array, NULL, 'en')
#3 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(1003): MetaModels\MetaModel->updateVariants(Object(MetaModels\Item), 'en', Array)
#4 composer/vendor/metamodels/core/src/MetaModels/Item.php(299): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#5 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(562): MetaModels\Item->save()
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(611): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(668): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#11 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#17 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#18 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_fi...')
#19 contao/main.php(20): Contao\BackendMain->run()
#20 {main}
```

**Comment by Creational** [comment]
Gibt es hier schon irgendwas Neues?

Bei mir scheint der Fehler aufzutreten, wenn mehr als ein Datei-Attribut im Metamodel existiert. Bei nur einem Datei-Attribut funktioniert das Speichern des Datensatzes in allen Konstellationen (Anpassen des Dateibaums, Nur Dateien, Mehrfachauswahl) einwandfrei.

Mein Konfiguration ist:
- Contao 3.4.4
- Übersetztes Metamodel
- ca. 50 Attribute, davon 6 Datei-Attribute
- Integration Eingabemaske: Unabhängig
- Render mode: Flat

**Comment by pju-** [comment]
Ich hab ein bisschen gegraben. Was ich herausgefunden habe, betrifft nur den Fall, den ich beschrieben habe: es gibt ein Select-Attribut, das als visibility condition für das File-Attribut fungiert:

In diesem Fall tritt der Error auf, wenn man das Auswahl-Attribut umstellt und daher das File-Attribut nicht mehr sichtbar ist.

Beim speichern wird `MetaModels\MetaModel->saveAttribute($objAttribute, $arrIds, $varData, $strLangCode)` aufgerufen.
`$varData` ist in diesem Fall `NULL`.
Das führt zu: `MetaModels\Attribute\File\File->serializeData(NULL)`

Das File-Attribut ist wohl das einzige Attribut mit eigener Implementierung von `serializeData`, oder? Das funktioniert über `ToolboxFile::convertValuesToDatabase($mixValues);`
`ToolboxFile::convertValuesToDatabase` erwartet ein Array mit der Struktur
````
    [bin] => Array
        (
        )

    [value] => Array
        (
        )

    [path] => Array
        (
        )
````
Weil NULL statt einem solchen Array übergeben wird, kommt die Exception. Soweit alles klar.

**Jetzt kann ich das für mich trivial lösen, indem ich gegen `NULL` checke und gegebenenfalls ein leeres Array mit der Struktur an `ToolboxFile::convertValuesToDatabase` übergebe. Das erscheint mir aber ziemlich unsauber, oder?**

Wenn das Datei-Attribut sichtbar ist und ich es abspeichere, wird in `MetaModels\Item->arrData['file']` das Array richtig generiert (mit bin, value und path als leeren Arrays, so wie oben).

Wenn das Datei-Attribut aber unsichtbar und leer ist und ich es abspeichere, dann ist `MetaModels\Item->arrData['file'] == NULL`.

 Das betrifft aber nur den Fall, dass das Datei-Attribut leer ist, wenn etwas ausgewählt ist, wird das Array immer korrekt übergeben.


Leider konnte ich nicht herausfinden, wo genau `MetaModels\Item->arrData`erzeugt wird, daher komm ich nicht dahinter, wie eine "saubere" Lösung aussehen würde. Aber ich hoffe, das hilft den Entwicklern.

**Comment by inred-froehlich** [comment]
pju hat recht, der Fehler liegt in der Datei "metamodels\attribute_file\src\MetaModels\Attribute\File" Zeile 113 in der Funktion "serializeData".

Dort einfach in der ersten Zeile der Funktion "if(is_null($mixValues)) return $mixValues;" einfügen.

**Comment by valentin-** [comment]
Der Fehler ist bei mir durch die Änderung in der File.php auch behoben.

**Comment by discordier** [comment]
The correct fix is given by @pju- in https://github.com/MetaModels/core/issues/784#issuecomment-102642859.
The `isset` was wrong there, see the comment in https://github.com/MetaModels/core/commit/cbbe4a1b163e1a01045a0849f4e5a81145f7c24b#diff-10016bad386a85c50b7e697ab5abdacbR445.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Hauge could you please have a final look at this and tell if your issue has been resolved?

**Comment by pju-** [comment]
Sorry, I did some testing but I'm afraid I was mistaken.

While my described solution indeed might get rid of some bugs, it doesn't solve the problem completely. In my specific case as described in https://github.com/MetaModels/core/issues/784#issuecomment-89035016, it only works if the item has been saved once before.

Else, if there is a file-attribute, but it is not visible, it will not be part of a newly created item (i.e. Item->arrData['your_file_attribute_name'] is not set). The problem then is that \MetaModels\Item->get returns NULL (Item.php, line 192).

I have no idea whether this is intended or whether it is a bug. It's probably not a problem for other attributes, as they can handle NULL values, but the file-attribute always expects an array.

**Comment by discordier** [comment]
Well your solution got rid of the root problem why the values were improperly converted to null.

I think I can follow your point about the "hidden" attribute when posting a new item. In that case, the value will be null. However, when loading from Database, the value should be properly handled by the file attribute in the `deserializeData` method (as `NULL` is the default value in the database anyway) rather than hacking the `serializeData` method.

**Comment by Teetrinker** [comment]
Sehr geehrte Damen und Herren

Danke für Ihre Nachricht. Ich bin ab 22. Juli wieder im Büro.

Ihre Nachricht wird nicht weitergeleitet. In dringenden Fällen wenden Sie sich bitte an Peter Oberhänsli: p.oberhaensli@webbaumeister.ch

Mit freundlichen Grüssen
David Bopp

**Comment by discordier** [comment]
Sorry for the automatic close. The ticket was mentioned in the commit message which has just been merged. Reopened it.

**Comment by xantippe** [comment]
bitte mit aktuellem MM testen - m.E. gibt es mit dem File-Attribut keine Probleme (mehr)

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Hauge could you please have a final look at this and tell if your issue has been resolved?
