### ISSUE TITLE
Fatal Error: Invalid date bei Eingabe einer Uhrzeit im Attribut timestamp

### ISSUE THREAD

**Issue by janborg** [MetaModels/core#785]
ich habe Contao 3.2.19 mit der aktuellsten nightly dev-tng von MetaModels im Einsatz.

Seit dem letzten Update erhalte ich bei Eingabe eines neuen Datensatzes und auch beim Öffnen eines bereits vorhandenen Datensatzes im Backend folgenden Fehler:

    Fatal error: Uncaught exception OutOfBoundsException with message Invalid date "20:00" thrown in system/modules/core/library/Contao/Date.php on line 440

    #0 system/modules/core/library/Contao/Date.php(85): Contao\Date->dateToUnix()
    #1 system/modules/core/library/Contao/Widget.php(1409): Contao\Date->__construct('20:00')
    #2 composer/vendor/contao-community-alliance/events-contao-bindings/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/WidgetSubscriber.php(55): Contao\Widget::getAttributesFromDca(Array, 'match_uhrzeit', '20:00', 'match_uhrzeit', 'mm_matches', Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
    #3 [internal function]: ContaoCommunityAlliance\Contao\Bindings\Subscribers\WidgetSubscriber->handleGetAttributesFromDca(Object(ContaoCommunityAlliance\Contao\Bindings\Events\Widget\GetAttributesFromDcaEvent), 'contao.events.w...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #4 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\Contao\Bindings\Events\Widget\GetAttributesFromDcaEvent), 'contao.events.w...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #5 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'contao.events.w...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Widget\GetAttributesFromDcaEvent))
    #6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(533): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('contao.events.w...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Widget\GetAttributesFromDcaEvent))
    #7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(681): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->getWidget('match_uhrzeit', NULL)
    #8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(420): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->renderWidget('match_uhrzeit', false, NULL)
    #9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(665): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->buildFieldSet(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Palette), NULL)
    #10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
    #11 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
    #12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
    #13 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
    #14 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #15 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #16 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
    #17 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
    #18 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
    #19 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
    #20 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_ma...')
    #21 contao/main.php(288): Main->run()
    #22 {main}

Ich habe zweimal das Attribut Timestamp im Einsatz, einmal als Datum und einmal als Uhrzeit! Ändere ich das Schema von Uhrzeit auf Datum, läuft alles problemlos. 

Wenn das Schema des Attributs auf "Datum und Uhrzeit" steht, kommt der Fehler nicht, es wird aber keine Uhrzeit abgespeichert. Wenn ich "20.09.2014 20:00" in das Feld eintrage, wird daraus nach dem Speichern "20.09.2014 00:00" Die Uhrzeit wird beim Speichern ignoriert. 

Gleicher Fehler tritt auch auf zweitem Testsystem unter Contao 3.3.7 auf.

**Comment by janborg** [comment]
https://community.contao.org/de/showthread.php?56330-Fatal-Error-Invalid-date-bei-Eingabe-einer-Uhrzeit-im-Attribut-timestamp

**Comment by discordier** [comment]
Habe es eingegrenzt https://github.com/contao/core/pull/7721

**Comment by discordier** [comment]
Has been fixed in [contao/core#3.2.20](https://github.com/contao/core/releases/tag/3.2.20), [contao#core/3.4.5](https://github.com/contao/core/releases/tag/3.4.5), [contao/core#3.5.0-beta1](https://github.com/contao/core/releases/tag/3.5.0-beta1)

**Comment by janborg** [comment]
Kann ich bestätigen, Fehler tritt in 3.2.20 nicht mehr auf! Danke!
