### ISSUE TITLE
kein RTE bei Textfeldern

### ISSUE THREAD

**Issue by poutvie** [MetaModels/core#787]
contao 3.2.19
metamodels/core 	dev-tng (16bf9e24)
contao-community-alliance/dc-general 	dev-develop (1ecd6180)
metamodels/bundle_all 	1.0.1

RTE bei Textfeldern wird nicht mehr geladen. Translated und nicht übersetzte.

**Comment by bizon1** [comment]
Contao 3.4.4
Metamodels heute über Composer aktuallisiert

Kann ich bestätigen, habe bei den Longtext-Feldern auch keinen tinyMCE mehr, obwohl für die Eingabemaske aktiviert.

**Comment by haendersonfox** [comment]
betrifft ebenfalls die einstellung "Leere Option einfügen"...

**Comment by haendersonfox** [comment]
funktioniert auf anhieb. vielen dank.
