### ISSUE TITLE
Alle (auch nicht filterbare) Attribute werden als Filter gezeigt, sobald "Filter" im Panellayout angegeben ist

### ISSUE THREAD

**Issue by poutvie** [MetaModels/core#788]
contao 3.2.19
metamodels/core dev-tng (16bf9e2)
contao-community-alliance/dc-general dev-develop (1ecd6180)
metamodels/bundle_all 1.0.1

unabhängig davon, ob unter Eingabemasken bei einem Attribut "filterbar" angehakt ist oder nicht, wird es als Filter im BE angeboten (also alle Attribute), sobald "Filter" im Panellayout angegeben ist.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@poutvie could you please have a final look at this and tell if your issue has been resolved?

**Comment by poutvie** [comment]
Ja, ist behoben. Danke!
