### ISSUE TITLE
Backlink not working

### ISSUE THREAD

**Issue by fritzmg** [MetaModels/core#793]
### Problem description

Assume you have two MetaModels, e.g. `mm_items` and `mm_categories` or something similar. Assume you want to create a frontend list that shows you all items of a specific category. Furthermore you have a detail page, where you show the details of a single item. Now assume you want the `jumpTo` link of that single item to point back towards the item list of the category. In theory this should be possible, by inserting the specific `{{link_url::*}}` for the `jumpTo` page of the category list and selecting the correct filter (which filters the items by category). This is also explained in the german Contao Wiki ([MetaModels Beispiel 2 - Detailansicht erstellen](http://de.contaowiki.org/MetaModels_Beispiel_2#Detailansicht_erstellen)).

However, this does not seem to work currently. Assume your item list for a specific category is under the following URL:

```
category/lorem-ipsum.html
```

Where `lorem-ipsum` is the **alias** of the category and "Lorem ipsum" would be the **name** of the category. This should also be the URL where the back-link points to in the detail list view of a specific item. However, the actual generated URL will be the following:

```
category/Lorem ipsum.html
```

So instead of using the **alias**, the system erroneously  retrieves the **name** of the category.
### Possible cause

I debugged through the code a little bit and the problem seems to originate from [MetaModels\Filter\Setting::generateFilterUrlFrom](https://github.com/MetaModels/core/blob/tng/src/MetaModels/Filter/Setting/SimpleLookup.php#L153).

``` php
public function generateFilterUrlFrom(IItem $objItem, IRenderSettings $objRenderSetting)
{
    $objAttribute = $this->getMetaModel()->getAttributeById($this->get('attr_id'));
    if ($objAttribute) {
        // TODO: shall we omit returning of empty values?
        $strResult = $objAttribute->getFilterUrlValue($objItem->get($objAttribute->getColName()));var_dump(get_class($objAttribute));
        return array($this->getParamName() => $strResult);
    }

    return array();
}
```

More specifically: the function call `$objAttribute->getFilterUrlValue(...)` actually calls [MetaModels\Attribute\Base::getFilterUrlValue](https://github.com/MetaModels/core/blob/tng/src/MetaModels/Attribute/Base.php#L542), which simply does

``` php
public function getFilterUrlValue($varValue)
{
    // We are parsing as text here as this was the way before this method was implemented. See #216.
    $arrResult = $this->parseValue(array($this->getColName() => $varValue), 'text');

    return urlencode($arrResult['text']);
}
```

i.e. it returns the user defined textual representation of the foreign column - which is the category's name in this case. Instead the call should probably go to [MetaModels\Attribute\Select\Select::getFilterUrlValue](https://github.com/MetaModels/attribute_select/blob/tng/src/MetaModels/Attribute/Select/Select.php#L119) which, I am guessing, would return the correct value of the **alias** field. So maybe this is just a polymorphism problem or something? Because the function `$this->getMetaModel()->getAttributeById($this->get('attr_id'))` actually returns a `MetaModels\Attribute\Select\MetaModelSelect` object and not a `MetaModels\Attribute\Select\Select` object.
### References

[Backlink funktioniert nicht](https://community.contao.org/de/showthread.php?56593-Backlink-funktioniert-nicht)
[MetaModels - erste Versuche - im Wiki](https://community.contao.org/de/showthread.php?36679-MetaModels-erste-Versuche-im-Wiki/page2&p=337179&viewfull=1#post337179)

**Comment by discordier** [comment]
The analysis is correct. Well done @fritzmg. There should be in fact an separate `MetaModelSelect::getFilterUrlValue()`.

**Comment by zonky2** [comment]
@fritzmg it´s possible to you to make a PR?

Thanks

**Comment by fritzmg** [comment]
Sorry, it has been a long time since I last used MetaModels, I don't know if I would ever get around to it.

**Comment by zonky2** [comment]
What a pity!

**Comment by zonky2** [comment]
Checked in MM 2.1 - maybe this already works in MM 2.1

Filtered with domain.tld/de/listenausgabe/division/produktion

![FireShot Pro Webpage Screenshot #386 - 'Listenausgabe - MM 2_2 - DE' - mm](https://user-images.githubusercontent.com/1045318/119357845-4d291e00-bca8-11eb-8e96-bcde233b300f.jpg)
Link "Details": domain.tld/de/listenausgabe/details/doe-john


![FireShot Pro Webpage Screenshot #387 - 'Details - MM 2_2 - DE' - mm](https://user-images.githubusercontent.com/1045318/119357868-531eff00-bca8-11eb-960b-95ba5ef55949.jpg)

Link "Details": domain.tld/de/listenausgabe/division/produktion
