### ISSUE TITLE
angepasste Templates werden nicht gefunden

### ISSUE THREAD

**Issue by Spelmann** [MetaModels/core#795]
Hi,
in der Listenansicht der Datensätze im Backend gibt es eine Fehlermeldung, wenn das Attribut ein angepasstes Template verwendet, das nicht im root von "templates" sondern dort in einem Unterverzeichnis liegt.

Meldung: Template not found (it is maybe within a unreachable theme folder?)

Wär es nicht möglich, die Unterverzeichnisse mit zu lesen?

**Comment by tim-bec** [comment]
Jaein. Siehe https://github.com/MetaModels/core/issues/579
