### ISSUE TITLE
Fatal error: Class 'MetaModels\DcGeneral\Events\BreadCrumb\BreadCrumbDcaCombine' not found in /bachstiftung-beta/system/modules/metamodels/classes/src/MetaModels/DcGeneral/Events/Table/DcaCombine/Subscriber.php on line 46

### ISSUE THREAD

**Issue by Kreativsoehne** [MetaModels/core#796]
Fatal error: Class 'MetaModels\DcGeneral\Events\BreadCrumb\BreadCrumbDcaCombine' not found in ../system/modules/metamodels/classes/src/MetaModels/DcGeneral/Events/Table/DcaCombine/Subscriber.php on line 46

MetaModel nightly-tng zip vom 16.04.2015

**Comment by discordier** [comment]
Das ist doch seit #792 durch e984590eb2bfdfb415b94802c544f705deaa53a7 gefixt?

**Comment by discordier** [comment]
Feedback bitte in #792 und ggf. dort reopen, aber vorher bitte checken dass das nightly wirklich die Datei nicht beinhaltet.
