### ISSUE TITLE
verbleibende Tags werden nicht ausgeblendet

### ISSUE THREAD

**Issue by haendersonfox** [MetaModels/core#798]
trotz der Option "verbleibende Tags" in den Filtereinstellungen werden die nachfolgenden Filterergebnisse nicht angepasst, somit wird die Ausgabe von 0 Ergebnissen forciert...

**Comment by haendersonfox** [comment]
https://github.com/MetaModels/attribute_select/issues/29

**Comment by MacKP** [comment]
Hier mal der Link zu dem Forenthread https://community.contao.org/de/showthread.php?56775-verbleibende-Ergebnisse-Ergebnisse-z%E4hlen&p=366813&viewfull=1#post366813

**Comment by xantippe** [comment]
@haendersonfox bitte testen, ob das Verhalten bei der aktuellen Version noch besteht

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@haendersonfox could you please have a final look at this and tell if your issue has been resolved?
