### ISSUE TITLE
Ergebnisse zählen

### ISSUE THREAD

**Issue by haendersonfox** [MetaModels/core#799]
bei Filtern funktioniert nicht. Es wird nur eine KlammerAufKlammerZu angezeigt…

**Comment by haendersonfox** [comment]
https://github.com/MetaModels/attribute_select/issues/29

**Comment by MacKP** [comment]
Wird daran liegen (hat Xtra gerade eben gesehen): count value ist ID der key und bei options der Alias

Muss dann 'nur' noch behoben werden ;-)

**Comment by discordier** [comment]
https://github.com/MetaModels/attribute_select/commit/892a570e3ed2bc9d703f797bb1a8c3a69db18c48

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@haendersonfox could you please have a final look at this and tell if your issue has been resolved?
