### ISSUE TITLE
Tag List lässt sich nicht komplett leeren. Wenn ich auf Checkbox Menü umstelle, geht es.

### ISSUE THREAD

**Issue by pointout** [MetaModels/core#803]
Contao 3.2.19
metamodels/core 	dev-tng (85826a73)
contao-community-alliance/dc-general 	dev-develop (3aaa54f1)

Ich habe eine Mehrfachauswahl (uas anderem MM) in den Eingabemaskeneinstellungen als Tag List angelegt. So kann ich in der Eingabe nicht mehr alle Tags aus dem Feld löschen. Eines bleibt über. Sprich: Ich lösche es und nach dem Speichern ist es wieder in der Tag List. 
Wenn ich auf Checkbox Menü umstelle, kann ich alle entfernen.

**Comment by denunv** [comment]
Kann das Problem leider reproduzieren. Gibt es dazu schon einen Lösungsansatz?

**Comment by xantippe** [comment]
@pointout: aktueller Test mit Contao 3.5.6 und MM core 2.0.0-alpha

=> ich kann alle Zuordnungen löschen...

bitte nochmal testen und ggf. Ticket schließen
