### ISSUE TITLE
Manuelles Sortieren (Eingabemaske) im Backend - seltsames Verhalten

### ISSUE THREAD

**Issue by Znrl** [MetaModels/core#804]
Sortierungseinstellungen (Eingabemaske)

1. Es können mehrere Sortierungseinstellungen als "Is default" markiert werden

2. Manuelles Sortieren  KEIN default (Spalte "sorting")
Es werden nur dann Werte für sorting in die Datenbank geschrieben, wenn die Manuelle Sortierung "default" ist.
Will man Backendusern die Möglichkeit geben die Einträge nach mehreren Kriterien zu Sortieren (manuell, verschiedene Attribute)
wird die manuelle Sortierung nicht gespeichert. Das Umschalten zwischen Sortierungsoptionen funktioniert hier ansonsten.

Als Beispiel habe ich einem Kunden die Möglichkeit gegeben die Einträge im Backend nach dem gleichen Attribut wie das Frontend zu sortieren.
Zusätzlich noch die manuelle Sortierung. Er hat hier damit begonnen die Einträge nach oben zu verschieben, die er als nächstes bearbeiten will.
Grundsätzlich soll die Sortierung aber wie im Frontend also war diese default.
Das führt natürlich dazu, dass seine manuelle Sortierung verloren geht.

Es wäre also denke ich praktisch, wenn die Werte für sorting immer gesetzt werden.

Praktisch wäre das auch für:
https://github.com/MetaModels/attribute_tags/issues/39
Da einem bei Tags die Spalte sorting angeboten wird neigt man dazu diese zu wählen. Das führt dann, weil sorting u.U. keine Werte hat zu den dortigen Fehler (zmindest wohl zu einem Teil).

3. Manuelles Sortieren default
Hier funktioniert das manuelle Sortieren, wählt man aber eine andere Option ändert sich (nach aktualisieren "Die Änderungen anwenden") nichts.
Das manuelle Sortieren "überschreibt" also andere Sortierungsptionen.

**Comment by xantippe** [comment]
Test in Contao 3.5.6  + MM core 2.0.0-alpha8:

* Vergabe "Standard" weiterhin mehrfach möglich
* ob Manuell "Standard" oder nicht - man kann eine manuelle Sortierung anlegen, die auch gespeichert wird...

also bleibt m.E. der "Schönheitsfehler" mit dem Standard
