### ISSUE TITLE
Filter Einzelauswahl mit Standardwert auf eine Mehrfachauswahl mit translated Alias funktioniert nur einsprachig

### ISSUE THREAD

**Issue by pointout** [MetaModels/core#806]
contao 3.2.19
metamodels/core 	dev-tng (85826a73)
contao-community-alliance/dc-general 	dev-develop (3aaa54f1)

2 MM
in einem wird eine Mehrfachauswahl auf das zweite MM als Feld mit einem translated Alias als Alis für die Mehrfachauswahl angelegt.
![einzelauswahl-feld](https://cloud.githubusercontent.com/assets/8960545/7411831/18897888-ef3c-11e4-8e72-496dabbe1f9e.JPG)

Ein FE Filter mit Einzelauswahl auf dieses Feld mit Standardwert:
![einzelauswahl-maincat](https://cloud.githubusercontent.com/assets/8960545/7411847/48a50a32-ef3c-11e4-8a60-a12da9d78101.JPG)

Wenn ich die Seite mit eingebundem Filter und Listing aufrufe, funktioniert das Listing nur in deutsch. Auf der englischen Seite wird auch nach dem deutsche Alias gefiltert:
````
[29] => Array
                (
                    [query] => SELECT DISTINCT item_id FROM tl_metamodel_translatedtext WHERE value LIKE 'leuchten' AND att_id='92' AND langcode IN ('en')
                    [explain] => Array
                        (
                            [id] => 1
                            [select_type] => SIMPLE
                            [table] => tl_metamodel_translatedtext
                            [type] => range
                            [possible_keys] => attvalue,attlang,attitem
                            [key] => attvalue
                            [key_len] => 771
                            [ref] => 
                            [rows] => 1
                            [Extra] => Using where; Using temporary
                        )

                    [returned] => 0 row(s) returned
                )
````
ein englischer Alias existiert.
Funktioniert auch nicht mit auto_item als URL-Parameter.

**Comment by xantippe** [comment]
@pointout die "translated..."-Attribute sind in vielen Fällen nicht merh explizit notwendig, da sich MM selbst um die "Übersetzung" kümmert - bitte mal mit aktuellem MM und "normalem" Alias testen...

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@pointout could you please have a final look at this and tell if your issue has been resolved?
