### ISSUE TITLE
MetaModels breaks automator

### ISSUE THREAD

**Issue by amenk** [MetaModels/core#807]
Steps to reproduce:

me@myhost:~/local-workspace/example/public/system/bin$ php automator -h
- No Output.

I debugged that and found, that it is running into a redirect which does an exit.

This should not only be fixed for the automator but for all (in our case a custom) shell scripts that might run.

![screenshot_selection_005](https://cloud.githubusercontent.com/assets/1087128/7493728/8f007bda-f403-11e4-85d7-07e07a9bfe3c.png)

**Comment by discordier** [comment]
I have no way to tell apart that your Backend is not the Backend but a shell script.
I could however deactivate MetaModels in PHP_SAPI cli.
This will however break the use of MetaModels from shell scripts altogether.

I again hate it that we do not have an additional TL_MODE like "automator" or "cron"... *sigh*

**Comment by discordier** [comment]
sidenote: the redirect is not the fault of MetaModels but of the Contao core which redirects to the login screen and exits when trying to authenticate the user. This issue keeps biting me every few months.

**Comment by blackbee** [comment]
Hi everybody,

can you explain, which file and which line in the core is producing this issue? So maybe I can takie a look at the line and may be put a fix for me inside. I need the Cron Jobs and the automator functions.

Background:
I wondered why several Cron Job Tasks not working anymore. So i tried to deactivate all extensions and tried to locate the problem, which results this redirect. And i consered that Metamodels - like described above - is producing the redirect, which stops all Cron Job Tasks to work.

**Comment by discordier** [comment]
The problem lies within `\BackendUser::authenticate()`. That one is redirecting to the login screen when no user is authenticated.

**Comment by discordier** [comment]
Could be fixed with 7932e3c9c4eea430f6bca0588f7fa2077f47609b, thanks to @sheeep.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@amenk could you please have a final look at this and tell if your issue has been resolved?
