### ISSUE TITLE
"Ergebnisse zählen" gibt nur leere Klammern aus

### ISSUE THREAD

**Issue by JT-007** [MetaModels/core#808]
Hallo zusammen,

ich habe das Problem, dass bei Mehrfachauswahl Filtern welche auf ein Tag Feld verweisen in der Klammer nach dem Label nichts ausgegeben wird obwohl die Option "Ergebnisse zählen" aktiv ist.

System:
Contao 3.4.5
DCG 2.0.0-beta23
metamodels/core dev-tng (1f4fd69b)
metamodels/bundle_all 1.0.1

Lg,
JT

**Comment by JT-007** [comment]
Ich habe nun raus gefunden weshalb das Ergebnisse zählen nicht korrekt funktioniert. Um beim Filtern in der URL den Alias des Eintrags zu verwenden habe ich bei der Filtereinstellung "Alias der Mehrfachauswahl" den alias genommen. Die Zuweisung der Anzahl erfolgt aber, soweit ich dies nun gesehen habe, über die ID des Eintrags. Wenn man bei "Alias der Mehrfachauswahl" die ID wählt wird der Counter zwar korrekt ausgegeben aber es wird dann für die URL auch die ID herangezogen. Idealerweise sollte der Counter auch mit einem Aliasfeld funktionieren.

**Comment by discordier** [comment]
See MetaModels/attribute_tags/issues/26.
