### ISSUE TITLE
Fehler beim Erstellen eines Alias eines Metamodels

### ISSUE THREAD

**Issue by elebar** [MetaModels/core#809]
MacKP bat mich ein Ticket zu erstellen. Habt Nachsicht, es ist mein erstes.
Ich habe einen neuen Stand Contao 3.2.20 mit MetaModels aufgebaut, via ftp, und dort ein MetaModel Orte angelegt. Beim Erfassen des Attributs Alias bekam ich schon beim Speichern und schließen den Fehler:
<pre><code>Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php on line 139
#0 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php(70): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer::fromSerialized('')
#1 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php(50): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->checkLanguage(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(121): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#8 contao/main.php(137): Contao\Backend->getBackendModule('metamodels')
#9 contao/main.php(288): Main->run()
#10 {main}</code></pre>

Er hat den Alias aber trotzdem angelegt.
Ich habe dann alle Felder weitererfasst bis zum 
    MetaModels
    Alle Eingabemasken für "Orte"
    Sorting and grouping in "BE Erfassung Orte"
und dort die alphabetische Sortierng angelegt.

Wenn ich nun dort oben den Header bearbeiten möchte, ist der Fehler auch da.
Den gleichen Fehler bekam ich bei einem update einer Contao 3.2.13 auf Contao 3.2.20.
Der Ursprung der Geschichte: https://community.contao.org/de/showthread.php?56963-MetaModels-Fehler-nach-contao-update-auf-3-2-20&p=369668#post369668

**Comment by discordier** [comment]
Das Problem sollte eigentlich mit dem aktuellen DCG nicht mehr auftreten, oder?

**Comment by xantippe** [comment]
aktueller Test: MM core 2.0.0-alpha8
sowohl bei Installation per Composer als auch "per FTP" kann ich das Verhalten nicht (mehr) feststellen...

Ticket kann m.E. geschlossen werden
