### ISSUE TITLE
!metamodels-tng-branch config.php produces invalid HTML ID

### ISSUE THREAD

**Issue by Aybee** [MetaModels/core#810]
```php
$GLOBALS['BE_MOD']['Nightly builds']['BackendModule_446df1d8536436f29587dcf24ddac2f8'] = array(
	'callback' => 'BackendModule_446df1d8536436f29587dcf24ddac2f8',
	'icon'     => 'system/themes/default/images/modules.gif',
);
```
results in
```html
<li id="Nightly builds" class="tl_parent">
```
You can use this one
```php
$GLOBALS['BE_MOD']['nightlyBuilds']['BackendModule_446df1d8536436f29587dcf24ddac2f8'] = array(
	'callback' => 'BackendModule_446df1d8536436f29587dcf24ddac2f8',
	'icon'     => 'system/themes/default/images/modules.gif',
);
$GLOBALS['TL_LANG']['MOD']['nightlyBuilds'] = 'Nightly Builds';
```
*Wird !metamodels-tng-branch eigentlich hier auf github verwaltet, oder kann ich das nicht finden, weil das dynamisch erzeugt wird? Kann ich bei der manuellen Installation ohne Composer auch auf diesen Ordner verzichten?*

**Comment by discordier** [comment]
1. Is this still valid? If so, can you explain in more detail what the problem is? Is the backend menu broken?
2. How to reproduce? For me it renders just fine in the backend.
3. The module `!metamodels-tng-branch` is generated by the nightly build job via https://github.com/cyberspectrum/nightly-builder and therefore has no custom repository on it's own.

**Comment by Aybee** [comment]
Do you have this ID in BE? "Nightly builds"? This is an invalid ID.

Seems that the ID gets build from this key `$GLOBALS['BE_MOD']['Nightly builds']`. That's why I proposed to rename this key to `$GLOBALS['BE_MOD']['nightlyBuilds']`.

I can not reproduce why and in which situation I stumbled upon this invalid ID.

**Comment by discordier** [comment]
You are right, there is no language key defined.
See https://github.com/cyberspectrum/nightly-builder/blob/dd1cf6f55cb446ce501f97a181c2ccce4295f43a/src/CyberSpectrum/Command/BuildCommand.php#L803
https://github.com/cyberspectrum/nightly-builder/blob/dd1cf6f55cb446ce501f97a181c2ccce4295f43a/src/CyberSpectrum/Command/BuildCommand.php#L917

**Comment by discordier** [comment]
I created an issue at cyberspectrum/nightly-builder#8
