### ISSUE TITLE
Rendereinstellung: Probleme beim Kopieren

### ISSUE THREAD

**Issue by AgentCT** [MetaModels/core#811]
1. Problem
   Das Kopieren der Rendereinstellung ist möglich und funktioniert auch fast fehlerfrei, jedoch werden die enthaltenen Felder nicht mit kopiert. Die neue Rendereinstellung bleibt leer. Das ist suboptimal, die Kopierfunktion ist somit eigentlich nutzlos ;)
2. Verbesserungsvorschlag
   Außerdem müsste eine Bezeichnung wie "Kopie" an die neue Rendereinstellung gefügt werden, sonst sucht man bei großen Projekten nach der Kopie.... 

Verwendete Version:
Metamodels dev-tng 1f4fd69b über Composer installiert

**Comment by zonky2** [comment]
Stand C 3.5.12, MM a11, DCG b36

zu 1: deep copy ist im DCG noch in Arbeit....

zu 2: beim Kopieren kommt man nun direkt in die Bearbeitungsmaske und kann (sollte) die Bezeichnung ändern

**Comment by discordier** [comment]
@zonky2 Dupe of contao-community-alliance/dc-general#191?

**Comment by zonky2** [comment]
it´s true..
@AgentCT pls observe https://github.com/contao-community-alliance/dc-general/issues/191
