### ISSUE TITLE
Sortierung wird bei Rendereinstellung nicht übernommen

### ISSUE THREAD

**Issue by AgentCT** [MetaModels/core#812]
Sortiert man die Reihenfolge der einzelnen Attribute bei MM unter Attribute, wird die Sortierreihenfolge bei den Rendereinstellung nicht übernommen. Stattdessen werden die Felder (Attribute) der Reihenfolge nach angezeigt, wie sie ursprünglich angelegt wurden.

Könnte Ihr bitte die Sortierreihenfolge bei der Anlage der Attribute unter Rendereinstellung übernehmen.

**Comment by xantippe** [comment]
aktueller test: core 2.0.0-alpha8

Reihenfolge der Attribute wird übernommen - siehe Screenshots (Abteilung)

![shot21](https://cloud.githubusercontent.com/assets/1045318/12017760/1ca7e638-ad5b-11e5-9cf4-730f0a4f5547.jpg)

::::::::::::::::::::

![shot22](https://cloud.githubusercontent.com/assets/1045318/12017764/259b6378-ad5b-11e5-9d1b-e203402c70a9.jpg)

kann m.E. geschlossen werden
