### ISSUE TITLE
BE Listenansicht anpassen

### ISSUE THREAD

**Issue by mhammerschmidt** [MetaModels/core#813]
Ich möchte im Backend in der Tabelle der Metamodels die Ansicht der Einträge zweispaltig erzeugen.
Mit Typ und Name als Spaltenüberschrift.

Durch das Anpassen des entsprechenden Templates bekomme ich die Ansicht zweispaltig. Allerdings steht die Bezeichnung und der Typ jedes Eintrages immer dabei und ich bekomme die Spaltenüberschrift nicht hinein.

Wenn ich in der DefaultListingConfig.php getShowColums() true zurückgebe bekomme ich eine zweispaltige Liste allerdings ohne Inhalt. Gibt es eine Möglichkeit dies dort für eine/zwei Listen anzupassen oder bin ich dort komplett falsch?

**Comment by MacKP** [comment]
Hallo @mhammerschmidt Fragen bitte im Forum klären.
(Ich würde da ja mit CSS Sachen ausblenden etc.).

Viele Grüße

**Comment by mhammerschmidt** [comment]
Wäre es möglich dieses Problem in MM 2.1 auf zu nehmen?
https://community.contao.org/de/showthread.php?57312-BE-Listenansicht-anpassen

**Comment by tim-bec** [comment]
Da wir aktuell selbst keine Verwendung für dieses Feature haben, setze ich das mal auf die "Feature" Liste. Wir haben leider immer noch zu viele Baustellen um mit der 2.1 überhaupt anfangen zu können.

**Comment by xantippe** [comment]
@MacKP: mit CSS kommt man da nicht so richtig ran - da müsste man m.E. schon heftig mit Javascript das DOM umbauen...

@tim-bec: ich hätte für die Tabellenansicht immer eine Verwendung - im Forum gabe es dazu auch schon von verschiedener Seite Anfragen.

Bei den meisten "CRUD-Systemen" gibt es als Standard eine Tabellenansicht + "Arbeitsspalte" rechts mit Bearbeiten, Löschen usw. - auch ein variables Ein/Aus-Blenden von Spalten ist hier möglich...

z.B. http://www.yiiframework.com/demos/blog/index.php/post/admin
Login: demo | demo

**Comment by amenk** [comment]
Die showColumns() Geschichte gibt es ja auch schon in Contao bei normalen DCA und im DcaGeneral ist das in DefaultListingConfig ja auch schon vorgesehen.

**Comment by tim-bec** [comment]
Wir nehmen Pull-Requests liebend gern an :-)

**Comment by amenk** [comment]
Ja ... wir haben nicht so viel Erfahrung mit dem MetaModels Code. Für wie aufwändig haltet ihr das ganze? Evtl. würden wir auch dafür bezahlen.

**Comment by amenk** [comment]
Habs schonmal geschafft die Header ausgeschrieben anzuzeigen.
https://github.com/contao-community-alliance/dc-general/pull/130

Sind aber noch zu viele. Felder wie "sorting" sind auch dabei.

Und ich muss noch rausfinden, wie ich \ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\View\DefaultListingConfig::getShowColumns beeinflussen kann. Momentan hab ich da return true; reingeschrieben.

Außerdem werden die Feldwert nicht angezeigt.

**Comment by amenk** [comment]
Noch einer: https://github.com/contao-community-alliance/dc-general/pull/131

**Comment by amenk** [comment]
Könnt ihr dieses Issue bitte wiedereröffnen?

**Comment by amenk** [comment]
I am building that in https://github.com/MetaModels/core/pull/827

**Comment by xantippe** [comment]
mit der Einstellung "Anzeige in Tabellenform" in den Eigenschaften der Eingabemaske funktioniert die Tabellenanzeige sehr gut 
kleiner Bug: wenn bei Sortierung eine Gruppierungseinstellung ausgewählt wurde, kommt keine Tabelle - siehe #936

Issue kann m.E. geschlossen werden

![shot20](https://cloud.githubusercontent.com/assets/1045318/12017639/d519193c-ad59-11e5-8f0e-43cd492171c7.jpg)
