### ISSUE TITLE
Order of MetaModels within existing backend modules

### ISSUE THREAD

**Issue by fritzmg** [MetaModels/core#815]
I realize that it's probably not easily possible to truly customize the exact order where the MetaModels should appear in existing backend modules (e.g. within the content module) - however, in past versions of MetaModels, the MetaModels were inserted at the bottom of the the module (as evidenced by the old Wiki entry: http://de.contaowiki.org/images/de/1/1d/Mm_backend_erfassen.png) - now they are inserted at the top.

This issue comes up in the forum every now and then I think most people would prefer it, if the MetaModels were inserted after all the other entries within an existing backend module. So that the existing order of content modules is not disrupted by MetaModels.

**Comment by xantippe** [comment]
1+

**Comment by discordier** [comment]
Problem here is, that then we would effectively kill any `dcaconfig.php` manipulations.

The problem here is, that we are merging two arrays here, the BE config and the config built by MetaModels (and most likely obtained from the cache).
Right now we are using this for every backend menu section:
```php
$GLOBALS['BE_MOD'][$section] = array_merge_recursive($entries, $GLOBALS['BE_MOD'][$section]);
```
If we change the parameter order, we would end up having the desired order, however we will loose any custom information that has been added to the `mm_*` backend modules from other extensions/`dcaconfig.php`.
Solution to this would be to walk each backend module by hand.

**Comment by xantippe** [comment]
und was ist bei
```$GLOBALS['BE_MOD'][$section] = array_merge_recursive($GLOBALS['BE_MOD'][$section], $entries); ```
?

**Comment by discordier** [comment]
As written above, we will overwrite the settings from other extensions/`dcaconfig.php` then.

**Comment by fritzmg** [comment]
> Problem here is, that then we would effectively kill any dcaconfig.php manipulations.

Hm, I don't understand, as far as I have tested it, we cannot alter the MetaModels DCA anyway in any dcaconfig.php. Which manipulations are you referring to?

**Comment by discordier** [comment]
You should still be able to alter stuff via dcaconfig.php. It just isn't the recommended way anymore as we have events now for building the data containers.

**Comment by fritzmg** [comment]
Actually no - at least not always. If you use the metamodelsboilerplate for instance and insert something like
```php
var_dump( $GLOBALS['BE_MOD']['metamodelsboilerplate'] );
```
into your `dcaconfig.php`, then you will notice the following behavior (at least when the internal cache is disabled):

* when you log into the backend, i.e. when you are on the start page of the backend, the array will be empty
* if you click on _Articles_, the array will be filled with the metamodels
* if you click on the file manager, the array will be empty again

So, depending on where you are in the backend, the inserted MetaModels backend modules are sometimes not editable via `dcaconfig.php`.

As far as I have observed it there are no MetaModels present when the dcaconfig.php is processed if you are on a page in the backend, that did not need to load a DCA. Examples are

* the file manager
* the MetaModels support page
* the maintenance module
* the package manager
* the system check module of syncCto
* the autoload creator
* the missing labels module

**Comment by discordier** [comment]
I guess you are mixing things up here a little.

I was referring to manipulating the dcas via dca_config (like changing input fields etc.) and not modifying the backend menu after MetaModels has been injected.

This is a race condition here, as if we would load the dca_config after building our menu, you will not be able to create a new backend section via dca_config (like in the boilerplate) to host your MetaModels backend modules.

**Comment by zonky2** [comment]
At the moment the items are inserted at the end - the Contao API does not provide a way to place itself explicitly between the items.

A better way is certainly to create your own section using the "boilerplate".
