### ISSUE TITLE
Good news: Compatibility

### ISSUE THREAD

**Issue by seaneble** [MetaModels/core#829]
I did some tests with MetaModels/core dev-tng on Contao/core 3.5.0 and did not run into any unexpected issues. I'm using quite a lot of attribute types and filters.

All the bugs I encountered have already been there in earlier versions. I would recommend to mark MetaModels as compatible with the new Contao LTS version, so that updates will be available.

**Comment by tim-bec** [comment]
\o/ thanks!

**Comment by discordier** [comment]
:+1:

**Comment by tim-bec** [comment]
We bumped the core and all attributes & filters, tags are still outstanding but will follow in a some days. thanks again for testing.
