### ISSUE TITLE
File attribute : pb if filepicker checked when not present

### ISSUE THREAD

**Issue by JLBA** [MetaModels/core#830]
Hi,
With Contao 3.2.20 and MM 1.1.

I've created a file attribute and checked to use filepicker instead of filetree if possible. But in C3.2, the isn't filepicker. 
Then, when creating or modifying a record in BE, I could select an image as usual but the field only show the filepath (not the thumbnail) and doesn't save it. Sonthe field stays empty and so no picture is displayed in BE or FE.

**Comment by MacKP** [comment]
MM 1.1 is totaly outdatet. So you should update your MM and test it again (don't forget to clear your contao cache!).

**Comment by JLBA** [comment]
Outdate but still on the website and working with my Contao 3.2.20 install.

I can't install MM 2 as I want to use syncCto too but it seems there is a conflict between them. I think the pb comes from dc_general version.

So am I waiting for MM 2 stable version. Or can you tell me how to install MM and syncCto together ?

Thanks.


-- 
JL Barts-Andreetto

**Comment by MacKP** [comment]
Erm.. you see it is not realy working ;-)
Try to use the tng from syncCto also. Then it would work.
When you post Bugs from 1.1 no one will do anything about that.. because these are mostly fixed in the newer MM Versions.

regards

**Comment by JLBA** [comment]
Ok. I’ll try. What is the TNG ? And where do I find it ?

Thanks


JL Test
jltest@free.fr

**Comment by MacKP** [comment]
Here you can find the tng Version from SyncCto -> https://github.com/menatwork/syncCto/tree/tng

regards

**Comment by JLBA** [comment]
Thanks. What does tng meen ?

JL Test
jltest@free.fr

**Comment by MacKP** [comment]
tng = the next generation ;-)

**Comment by JLBA** [comment]
Ok. Like with Star Trek ;-)) Thanks again. 

Last question : do MM 2 tng and syncCto tng work with Contao 3.4 or 3.5. When I tried to install them with composer, one of them (I think it was MM) was noticed about conflict with 3.4.


JL Test
jltest@free.fr

**Comment by tim-bec** [comment]
@JLBA - there is a conflict with mm and contao 3.4 - contao 3.5 will work in a few days. i know, it's currently a bit confusing and annoying but we are working to get rid of it.

**Comment by JLBA** [comment]
Thanks Tim.

Will the conflict be solved with 3.4 or would it be necessary to upgrade to 3.5.
Do you know the conflict with syncCto as I mentionned above (because of dc_general version, I suppose) ?

JL Test
jltest@free.fr

**Comment by tim-bec** [comment]
the conflict with 3.4 will not be solved. we'll stick to LTS version compatibility. 
I know the conflicts with synccto - but the synccto TNG branch or 3.0 beta works totaly fine with metamodels TNG.

**Comment by JLBA** [comment]
-- 
JL Barts-Andreetto

> Le 3 juil. 2015 à 10:11, Tim Becker <notifications@github.com> a écrit :
> 
> the conflict with 3.4 will not be solved. we'll stick to LTS version compatibility. 
Ok.
> I know the conflicts with synccto - but the synccto TNG branch or 3.0 beta works totaly fine with metamodels TNG.
So under Contao 3.2 for the moment. Thanks for these answers I was looking for weeks (but found nowhere do precisely) !!

**Comment by discordier** [comment]
The conflict was only with `3.4.0` due to a bug in Contao and has been resolved with `3.4.1` so there really should be no conflict (at least from MM side, do not know about syncCto though).
