### ISSUE TITLE
Tag Core and Attributes

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#831]
We need to tag all attributes, therefore we need to merge & tag a lot attributes:

```
Ziel:
master ( 2.0.x-dev )
develop ( 2.1.x-dev )
```

```
Zum erstellen des alpha release wie folgt Vorgehen:
git checkout dev
git merge master
git checkout contao3
git merge dev
git tag -s 1.1.0-alpha1 # <-- um eine Referenz auf den alten Stand zu behalten.
git checkout tng
git merge contao3 # <-- hier kann es zu merge conflicts kommen
git checkout master
git merge tng
vi composer.json # hier branch aliase anpassen, s.o.
git add composer.json && git commit -m "Change branch aliases."
git checkout -b develop
git checkout master
git tag -s 2.0.0-alpha1
git checkout develop
git merge --no-ff 2.0.0-alpha1 -m "Merge tag 2.0.0-alpha1 to develop."
git push --all && git push --tags
git push origin :refs/heads/contao3
git push origin :refs/heads/tng
git push origin :refs/heads/dev
```

- [X] https://github.com/MetaModels/core (depends on #824 and contao-community-alliance/dc-general#133)
- [x] https://github.com/MetaModels/attribute_alias
- [X] https://github.com/MetaModels/attribute_checkbox
- [X] https://github.com/MetaModels/attribute_color
- [X] https://github.com/MetaModels/attribute_combinedvalues
- [X] https://github.com/MetaModels/attribute_country
- [X] https://github.com/MetaModels/attribute_decimal
- [X] https://github.com/MetaModels/attribute_file (Needs https://github.com/MetaModels/attribute_file/pull/46 to be merged first)
- [X] https://github.com/MetaModels/attribute_geoprotection (Needs to be fixed by @stefanheimes  first)
- [X] https://github.com/MetaModels/attribute_langcode
- [X] https://github.com/MetaModels/attribute_longtext
- [X] https://github.com/MetaModels/attribute_numeric
- [X] https://github.com/MetaModels/attribute_rating
- [X] https://github.com/MetaModels/attribute_select
- [X] https://github.com/MetaModels/attribute_tabletext
- [X] https://github.com/MetaModels/attribute_tags
- [X] https://github.com/MetaModels/attribute_text
- [X] https://github.com/MetaModels/attribute_timestamp
- [X] https://github.com/MetaModels/attribute_translatedalias
- [X] https://github.com/MetaModels/attribute_translatedcheckbox
- [X] https://github.com/MetaModels/attribute_translatedcombinedvalues
- [X] https://github.com/MetaModels/attribute_translatedfile
- [X] https://github.com/MetaModels/attribute_translatedlongtext
- [x] https://github.com/MetaModels/attribute_translatedselect (Needs https://github.com/MetaModels/attribute_translatedselect/pull/8 to be included by @stefanheimes  first)
- [X] https://github.com/MetaModels/attribute_translatedtabletext
- [X] https://github.com/MetaModels/attribute_translatedtags
- [X] https://github.com/MetaModels/attribute_translatedtext
- [X] https://github.com/MetaModels/attribute_translatedurl
- [X] https://github.com/MetaModels/attribute_url
- [X] https://github.com/MetaModels/filter_checkbox
- [X] https://github.com/MetaModels/filter_fromto
- [X] https://github.com/MetaModels/filter_perimetersearch
- [X] https://github.com/MetaModels/filter_range
- [X] https://github.com/MetaModels/filter_register
- [X] https://github.com/MetaModels/filter_select
- [X] https://github.com/MetaModels/filter_tags
- [X] https://github.com/MetaModels/filter_text

**Comment by stefanheimes** [comment]
GeoProtection is ready.

**Comment by discordier** [comment]
@stefanheimes What about translatedselect?

**Comment by xantippe** [comment]
@stefanheimes was ist mit "translatedselect"? ist der letzte unkt und dann könnte man das Ticket schließen...

**Comment by stefanheimes** [comment]
Done,... and now... where is the beer and let the party start.

**Comment by discordier** [comment]
\o/

**Comment by xantippe** [comment]
=> dann kann ich das schließen?
