### ISSUE TITLE
Issue with / in text field used as url parameter

### ISSUE THREAD

**Issue by JLBA** [MetaModels/core#833]
Hi,
Contao 3.4.5 and MM-tng.

I got a text attribute where content will be like 2013/2014, 2014/2015 and so on. The issue is when using this field as url parameter in filter. The url last by …/2013/2014.html and so generates a non existing error page. 
Is there a solution as It seems not possible to use alias instead of text attribute.
Thanks.

**Comment by discordier** [comment]
Why is this not possible?
How is your URL parameter generated?
What kind of filter do you use?

We need more information on your setup to be of help here.

**Comment by JLBA** [comment]
Hi Christian,

Here are the answers : 

One MM : mm_events to manage… events. with attributes : Event_name (text) and Event_alias (alias base on Event_name) 

In site structure : one page for the list and one for the détail.

In list page article, 1 MM_List content element with FE - Events list rendersetting [all attributes active ;  JumpToPage : Event detail page ; Filter : that is the pb - see further]
In Detail page article, 1 MM_list content element with  FE - Event detail rendersettings (all attributes active).

For JumpTo Page filter, I’ve tried a spécific filter (jumpto_filter)  : 
- with single selection : URL parameter : empty ; Attribute => event_name but each space is rendered by + in the url ; then I get a “page non exists” error.
- with simple_lookup setting : attribute = event_alias ; url parameter : empty (or not) ; still the same problem : page doesn’t exists.

How can I simply link my list page to my detail page (just as we did it in Catalog) ?

Thanks.


JL Test
jltest@free.fr

**Comment by discordier** [comment]
Setup the filter setting to contain a simple-lookup on attribute alias and url parameter "auto_item".
Attach this filter setting on the list render setting as jump to filter and as filter in the reader module.

**Comment by JLBA** [comment]
This works ! I didn’t understand the filter should be attached to the reader module too.

Thanks.


JL Test
jltest@free.fr
