### ISSUE TITLE
No output when alias of second language is the same as the first language

### ISSUE THREAD

**Issue by Teetrinker** [MetaModels/core#834]
I have a MM installation from August 2014. I deleted all MM modules and installed the nightly build of today (2015-07-06).
Still this issue:
If the alias after which is filtered is the same as the alias in the main language, no items are shown. If I change the alias, it works. (Strange issue: in a third language, it works with the same alias).

example URL: /[metamodel]/alias

I can provide access to the installation if needed.

**Comment by xantippe** [comment]
@Teetrinker bitte prüfen ob das Verhalten bei aktuellem MM noch vorhanden ist - an den Bereich "Mehrsprachigkeit" hat(te) sich einiges geändert...

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Teetrinker could you please have a final look at this and tell if your issue has been resolved?
