### ISSUE TITLE
Rendertemplates not found in theme folders

### ISSUE THREAD

**Issue by pju-** [MetaModels/core#837]
Using Contao 3.5.0
Current Nightly (metamodels/core    dev-tng @ f72a24     2015-07-13 11:44:00)

I have my mm templates in a theme folder. I can select them just fine in the settings. The template folder is set in the theme and has proper ownership & rights (even tried 777).

If I want to enter items however, I get an error message:

For attribute templates I get a message in the backend list (not an error, just instead of the attribute output):  Template not found (it is maybe within a unreachable theme folder?)

If it's a render template, I get the following message.

````
Fatal error: Uncaught exception RuntimeException with message Could not find template metamodel_unrendered_test.html5 thrown in system/modules/metamodels/classes/src/MetaModels/Render/Template.php on line 241

#0 system/modules/metamodels/classes/src/MetaModels/Render/Template.php(296): MetaModels\Render\Template->getTemplate('metamodel_unren...', 'html5', true)
#1 system/modules/metamodels/classes/src/MetaModels/DcGeneral/Events/MetaModel/RenderItem.php(109): MetaModels\Render\Template->parse('html5', true)
#2 [internal function]: MetaModels\DcGeneral\Events\MetaModel\RenderItem::render(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(168): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent))
#5 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/FormatModelLabelSubscriber.php(87): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent))
#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FormatModelLabelSubscriber->handleFormatModelLabel(Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(168): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#9 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(243): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#10 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(264): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->setListViewLabel(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), NULL)
#11 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(381): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->viewList(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection))
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->showAll(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(145): call_user_func_array(Array, Array)
#14 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(168): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#16 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(121): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#18 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#19 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#20 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_te...')
#21 contao/main.php(20): Contao\BackendMain->run()
#22 {main}
````

**Comment by discordier** [comment]
You should get the same message for the pre/unrendered templates, this is indeed a bug.

**Comment by pju-** [comment]
I should get the same message as for the attribute templates? Are templates in theme folders not supported anymore?

Everything works fine in the frontend btw.

**Comment by discordier** [comment]
They are supported but, as you state ONLY in the Frontend. This is a Contao limitation as in the backend there is no Theme context and therefore the templates from a theme are not reachable.

To make templates in a sub directory reachable, you have to define the template folder within your theme (as you have done for the Frontend) and then Contao knows it should look in that folder. In the Backend this information is simply not available at all.

**Comment by pju-** [comment]
I see. Still – if I set the pre/unrendered tempalte for a render setting that is only displayed in the frontend, I still get the same error. Shouldn't that work? It worked before for me (Contao 3.2.20)

**Comment by discordier** [comment]
You are getting this error in the frontend on a page using a layout from the theme the directory the template is contained within?

**Comment by pju-** [comment]
No, sorry to be unclear. I'm getting the error in the backend, but the rendering template is used for a frontend module. The backend display is using the standard rendering template. Before the update to Contao 3.5, this used to work just fine.

**Comment by discordier** [comment]
I doubt it strongly, this has never been possible...

**Comment by pju-** [comment]
Hm, just to be sure that we get each other, here are my settings from a Contao 3.2 installation where it worked just fine.

<img width="720" alt="bildschirmfoto 2015-07-16 um 17 33 06" src="https://cloud.githubusercontent.com/assets/5202770/8727664/25e0b802-2be1-11e5-9db7-2b229e82f83e.png">

<img width="726" alt="bildschirmfoto 2015-07-16 um 17 33 43" src="https://cloud.githubusercontent.com/assets/5202770/8727665/25e7d204-2be1-11e5-9ef4-5ecbf4f7c819.png">

<img width="714" alt="bildschirmfoto 2015-07-16 um 17 33 52" src="https://cloud.githubusercontent.com/assets/5202770/8727666/25ebded0-2be1-11e5-9a38-88cf1a901f54.png">

**Comment by discordier** [comment]
And there you go, this rendersetting is used in the frontend (at least the name suggests so).
I think you have another rendersetting which is named "backend" or "backend list" and either marked as "is default" or hooked to your user via the dca combinations (the very last icon in the metamodel list).

For the frontend this works just fine but when rendering in the backend, it borks.

**Comment by discordier** [comment]
The exception should be gone by now and you should get the normal error message.

**Comment by pju-** [comment]
Missing "is default" indeed. Sorry for the false alarm, no idea how that happened.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@pju- could you please have a final look at this and tell if your issue has been resolved?

**Comment by pju-** [comment]
This has indeed been resolved
