### ISSUE TITLE
Metainformationen aus Dateiverwaltung

### ISSUE THREAD

**Issue by mlwebworker** [MetaModels/core#839]
Bei Auwahl von einer oder mehrere Dateien, ist es möglich auf die Metainformationen der Dateiverwaltung zuzugreifen.
Bei Auswahl eines kompletten Ordners gibt es keinen Zugriff auf die Metainformationen (für "caption" wir der "title" verwendet und "title" ist der Dateiname).

**Comment by discordier** [comment]
Kann das jemand reproduzieren? Bei mir geht es.

**Comment by mlwebworker** [comment]
Das Problem schein nur in Windows aufzutreten. Als Ursache werden von discordier mixed pathes vermutet (siehe dazu auch Contao Forum https://community.contao.org/de/showthread.php?58246-Metamodels-und-Metainformationen-aus-Dateiverwaltung&p=377852&viewfull=1#post377852)

**Comment by discordier** [comment]
von dir im Forum gegebene Ausgabe, ist die aus dem file template?
Wenn ja, was steht in der Datenbanktabelle `tl_files`?

**Comment by mlwebworker** [comment]
Ja ist aus dem file template. In tl-files ist die Angabe unter path: files/content/test_metainfos/2002_Kroatien_05.jpg. Hatte da auch kein Problem erwartet weil ja es ja bei Direktwahl der Datei funktioniert. Ich verlinke hier noch mal das Bild aus dem aus dem Eröffnungsthread. 
![2015_07_19_metainformationen_metamodels](https://cloud.githubusercontent.com/assets/3602676/8836378/c4804822-30c0-11e5-8677-cbda98cdcf12.jpg)
Dort sind beide Varianten zu sehen (einmal Direktauswahl der Dateien und einmal Auswahl über den Ordner).
Das Problem muss m.E. irgendwo beim Auslesen der Einzelbilder aus dem Ordner passieren.
Ich hab natürlich auch getestet wie sich die ganz normale Galerie vom contao-core verhält. Das klappt alles wie erwartet.

**Comment by mlwebworker** [comment]
Ich habe heute in meiner Liveumgebung den identischen Test aufgesetzt. Da funktioniert alles wie es soll. Damit ist Windows mal wieder der wahre Schuldige.

**Comment by xantippe** [comment]
@mlwebworker ... dann Ticket bitte schließen
