### ISSUE TITLE
1.1-alpha conflict für 3.5

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#840]
Die 1.1-alpha ist unter 3.5 aktuell installierbar, sorgt aber für ne weiße Seite, wir sollten einen conflict eintragen
```
"conflict": {
    "contao/core": "3.4.0",
    "contao/core": "3.5.0"
  },
```

**Comment by discordier** [comment]
Oha, ist das mit dem 3.2 evtl. schon ein Problem? Oder ging es bis 3.3?

**Comment by tim-bec** [comment]
3.3 nie getestet, unter 3.2 hab ichs selbst grad noch am laufen

**Comment by discordier** [comment]
aktuell ist es fyr `"contao/core": ">=2.11,<4.0",` freigegeben.

Ich tendiere dazu, es generell nur noch auf `<=3.2` laufen zu lassen, hat glaub ich nie jemand getestet mit neuerem.

**Comment by tim-bec** [comment]
doit

**Comment by discordier** [comment]
See b39c8744c3ea474e9f3d9127ed44a36f17da626f.
