### ISSUE TITLE
Fatal error Kind-Tabelle

### ISSUE THREAD

**Issue by 1stof8** [MetaModels/core#842]
Habe gerade ein Update durchgeführt und bekomme beim editieren der Kindtabelle einen Fehler angezeigt. Kann mir jemand die Fehlermeldung übersetzen oder ist das ein Bug im Core?

System:
Contao 3.4.5
metamodels/core dev-tng (b46d09d5)
metamodels/bundle_translated 1.0.2

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Property bsp_header is not registered. thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/DefaultPropertiesDefinition.php on line 110
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php(252): ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\DefaultPropertiesDefinition->getProperty('bsp_header')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php(581): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ParentView->renderFormattedHeaderFields(Object(MetaModels\DcGeneral\Data\Model))
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php(641): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ParentView->viewParent(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), Object(MetaModels\DcGeneral\Data\Model))
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ParentView->showAll(Object(ContaoCommunityAlliance\DcGeneral\Action))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(141): call_user_func_array(Array, Array)
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(121): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#11 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_ko...')
#12 contao/main.php(20): Contao\BackendMain->run()
#13 {main}
```

**Comment by discordier** [comment]
Ich kenne dein Attribut `bsp_header` nicht.Da ist es also schwer zu raten.

**Comment by 1stof8** [comment]
bsp_header ist ein Translatedtext

**Comment by 1stof8** [comment]
Wenn ich den Render mode statt "Parented" auf "Flat" stelle kann ich die Liste sehen ist aber natürlich ungünstig beim Einpflegen von Inhalten.

**Comment by discordier** [comment]
Lass dir deine Konfiguration doch bitte nicht so aus der Nase ziehen.
Welche MetaModels hast du, welche Attribute sind darin, wer ist kind von wem. etc.

**Comment by 1stof8** [comment]
### mm_Kompetenzen:
kompetenzen_titel [translatedtext]
kompetenzen [translatedalias]
kompetenzen_subline [translatedtext]
kompetenzen_langtext [translatedlongtext]
kompetenzen_img [translatedfile]
kompetenzen_teaser [translatedlongtext]

### mm_kompetenzen_bsp:
bsp_header [translatedtext]
bsp_header_s [translatedtext]
awbsp_subheader [translatedtext]
awbsp_alias [translatedalias]
awbsp_desc [translatedlongtext]
awbsp_img [translatedfile]

#### mm_kompetenzen_bsp ist Kind-Teabelle von mm_Kompetenzen

### Einstellungen mm_kompetenzen_bsp:
Integration - Als Kind-Tabelle
Name der Elterntabelle mm_kompetenzen
Render mode Parented
Allow editing of items checked
Allow creating of items checked
Allow deleting of items checked

### Einstellungen mm_kompetenzen:
Integration - Unabhängig
Render mode Flat
Allow editing of items checked
Allow creating of items checked
Allow deleting of items checked

**Comment by asaage** [comment]
Ich bekomme hier den selben Fehler beim Versuch Kindelemente zu editieren.
* metamodels/core	dev-tng @ b46d09
* Contao 3.5.0
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Property headline is not registered. thrown in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/DefaultPropertiesDefinition.php on line 110
```

**Comment by xantippe** [comment]
dito
Contao 3.5.2
MM TNG 14.08.2015 (23:25h)

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Property speise is not registered. thrown in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/DefaultPropertiesDefinition.php on line 116
```

**Comment by asaage** [comment]
ja - alle Attribute im BE Rendersetting verstecken ist auch keine Option :smile:

**Comment by xantippe** [comment]
?? sorry - habe ich nicht verstanden :-(

**Comment by asaage** [comment]
das ist nur ein Workaround. Falls du Kinddatensätze bearbeiten musst die schon angelegt wurden (die Sache hat nämlich schonmal funktioniert) mach die Attribute im Rendersetting unsichtbar! dann kommt man zumindest in den Child-View.

**Comment by asaage** [comment]
Contao 3.5.2
MM TNG 15.08.2015 (19:54h)
Behoben... :+1: 
der nightly-build ist jezt auch wieder wesentlich schlanker und aktuell.

die aktuellen Daten:
dc-general @ 388f7a
metamodels/core @ 73c636

Wenn @xantippe dass bestätigen kann - dann zu damit.

**Comment by xantippe** [comment]
jut - habe das aktuelle Paket hochgeladen... ich hatte extra die Zeit dazu geschrieben, da xtra nach 23h das Paket nochmal änderte

Frage: wie sollte sich die "Optik" zwischen Flat und Parentend unterscheiden? vermutet hatte ich bei Parented sowas wie beim Artikelbaum... zu sehen ist kein Unterschied.

aber! 
bei Parented ist der Bug https://github.com/MetaModels/core/issues/863 raus - die Zuornung der pid´s stimmen wieder (verzeiht das Idioten-Apostroph).

**Comment by asaage** [comment]
flat: selbstklärend
parented: wenn du ein Kindmodell und ein Parentmodell (also zwei verschiedene) hast geht denke ich nur, wenn du keine unabhängige Darstellung nutzt
Hirarchical: das ist der Baum den du meinst - das geht meines Erachtens nur mit Datensätzen des gleichen Modells.

so hab ich mir das jedenfalls erschlossen.

**Comment by xantippe** [comment]
ich habe zwei unterschiedliche MMs, welche ich per (Eltern-)Kindtabelle zugeordnet habe - in der Ansicht gibt es zwischen Flat und Parented (aktuell) keinen Unterschied - lediglich der pid-Bug ist in Parented nicht vorhanden..

**Comment by asaage** [comment]
Das ist genau das, was parented (beim Kindmodell) bewirkt: du bekommst einen Header und die Berücksichtigung der pid. Das Elternmodell ist dann bei mir Flat oder Hirarchical und Eigenständig.

**Comment by xantippe** [comment]
Irgenwie stehe ich auf dem Schlauch...

aus den Einstellungen im BE würde ich lesen, dass die Auswahl bei "Backend-Integration" als "Kind-Tabelle" *immer* eine hierarchische Zuordnung ergibt (da hier [leider] nicht mit nested-sets gearbeitet wied - also per pid)

In der Rubrik "Data display settings" würde ich, insbesondere mit der Bezeichnung "Render mode", rein die "optische Ausrichtung" der Anzeige erwarten und nicht irgendwelche Zuordnungssachen.

**Comment by tim-bec** [comment]
Mit dem aktuellen dev-develop ist der Fehler wohl behoben. Ich mach das Ticket mal zu.
