### ISSUE TITLE
Wrong redirect after "saveandclose" and clicking on the Back-Button

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [MetaModels/core#843]
I always get to the composer, "Paketverwaltung", after I save what ever. That's a pain :), It's hard to focus the task.
Clicking on the Back-Button also don't work.

**Comment by asaage** [comment]
Ich denk, das ist mit dmolineus@026df1d21768f09ffdba0ab8bc6490f3a3a4d6dc behoben.
Ich kanns jedenfalls nichtmehr reproduzieren.
