### ISSUE TITLE
"Neuer Datensatz" ohne Funktion

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#844]
Beim Anlegen eines neuen Datensatz in einem "Hierarchical" Model erschein kein Klemmbrett mehr um die Position zu bestimmen.
Das Duplizieren und Verschieben bereits vorhandener Datensätze funktioniert hingegen problemlos.
Ebenso funktioniert "Neuer Datensatz" in "Flat" Models.
* metamodels/core dev-tng @ b46d09
* Contao 3.5.0

**Comment by discordier** [comment]
@dmolineus Ne Idee?

**Comment by dmolineus** [comment]
It's definitly DCG related. When I use an older branch (feature/widget-manager-cleanup or instance) it works fine. With the latest develop breanch of the dc general not. Didn't find what's break it yet.

**Comment by dmolineus** [comment]
You've break it by optimizing the depcrecated IdSerializer. If the id was empty no data provider was given which caused a lot of issues. At least this one and contao-community-alliance/dc-general#86 are covered by it. Propably #843 is solved as well.

**Comment by discordier** [comment]
Yeah, I broke it.
However it was not an optimization but necessary fix in order to allow phasing out the `IdSerializer` class.

**Comment by asaage** [comment]
scheint wieder zu funktionieren.
