### ISSUE TITLE
numeric sorting

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#845]
Bei einem Model mit einem "numeric" Attribut habe ich Sorting and grouping für die Eingabemaske konfiguriert.
_rendersortattr: numeric-Attibut_
_Grouping type: Do not group_
es erfolgt aber keine Sortierung.

Ich hab alternativ versucht ein Textfeld zu verwenden:
etwas besser: aber 17,18,19,2,20,21 ist auch nicht das, was ich will.

* metamodels/core dev-tng @ b46d09
* Contao 3.5.0

**Comment by discordier** [comment]
Wir haben anscheinend einige Probleme mit den Sortierungen, bei einem schnellen check habe ich schon 3 Attribute gefunden, die nach falschem Kriterium sortieren.
Bitte schaue dir MetaModels/core#851 an und beteilige dich ggf. an den tests, dann kommen wir schneller voran.

**Comment by dmolineus** [comment]
Propably related to contao-community-alliance/dc-general#155.

**Comment by asaage** [comment]
fixed in #860.
Inwieweit ist #851 jetzt noch relevant?

**Comment by discordier** [comment]
Habe es entsprechend in #851 notiert.
