### ISSUE TITLE
Add .gitattributes files

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#846]
We should add proper `.gitattributes` files to all repositories and exclude unneeded files to make the distributions smaller.
eg:

```
tests/ export-ignore
.gitattributes export-ignore
.gitignore export-ignore
.travis.yml export-ignore
.check-author.yml export-ignore
composer.lock export-ignore
phpunit.xml.dist export-ignore
build.default.properties export-ignore
build.xml export-ignore
```

**Comment by xantippe** [comment]
@discordier noch offen oder kann geschlossen werden?

**Comment by discordier** [comment]
Noch offen, keines der repos hat die Datei.

**Comment by zonky2** [comment]
alle Repos + Core (https://github.com/MetaModels/core/blob/hotfix/alpha-15/.gitattributes) hat die Datei => close
