### ISSUE TITLE
Fatal error: Class name must be a valid object or a string

### ISSUE THREAD

**Issue by siemendev** [MetaModels/core#848]
Hey Guys,
still not sure if I´m right here, this is my first real github issue... i´ve got this (still reproduceable) error while saving my form (see screenshots below):

```
Fatal error: Class name must be a valid object or a string in /var/www/*******/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php on line 569
```

It worked fine till I added the image and the database select some days ago.

I´ve added Frontend Image Upload Support by using the storeFormData Hook like here:
https://github.com/contao/core/issues/7751#issuecomment-92637634

![screenshot_2](https://cloud.githubusercontent.com/assets/11353665/8901399/c7023728-3448-11e5-9d53-39a9c72c28bb.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/11353665/8901401/ca764106-3448-11e5-8b7a-efc95af3b224.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/11353665/8901407/d289b576-3448-11e5-9aa3-92fb8e41f942.png)

Thank you!

**Comment by siemendev** [comment]
Edit: I´ve updated my metamodels and now I´m getting this one while loading the Metamodels Backend Module, too:
´´´
Fatal error: Class 'ContaoCommunityAlliance\DcGeneral\Data\ModelId' not found in /var/www/goaone/composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/MetaModels/Subscriber.php on line 116
´´´

**Comment by discordier** [comment]
Your dc-general version appears to be too old.

I have just tagged beta26, please try to upgrade again.

**Comment by siemendev** [comment]
Thank you! Updated & it works! Great support, thanks!
