### ISSUE TITLE
Unique values broken for manual input?

### ISSUE THREAD

**Issue by pju-** [MetaModels/core#849]
Tested with text and alias attributes.
If I set an attribute to "unique values" I can still enter the same value for several items.

For alias: if I hide the alias attribute in the backend, it is correctly generated with a trailing number.

<img width="916" alt="bildschirmfoto 2015-07-28 um 20 19 14" src="https://cloud.githubusercontent.com/assets/5202770/8939669/0cc421d6-3566-11e5-9331-41d0eb11e8f5.png">

<img width="535" alt="bildschirmfoto 2015-07-28 um 20 19 18" src="https://cloud.githubusercontent.com/assets/5202770/8939668/0cc3887a-3566-11e5-9cb3-faba1eb7f494.png">

Current nightly (2015-07-28), Contao 3.5.0

**Comment by discordier** [comment]
Will have a look into it.
I am unsure what you mean be hiding the alias. Is it not generated correctly when it is visible in the input screen?

**Comment by pju-** [comment]
Yes exactly. If the alias is visible in the input screen, there are duplicate values. If it is not visible, everything's alright.

**Comment by discordier** [comment]
The duplicate values are being generated, not typed in by hand I suppose?

**Comment by pju-** [comment]
Ugh, just tested again. Automatic generationg for the alias works indeed, not depending on the visibility in the input screen. Very, very sorry for the confusion.
But unique values should also work for values entered by hand, correct?

**Comment by pju-** [comment]
Maybe this is already known, I just found [a related dc-general ticket] (https://github.com/contao-community-alliance/dc-general/issues/54)

**Comment by discordier** [comment]
Indeed, the referenced ticket is the same issue, closing this one therefore.
