### ISSUE TITLE
Check method sortIds() in all attributes.

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#851]
As stated in #845, some attributes have improper sorting.
We have to check every attribute that it has a working `sortIds()` implementation or that the implementation from the parent class is working for the attribute type.
- [x] https://github.com/MetaModels/attribute_alias
- [x] https://github.com/MetaModels/attribute_checkbox
- [x] https://github.com/MetaModels/attribute_color
- [x] https://github.com/MetaModels/attribute_combinedvalues
- [x] https://github.com/MetaModels/attribute_country
- [x] https://github.com/MetaModels/attribute_decimal
- [x] https://github.com/MetaModels/attribute_file
- [x] https://github.com/MetaModels/attribute_langcode
- [x] https://github.com/MetaModels/attribute_longtext
- [x] https://github.com/MetaModels/attribute_numeric
- [x] https://github.com/MetaModels/attribute_rating
- [x] https://github.com/MetaModels/attribute_select
- [x] https://github.com/MetaModels/attribute_text
- [x] https://github.com/MetaModels/attribute_timestamp
- [x] https://github.com/MetaModels/attribute_translatedalias
- [x] https://github.com/MetaModels/attribute_translatedcombinedvalues
- [x] https://github.com/MetaModels/attribute_translatedfile
- [x] https://github.com/MetaModels/attribute_translatedlongtext
- [x] https://github.com/MetaModels/attribute_translatedselect
- [x] https://github.com/MetaModels/attribute_translatedtext

**Comment by discordier** [comment]
I would like to call for help on this one.
Could everyone please report the attributes that are working so we can track the bad ones down?

**Comment by discordier** [comment]
Numeric working as of https://github.com/MetaModels/core/issues/845#issuecomment-130489059

**Comment by asaage** [comment]
also working:
[x]attribute_checkbox
[x]attribute_text
[x]attribute_alias

**Comment by discordier** [comment]
Thanks, updated.

**Comment by xantippe** [comment]
Vorgehen:
* Attribut anlegen
* mit Werten befüllen
* im FE (oder BE) sortieren

per "Default" sollte nach MySQL "ORDER BY" sortiert werden - bei komplexeren Attributen muss ggf. eine eigene Sortierroutine eingebaut werden

**Comment by discordier** [comment]
@xantippe das schrieb ich doch schon oben, es geht aber darum nun zu identifizieren welche Attribute eine "falsche" Sortierung haben (mit dem "normalen" ORDER BY).
Alle die ok sind kann man oben abhaken

**Comment by johannes-bittner** [comment]
So far tested and working:
- [x] attribute_country 
- [x] attribute_decimal
- [x] attribute_combinedvalues
- [x] attribute_file
- [x] attribute_select

**Comment by discordier** [comment]
Thanks @johannes-bittner.

**Comment by zonky2** [comment]
* wie soll die Sortierung bei tags und tabletext sein? - hier würde ich eher die Sortieroption entfernen...
* Sortierung bei URL: nach Domain oder Bezeichnung?

**Comment by zonky2** [comment]
Besprechung MM-call 07.09.2017: => ausblenden...

**Comment by johannes-bittner** [comment]
Working:
- [x] attribute_langcode
- [x] attribute_translatedcombinedvalues
- [x] attribute_translatedfile
- [x] attribute_translatedtext
- [x] attribute_translatedalias

No successful tests:
- [] ~~attribute_geoprotection~~
- [] ~~attribute_translatedcheckbox~~

Does it make sense to have sorting on geoprotection? how is this supposed to work, because we have a combination of off/on + countries to allow/disallow?

**Comment by johannes-bittner** [comment]
- [x] attribute_color

**Comment by zonky2** [comment]
o.k. alles getestet - Dank an @johannes-bittner
