### ISSUE TITLE
Warning bei Filter in Eingabemasken

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#852]
Alle Eingabemasken, für die "filter" im Panellayout definiert sind werfen seit neuestem folgende Warnung:
```
Warning: Invalid argument supplied for foreach() in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultFilterElement.php on line 203
#0 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultFilterElement.php(203): __error(2, 'Invalid argumen...', '/var/www/vhosts...', 203, Array)
#1 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/PanelRenderer.php(81): ContaoCommunityAlliance\DcGeneral\Panel\DefaultFilterElement->render(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoBackendViewTemplate))
#2 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/PanelRenderer.php(153): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\PanelRenderer->renderPanelElement(Object(ContaoCommunityAlliance\DcGeneral\Panel\DefaultFilterElement), 'even first')
#3 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/PanelRenderer.php(182): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\PanelRenderer->renderPanelRow(Object(ContaoCommunityAlliance\DcGeneral\Panel\DefaultPanel), Array)
#4 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1401): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\PanelRenderer->render(Array)
#5 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(318): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->panel()
#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->showAll(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(143): call_user_func_array(Array, Array)
#8 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(168): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(122): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(75): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#14 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_ex...')
#15 contao/main.php(20): Contao\BackendMain->run()
#16 {main}
```
* contao 3.5.2
* metamodels/core	dev-tng @ 72080a
* contao-community-alliance/dc-general	dev-develop @ a33cd9

Die Filter-selectbox bleibt leer.
Es scheint unabhängig von der Art der filterbaren Attributes zu sein.

**Comment by discordier** [comment]
Siehe #853, sollte mit contao-community-alliance/dc-general@f678d13 behoben sein.

**Comment by hh-com** [comment]
Danke, Warnung wurde behoben und die Filter werden wieder korrekt angezeigt.
Das Ticket #853 allerdings nicht.
Die Anzahl der angezeigten Datensätze kann nicht eingestellt werden.
Es wird im Select zwar die richtige Anzahl der Datensätze angezeigt, wenn ein Filter ausgewählt wurde, angezeigt werden aber trotzdem alle.

Mit dem Filter selbst dürfte das nichts zu tun haben, denn wird dieser entfernt, ist es auch nicht möglich die Anzahl zu limitieren.

**Comment by asaage** [comment]
Ich würde diesen hier erstmal schließen - aber hh's Aussage bzgl. #853 bestätigen.

**Comment by asaage** [comment]
jetzt ist der Wurm drinn.
einige Filter funktionieren andere nicht,
beim Klick auf "Mehrere Bearbeiten" alle Warnungen wieder da... :reopen

**Comment by cyberlussi** [comment]
Hi,

Ich habe ein tags attribute "Gruppenzugehörigkeit" als filterbar definiert. die Warnung erscheint nicht mehr nach der Installation von contao-community-alliance/dc-general 	dev-develop (220dbbcc). 

Dafür allerdings:
- nach Klick auf "Mehrere Bearbeiten" (wie @asaage )
- Filter funktioniert nicht, wenn man ein Tags-Wert, Text oder Checkbox auswählt (kein Effekt)

**Comment by discordier** [comment]
Nun mischen wir hier aber eifrig issues... @cyberlussi, @asaage Bitte nochmal genau beschreiben was genau nun mit der aktuellsten Version nun nicht funktioniert.

**Comment by cyberlussi** [comment]
contao-community-alliance/dc-general 	dev-develop (dfca095e)
metamodels/core 	dev-master (4bcb7e12)

Filter funktioniert! Keine Warnings.

**Comment by asaage** [comment]
* contao 3.5.2
* mm/core @ 5958df
* cca//dcg @ dfca09
liefert folgendes Testergebnis:
* Filter auf attribute [tags] & [text] funktionieren in flat-, hirachical- & table-view
* das mit "Mehrere Bearbeiten" hat sich auch erledigt.
* Die limit-Funktion liefert auch die gewünschten Ergebnisse (siehe #853)
das Selectfeld dazu springt aber nach der Auswahl von "Alle" zurück auf (1-30) - zeigt aber "Alle" an.
im Gegensatz zu den Filtern passiert hier wohl was ajaxiges...
