### ISSUE TITLE
Keine Einschränkung zur Anzeige von Datensätzen im BE möglich

### ISSUE THREAD

**Issue by 31er** [MetaModels/core#853]
Contao 3.2.21
metamodels/core dev-tng (72080ad6)
metamodels/bundle_all 1.0.1
contao-community-alliance/dc-general dev-develop (a33cd9a8)

Nach dem Update auf MetaModels dev-tng (72080ad6) ist keine Einschränkung zur Anzeige von Datensätzen im BE möglich. Es werden alle Datensätze in einer Liste aufgeführt, zurzeit bei mir 738. 

Im Quellcode wird für tl_limit nur ein Option Value "Datensätze" ausgegeben, die gewohnten 1-30, 31-60 usw. fehlen.

**Comment by discordier** [comment]
Sollte mit contao-community-alliance/dc-general@f678d13 behoben sein.

**Comment by discordier** [comment]
According to https://github.com/MetaModels/core/issues/852#issuecomment-127530490 NOT fixed.

**Comment by 31er** [comment]
Danke für die Bemühungen.
Nun werden zwar die Bereiche (1-30, 31-60 usw.) als Value wieder aufgelistet, aber bei einer getroffenen Auswahl werden weiterhin immer alle Datensätze aufgelistet. Eine Beschränkung auf nur 30 Datensätze ich nicht möglich.

**Comment by 31er** [comment]
Nur zur Info, auch mit
contao-community-alliance/dc-general dev-develop (220dbbcc)
metamodels/core dev-tng (72080ad6)
leider keine Einschränkung der Auflistung der Datensätze möglich.

**Comment by dmolineus** [comment]
Will most likely being solved with contao-community-alliance/dc-general/pull/155.

**Comment by discordier** [comment]
contao-community-alliance/dc-general#155 has been merged. Please test.

**Comment by 31er** [comment]
Thx, you made my day!
Sieht gut aus, es werden nun wieder die Datensätze gem. Vorgabe wie gewohnt aufgelistet.
