### ISSUE TITLE
visibility condition shows only checkbox attributes in the Attribute Field

### ISSUE THREAD

**Issue by MacKP** [MetaModels/core#857]
Configuration for the visibility condition:
'Property is visible'
'Active'

regards

**Comment by xantippe** [comment]
was meinst Du damit? Beispiel/Screenshot?

**Comment by discordier** [comment]
The other attributes must be selectable as well. Otherwise the condition does not make sense at all.

**Comment by xantippe** [comment]
https://github.com/MetaModels/core/pull/950

![shot49](https://cloud.githubusercontent.com/assets/1045318/12193622/3d720b68-b5ea-11e5-9878-617428a7c305.jpg)

::::::::::::::::::::

![shot50](https://cloud.githubusercontent.com/assets/1045318/12193628/454c691e-b5ea-11e5-9e24-ebb9f53ed125.jpg)

**Comment by xantippe** [comment]
in dev-master (294dc9da) gefixt

**Comment by xantippe** [comment]
http://metamodels.readthedocs.org/de/latest/manual/metamodel-special/visibility-conditions.html
