### ISSUE TITLE
Bug: pid-Filterung von Kindtabelle zu Parent funktioniert nicht

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#863]
pid-Filterung von Kindtabelle zu Parent funktioniert nicht

pid wird auch nicht befüllt

Änderungen direkt im Datensatz per phpMyAdmin hat keine Wirkung

TNG 14.08.2015 (23:25h)

**Comment by xantippe** [comment]
beim Rendermode "Parented" funktioniert die pid-Zuordnung (wieder)

https://github.com/MetaModels/core/issues/842#issuecomment-131427831

**Comment by m-knorr** [comment]
scheinbar funktioniert es wieder nicht mehr.

Habe den Versuch über 2 Metamodels gemacht oder eine Standardtabelle und MM als Kind.

Die pid wird nicht geschrieben und in der Auflistung der Kindtabelle werden manuelle pid Änderungen auch nicht angenommen.

**Comment by discordier** [comment]
Kann also zu?

**Comment by xantippe** [comment]
ja - aus meiner Sicht
