### ISSUE TITLE
(kleiner) Bug: "Speichern und neu" z.B. beim MM anlegen bringt keine Klemmmappe

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#864]
(kleiner) Bug: "Speichern und neu" z.B. beim MM anlegen bringt keine Klemmmappe "rechts" bei den Icons  lediglich "links" das Icon zum Löschen der Zwischenablage.

TNG: 14.08.2015 (23:25h)

**Comment by dmolineus** [comment]
The paste button detection has some issues at the moment. Probably will be fixed by https://github.com/MetaModels/core/pull/856.

**Comment by discordier** [comment]
#856 has been merged, @xantippe please test again

**Comment by xantippe** [comment]
gerade getestet mit 
* dev-master (0b68f4a7)
* Composer-Cache geleert
* Contao BE-Cache aus

=> keine Veränderung :-( 

so sieht das nach "Speichern und neu" aus:

![zwischenablage04](https://cloud.githubusercontent.com/assets/1045318/11056249/1a4e8c76-8780-11e5-9610-cc08704354e2.jpg)

ein Klick auf das rechte [x] hat keine Reaktion - mit dem linken Icon kann die Klemmmappe geleert werden

btw: mit Klick auf "Verschieben" (blauer Pfeil) kommt auch keine Klemmmappe zum Vorschein - kann aber mit dem [x]

**Comment by xantippe** [comment]
getestet mit "dev-remove-dcg-deprecated (fc7885b3)"

erst wenn auf die "Aktualisieren-Pfeile" bei Sortierung/Filterung geklickt wurde, erscheinen die Icons zum Sortieren ("grüner Hamburger") und zum Einfügen (grüner Button mit w. Kreuz).

Die Klemmmappe zum Einfügen erscheint auch erst anschließend.

was funktioniert: Speichern & Neu in MM zeigt sofort eine neue Eingabemaske

Gruss

**Comment by discordier** [comment]
@dmolineus wir haben anscheinend irgendwo die defaultsortierung verloren bzw. es kommt vom panel ein `null`.

**Comment by dmolineus** [comment]
@discordier Hast du mehr Details? Welcher Stand vom DCG und MM Core nutzt du? Um welche View handelt es sich? Kann es gerade nicht nachvollziehen.

**Comment by xantippe** [comment]
@dmolineus wo sehe ich Version vom DCG?

ich kann auch ein Contao2go-Snapshot senden (kann man auch auf "echten Servern" einspielen
http://www.e-spin.de/contao-contao2go-pakete.html

**Comment by dmolineus** [comment]
Im Composer Paketmanager auf Checkbox "xy Abhängigkeiten installiert".

**Comment by xantippe** [comment]
contao-community-alliance/dc-general 	2.0.0-beta30

**Comment by xantippe** [comment]
Bugs zur Anzeige des Clipboards hier posten oder bei DCG?

**Comment by discordier** [comment]
@dmolineus tritt sowohl in meinem deprecated removed als auch im current beta auf, also hab ich es anscheinend nicht durch die Dinge kaputt gemacht, aber auch nicht gefixt.
Ich vermute, dass einfach der `ContaoCommunityAlliance\DcGeneral\Contao\Event::initializePanels()` nicht mehr kommt.

**Comment by discordier** [comment]
@dmolineus Update, in MM klappt es, da ist auch das default flag gesetzt.
Es scheint so, als ob der legacy dca parser bei der sorting und grouping definition das default flag nicht  setzt, daher schlaegt im listener das `hasDefault()` fehl und es klappt nix mehr.

Habe leider aktuell keine Zeit zum tracen.

**Comment by dmolineus** [comment]
@discordier Okay, hatte es nur bei den MM probiert. Bei `tl_metamodel` kann ich das Problem nachstellen und weiß auch woher es kommt. Wenn unter `list/sorting/fields` keine Standardsortierung ausgewählt ist, wird auch keine gesetzt. Dies ist bei `tl_metamodel` der Fall.

Hier könnte man einen Fallback einbauen, sodass hier die erste Sorting und Grouping Information genommen wird. 

Das Problem muss aber schon länger bestehen, denn daran hast weder du noch ich etwas geändert mit den neusten Changes.

**Comment by dmolineus** [comment]
Schau, dass ich am Wochenende nen PR erstelle. Denke, folgendes in `parsePropertySortingAndGrouping` sollte reichen:

```php
if (!$definitions->hasDefault()) {
        $definitions->markDefault($definition);
}
```

**Comment by xantippe** [comment]
ist beim aktuellen MM 2.0.0-alpha8 mit dem Workaround #922 erledigt
