### ISSUE TITLE
Anzeigefehler bei "Data display settings" mit Flat+showColumns

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#866]
ist in der Eingabemaske Flat mit showColumns angegeben, werden in der Tabellenansicht zu viele Spalten ausgegeben => es werden alle Attribute ausgegeben, auch wenn nicht aktiv oder "nicht vorhanden" (in der Renderauswahl) - siehe alias

siehe Screenshot(s)
![04](https://cloud.githubusercontent.com/assets/1045318/9288427/94f36f9c-4346-11e5-9203-7da821be9ef4.png)

**Comment by asaage** [comment]
ähnlich wie hier #861 (2ter Punkt - betrifft nicht nur "Flat mit showColumns")
und dort #858.

**Comment by xantippe** [comment]
hast Du eine Idee was das "Sorting" soll?
https://community.contao.org/de/showthread.php?58699-quot-Data-display-settings-quot-mit-Flat-showColumns-gt-Anzeige-von-quot-Sorting-quot-Spalten-leer&p=380869#post380869

**Comment by xantippe** [comment]
ist wohl eher was für den DC-General
https://github.com/contao-community-alliance/dc-general/issues/159

**Comment by xantippe** [comment]
mm bundle_all core 2.0.0-alpha 8 werden nur ausgewählte Attributspalten angezeigt
