### ISSUE TITLE
 InvalidArgumentException with message Identifier "translator" is not defined

### ISSUE THREAD

**Issue by amenk** [MetaModels/core#869]
Is this a bug in MM or DC General?

Happens when browsing a meta model in the backend.

	Fatal error: Uncaught exception InvalidArgumentException with message Identifier "translator" is not defined. thrown in composer/vendor/pimple/pimple/lib/Pimple.php on line 78
	#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(129): Pimple->offsetGet('translator')
	#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(66): ContaoCommunityAlliance\DcGeneral\DC_General->getTranslator()
	#2 system/modules/core/classes/Backend.php(393): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('mm_standorte', Array)
	#3 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_st...')
	#4 contao/main.php(20): Contao\BackendMain->run()
	#5 {main}

**Comment by MacKP** [comment]
More Information please:
- MM / DCG Version
- Setting from your MetaModel (i think you use tranlated Attributes)
regards

**Comment by amenk** [comment]
In the composer.json i Use `"metamodels/bundle_all": "dev-master",`
Here is the attributes table: https://gist.github.com/amenk/b5de39ce6df291e8dfd5
The error also seems to come for MM ID 1 which does not have any translated attributes.

**Comment by dmolineus** [comment]
It's not related to translated attribute but to the translator service, being created by the [translator package](https://github.com/contao-community-alliance/translator).

Could you please evaluate following:
 - Is the translator installed in version 2?
 - Is the issue fixed by adding `requires[] = "translator"` to `system/modules/dc-general/config/autoload.ini`

**Comment by amenk** [comment]
Looks like something went wrong with the installation of the translator module. It was not in `system/modules`. I was able to fix  the problem by `rm -r composer/vendor/contao-community-alliance/translator/` and `composer.phar install`. The `requires[]` was not even necessary.

Thanks a lot!
