### ISSUE TITLE
Offset und Limit für die Auflistung verwenden wirft einen JS Fehler aus

### ISSUE THREAD

**Issue by MacKP** [MetaModels/core#872]
Fix wäre in tl_modules.php Zeile 48 durch das hier ersetzen:

```
$GLOBALS['TL_DCA']['tl_module']['palettes']['__selector__'][] = 'metamodel_use_limit';
$GLOBALS['TL_DCA']['tl_module']['palettes']['__selector__'][] = 'metamodel_sort_override';
```

Xtra weiß Bescheid.

Viele Grüße

**Comment by xantippe** [comment]
https://github.com/MetaModels/core/blob/master/contao/dca/tl_module.php#L48

**Comment by discordier** [comment]
What do you mean @xantippe?

**Comment by MacKP** [comment]
Fix does what he should do ^^

**Comment by xantippe** [comment]
@discordier => welche Zeile & wo als Ergänzung zu @MacKP
