### ISSUE TITLE
Recoverable errors  beim Aufbau des Suchindex 

### ISSUE THREAD

**Issue by n-m-k** [MetaModels/core#873]
Wenn ich den Suchindex neu aufbauen möchte, so erhalte ich eine ganze Reihe Fehlermeldungen. Der Aufbau des Suchindexes läuft bis zum Schluss weiter und die Suchfunktion als solches klappt im FE auch wie vorgesehen.

Dies ist immer die erste Fehlermedung von vielen weiteren (siehe Anhang):
Recoverable error: Argument 1 passed to ContaoCommunityAlliance\Contao\Bindings\Events\Con troller\GenerateFrontendUrlEvent::__construct() must be of the type array, null given, called in E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\met amodels\core\src\MetaModels\BackendIntegration\Sea rchablePages.php on line 288 and defined in E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\con tao-community-alliance\events-contao-bindings\src\ContaoCommunityAlliance\Contao\Bindin gs\Events\Controller\GenerateFrontendUrlEvent.php on line 62

Contao Version 3.5.2
Metamodels nightly build vom 21.08.2015 und mehrere Versionen vorher.

![versionen](https://cloud.githubusercontent.com/assets/13907919/9423061/8bfcb5b6-48b3-11e5-9aa5-2fce4bdf4ec2.jpg)

**Comment by n-m-k** [comment]
https://community.contao.org/de/showthread.php?58712-Fehler-bei-Suchindex-aufbauen&p=381519#post381519

**Comment by n-m-k** [comment]
Hier der Rest der Fehlermeldungen:

#0 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\contao-community-alliance\events-contao-bindings\src\ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent.php(62): __error(4096, 'Argument 1 pass...', 'E:\xampp\htdocs...', 62, Array)
#1 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(288): ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent->__construct(NULL, NULL, NULL)
#2 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(318): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL)
#3 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#4 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#5 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#6 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\modules\ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#7 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\BackendModule.php(98): Contao\ModuleMaintenance->compile()
#8 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\Backend.php(423): Contao\BackendModule->generate()
#9 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#10 E:\xampp\htdocs\erf_2_11_to_3x\contao\main.php(20): Contao\BackendMain->run()
#11 {main}


Recoverable error: Argument 1 passed to Contao\Controller::generateFrontendUrl() must be of the type array, null given, called in E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\contao-community-alliance\events-contao-bindings\src\ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber.php on line 126 and defined in E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\Controller.php on line 1079

#0 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\Controller.php(1079): __error(4096, 'Argument 1 pass...', 'E:\xampp\htdocs...', 1079, Array)
#1 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\contao-community-alliance\events-contao-bindings\src\ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber.php(126): Contao\Controller::generateFrontendUrl(NULL, NULL, NULL)
#2 [internal function]: ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber->handleGenerateFrontendUrl(Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#5 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(289): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#6 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(318): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL)
#7 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#8 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#9 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#10 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\modules\ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#11 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\BackendModule.php(98): Contao\ModuleMaintenance->compile()
#12 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\Backend.php(423): Contao\BackendModule->generate()
#13 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#14 E:\xampp\htdocs\erf_2_11_to_3x\contao\main.php(20): Contao\BackendMain->run()
#15 {main}


Recoverable error: Argument 1 passed to ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent::__construct() must be of the type array, null given, called in E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php on line 288 and defined in E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\contao-community-alliance\events-contao-bindings\src\ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent.php on line 62

#0 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\contao-community-alliance\events-contao-bindings\src\ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent.php(62): __error(4096, 'Argument 1 pass...', 'E:\xampp\htdocs...', 62, Array)
#1 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(288): ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent->__construct(NULL, NULL, NULL)
#2 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(325): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL, NULL, true)
#3 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#4 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#5 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#6 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\modules\ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#7 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\BackendModule.php(98): Contao\ModuleMaintenance->compile()
#8 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\Backend.php(423): Contao\BackendModule->generate()
#9 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#10 E:\xampp\htdocs\erf_2_11_to_3x\contao\main.php(20): Contao\BackendMain->run()
#11 {main}


Recoverable error: Argument 1 passed to Contao\Controller::generateFrontendUrl() must be of the type array, null given, called in E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\contao-community-alliance\events-contao-bindings\src\ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber.php on line 126 and defined in E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\Controller.php on line 1079

#0 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\Controller.php(1079): __error(4096, 'Argument 1 pass...', 'E:\xampp\htdocs...', 1079, Array)
#1 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\contao-community-alliance\events-contao-bindings\src\ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber.php(126): Contao\Controller::generateFrontendUrl(NULL, NULL, NULL)
#2 [internal function]: ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber->handleGenerateFrontendUrl(Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#5 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(289): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#6 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(325): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL, NULL, true)
#7 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#8 E:\xampp\htdocs\erf_2_11_to_3x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#9 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#10 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\modules\ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#11 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\BackendModule.php(98): Contao\ModuleMaintenance->compile()
#12 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\Backend.php(423): Contao\BackendModule->generate()
#13 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#14 E:\xampp\htdocs\erf_2_11_to_3x\contao\main.php(20): Contao\BackendMain->run()
#15 {main}


Warning: Cannot modify header information - headers already sent by (output started at E:\xampp\htdocs\erf_2_11_to_3x\system\helper\functions.php:65) in E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\System.php on line 574

#0 [internal function]: __error(2, 'Cannot modify h...', 'E:\xampp\htdocs...', 574, Array)
#1 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\System.php(574): setcookie('FE_PREVIEW', '0', 1439661161, '/erf_2_11_to_3x', '', false, false)
#2 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\RebuildIndex.php(94): Contao\System::setCookie('FE_PREVIEW', 0, 1439661161)
#3 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\modules\ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#4 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\BackendModule.php(98): Contao\ModuleMaintenance->compile()
#5 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\Backend.php(423): Contao\BackendModule->generate()
#6 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#7 E:\xampp\htdocs\erf_2_11_to_3x\contao\main.php(20): Contao\BackendMain->run()
#8 {main}


Warning: Cannot modify header information - headers already sent by (output started at E:\xampp\htdocs\erf_2_11_to_3x\system\helper\functions.php:65) in E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\System.php on line 574

#0 [internal function]: __error(2, 'Cannot modify h...', 'E:\xampp\htdocs...', 574, Array)
#1 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\System.php(574): setcookie('FE_USER_AUTH', '482442b61e27406...', 1439661161, '/erf_2_11_to_3x', '', false, true)
#2 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\RebuildIndex.php(118): Contao\System::setCookie('FE_USER_AUTH', '482442b61e27406...', 1439661161, NULL, NULL, false, true)
#3 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\modules\ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#4 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\BackendModule.php(98): Contao\ModuleMaintenance->compile()
#5 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\Backend.php(423): Contao\BackendModule->generate()
#6 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#7 E:\xampp\htdocs\erf_2_11_to_3x\contao\main.php(20): Contao\BackendMain->run()
#8 {main}


Warning: Cannot modify header information - headers already sent by (output started at E:\xampp\htdocs\erf_2_11_to_3x\system\helper\functions.php:65) in E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\System.php on line 574

#0 [internal function]: __error(2, 'Cannot modify h...', 'E:\xampp\htdocs...', 574, Array)
#1 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\System.php(574): setcookie('FE_AUTO_LOGIN', '', 1439661161, '/erf_2_11_to_3x', '', false, true)
#2 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\RebuildIndex.php(119): Contao\System::setCookie('FE_AUTO_LOGIN', NULL, 1439661161, NULL, NULL, false, true)
#3 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\modules\ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#4 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\BackendModule.php(98): Contao\ModuleMaintenance->compile()
#5 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\Backend.php(423): Contao\BackendModule->generate()
#6 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#7 E:\xampp\htdocs\erf_2_11_to_3x\contao\main.php(20): Contao\BackendMain->run()
#8 {main}


Warning: Cannot modify header information - headers already sent by (output started at E:\xampp\htdocs\erf_2_11_to_3x\system\helper\functions.php:65) in E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\Template.php on line 294

#0 [internal function]: __error(2, 'Cannot modify h...', 'E:\xampp\htdocs...', 294, Array)
#1 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\Template.php(294): header('Vary: User-Agen...', false)
#2 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\BackendTemplate.php(120): Contao\Template->output()
#3 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(275): Contao\BackendTemplate->output()
#4 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(135): Contao\BackendMain->output()
#5 E:\xampp\htdocs\erf_2_11_to_3x\contao\main.php(20): Contao\BackendMain->run()
#6 {main}


Warning: Cannot modify header information - headers already sent by (output started at E:\xampp\htdocs\erf_2_11_to_3x\system\helper\functions.php:65) in E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\Template.php on line 295

#0 [internal function]: __error(2, 'Cannot modify h...', 'E:\xampp\htdocs...', 295, Array)
#1 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\library\Contao\Template.php(295): header('Content-Type: t...')
#2 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\classes\BackendTemplate.php(120): Contao\Template->output()
#3 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(275): Contao\BackendTemplate->output()
#4 E:\xampp\htdocs\erf_2_11_to_3x\system\modules\core\controllers\BackendMain.php(135): Contao\BackendMain->output()
#5 E:\xampp\htdocs\erf_2_11_to_3x\contao\main.php(20): Contao\BackendMain->run()
#6 {main}

**Comment by xantippe** [comment]
Quelltexte u.ä. in die drei "Ticks" ``` davor und dahinter einsetzen

**Comment by ADoebeling** [comment]
We have the same error in recently updated installation (2.10=>3.2) when creating new pages.
If u disable `displayErrors` in localconfig.php it seems to cause no problems.

Contao 3.2.21

```
[27-Sep-2015 19:18:17 GMT]
PHP Recoverable error: Argument 1 passed to ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent::__construct() must be of the type array, null given, called in {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php on line 288 and defined in {$INSTALL_PATH}/composer/vendor/contao-community-alliance/events-contao-bindings/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php on line 62
#0 {$INSTALL_PATH}/composer/vendor/contao-community-alliance/events-contao-bindings/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php(62): __error(4096, 'Argument 1 pass...', '/kunden/226796_...', 62, Array)
#1 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(288): ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent->__construct(NULL, NULL, NULL)
#2 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(318): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL)
#3 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#4 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, '1', 'en')
#5 {$INSTALL_PATH}/system/modules/core/library/Contao/Automator.php(395): MetaModels\BackendIntegration\SearchablePages->addPages(Array, '1', true, 'en')
#6 {$INSTALL_PATH}/system/cache/dca/tl_page.php(1560): Contao\Automator->generateSitemap('232')
#7 {$INSTALL_PATH}/system/modules/core/drivers/DC_Table.php(1986): tl_page->updateSitemap(Object(Contao\DC_Table))
#8 {$INSTALL_PATH}/system/modules/core/classes/Backend.php(425): Contao\DC_Table->edit()
#9 {$INSTALL_PATH}/contao/main.php(137): Contao\Backend->getBackendModule('page')
#10 {$INSTALL_PATH}/contao/main.php(288): Main->run()
#11 {main}

[27-Sep-2015 19:18:17 GMT]
PHP Recoverable error: Argument 1 passed to Contao\Controller::generateFrontendUrl() must be of the type array, null given, called in {$INSTALL_PATH}/composer/vendor/contao-community-alliance/events-contao-bindings/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php on line 126 and defined in {$INSTALL_PATH}/system/modules/core/library/Contao/Controller.php on line 2185
#0 {$INSTALL_PATH}/system/modules/core/library/Contao/Controller.php(2185): __error(4096, 'Argument 1 pass...', '/kunden/226796_...', 2185, Array)
#1 {$INSTALL_PATH}/composer/vendor/contao-community-alliance/events-contao-bindings/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php(126): Contao\Controller::generateFrontendUrl(NULL, NULL, NULL)
#2 [internal function]: ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber->handleGenerateFrontendUrl(Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 {$INSTALL_PATH}/composer/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 {$INSTALL_PATH}/composer/vendor/symfony/event-dispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#5 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(289): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#6 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(318): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL)
#7 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#8 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, '1', 'en')
#9 {$INSTALL_PATH}/system/modules/core/library/Contao/Automator.php(395): MetaModels\BackendIntegration\SearchablePages->addPages(Array, '1', true, 'en')
#10 {$INSTALL_PATH}/system/cache/dca/tl_page.php(1560): Contao\Automator->generateSitemap('232')
#11 {$INSTALL_PATH}/system/modules/core/drivers/DC_Table.php(1986): tl_page->updateSitemap(Object(Contao\DC_Table))
#12 {$INSTALL_PATH}/system/modules/core/classes/Backend.php(425): Contao\DC_Table->edit()
#13 {$INSTALL_PATH}/contao/main.php(137): Contao\Backend->getBackendModule('page')
#14 {$INSTALL_PATH}/contao/main.php(288): Main->run()
#15 {main}

[27-Sep-2015 19:18:17 GMT]
PHP Recoverable error: Argument 1 passed to ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent::__construct() must be of the type array, null given, called in {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php on line 288 and defined in {$INSTALL_PATH}/composer/vendor/contao-community-alliance/events-contao-bindings/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php on line 62
#0 {$INSTALL_PATH}/composer/vendor/contao-community-alliance/events-contao-bindings/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php(62): __error(4096, 'Argument 1 pass...', '/kunden/226796_...', 62, Array)
#1 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(288): ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent->__construct(NULL, NULL, NULL)
#2 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(325): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL, NULL, true)
#3 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#4 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, '1', 'en')
#5 {$INSTALL_PATH}/system/modules/core/library/Contao/Automator.php(395): MetaModels\BackendIntegration\SearchablePages->addPages(Array, '1', true, 'en')
#6 {$INSTALL_PATH}/system/cache/dca/tl_page.php(1560): Contao\Automator->generateSitemap('232')
#7 {$INSTALL_PATH}/system/modules/core/drivers/DC_Table.php(1986): tl_page->updateSitemap(Object(Contao\DC_Table))
#8 {$INSTALL_PATH}/system/modules/core/classes/Backend.php(425): Contao\DC_Table->edit()
#9 {$INSTALL_PATH}/contao/main.php(137): Contao\Backend->getBackendModule('page')
#10 {$INSTALL_PATH}/contao/main.php(288): Main->run()
#11 {main}

[27-Sep-2015 19:18:17 GMT]
PHP Recoverable error: Argument 1 passed to Contao\Controller::generateFrontendUrl() must be of the type array, null given, called in {$INSTALL_PATH}/composer/vendor/contao-community-alliance/events-contao-bindings/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php on line 126 and defined in {$INSTALL_PATH}/system/modules/core/library/Contao/Controller.php on line 2185
#0 {$INSTALL_PATH}/system/modules/core/library/Contao/Controller.php(2185): __error(4096, 'Argument 1 pass...', '/kunden/226796_...', 2185, Array)
#1 {$INSTALL_PATH}/composer/vendor/contao-community-alliance/events-contao-bindings/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php(126): Contao\Controller::generateFrontendUrl(NULL, NULL, NULL)
#2 [internal function]: ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber->handleGenerateFrontendUrl(Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 {$INSTALL_PATH}/composer/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 {$INSTALL_PATH}/composer/vendor/symfony/event-dispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#5 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(289): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#6 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(325): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL, NULL, true)
#7 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#8 {$INSTALL_PATH}/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, '1', 'en')
#9 {$INSTALL_PATH}/system/modules/core/library/Contao/Automator.php(395): MetaModels\BackendIntegration\SearchablePages->addPages(Array, '1', true, 'en')
#10 {$INSTALL_PATH}/system/cache/dca/tl_page.php(1560): Contao\Automator->generateSitemap('232')
#11 {$INSTALL_PATH}/system/modules/core/drivers/DC_Table.php(1986): tl_page->updateSitemap(Object(Contao\DC_Table))
#12 {$INSTALL_PATH}/system/modules/core/classes/Backend.php(425): Contao\DC_Table->edit()
#13 {$INSTALL_PATH}/contao/main.php(137): Contao\Backend->getBackendModule('page')
#14 {$INSTALL_PATH}/contao/main.php(288): Main->run()
#15 {main}
```

![image](https://cloud.githubusercontent.com/assets/10674780/10124793/7287801c-655e-11e5-96dd-99d204b03d7f.png)

**Comment by asaage** [comment]
@n-m-k schau mal ob du das vorläufig so beheben kannst #902

**Comment by n-m-k** [comment]
Mit den oben beschriebenen Maßnahmen kann ich auch die Fehlermeldungen aus diesem Ticket  unterbinden.
Danke für die Hilfe

**Comment by stefanheimes** [comment]
Should be fixed with the commit 5c43c268e4e02b77fbcac061c0b254e645b0848a ans the new version 2.0.0-alpha6.

**Comment by n-m-k** [comment]
Hello,
I have tested the change. I get no error messages.
