### ISSUE TITLE
Überschrift des Kind MM anzeigen, wenn man in der Liste ist

### ISSUE THREAD

**Issue by MacKP** [MetaModels/core#874]
Ich habe ein MM mit mehreren Kind-MM. Das geht soweit schon sehr gut :)
Wenn man in ein Kind-MM geht sieht man aber nicht mehr in welchem Kind-MM man ist. Es wäre gut, wenn das oben angezeigt wird, anstelle von dem Namen des Eltern-MM.

Es wäre auch möglich über einen neuen Feldtypen. Anstelle von Legende dann so etwas wie Überschrift oder so...

Viele Grüße

**Comment by xantippe** [comment]
wäre dann nicht etwas "like breadcrumb" besser damit man Eltername UND Kindname sieht?

**Comment by design23** [comment]
+1

**Comment by zonky2** [comment]
dupe of #586
