### ISSUE TITLE
Bug bei MM-Werteeingabe "Speichern und neu": keine "Klemmmappe"

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#875]
Das "Speichern und neu" funktioniert beim Anlegen der MM inzwischen sehr gut - wenn ein MM "befüllt" wird und man verwendet "Speichern und neu" fehlt wieder die Klemmmappe rechts bei den Icons und oben links das Icon "Neuer Datensatz" kann nur über das linke "Teilicon" gelöscht werden - rechts mit dem "x" geht es nicht

TNG 24.08.2015

**Comment by MacKP** [comment]
@xantippe bitte gib noch an, welche Sortier Option du da eingestellt hast etc.

btw: Datensatz löschen ist da.. kommt aber nur bei hover oben links ;-)

**Comment by xantippe** [comment]
Habe zwei Sortieroptionen angelegt, Name und Alias

Löschen geht - hatte ich geschrieben bzw. gemeint mit ```linke "Teilicon"```

**Comment by xantippe** [comment]
wird wahrscheinlich der gleiche "DCG-Bug" wie hier sein #864
