### ISSUE TITLE
Fehlermeldung CE MetaModel-Liste: Unknown column 'metamodel_sort_override'

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#876]
Beim Erstellen einer MM-Liste taucht die folgende Meldung bei "Allow sort override" auf:

```Query error: Unknown column 'metamodel_sort_override' in 'field list' (UPDATE tl_content SET metamodel_sort_override='' WHERE id='508')```

TNG: 24.08.2015

**Comment by asaage** [comment]
"Datenbank aktualisieren" könnte wohl weiter helfen.

**Comment by xantippe** [comment]
jesses... manchmal sieht man den Wald vor Bäumen nicht ;-)

Stimmt: DB Update und die Meldung ist weg
