### ISSUE TITLE
Popup-Tags werden nicht übernommen

### ISSUE THREAD

**Issue by siemendev** [MetaModels/core#883]
Wenn ich bei Metamodels ein Feld vom Typ Tags anlege, dem dann die Option _Als Checkbox-Wizard anzeigen_ auf _Display as Picker Popup_ setze und dann versuche, in der Eingabemaske nach der Auswahl der Tags auf schließen zu klicken, dann bewirkt das nichts.
Ursache ist hier eine falsch gesetzte CSS ID, wenn der Container die ID _#tl_listing_ statt _#tl_select_ bekommen würde, dann funktioniert das ganze wieder 1A.

Ich habe als vorrübergehende Lösung die Zeile 320 in der Datei vanillaGeneral.js vom DC General in folgenden Code geändert:
```
var psElement = frm.document.getElementById('tl_listing');
if (psElement == null) {
psElement = frm.document.getElementById('tl_select');
}
var inp = psElement.getElementsByTagName('input');
```

![screenshot_2](https://cloud.githubusercontent.com/assets/11353665/9686561/d07b5da2-5324-11e5-8a0b-88618e98ad18.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/11353665/9686771/d373f770-5325-11e5-813f-dc8cc04350ae.png)

**Comment by Aybee** [comment]
Nur am Rande bemerkt: Ist diese Überschrift "Als Checkbox-Wizard anzeigen" da nicht falsch? Müsste da nicht "Feldtyp" o.ä. stehen?

**Comment by siemendev** [comment]
Stimmt! War mir dabei jetzt garnicht direkt aufgefallen :+1:

**Comment by xantippe** [comment]
@stefanheimes ist die Sache nun gefixt? und kann Ticket zu?

**Comment by xantippe** [comment]
ist mit https://github.com/xantippe/dc-general/commit/1ef3684e5c04795a09625f21d8bfd34ff05f218c gefixt - sowohl für Select als auch Tags

**Comment by discordier** [comment]
Fixed in contao-community-alliance/dc-general@d169f0dbcf4ccef8cc6c6ea643b5282a1bc3f3f2
