### ISSUE TITLE
Attribute: Mehrere Bearbeiten: Checkbox "Alle" ist doppelt

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#885]
Attribute: Mehrere Bearbeiten: Checkbox "Alle" ist doppelt
![Uploading Zwischenablage01.jpg…]()

**Comment by asaage** [comment]
![image](https://cloud.githubusercontent.com/assets/4138336/9811284/98fab2b8-5876-11e5-90ea-61f42431db32.png)
Kosmetikbug oder usability-feature ;-)

**Comment by zonky2** [comment]
add PR: https://github.com/contao-community-alliance/dc-general/pull/217
