### ISSUE TITLE
Falsche Bezeichnung und Beschreibung im Listen-Inhaltselement

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [MetaModels/core#886]
Hi,

>$GLOBALS['TL_LANG']['tl_content']['metamodel_noparsing']['0']            = 'Keine Items ausgeben';
$GLOBALS['TL_LANG']['tl_content']['metamodel_noparsing']['1']            = 'Wenn diese Box aktiviert ist gibt das Module keine Items aus. Stattdessen stellt es Items-Objekte im Template zur Verfügung.';

Falsch ist: 
"keine Items " -> Es geht hierbei nicht um die items, sondern um die geparsten Items im data-Array.
UND
" Stattdessen stellt es Items-Objekte im Template zur Verfügung" 
-> diese werden immer ausgegeben wie in der render-Funktion zu sehen ist.

https://github.com/MetaModels/core/blob/master/src/MetaModels/ItemList.php#l803-l807

Mein Vorschlag wäre hier:
>$GLOBALS['TL_LANG']['tl_content']['metamodel_noparsing']['0']            = 'Keine geparsten Items über "$data" ausgeben';
$GLOBALS['TL_LANG']['tl_content']['metamodel_noparsing']['1']            = 'Wenn diese Box aktiviert ist gibt das Module keine geparsten Items über "$data" aus. Die Items-Objekte stehen nach wie vor im Template zur individuellen Verwendung zur Verfügung.';

Soll ich dafür einen PR machen oder muss das über Transiflex oder wie kann ich da noch helfen???

**Comment by Teetrinker** [comment]
Sehr geehrte Damen und Herren

Danke für Ihre Nachricht. Ich bin ab dem 16. September wieder im Büro.

Ihre Nachricht wird nicht weitergeleitet. In Fällen die dringend und wichtig sind wenden Sie sich bitte an Peter Oberhänsli (p.oberhaensli@webbaumeister.ch) oder schreiben Sie mir eine SMS auf 079 530 25 24 um auf ihre E-Mail hinzuweisen.

Mit freundlichen Grüssen
David Bopp

**Comment by MacKP** [comment]
Hey,
das läuft alles über Transiflex. Von daher wäre es super, wenn du dich da einbringen würdest!

Viele Grüße

**Comment by MoniqueHahnefeld** [comment]
@MacKP Bin bei transiflex als designs2, info@designs2.de
Könnt ihr mich da zuweisen oder wie komm ich da ran :)?

**Comment by MacKP** [comment]
@MoniqueHahnefeld kann ich leider nicht... oder auch gut so ^^ Muss @discordier machen ;-)

**Comment by MoniqueHahnefeld** [comment]
Haha, hab gerade den Button für die Anfrage gefunden :dancer:  :)

**Comment by MoniqueHahnefeld** [comment]
Habe die Änderungen in Transifex übernommen. Soll ich das Ticket da schließen?

**Comment by MacKP** [comment]
Jap, beim nächsten mal einfach das Ticket hier dann schließen. Ist hier ja eh fehl am Platz ;-) Ich mach das mal direkt zu.

**Comment by MoniqueHahnefeld** [comment]
ok thx :)

**Comment by Teetrinker** [comment]
Sehr geehrte Damen und Herren

Danke für Ihre Nachricht. Ich bin bis zum 12. Oktober ferienhalber abwesend und ab dem 13. Oktober wieder im Büro.

Ihre Nachricht wird nicht weitergeleitet. In Fällen die dringend und wichtig sind wenden Sie sich bitte an Peter Oberhänsli (p.oberhaensli@webbaumeister.ch) oder schreiben Sie mir eine SMS auf 079 530 25 24 um auf ihre E-Mail hinzuweisen.

Mit freundlichen Grüssen
David Bopp

**Comment by discordier** [comment]
@Teetrinker langsam wird das Ticket hier zu deinem Urlaubsplan... ;)
