### ISSUE TITLE
[TNG 3b171dcf] Filter zurücksetzen: keine Ausgabe als CE; als FE-Modul o.k.

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#888]
das Element "Filter zurücksetzen" gibt keine Ausgabe aus, wenn es als Inhaltselement definiert wird - auch die Überschrift nicht - hingegen als FE-Modul funktioniert es

Die Bezeichnung ist auch unterschiedlich "Zurücksetzen" vs. "MetaModel-Filterreset"

**Comment by stefanheimes** [comment]
Should be fixed with 673766b1ee525c664107c0e3532ff6a06373dcbb

**Comment by stefanheimes** [comment]
@xantippe can you check it with the hotfix version, pls.

**Comment by xantippe** [comment]
kann ich das per Composer laden?

**Comment by stefanheimes** [comment]
Good question, next one pls. I don't know how i just jump into the core folder and check out the version via git. 

Maybe @discordier can help us.

**Comment by xantippe** [comment]
Composer Schön und Gut - wenn es denn funktionieren würde..

**Comment by discordier** [comment]
Put `"metamodels/core": "dev-hotfix-clearall as 2.0.0"` in your project composer.json in the require section.

**Comment by xantippe** [comment]
Ich habe

1.) im Composer das Paket metamodels/core von "dev-master" auf "dev-hotfix-clearall Referenz: 8703a557" umgestellt

2.) in den Experteneinstellungen ```"metamodels/core": "dev-master",``` zu ```"metamodels/core": "dev-hotfix-clearall as 2.0.0" - hier kommt Meldung: ```Warning: require.metamodels/bundle_all : unbound version constraints (dev-master) should be avoided```

3.) Pakete geupdatet - dann kommt:
```
Loading composer repositories with package information
Updating dependencies
  - Removing metamodels/core (dev-master 5202076)
  - Installing metamodels/core (dev-hotfix-clearall 8703a55)
    Downloading

  - installed 248 files
Package tecnick.com/tcpdf is abandoned, you should avoid using it. Use tecnickcom/tcpdf instead.
Writing lock file
Generating autoload files
Warning: Ambiguous class resolution, "MultiColumnWizard" was found in both "C:/Contao2Go/htdocs/vhosts/contao-3.5.x/composer/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/MultiColumnWizard.php" and "C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao\core\system\modules\multicolumnwizard\MultiColumnWizard.php", the first will be used.
Warning: Ambiguous class resolution, "MultiColumnWizardHelper" was found in both "C:/Contao2Go/htdocs/vhosts/contao-3.5.x/composer/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/MultiColumnWizardHelper.php" and "C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao\core\system\modules\multicolumnwizard\MultiColumnWizardHelper.php", the first will be used.
Warning: Ambiguous class resolution, "MenAtWork\MultiColumnWizard\Event\GetOptionsEvent" was found in both "C:/Contao2Go/htdocs/vhosts/contao-3.5.x/composer/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/src/Event/GetOptionsEvent.php" and "C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao\core\system\modules\multicolumnwizard\src\Event\GetOptionsEvent.php", the first will be used.
Runonce created with 1 updates
```
- - -

bei den CE im Artikel mit dem Filter+Liste habe ich ein "Zurücksetzen eingefügt" - zunächst wird in der FE-Ausgabe nur die Section mit einem leeren Form-Tag ausgegeben - nachdem man das Template von mm_filter_default auf mm_filter_clearall umgestellt hat, funktioniert das

**=> Fazit:** funktioniert soweit **aber** das "Standardtemplate" sollte auf ```mm_filter_clearall``` stehen

Hinweis: https://github.com/MetaModels/core/issues/890

**Comment by stefanheimes** [comment]
Okay, also Bug behoben. 

#890 hab ich was zu geschrieben. Wegen dem "default" muss ich schauen. Wäre dann aber auch ein neues Ticket. :)

**Comment by xantippe** [comment]
die Templateumstellung ist wichtig - auf die Umschaltung kommt "niemand"

**Comment by discordier** [comment]
Anscheinend ist deine Installation noch nicht sauber. Du hast da immer noch einen contao core im vendor verzeichnis.

**Comment by xantippe** [comment]
ja ... unter composer gibt es - wieder " ein /contao/core - obwohl der schonmal weg war...

habe nach https://github.com/contao-community-alliance/composer-plugin/issues/44#issuecomment-151168549 das composer-plugin überschrieben/aktualisiert, ohne dass anschließend eine Änderung "zu sehen war" 

was nun zu tun?

**Comment by discordier** [comment]
Loesche aus deinem `composer/vendor` Verzeichnis das Verzeichnis `contao` komplett weg, anschliessned machst du mal einen dry-run. Da sollte er eigentlich dann einiges loeschen wollen.

**Comment by xantippe** [comment]
```dry-run``` == Testlauf?

**Comment by xantippe** [comment]
Ich habe eine Sicherungskopie eingespielt und das ganze nochmal durchlaufen:

* dev-hotfix-clearall ausgewählt
* in Expertenmodus ```"metamodels/core": "dev-hotfix-clearall as 2.0.0"```
* "Pakete aktualisieren"

=> CE "Zurücksetzen" angelegt - Ausgabe erscheint, wenn man (manuell) das Template auf ```mm_filter_clearall``` ändert

**Comment by xantippe** [comment]
habe aktualisiert auf
*  	metamodels/bundle_all 	dev-master (f5892747)
*  	metamodels/core 	2.0.0-alpha3

Der Fehler, dass das CE-Filterrest **nicht angezeigt** wird ist noch oder wieder da :-(

**Comment by stefanheimes** [comment]
Das nicht gut. Test bei mir liefen ich schau die aktuelle Version noch einmal an.

**Comment by xantippe** [comment]
ist den der Hotfix in die alpha3 mit rein gekommen?

**Comment by stefanheimes** [comment]
Laut commit logs ja.

**Comment by xantippe** [comment]
alpha6 getestet
* Modul: im FE ja
* CE: im FE nein

es wird nur folgendes ausgegeben
```
<section class="ce_metamodels_frontendclearall block">
<form method="post">
<input type="hidden" value="63d4347ab09eff364e927a8174bec5ff" name="REQUEST_TOKEN">
<input type="hidden" value="" name="FORM_SUBMIT">
<div class="formbody"> </div>
</form>
</section>
```

**Comment by xantippe** [comment]
nochmal ein paar debugausgaben eingestreut...

in
```
    public function generateReal()
    {
        // Fallback template.
        if (!empty($this->metamodel_fef_template)) {
            $this->strTemplate = $this->metamodel_fef_template;
        }

        return parent::generate();
    }
```
laufen beide Aufrufe in das Fallback... 
bei mod ist das
```[metamodel_fef_template] => mm_filter_clearall```
und bei ce
```[metamodel_fef_template] => mm_filter_default```

... letzteres dürfte falsch sein

**Comment by stefanheimes** [comment]
Die Elemente geben alles über InsertTags aus. Eigentlich sollte das laufen. Tat es bei meinen test. Okay ich schau nochmal nach.

**Comment by xantippe** [comment]
ich glaube, ich habe den "Fehler" gefunden - beim CE **MUSS** man das Template im BE umschalten, da das auf ```mm_filter_default``` steht
