### ISSUE TITLE
metamodel_sort_override Parameter ohne Binnenmajuskel

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#889]
die URL- bzw. GET-Parameter auf case-insensitive umstellen

**Comment by discordier** [comment]
Warum? Da schreien dann doch gleich wieder die SEO spezialisten.

Zumal das bei dem Attributsnamen nicht gehen wird (btw. sind doch yberall in Contao die parameter case sensitive?)

**Comment by xantippe** [comment]
Alternative:
* case-sensivive lassen 
&&
* Binnenmajuskel raus
;-)

**Comment by discordier** [comment]
Dann wird nichts mehr gefunden, weil case sensitive gesucht wird und lowercase die Werte kommen. :)

**Comment by xantippe** [comment]
geht das nicht auch so:
https://github.com/MetaModels/core/blob/fa305c9d3ce55fa0a7c92b37599e09b5c46161a1/src/MetaModels/FrontendIntegration/HybridList.php#L93-L100

```
        if ($this->metamodel_sort_override) {
            if (\Input::get('orderBy') || \Input::get('orderby')) {
                $sorting = \Input::get('orderBy') ? \Input::get('orderBy') : \Input::get('orderby');
            }
            if (\Input::get('orderDir') || \Input::get('orderdir')) {
                $direction = \Input::get('orderDir') ? \Input::get('orderDir') : \Input::get('orderdir');
            }
        }
```

**Comment by discordier** [comment]
Sollte man dann wenn gleich ganz konfigurierbar machen...

**Comment by zonky2** [comment]
> Sollte man dann wenn gleich ganz konfigurierbar machen...

was soll(te) daran konfigurierbar sein?

**Comment by discordier** [comment]
Du definierst hier nun 2 Schreibweisen, anschliessend kommt der naechste und will lieber `ORDERBY` haben, oder gleich `sortierung` oder `sortiert-nach`... du siehst das Problem?

**Comment by zonky2** [comment]
o.k.

**Comment by discordier** [comment]
DAS ist nochmal was anderes, da muss man das wieder mehrsprachig machen, vgl. hierzu auch die parameter namen der Filter.
