### ISSUE TITLE
Kommentar Interfaces anpassen

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#892]
https://github.com/MetaModels/core/blob/master/src/MetaModels/IFactory.php
- bei byId und byTableName im @deprecated das createMetamodel zu getMetaModel
- im "Einleitungstext" Beispiel ändern "and call {@link \MetaModels\IFactory::byTableName()"
- getServiceContainer ermittelt nicht den "event dispatcher" sondern den "service container"

https://github.com/MetaModels/core/blob/master/src/MetaModels/IMetaModel.php
- Einleitungstext: statt MetaModelFactory::byTableName -> \MetaModels\IFactory::getMetaModel($metaModelName)

**Comment by discordier** [comment]
The `IFactory` has been fixed. `IMetaModel` is still open.

**Comment by zonky2** [comment]
fixed https://github.com/MetaModels/core/pull/1066
