### ISSUE TITLE
Panel-Layout: limit wird nicht angezeigt und nur eine Seite sichtbar

### ISSUE THREAD

**Issue by pointout** [MetaModels/core#893]
Ich habe ein mehrsprachiges MM mit Varianten.
Bei Panel-Layout ist limit angegeben, wird aber nicht gezeigt. Das Listing zeigt nur eine Seite. Andere Datensätze können nur über Suche und Filter gelistet werden. 

auch bei MM ohne Varianten mit Rendermode "hirachical" gibt es kein limit.

Suche zeigt alle Attribute im Select, obwohl nur einige als suchbar makiert sind.

Contao 3.5.2
metamodels/core 	dev-master (ae034471)
contao-community-alliance/dc-general 	dev-develop (388f7a7c) → 2.0.x-dev

**Comment by pointout** [comment]
Wenn ich die Varianten ausschalte, funtkioniert es. Auch das Sorting funktioniert dann. 
Suchselect hat aber noch immer alle Attribute.

**Comment by MacKP** [comment]
Liegt am Rendermode. Da kann man nicht Limitieren. Kann man in der Seitenstruktur ja auch nicht ;-)
