### ISSUE TITLE
Inconsistent "varbase" type

### ISSUE THREAD

**Issue by richardhj** [MetaModels/core#897]
Hello,
you perform a identical string check (=== '0') for the function "isVariant" https://github.com/MetaModels/core/blob/master/src/MetaModels/Item.php#L236 but set a integer 0 for the function "varCopy" https://github.com/MetaModels/core/blob/master/src/MetaModels/Item.php#L464
This leads to an error in my development environment.

**Comment by discordier** [comment]
New code locations:
https://github.com/MetaModels/core/blob/bf78e1e8f8e576e4871f67ff22a13f4cd82da65c/src/MetaModels/Item.php#L263
https://github.com/MetaModels/core/blob/bf78e1e8f8e576e4871f67ff22a13f4cd82da65c/src/MetaModels/Item.php#L277
https://github.com/MetaModels/core/blob/bf78e1e8f8e576e4871f67ff22a13f4cd82da65c/src/MetaModels/Item.php#L490
https://github.com/MetaModels/core/blob/bf78e1e8f8e576e4871f67ff22a13f4cd82da65c/src/MetaModels/Item.php#L493

**Comment by xantippe** [comment]
wenn ich das richtig verstehe, müsste es so aussehen?
```diff
    public function varCopy()
    {
        $objNewItem = $this->copy();
        // If this item is a variant base, we need to clean the variant base and set ourselves as the base.
        if ($this->isVariantBase()) {
            $objNewItem->set('vargroup', $this->get('id'));
-           $objNewItem->set('varbase', 0);
+          $objNewItem->set('varbase', 1);
        } else {
            $objNewItem->set('vargroup', $this->get('vargroup'));
            $objNewItem->set('varbase', 0);
        }
        return $objNewItem;
    }
```

**Comment by richardhj** [comment]
Hi, *entweder* folgende Änderung
```php
public function isVariant()
    {
old: ~~return $this->getMetaModel()->hasVariants() && ($this->arrData['varbase'] === '0');~~
new:   return $this->getMetaModel()->hasVariants() && ($this->arrData['varbase'] === 0);
    }
```
*oder* folgende Änderung
```php
public function varCopy()
    {
        $objNewItem = $this->copy();
        // If this item is a variant base, we need to clean the variant base and set ourselves as the base.
        if ($this->isVariantBase()) {
            $objNewItem->set('vargroup', $this->get('id'));
old:  ~~$objNewItem->set('varbase', 0);~~
new:    $objNewItem->set('varbase', '0');
        } else {
            $objNewItem->set('vargroup', $this->get('vargroup'));
old:  ~~$objNewItem->set('varbase', 0);~~
new:    $objNewItem->set('varbase', '0');
        }
        return $objNewItem;
    }
```
Je nachdem, ob ein integer oder ein string mehr Sinn macht.

**Comment by xantippe** [comment]
ahh - o.k.

**Comment by zonky2** [comment]
@richardhj PR is merged https://github.com/MetaModels/core/commit/37efdef5493ea7995f5f9a18e77f221155ab028e pls test again...

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@richardhj could you please have a final look at this and tell if your issue has been resolved?
