### ISSUE TITLE
BE-Formular Pflichtfeld bei Decimal-Attribut

### ISSUE THREAD

**Issue by Hoch-3** [MetaModels/core#898]
Wenn ein Decimal-Attribute in der Eingabemaske als Pflichtfeld definiert wird, dann klappt das nicht.

**Comment by asaage** [comment]
https://github.com/MetaModels/attribute_decimal/issues/8

**Comment by Hoch-3** [comment]
Und das führt dann wieder zum Fehler 1 hier:
https://github.com/MetaModels/core/issues/861

**Comment by asaage** [comment]
Ist das so?
Auf die Idee einen solchen Zusammenhang herzustellen bin ich noch nicht gekommen.
Ich vermute mal ```(0 != null)```

**Comment by Hoch-3** [comment]
Konkret zeigt es 0 statt den Attribut-Namen an. Da 0 in der Reihenfolge der erste Eintrag ist.

**Comment by xantippe** [comment]
@Hoch-3: PR https://github.com/MetaModels/attribute_decimal/pull/9 zum Testen

**Comment by xantippe** [comment]
gefixt mit https://github.com/MetaModels/attribute_decimal/commit/126f8194385c4e4172872a8db0d7b221c1e998c8
