### ISSUE TITLE
Filter kopieren -> Neuer Filter ist ohne Filterregeln

### ISSUE THREAD

**Issue by AgentCT** [MetaModels/core#899]
Möchte man einen Filter mit entsprechenden Filterregeln kopieren, läßt sich dieser Filter kopieren, aber die entsprechenden Filterregeln werden nicht mit kopiert. Der neue Filter ist leer.
Dadurch macht die Kopierfunktion einen Sinn...

**Comment by asaage** [comment]
siehe hier #385

**Comment by AgentCT** [comment]
Uups... dabei hatte ich doch die Suche verwendet.

**Comment by xantippe** [comment]
@AgentCT wie hast Du das Filterset kopiert? in meiner aktuellen Version (2.0.0-alpha6) gibt es in der Auflistung der Filtersets keine Icon zum Kopieren - nur über mehrere Bearbeiten ist eine Kopie möglich - welche dann wie beschrieben ohne die Filterregeln ist

**Comment by xantippe** [comment]
aktuell können mehrere Filterregeln von einem Filterset zum nächsten kopiert werden - siehe #385

**Comment by xantippe** [comment]
geschlossen, da doppelte Fragestellung => #385
