### ISSUE TITLE
[WIP] Alias aware interface

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#904]
I want to add a new interface. The AliasAware Interface. This interface should identify attributes which have a alias value like the tags and selects. 

I want to add at the momtent 3 functions. 
- getAliasValue()
  - Returns the value from the alias field.
- isAliasMetaModelsAttribute()
  - Check if the field is a MetaModels attribute
- parseAlias($format = 'text')
  - If we have a MetaModels attribute parse it and return the value.

Did i miss some functions?

**Comment by discordier** [comment]
Where do you pass the id/data?
Please add code to the ticket and/or create a feature branch. I'd prefer code snippet here to discuss.

**Comment by stefanheimes** [comment]
https://github.com/MetaModels/core/commit/21a2b1ea3e8985390b082486508fb13cb88927af

Should i create a mockup for a attribute ?

**Comment by discordier** [comment]
Yes, please do, as your implementation does not work ;)
Where do you pass the data or id?

**Comment by stefanheimes** [comment]
Hmm jip, i have a wrong idear, i will change it.

**Comment by stefanheimes** [comment]
Okay new version AND the first implementation for the selects. https://github.com/MetaModels/attribute_select/commit/310792cd45c7eeb6ccc210392169bb61942a5dbe Not yet testet just some idears.

**Comment by xantippe** [comment]
@stefanheimes Ticket noch aktuell?

**Comment by xantippe** [comment]
siehe auch https://github.com/MetaModels/core/tree/feature-aliasaware

**Comment by zonky2** [comment]
Implemented in MM 2.2
