### ISSUE TITLE
Frontend Filter -> fehlender Count bei Leerer Auswahl

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#906]
BE Filtersetting:
 ![image](https://cloud.githubusercontent.com/assets/4138336/11062810/6be24a6e-87b2-11e5-88ac-540e7e5aa2ed.png)

FE Filter:
![image](https://cloud.githubusercontent.com/assets/4138336/11062844/a7140e56-87b2-11e5-859d-50542727533e.png)

Da müsste doch die Gesamtzahl zwischen die Klammern meine Ich.

Oder ist das so gewollt?
Dann setzt ich `.doNotFilter .count {display:none;}`

**Comment by xantippe** [comment]
siehe auch #312

**Comment by asaage** [comment]
ahh ja

**Comment by zonky2** [comment]
Die Anzeige wird bis auff weiteres nicht mehr unterstützt - siehe https://github.com/MetaModels/core/issues/906
Die Werte werden noch übergeben, so dass die Templates selbständig angepasst werden können.
