### ISSUE TITLE
Allow predefined or choseable sorting in Backend

### ISSUE THREAD

**Issue by amenk** [MetaModels/core#907]
I think currently it is not possible to sort the backend lists of metamodels by a specific column.

Can this be implemented? How can it by done?

Bonus: If showColumns is on, it would be great if the user can choose the column to sort by from the header (just like Contao core allows for example at /contao/main.php?do=user)

**Comment by asaage** [comment]
Define sorting-options in the input-screen
![image](https://cloud.githubusercontent.com/assets/4138336/11091316/8f23cf4e-8879-11e5-9892-48991846c29e.png)
That works for Listview and showColumns though it does not consider sorting by multiple colums.
I can even switch between manual and predifined sorting.
Add "sort" in the Panel layout.

**Comment by amenk** [comment]
Okay, thanks. That helps already.
But I was talking about setting the sort column "on-the-fly" when listing the metamodel entries in the backend. Useful for large lists.

**Comment by asaage** [comment]
not shure what you mean with "on-the-fly"...
If you need the select in the header of the page use the first icon.
If you like some kind of table sorting like the ce_table offers for the Frontend via js (by clicking on any table header cell) that is a different story.

**Comment by amenk** [comment]
Yes I am talking about the header. Like in users. What do you mean with "the first icon"? 

![screenshot_auswahl_003](https://cloud.githubusercontent.com/assets/1087128/11092633/1ad154c0-8885-11e5-8020-8981f40abd15.png)

**Comment by asaage** [comment]
"first icon": the pencil here https://github.com/MetaModels/core/issues/907#issuecomment-155767350
But according to your screenshot you already figured it out.

**Comment by amenk** [comment]
Nope - that screenshot is from the Users list, not a metamodels one.
But now I figured it out. The panel layout after clicking the pencil icon is the important option. Thanks.
