### ISSUE TITLE
Show Timestamp (`tstamp`) in Backend Lists

### ISSUE THREAD

**Issue by amenk** [MetaModels/core#908]
For a metamodel entry, the timestamp of creation is already stored in the `tstamp` field in the database.

How can this be displayed in the backend?

**Comment by amenk** [comment]
I have a workaround/hack for this:

* create Date+Time field `tstamp_` via Backend
* go to DB table `tl_metamodel_attribute` and rename it to `tstamp`

Which side-effects do I have to expect?

But I think it would be nice, if the `tstamp` column could be predefined / allowed to add via backend.

**Comment by xantippe** [comment]
zum Thema #592

**Comment by amenk** [comment]
Duplicate von #685
