### ISSUE TITLE
Missing translations (MSC.save, MSC.saveNclose etc.)

### ISSUE THREAD

**Issue by amenk** [MetaModels/core#909]
I am using the latest `metamodels/core (dev-master 0b68f4a)`, but translations in the backend are missing, even they seem to be in Contao core (Contao 3.4.5).

See screenshot
![screenshot_auswahl_001](https://cloud.githubusercontent.com/assets/1087128/11090602/71f253f6-8873-11e5-96f6-45f1356e1583.png)

**Comment by asaage** [comment]
that looks like you are missing the contao language-pack as metamodel specific labels are shown correctly.

**Comment by amenk** [comment]
I know that this are basically core strings, but the language pack is there and also working for other pages with the same buttons.

**Comment by asaage** [comment]
now i am afraid - i was going to update my project with the latest nightly...

**Comment by amenk** [comment]
What do you mean?

**Comment by asaage** [comment]
I would not want to mess up my working installation by updating metamodels if that bug is contained.
But i will backup and give it a try now.

**Comment by discordier** [comment]
I wonder what is going on there, as we did not tamper with the translator recently.

@asaage please give us a heads up if the problem occurs on your side.

**Comment by asaage** [comment]
<-- versuchskaninchen :rabbit:
ok

**Comment by amenk** [comment]
Hast du es schon getestet? Bei dir geht es? Kannst du deine `composer.lock` posten?

**Comment by amenk** [comment]
Das ganze läuft via `\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask::getButtonLabel` - ist also eher ne DcGeneral Sache, aber wir können das gerne hier weiter diskutieren.

**Comment by asaage** [comment]
contao-community-alliance/dc-general	dev-develop @ b1bf67
metamodels/core	dev-master @ 0b68f4
![image](https://cloud.githubusercontent.com/assets/4138336/11095377/f9101528-8894-11e5-84ac-47825672b68b.png)
alles schick...
composer zickt mir zu sehr rum. Ich nutze ganz oldscool nightly.tng und totalcommander filesyncronisation.
```composer.lock``` ist also mehr oder weniger im Werszustand

**Comment by asaage** [comment]
der String "Speichern und neu" kommt in den Dateien von Metamodels nicht vor - ich tippe also stark auf ein Problem mit deiner Contao-Installation.

**Comment by amenk** [comment]
Das vermute ich auch :-(

**Comment by asaage** [comment]
check for
system/modules/core/languages/de/default.xlf

**Comment by amenk** [comment]
This stuff is fine - also in other backend pages, the buttons are fine. I found that DCGeneral is using an own layer on top of the TL_LANG. Stuff seems to go wrong here: `\ContaoCommunityAlliance\Translator\Contao\LangArrayTranslator::getValue`

**Comment by asaage** [comment]
are you using a different dcg than b1bf67

**Comment by amenk** [comment]
I found the problem. Is because of a module we developed:

https://github.com/iMi-digital/imi_conditional_content/blob/master/contao/languages/de/default.php

Seems to be a bad idea to write to ['TL_LANG']['default'] - this causes problems around here: https://github.com/contao-community-alliance/translator/blob/master/src/ContaoCommunityAlliance/Translator/Contao/LangArrayTranslator.php#L61

Solution will be to change my module.

Thanks for all your efforts!

**Comment by discordier** [comment]
Yes, sadly these language domains are "special" for compatibility reasons.
