### ISSUE TITLE
[2.0.0.alpha5] Fatal error... SubSystemBoot not found

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#911]
```
Fatal error: Class 'MetaModels\Helper\SubSystemBoot' not found in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\metamodels\config\config.php on line 235
```
nach Aktivierung von alpha5 in Composer

Nachtrag: Ordner
```composer\vendor\metamodels\core\``` ist nicht mehr da..??

**Comment by discordier** [comment]
Muss aber da sein?

**Comment by xantippe** [comment]
ich habe noch zwei andere Installationen geupdatet - ohne Fehler...

sehr merkwürdig, dass der Ordner raus gekickt wurde... => ich beahlte das im Auge!
