### ISSUE TITLE
Einblenden von Attributen über Auge mit FontAwesome

### ISSUE THREAD

**Issue by lucdesign** [MetaModels/core#912]
Einblenden von Attributen über Auge funktioniert nicht, wenn das Backend Theme Font Awesome verwendet. Ein Javascript-Fehler wird angezeigt in BackendGeneral, toggleVisibility() auf Zeile 116.

Ausblenden geht aber!

Im übrigen Backend gibt es keine Probleme dieser Art mit dem Theme.

**Comment by discordier** [comment]
Welcher Fehler? Wie kann man die Konfiguration nachstellen?

**Comment by lucdesign** [comment]
Contao 3.5.4
MM metamodels/budle_all 2.0.0 über Paketverwaltung gezogen ().
BE-Theme contao-legacy/sb-admin (https://github.com/Zeromax/contao-sb-admin)
Z.B. MM Eingabemaske bearbeiten:
![bildschirmfoto 2015-11-22 um 21 48 07](https://cloud.githubusercontent.com/assets/1125564/11326181/c2f498b6-9162-11e5-8f27-6661c0eb78c8.png)
Grünes Auge klicken deaktiviert das Eingabefeld. Rotes Auge bringt JS-Fehler (hier aus dem Safari-Debugger):
![bildschirmfoto 2015-11-22 um 21 49 53] https://cloud.githubusercontent.com/assets/1125564/11326194/280350bc-9163-11e5-8db4-a6b5b0b29139.png)
Seite wird immer neu geladen, daher ist die Konsolenmeldung nur ganz kurz zu sehen.
Gleiches Problem beim Aktivieren/Deaktivieren von Datensätzen (also überall, wo MM das Auge in BE-Listen verwendet.
Deaktivieren muss man dann z.B. in "default" oder "flexible".
Danke fürs Ansehen!

**Comment by discordier** [comment]
Codestellen die relevant sind:
- Rewrite der images auf `<i>` fyr FA https://github.com/Zeromax/contao-sb-admin/blob/e5df43ca26fb9c01873626820b0274fefa6cd6c2/contao/system/modules/sb-admin/src/Image.php#L97
- Handling der umgeschriebenen icons https://github.com/Zeromax/contao-sb-admin/blob/e5df43ca26fb9c01873626820b0274fefa6cd6c2/js/components/contao/core-uncompressed.js#L467

Die Frage ist nun, ob es nicht sinnvoller ist, die im backend theme zu beheben anstatt in DCG.
//cc @Zeromax, @stefanheimes, @dmolineus

**Comment by lucdesign** [comment]
Bei zeromax hab ich das Issue schon deponiert. sb-admin hat wohl noch mehr Probleme mit MM's Icons. Schade, denn das "default" theme ist nicht sehr verkaufsfördernd.

**Comment by discordier** [comment]
Nunja, sagen wir mal so, es sollte theorethisch mit allen custom icons Probleme geben die eine action haben, nur hat MM davon halt ne ganze Menge. :)

**Comment by cliffparnitzky** [comment]
Ich bin gegen eine Änderung im DCG:

a.) MM setzt auf Contao auf, nicht auf sb-admin
b.) die Contao Core Icons sollen demnächst geändert werden
c.) es handelt sich hier um eine Einzelproblem, was eher nicht die breite Masse betrifft
usw.

**Comment by Zeromax** [comment]
Ich stimme @cliffparnitzky zu. Es ist ein Problem von sb-admin.

@discordier Das Ticket kann aus meiner Sicht geschlossen werden. Es muss in meinem Theme angepasst und unterstützt werden. Das ist definitiv kein MetaModels Problem.
Es war mir klar dass es Probleme geben wird mit MetaModels. Aber die habe ich mal in kauf genommen ;).
@lucdesign hat auch ein Ticket angelegt: https://github.com/Zeromax/contao-sb-admin/issues/26

**Comment by cliffparnitzky** [comment]
@Zeromax Danke :+1:

**Comment by discordier** [comment]
Dann sind wir uns ja alle einig. :)

**Comment by lucdesign** [comment]
Yep.
