### ISSUE TITLE
FR: zus. Parameter bei Filter: kein Label + HTML5 Platzhalter

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#916]
Bei den Filtereinstellungen wäre 
- [x] die Option bei der Ausgabe das Label zu unterdrücken (Checkbox)
- [x] Eingabemöglichkeit eines HTML5-Platzhalter-Textes (bei Textfeldern)

schön.

(Labels können zwar per CSS ausgeblendet werden - die Möglichkeit des Ab/Zuschaltens wäre aber besser)

**Comment by xantippe** [comment]
Mit den zwei PR wird den Einstellungen für die Filterregel "Text" ein Feld für einen HTML5-Placholder-Text mit max 255 Zeichen hinzugefügt, welches im FE in dem Eingabefeld eingeblendet wird.

**Comment by zonky2** [comment]
in MM 2.2 gibt es beide Optionen
