### ISSUE TITLE
Expensive converting of uuids to paths

### ISSUE THREAD

**Issue by dmolineus** [MetaModels/core#917]
The converting always call the Dbafs::addRessource() method.
https://github.com/MetaModels/core/blob/master/src/MetaModels/Helper/ToolboxFile.php#L793-L805

With Contao 4.1 it will always refresh the keys. Following described check should be added.
https://contao.org/de/news/contao_4-1-beta1.html

**Comment by discordier** [comment]
Yep, as soon as we are moving to C4 we will have to change several other things like that as well. Thanks for pointing out.

**Comment by dmolineus** [comment]
Unfortunately it's already a huge perfomance issue. `Dbafs::addRessource` always triggers the updateFolderHashes which always does a full sync of the file system. Having a large filesystem with > 200.000 files this really slows down the system.

**Comment by dmolineus** [comment]
:+1:

**Comment by discordier** [comment]
Do you have any numbers how big the impact was? Like comparing previous to after loading times?
