### ISSUE TITLE
tree_xtnd toggler injects at wrong dom-position

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#918]
That seems do be a generalDriver_src.js bug

mode:6
action:DcGeneralLoadSubTree

in Hierarchy-input-screen extending a node with 30+ childnodes places them on-top of the parent and not below. If you refresh the page the parent-node is expanded correctly.

![image](https://cloud.githubusercontent.com/assets/4138336/11432206/37c00e52-94a9-11e5-815d-b469798f4544.png)wrong     ![image](https://cloud.githubusercontent.com/assets/4138336/11432224/7ad18c20-94a9-11e5-906c-79d4a0a63d84.png)correct

**Comment by stefanheimes** [comment]
Duplicate: #667
Commit which cause the error: https://github.com/contao-community-alliance/dc-general/commit/ba80328212aa905fefdf31b1ed88becc2066eb15
Wrong Repro see: https://github.com/contao-community-alliance/dc-general/issues/168

**Comment by xantippe** [comment]
aktueller Workaround: Seite neu laden (reload)

**Comment by discordier** [comment]
Bitte in contao-community-alliance/dc-general#89 weiter.
