### ISSUE TITLE
Bug: Anlegen eines MetaModel bei "frischem" MM ist nur mit "Workaround" möglich

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#922]
Der Bug ist bis 2.0.0-alpha6 (alpha7 s.u.) enthalten - von wann ab ist schwer zu sagen

Hat man ein "frisches" MetaModels - also ohne angelegtes MetaModel - kommt man nach Klick auf "Neues MetaModel" weder in die Eingabemaske noch erscheint die Klemmmappe zum Einfügen.

Als Workaround gibt es verschiedene Varianten - bei allen Varianten muss im MM-Header (gelbe Pfeile); ggf. mit Umschaltung von Sortieren auf "Name" oder auf "Sortierung".

siehe
https://community.contao.org/de/showthread.php?60259-Neues-Metamodel-anlegen-funktioniert-nicht-!
https://community.contao.org/de/showthread.php?60326-Anlegen-von-MM

In dem Zusammenhang wird sicher auch der Bug stehen, das die Sortierung (Hamburger) auch erst nach dem "Aktualisieren" erscheinen.

**Comment by dmolineus** [comment]
Welche Version des DCG ist installiert? Tritt dieses Verhalten sowohl mit beta30 und beta31 auf? Bitte mal beides Testen. Nach dem Installieren einer andere Version bitte die Session-Daten des Benutzers löschen und es dann probieren.

**Comment by xantippe** [comment]
Version wo ich es definitiv sagen kann ist "dev-develop @ d4342e" ("FTP-Installation")

bei einer "Composer-Installation" mit 2.0.0-beta31 (2a15786e) kann ich die MMs nur nach Klick auf "Aktualisieren" sortieren - erst dann erscheinen die "Hamburger"

**Comment by UlrichHolland** [comment]
Für die 2.0.0-beta31 kann ich dieses Verhalten ebenfalls bestätigen.

**Comment by jgrotstabel** [comment]
Ich kann den Fehler bestätigen und den Workaround auch :-)
Habe die Version dev-master @ 6f6721 unter Contao 3.5.4 am laufen. Konnte nichts anlegen, nach umschalten auf Sortierung "Name" unter dem Menüpunkt "MetaModels" ging es ohne Probleme.
Könnte mir vorstellen, dass man daran verzweifelt wenn man mit dem Contao-Forum und GitHub noch keinen Kontakt hatte.

**Comment by asaage** [comment]
Dass ich da nichtmehr sortieren kann ist mir auch schon aufgefallen - Danke für den Workaround mit den gelben Pfeilen.

**Comment by cliffparnitzky** [comment]
Der Bug ist in der alpha7 nachvollziehbar.

Im Sortiermodus "Sortierung" wird immer ein Einstiegspunkt benötigt benötigt ("Hinter einfügen ..."). Der fehlt beim initialen MetaModel.

Im Sortiermodus "Name" ist der Einstiegspunkt nicht notwendig, deshalb öffnet sich die Eingabemaske direkt.

**Comment by xantippe** [comment]
mit folgendem Bugfix zu lösen "Hotfix missing insert into icons"
=> zu beachten: https://github.com/contao-community-alliance/dc-general/pull/171#issuecomment-170285176
