### ISSUE TITLE
MM-latest Link list problem

### ISSUE THREAD

**Issue by Zeromax** [MetaModels/core#924]
### Following setup
* 3 Metamodels
* one is the Project 2 others are the tags
* Linklist filter

### Following Problem:
* call the page with the link list
* nothing selected, all links are generated fine
* select one tag -> the link generation for this active tag ist the current page like defined in the render setting, the param is missing

### Problem is here, followed up:
Get frontend filter Value
https://github.com/MetaModels/core/blob/a7678491f04983fce8abed17c9dd0c0096bd8637/src/MetaModels/Filter/Setting/Simple.php#L305
Check if it is active
https://github.com/MetaModels/core/blob/a7678491f04983fce8abed17c9dd0c0096bd8637/src/MetaModels/Filter/Setting/Simple.php#L156
-> It returns nothing. But why?

I need this link full generated and it is not important if it is active or not.

So if i click the same/active link again it is like "clear" the filter.

@discordier maybe you can explain it to me ;)

**Comment by discordier** [comment]
The tag links are "toggler". This means, when it is active, the generated link will not contain it anymore.

**Comment by Zeromax** [comment]
Ah ok. So is it possible to add the Link to the array to use it otherwise?
This could be usefull for a difrent user journey.

It could have both links in it:
* The Real Link
* The Toggle Link

So you can decide in the template which link to use? Not sure if this is be usefull.

Or feel free to close it ;) I have solved it in my project and injected the classes. So I am fine with this.

**Comment by xantippe** [comment]
@discordier close?

**Comment by discordier** [comment]
:+1
