### ISSUE TITLE
Backend - Probleme beim Filtern von Werten, die Anführungsstriche im Namen enthalten

### ISSUE THREAD

**Issue by AgentCT** [MetaModels/core#925]
Hat man einen Wert mit Anführungsstrichen wie zum Beispiel <b> Produktbeispiel "Berlin" </b>, den man mit der Funktion "Filtern" auswählt, so führen die Anführungsstriche dazu, dass der Filter keinen Eintrag in der Übersicht mehr anzeigt.

Contao 3.5.6
MM 2.0.0-alpha7

**Comment by xantippe** [comment]
funktioniert ``` Produktbeispiel \"Berlin\"``` ?

**Comment by AgentCT** [comment]
Ja, das Problem besteht weiter. Auch dann bleibt es dabei, dass beim Filtern kein Wert an die Übersicht übergeben wird.

**Comment by xantippe** [comment]
[_] JA = funktioniert
[_] JA = funktioniert nicht
?

**Comment by AgentCT** [comment]
Nein funkioniert noch nicht!

**Comment by xantippe** [comment]
und um welchen Filter handelt es sich Text, Auswahl...

**Comment by zonky2** [comment]
der "Fehler" liegt beim DCG - speziell beim Filter-Widget => In der Select-Option wird als value der entsprechende Wert, d.h. inkl. Anführungszeichen eingetragen; das führt zu dem Fehlverhalten.

Zur Lösung gibt es m.E. zwei Möglichkeiten:

1) Workaround: Anpassung des Filter-Templates (sofern bei dem Werten nicht auch noch Hochkommata vorkommen:

https://github.com/contao-community-alliance/dc-general/blob/master/contao/templates/dcbe_general_panel_filter.html5#L5
```diff
<div class="tl_filter tl_subpanel <?php echo $this->rowClass; ?>">
	<strong><?php echo $GLOBALS['TL_LANG']['MSC']['filter']; ?>:</strong>
	<select name="<?php echo $this->name; ?>" id="<?php echo $this->id; ?>" class="<?php echo $this->class; ?>">
		<?php foreach ($this->options as $arrOption): ?>
-			<option value="<?php echo $arrOption['value']; ?>"<?php echo $arrOption['attributes']; ?><?php if ($arrOption['value'] == $this->active): ?> selected<?php endif; ?>><?php echo $arrOption['content']; ?></option>
+			<option value='<?php echo $arrOption['value']; ?>'<?php echo $arrOption['attributes']; ?><?php if ($arrOption['value'] == $this->active): ?> selected<?php endif; ?>><?php echo $arrOption['content']; ?></option>
		<?php endforeach; ?>
	</select>
</div>
```

2) bei der Erstellung des Widget wird der Fall bzw. das Zeichen abgefangen - wobei hier das ```"``` gegen ein ```&quot;``` ausgetauscht werden muss

https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultFilterElement.php#L211

```diff
        foreach ($this->arrfilterOptions as $key => $value) {
            $arrOptions[] = array(
-                'value'      => $key,
+                'value'      =>  str_replace('"', '&quot;', $key),
                'content'    => $value,
                'attributes' => ($key === $this->getValue()) ? ' selected="selected"' : ''
            );
        }
```

dann geht´s auch mit "Gänsefüßchen" 
![shot173](https://cloud.githubusercontent.com/assets/1045318/14030865/309077fc-f20a-11e5-9582-75f3b314dacf.jpg)

**Comment by zonky2** [comment]
gefixt mit https://github.com/contao-community-alliance/dc-general/pull/302
