### ISSUE TITLE
Paletten and Legends -> parsing BE

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [MetaModels/core#926]
I have an multilanguage Installation and in my models I changed the languages in the rendersettings after I build my metamodels. The legends for the entry mask was already named. So now I wondered why there was only the last Legend with its fields got parsed in my entry mask :)

Now I found the reason for it. in the Database table tl_metamodel_dcasetting was no legendtitle in one of the available languages. In the Class Builder the palletes array key for the legend is generated by the legendtitle from database. So the loop found no name and always add the same key to the array: "_legend" Here you can see the part of it:
>  $this->translator->setValue(
                $legendName . '_legend',
                isset($legend['name']) ? $legend['name'] : '',
                $container->getName()
            );

https://github.com/MetaModels/core/blob/master/src/MetaModels/DcGeneral/Dca/Builder/Builder.php#L1473

I think it will be a great feature if you can add a serial Number for the legendkey als Fallback. So it will be less irritation for someone who has the case. Looked for the reason many hours^^

btw, sql to fix the problem in the database:
>UPDATE tl_metamodel_dcasetting SET legendtitle = REPLACE(legendtitle, '2:"de"', '5:"de-DE"')

**Comment by MoniqueHahnefeld** [comment]
@discodier Äähm, maybe I'm wrong, but isn't it the same  with:
$strLegend = 'legend' . (count($this->legends) + 1); 
The count of legends in the rendering view will be the same in each item of the loop or not? =)

**Comment by xantippe** [comment]
@MoniqueHahnefeld ist die Sache nun damit gefixt?
