### ISSUE TITLE
Auswahlliste/Radiobuttons zeigen nur den letzten Wert einer Liste

### ISSUE THREAD

**Issue by mosesontheweb** [MetaModels/core#927]
Ich habe ein Metamodel angelegt, das für bestimmte Attribute fremde Werte von anderen Metamodels (ich nenne sie Supporting Models) verwenden, z.B. Werte wie Sommer, Winter, oder Wettbewerbsarten ( Datensätze).

Mir ist in der BE Eingabemaske ausgefallen, dass ich im Dropdown-Feld bzw. in den Radiobuttons nur den letzten jeweils Wert der Werteliste sehe.

Z.B. sieht Wettbewerbsarten so aus:
Solo
Duo
Trio
Mixed
Mannschaft
Zielbewerb 

Somit sehe ich im Dropdown in der Eingabemaske nur den Wert Zielbewerb, alles andere ist nicht auswählbar.

Warum das so ist, kann ich leider nicht sagen. Von den Definitionen her habe ich das mit anderen von mir erstellten Metamodels, die ziemlich genauso funktioneren, verglichen und konnte keinen Unterschied erkennen.

Gruß, Thomas

**Comment by discordier** [comment]
Ich verstehe nicht genau was du damit meinst. Kannst du uns evtl. Details deiner Konfiguration und Screenshots zukommen lassen?

**Comment by cliffparnitzky** [comment]
Im Grunde wäre es doch gut gewesen, wenn du diese Frage im Contao Forum gestellt hättest, weil es wohl kein Bug ist, sondern eher Anwenderfehler. Dafür am besten nächstes Mal hier eine Thread aufmachen: https://community.contao.org/de/forumdisplay.php?149-MetaModels

Ich gehe hier davon aus, dass bei deinem Attribut der verwendete Filter dafür sorgt, dass nicht alle Daten angezeigt werden. Schau doch mal in die Attributkonfiguration.

**Comment by mosesontheweb** [comment]
Ich hab beide Kanäle versucht. Ich muss mich entschuldigen, dass ich noch nicht geantwortet habe, aber ich bin zur Zeit krank und habe daher keine weiteren Schritte unternommen. Screenshots folgen.

Die Attributkonfiguration habe ich mir angesehen für die jeweiligen Attribute, die als Dropdown (Select) verwendet werden, es sind keine Filter darauf zugewiesen.

Gruß, Thomas

**Comment by cliffparnitzky** [comment]
Ah ja, alles klar. Dann würde ich trotzdem vorschlagen, dass im Forum weiter gemacht wird und du das Ticket schließt. Sollte es sich dann doch zeigen, dass es sich hierbei um einen Bug handelt, kann man es ja wieder aufmachen.

Forum-Thread: https://community.contao.org/de/showthread.php?60393-Auswahllisten-und-Radio-Buttons-zeigen-nur-den-letzten-Eintrag

**Comment by xantippe** [comment]
Im Forum wurde das Problem nicht weiter beantwortet bzw. von @mosesontheweb erfolgte keine Rückmeldung => würde deshalb Issue schließen

**Comment by discordier** [comment]
Wie von @xantippe geschrieben, bitte im Forum erstmal weiter.

**Comment by mosesontheweb** [comment]
Hab leider erst heute die Screenshots posten können, sind schon drinnen.
