### ISSUE TITLE
Mandatory translated longtext fields are not validated

### ISSUE THREAD

**Issue by cliffparnitzky** [MetaModels/core#929]
It doesnt matter, if the field uses a tiny mce config or not. if it is empty, but marked as mandatory in the input screen, it is not validated.

Environment: Contao 3.2.20 + MetaModel 2.0.0-alpha8

**Comment by stefanheimes** [comment]
Environment: Contao 3.5.3 + MetaModel dev-branch based on the 2.0.0-alpha8 version 

Test with no tiny and empty field: Mandetory works.
Test with tiny and empty text: Mandetory works.

Please take a look in the HTML View from the tiny maybe you have some p-tags or span-tags in the text or some other non-printable chars.

If you say everything is okay i will test it with a Contao 3.2.x version.

**Comment by xantippe** [comment]
@cliffparnitzky kannst du das bitte mal checken?

**Comment by cliffparnitzky** [comment]
Jo, werde ich asap tun.

**Comment by cliffparnitzky** [comment]
So, hab es mit der alpha9 getestet. Leider geht es nicht. Es wird weder das "mandatory" Sternchen in der BE Maske ausgegeben, noch validiert. Tags oder ähnliches sind nicht im HTML enthalten.

**Comment by cliffparnitzky** [comment]
Hier noch meine Konfiguration als Screenshot: 
![mm_maske](https://cloud.githubusercontent.com/assets/1247552/12260354/c3f07114-b91b-11e5-81f8-bc4b4022412a.jpg)

**Comment by xantippe** [comment]
kannst Du zum Test in

https://github.com/MetaModels/attribute_translatedlongtext/blob/master/src/MetaModels/Attribute/TranslatedLongtext/TranslatedLongtext.php

ein ```mandatory``` einsetzen wie in

https://github.com/MetaModels/attribute_longtext/blob/master/src/MetaModels/Attribute/Longtext/Longtext.php#L49

**Comment by xantippe** [comment]
ahh.. dafür gibt es rte bei https://github.com/MetaModels/attribute_translatedlongtext/blob/master/src/MetaModels/Attribute/TranslatedLongtext/TranslatedLongtext.php **2x**

**Comment by cliffparnitzky** [comment]
Das guck ich mir mal an

**Comment by cliffparnitzky** [comment]
Japp, das ist die Lösung. Wenn man diese Code Stelle gemäß `attribute_longtest` anpasst wird sowohl das "mandatory" Sternchen eingeblendet als auch die Validierung korrekt durchgeführt.

**Comment by xantippe** [comment]
kannst Du einen PR machen?

**Comment by cliffparnitzky** [comment]
Ja ...

**Comment by xantippe** [comment]
super

**Comment by xantippe** [comment]
und, wie siehts aus?!

**Comment by cliffparnitzky** [comment]
ich warte eigentlich auf Zugriff ...

**Comment by xantippe** [comment]
vielleicht können wir das zum nächsten MM-Call (abschließend) klären... aber einen PR könnte man aber schon (vorher) machen... ;-)

**Comment by cliffparnitzky** [comment]
Ist gefixt und wird demnächst released.

**Comment by xantippe** [comment]
prima!

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cliffparnitzky could you please have a final look at this and tell if your issue has been resolved?

**Comment by cliffparnitzky** [comment]
@stefanheimes ReadyToMerge :wink:
