### ISSUE TITLE
Darstellungsproblem mit Sprachauswahl unter Mac OS X

### ISSUE THREAD

**Issue by cliffparnitzky** [MetaModels/core#930]
Im Safari 9.0.1 unter Mac OS X gibt es ein Darstellungsproblem mit dem Sprachauswahl-Button:

![problem mit sprachauswahl](https://cloud.githubusercontent.com/assets/1247552/11698650/00e4cb36-9ec0-11e5-8b29-757c23d4bb17.png)

Gefunden durch @frontendschlampe ... er wird sicher auch bei der Lösung unterstützen, da die Text Environtment nicht bei jedem zuhause auf dem Schreibtisch steht :wink: .

**Comment by stefanheimes** [comment]
Moin, jo im IE gibt es auch immer wieder Probleme.

**Comment by frontendschlampe** [comment]
Ich habe mir das gerade mal angeschaut: Ihr ändert die Größe vom ``.tl_language_panel .tl_select`` in der ``generalDriver.css``von Standard 116px auf 240px. Das eigentliche ``<select>`` was darunter liegt, hat zwar die selbe Klasse ``.tl_select``, aber hier ist im Standard die Anweisung drin ``.mac .tl_panel select { max-width: 164px; }`` und diese überschreibt natürlich eure Anweisung von ``.tl_language_panel .tl_select``

**Comment by discordier** [comment]
@frontendschlampe kannst du die `generalDriver.css` bitte mac-konform anpassen (so dass es gut aussieht)?

**Comment by xantippe** [comment]
@frontendschlampe **Achtung** bitte die SASS ändern https://github.com/contao-community-alliance/dc-general/tree/develop/contao/html/sass **und** die CSS

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cliffparnitzky could you please have a final look at this and tell if your issue has been resolved?
