### ISSUE TITLE
Items should have Magic Setters/Getters to Set/Get Data

### ISSUE THREAD

**Issue by amenk** [MetaModels/core#931]
Analogue to Standard Contao Models

Compare `\MetaModels\Item::set`
with `\Contao\Model::__set`

**Comment by stefanheimes** [comment]
Hi, 

first a question: why? 

We have a normal get and a normal set which to the same job! 

$item->get('MyAttribute');
$item->MyAttribute;

It's only 7 chars more and we have IDE support for auto-completion. 

By the way the IDE'S can work better with the normal get and set than with a magical. I can see all funktion with my IDE and read the phpdoc for it. It much easier for me than to work with a magical function.

**Comment by amenk** [comment]
Just as I wrote: I feel it is better if it is consistent with Contao Core models.

**Comment by discordier** [comment]
The anonymous properties have caused much pain for many developers in Contao back in the day.
Anonymous properties should be avoided if possible.

**Comment by stefanheimes** [comment]
I agree with discordier. Only because Contao do it, means not it is the best way. I don't like the magical functions. Sometimes there are helpful functions but not the getter and setter.

So I will close this ticket or have we to discuss it more?

**Comment by amenk** [comment]
My original point of view was just to have some kind of consistent - I was surprised as the magic getters did not work.
I am not sure if I like them though ... "Hassliebe" ..:-D Let's close it, there are for sure more important things to be done.
