### ISSUE TITLE
Newly local installed Contao 3.4 (or 3.5) + Composer + Metamodels core dev-master : MM doesn't work

### ISSUE THREAD

**Issue by JLBA** [MetaModels/core#932]
Hi,

I've tested MM with Contao 3.2 and MM Nightly build

Now, I want to try it on Contao 3.5 on my MAMP installation (PHP 5.5.23). I've installed Composer as suggested. Through Composer, I've installed Metamodels/core dev-master (a333cef3) and metamodels/bundle_all (2.0.0.) 

But impossible to create any MM. When I try, I only got this (see picture).

Thanks for your help.

![capture 2015-12-14 a 17 02 58](https://cloud.githubusercontent.com/assets/2730432/11786607/c52e6428-a287-11e5-933d-683b7d57c103.png)

**Comment by asaage** [comment]
known bug... #922
try clicking the yellow arrows

**Comment by JLBA** [comment]
Thanks for your answer. 

If you mean these yellow arrows ![reload](https://cloud.githubusercontent.com/assets/2730432/11788190/09814d22-a290-11e5-9fd6-97176f93c310.gif) this doesn't work.

**Comment by JLBA** [comment]
Sorry. It worked after sorting by name and then clicking on the double yellow arrows.

Thanks.
