### ISSUE TITLE
(kleiner) Bug: Eingabemaske: Guppierung/Sortierung: Zuweisung "Standard" mehrfach möglich

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#935]
in Eingabemaske: Guppierung/Sortierung ist Zuweisung "Standard" mehrfach möglich - prima wäre auch die Anzeige "[Standard]" in der Listenansicht

**Comment by discordier** [comment]
@stefanheimes shouln't this now be possible to avoid as you have implemented support for fallback in dc-general?

**Comment by zonky2** [comment]
add PR: https://github.com/MetaModels/core/pull/1001

**Comment by zonky2** [comment]
fixed in https://github.com/MetaModels/core/compare/hotfix-2.0.0-alpha11
