### ISSUE TITLE
Bug: Anzeigefehler im BE bei Renderlisting "Tabelle" und Sortierung mit einer Gruppierung: HTML-Table fehlt

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#936]
Ist in der Renderansicht einer Eingabemaske "Tabellenform" angegeben und eine Gruppierung ausgewählt, fehlt in der Anzeige die "HTML-Tabelle"

siehe Screenshots

![shot18](https://cloud.githubusercontent.com/assets/1045318/12011318/e3c648f6-acc8-11e5-87c5-cdfe0979c6f4.jpg)

::::::::::::::::::::::::::::

![shot19](https://cloud.githubusercontent.com/assets/1045318/12011326/1077ce60-acc9-11e5-8091-31fcd0345aa3.jpg)

**Comment by xantippe** [comment]
der "Fehler" liegt eher an dem bei der Anzeigekombination ausgewählten Template - ```dcbe_general_grouping``` in https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php#L276 welches mit der Tabellenansicht nicht zurecht kommt.

In dem Screenshot nochmal eine Zusammenstellung welche Anzeigenkombination möglich ist und welche sich ausschließt 

![shot127](https://cloud.githubusercontent.com/assets/1045318/13278965/ac51e47c-dad4-11e5-85cc-4f95eaf8aa22.jpg)

unter der Maßgabe, dass sich bei einer Gruppierung keine manuelle Sortierung vornehmen lassen kann - oder sollte das auch ermöglicht werden?

**Comment by zonky2** [comment]
look at https://github.com/contao-community-alliance/dc-general/issues/198

**Comment by zonky2** [comment]
gefixt https://github.com/contao-community-alliance/dc-general/issues/198#issuecomment-378856346
