### ISSUE TITLE
(kleiner) Bug: bei Render-Einstellung ist Auswahl "Template" nur bei erster Render-Einstellung auf metamodel_prerendered

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#939]
Bei Render-Einstellung ist Auswahl "Template" nur bei erster Render-Einstellung auf metamodel_prerendered -> ist schon eine Render-Einstellung vorhanden, steht die Auswahl bei "Template" auf "nix"

**Comment by stefanheimes** [comment]
Sollte mit der nächsten MM und DCG behoben sein.

**Comment by xantippe** [comment]
uff... zum Testen habe ich mit dem Label nur 5 Tage - welche Version(en) soll ich ziehen?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@xantippe could you please have a final look at this and tell if your issue has been resolved?

**Comment by discordier** [comment]
Works for me.
Every new rendersetting is defaulting to the prerendered template.
