### ISSUE TITLE
(kleiner) Bug: Anzeigeeinstellung  ODER und UND: Zusatzinfo korrigieren

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#940]
In den Anzeigeeinstellungen von ODER und UND erscheinen bei den zus. Angaben "falsche Infos" - siehe Screenshot. Hier sollten Angaben wie bei NICHT erscheinen.

Z.Z. ist es auch so, dass die Angaben erhalten bleiben, wenn eine Einstellung z.B. "Eigenschaftswert ist" in "UND" umgewandelt wird (Screenshot unterer Block).

![shot32](https://cloud.githubusercontent.com/assets/1045318/12084871/3e7a88a2-b2b9-11e5-8498-c14f54678db3.jpg)

**Comment by xantippe** [comment]
wird hiermit korrigiert
https://github.com/MetaModels/core/pull/950

**Comment by discordier** [comment]
Neuer PR: #953

**Comment by xantippe** [comment]
mit PR #953 geschlossen
