### ISSUE TITLE
Bug: "Eindeutige Werte" validiert Eingaben bei Speicherung nicht

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#942]
Die Option "Eindeutige Werte" bei den Attribut-Einstellungen validiert nicht - in ```tl_metamodel_attribut``` ist "isunique" für die Attribute auf 1

Getestet mit
* Text
* Dezimal
* Numerisch
* Datum

Zudem wird das Feld vom Typ "Text" mit Option "Eindeutige Werte" in der Eingabemaske als Pflichtfeld ausgewiesen (und behandelt) obwohl es nicht als solches aktiviert ist - oder ist das ein "Feature"? würde ja Sinn manchen...

core 2.0.0-alpha8 und dev-develop (194be166)
dc-general 	2.0.0-beta31

siehe auch https://github.com/MetaModels/attribute_numeric/issues/5

**Comment by discordier** [comment]
Dass es zum Pflichtfeld wird, ist korrekt. Wenn man eindeutige Werte haben will, dann muss man logischerweise auch einen eingeben, sonst kann er ja nicht eindeutig sein.

**Comment by xantippe** [comment]
o.k. zum Thema Pflichtfeld - die Validierung läuft aber nicht :-(

**Comment by discordier** [comment]
Und das ist ein bug. :)

**Comment by xantippe** [comment]
siehe DCG-Hotfix https://github.com/contao-community-alliance/dc-general/tree/hotfix-unique

**Comment by discordier** [comment]
Gemerged in contao-community-alliance/dc-general@8ca62c97ad78020e447d3876ba003d6653b7f529
