### ISSUE TITLE
(kleiner) Bug: in Eingabemaske steht "ID" doppelt da

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#945]
siehe u.a. im Screenshot #930

**Comment by xantippe** [comment]
Fehler gefunden: in https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php#L543-L551 ist das ```' ID '``` zu viel - das kommt schon im Language-String

**Comment by xantippe** [comment]
https://github.com/contao-community-alliance/dc-general/pull/173

**Comment by discordier** [comment]
merged

**Comment by xantippe** [comment]
in contao-community-alliance/dc-general dev-develop (3e64be33) gefixt
