### ISSUE TITLE
Alle XHTML-Tags in HTML(5)-Tags umwandeln

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#949]
In den Sprach-Arrays und ggf. in Templates und HTML-Ausgaben finden sich noch XHTML-Tags wie z.B. `<br />`

**Comment by stefanheimes** [comment]
Ist XHTML tot oder was macht Contao damit ?

**Comment by xantippe** [comment]
das BE ist HTML(5) und kein XHTML mehr...

**Comment by discordier** [comment]
Dennoch ist es meines Wissens nach nicht falsch. Nur nicht mehr notwendig. Ich schreibe auch in html5 noch valides XML

**Comment by zonky2** [comment]
Templates bleiben mit bestehenden XHTML-Tags
