### ISSUE TITLE
Bug: Standardwerte (default) für Attribute lassen sich über die dcaconfig nicht vorbelegen

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#954]
Standardwerte für die Dateneingabe im BE können aktuell nicht über die /system/config/dcaconfig.php per
`$GLOBALS['TL_DCA']['mm_mein-mm']['fields']['mein-attributname']['default'] = "Meine Vorgabe";`
nicht vorgegeben werden - sollte aber so funktionieren...

Offensichtlich wird die Datei nicht korrekt ausgewertet oder zu spät.

siehe auch
https://github.com/MetaModels/core/issues/224
https://community.contao.org/de/showthread.php?42326-Standardwert-setzen&p=332326&viewfull=1#post332326
https://community.contao.org/de/showthread.php?52330-attribute_timestamp-automatisch-belegen-gel%F6st&p=338363#post338363

**Comment by asaage** [comment]
Ich frag mich gerade, ob es überhaupt möglich ist, mittels dcaconfig.php irgendwas metamodelliges zu beinflussen und verknüpfe das mal mit #967

**Comment by stefanheimes** [comment]
Should be solved with https://github.com/contao-community-alliance/dc-general/commit/3be9c7e06325c9be3322513ff22d6e413a7306d4.

Should be available with the new version of the DCG 2.0.0-beta34.

**Comment by xantippe** [comment]
@asaage kannst Du das mal testen?

**Comment by asaage** [comment]
Frühestens zum Monatsende - sorry.

**Comment by xantippe** [comment]
Test:
dcaconfig.php:
```
<?php

// Put your custom configuration here

$GLOBALS['TL_DCA']['mm_mitarbeiterliste']['fields']['email']['default'] = "hier@home.de";
```
=>

![shot95](https://cloud.githubusercontent.com/assets/1045318/12949430/0dc7f93a-d008-11e5-9cce-f9e5bcacd840.jpg)

**Comment by stefanheimes** [comment]
Für das neue Select muss die ID als String angegeben werden dann geht das auch.

**Comment by xantippe** [comment]
* welche Version soll/kann ich testen?
* bei Tags dann im Array auch IDs?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@xantippe could you please have a final look at this and tell if your issue has been resolved?

**Comment by Teetrinker** [comment]
Sehr geehrte Damen und Herren

Danke für Ihre Nachricht. Bis zum 22. Februar lese ich E-Mails unregelmässig.

Ihre Nachricht wird nicht weitergeleitet. Gerne kümmert sich Peter Oberhänsli um Ihr Anliegen:
p.oberhaensli@webbaumeister.ch

In Fällen die dringend und wichtig sind, können Sie mir eine SMS auf 079 530 25 24 schreiben um auf ihr E-Mail hinzuweisen.

Mit freundlichen Grüssen
David Bopp

**Comment by xantippe** [comment]
kann man @Teetrinker nicht mal raus werfen - mit den ständigen Auto-Antworten ist das nervig!

**Comment by discordier** [comment]
Koennen wir nicht. Zumindest nicht ohne ihn komplett von allen unseren repos auszuschliessen

**Comment by Teetrinker** [comment]
Sorry Leute, bin in den Ferien...
on a sidenote: Gibt es denn keinen Weg Auto-Antworten und Git-Hub-Abos zu vereinen?

**Comment by discordier** [comment]
Das musst du deinen autoresponder fragen. Normalerweise sollte man da eine Blacklist eintragen koennen.
Der Sinn der autoresponder erschliesst sich mir jedoch allgemein nicht, oder schicken deine Kollegen bei Briefpost auch eine Antwort raus, dass du gerade nicht da bist und daher der Brief aktuell nicht bearbeitet wird? ;)

**Comment by Teetrinker** [comment]
Mein Anbieter bietet leider keine Möglichkeit zum Nicht-Versand des Autoresponders an bestimmte Adressen.

Sinn und Zweck? Kunden erwarten Antwort auf eine E-Mai innert 1-2 Tagen, man möchte aber mal für 1-2 Wochen offline sein können - diese Lücke füllt der Autoresponder.

Ich werde mal schauen ob ich meine Github-Mails auf eine andere Adresse leiten kann.

**Comment by zonky2** [comment]
Zur Info:

http://metamodels.readthedocs.io/de/latest/cookbook/panels/default-values.html
