### ISSUE TITLE
Metamodel list and \Controller::getFrontendModule()

### ISSUE THREAD

**Issue by Chibko** [MetaModels/core#955]
Hi,
I'm trying to display a Metamodel list Module with ajax on a page after i click a button.
For ajax request i use  the "simpleAjax" extension.
In the Metamodel list Module setting, if i left blank the "Render setting to display" in the Template settings , everthing works fine ! But if a choose a "Render setting to display", i get this message : "Template not found (it is maybe within a unreachable theme folder)
All my tempaltes files are in /templates…
any ideas ?

**Comment by Chibko** [comment]
Sorry i forgot, in my ajaxrequest class, i use this to get the module to display;

$myContent= \Controller::getFrontendModule(7);

**Comment by xantippe** [comment]
Hi Chibko,
do you mean "Render settings to **apply**"?

**Comment by Chibko** [comment]
![capture d ecran 2016-01-12 a 16 13 43](https://cloud.githubusercontent.com/assets/8981739/12267283/a4570904-b947-11e5-9d5e-f651160b5d18.png)

**Comment by Chibko** [comment]
Yes sorry it's render setting top apply. If set to "-" My Ajax request works fine but with another one, i get the error message…

**Comment by xantippe** [comment]
o.k. - I´m not sure, but a module without the "fontend rendering" have no information at the themes and the themes folder => you can only templates at the "themes root folder"

**Comment by Chibko** [comment]
So if i understand.
When i set '-' in Render settings to apply, and try to display the module in the Frontend with the \Controller::getFrontendModule(7) il works because because it takes to default templates "metamodel_prerendered.html5"
When i set 'Liste comparateur" in Render settings to apply, it doesn't works because the \Controller::getFrontendModule(7) can't get the html5 templates behind "Liste comparateur"
So \Controller::getFrontendModule(7) is not the correct way to display a Metamodel list module in frontend with a custom "Render settings to apply". Do you have an idea to achieve this ?

**Comment by xantippe** [comment]
hmmm... as a workaround you can update the complete site per ajax or you build a "hidden" site with a copy of your listing module - in this case, you use a "naked" fe_page and ask this site per ajax...

**Comment by Chibko** [comment]
OK, Thank you, il will try the naked fe_page, it's a good idea ! Thanks again.

**Comment by xantippe** [comment]
if you have no more questions, you can close your issue...
