### ISSUE TITLE
FR: Checkbox "Pflichtfeld" automatisch setzen, wenn "Eindeutige Werte" gesetzt

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#956]
Wird die Option "Eindeutige Werte" gesetzt, wir das entsprechende Feld automatisch als Pflichtfeld behandelt - in den Einstellungen der Eingabemaske ist dieses verhalten aber nicht erkennbar.

Deshalb sollte in der Liste auch das "[Pflichtfeld]" erscheinen und die Checkbox gesetzt sein - mit dem Attribut "disabled". 

Siehe Screenshots:

![shot68](https://cloud.githubusercontent.com/assets/1045318/12319030/56a209a8-ba9f-11e5-8878-98d49b42ef11.jpg)

:::::::::::::::::

![shot69](https://cloud.githubusercontent.com/assets/1045318/12319033/5ca52b50-ba9f-11e5-8af9-65b8cf959147.jpg)

**Comment by cliffparnitzky** [comment]
Oh ja, sehr gute Idee. Bin ich gerade auch drüber gestolpert.

**Comment by zonky2** [comment]
@cliffparnitzky kannst Du den "FR" übernehmen?

**Comment by cliffparnitzky** [comment]
ja, schaue ich mir mal an

**Comment by zonky2** [comment]
prima!

**Comment by zonky2** [comment]
wie weit ist die Sache gediegen..?

**Comment by cliffparnitzky** [comment]
Werde die Sache **asap** bearbeiten. Will und kann aber keine zeitlichen Angaben machen. Wenn jmd. schneller ist, gern ... Würde den Arbeitsbeginn hier kurz notieren, um Überschneidung und Mehrarbeit zu vermeiden.

**Comment by zonky2** [comment]
o.k.!

**Comment by zonky2** [comment]
@cliffparnitzky "lebt" die Sache noch? ;-)

**Comment by zonky2** [comment]
> Werde die Sache asap bearbeiten.

wann ist "possible"? ;-)

**Comment by cliffparnitzky** [comment]
Wie besprochen ... passiert demnächst

**Comment by cliffparnitzky** [comment]
@zonky2 in der Hoffnung nun endlich eine funktionierende Lösung gefunden zu haben, gibt es einen passenden feature branch (feature-unique-attributes-marked-mandatory ). Kannst du den mal bitte testen?

**Comment by zonky2** [comment]
habe ich getestet - läuft bei mir!

**Comment by cliffparnitzky** [comment]
Sehr schön. Hab noch den Code gemäß der Empfehlung von @richardhj angepasst. Das gemeckert von Travis bezieht sich auf Code, den ich nicht angefasst habe. Das wird sicher noch im originalen Branche gefixt. Könnte also gemergt werden, oder?

**Comment by richardhj** [comment]
am besten als PR mit alpha15 als base branch. Code sieht aber gut aus :)

**Comment by cliffparnitzky** [comment]
Wozu nun noch nen PR, wenn das schon ein branch ist ?

**Comment by richardhj** [comment]
Ich finds nur übersichtlicher, da da der „Klickweg“ zur Compare-Ansicht kürzer ist. Aber geht beides.

**Comment by cliffparnitzky** [comment]
Jut, dann bitte den branch mergen

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@zonky2 could you please have a final look at this and tell if your issue has been resolved?
