### ISSUE TITLE
Vergleich von Dezimalzahlen - Validierung unzureichend

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#957]
Werden Dezimalzahlen verglichen, darf das nicht als Stringvergleich erfolgen - 1.5 und 1.50 ist mathematisch das Gleiche vs. bei einem Stringvergleich nicht

ggf. bei Integer nochmal nachprüfen..

in

https://github.com/MetaModels/core/blob/master/src/MetaModels/DcGeneral/Data/Driver.php#L511-L532

**Comment by discordier** [comment]
Wo wird da bitte verglichen? Was genau meinst du?

**Comment by xantippe** [comment]
upps - sorry! war falsche URL (korrigiert)

wenn auf isUniqueValue geprüft wird

**Comment by stefanheimes** [comment]
@xantippe I take a look into the flow of the data. At the end of the trail you where in the "searchFor" of the attribute and there we have for all simple attributes one function https://github.com/MetaModels/core/blob/master/src/MetaModels/Attribute/BaseSimple.php#L154. 

Maybe here is the problem? We searched with a "like".

**Comment by xantippe** [comment]
wo müsste man ansetzen für ein eigenes Query?
hier https://github.com/MetaModels/core/blob/fa305c9d3ce55fa0a7c92b37599e09b5c46161a1/src/MetaModels/Filter/Rules/SearchAttribute.php#L74-L81

**Comment by discordier** [comment]
Fixed in
https://github.com/MetaModels/attribute_decimal/commit/27071dd274ce696e578eb66862126fd21c926d6b
https://github.com/MetaModels/attribute_numeric/commit/071e919d2da5d62570f18d45126c87976261181e

**Comment by xantippe** [comment]
WOW!

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@xantippe could you please have a final look at this and tell if your issue has been resolved?

**Comment by xantippe** [comment]
getestet => o.k.!

https://github.com/MetaModels/attribute_decimal/pull/10#issuecomment-189480096
