### ISSUE TITLE
CSS-Klasse in Clipboard-Container wie Auflistung hinzufügen

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#958]
CSS-Klasse in Clipboard-Container wie Auflistung hinzufügen um Clipboard in MM gegenüber DCG getrennt ansprechen zu können

siehe u.A. https://github.com/contao-community-alliance/dc-general/pull/176

**Comment by discordier** [comment]
Ich verstehe das issue nicht.

**Comment by zonky2** [comment]
alles prima inzwischen...

![shot303](https://cloud.githubusercontent.com/assets/1045318/21004537/337f48d8-bd31-11e6-99b3-6476206e3293.jpg)
