### ISSUE TITLE
SCSS für MM erstellen

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#959]
SCSS für MM erstellen

**Comment by michelbalzer** [comment]
Was soll da denn rein? Die Standard-Ausgabe im Frontend?

**Comment by xantippe** [comment]
aktuell gibt es nur ein "normales CSS" - das sollte in ein SCSS für eine bessere Wartbarkeit überführt werden

**Comment by michelbalzer** [comment]
Also beide *_src.css auf SCSS umschreiben, wenn ich das jetzt richtig verstanden habe.

**Comment by xantippe** [comment]
genau...

**Comment by nordentwickler** [comment]
Ist SCSS pflicht oder tuts Less auch? Gulp oder Grunt?

**Comment by zonky2** [comment]
ich würde SCSS präferieren, da m.E. recht viele sie Sache warten können...
sofern Mixins o.ä. unbedingt benötigt werden, müsste man sich nochmal über das Tool verständigen - ansonsten sollten in das Repro z.B.
style.css (minimiert)
style_src.css (nicht minimiert für Debugmodus)
style.scss (als "Quelle") + ggf. noch eine style.map

**Comment by kikmedia** [comment]
Der Inhalt ist ja eher übersichtlich - bin mir gar nicht sicher ob das so viel mehr an Übersicht erzeugt wenn man es als SCSS macht.

Anyway: PR hier oder noch im Dev-Repo?

**Comment by zonky2** [comment]
hier - core ist ja wieder im Heimathafen

**Comment by kikmedia** [comment]
See https://github.com/MetaModels/core/pull/1262

**Comment by zonky2** [comment]
fixed https://github.com/MetaModels/core/pull/1286
