### ISSUE TITLE
Contao 3 - FrontendFilter.php function getJumpToUrl

### ISSUE THREAD

**Issue by stefanmeschke** [MetaModels/core#960]
Hallo,

wir haben das Problem, dass der Slash bei einer Suche mit in die URL übernommen wird und somit dann die Seite nicht mehr ausgeliefert wird.

```php
$strFilterAction .= sprintf(
                    $GLOBALS['TL_CONFIG']['disableAlias'] ? '&amp;%s=%s' : '/%s/%s',
                    $strName,
                    rawurlencode($strValue)
                );
```
Datei: core/src/MetaModels/FrontendIntegration/FrontendFilter.php

Durch `rawurlencode(str_replace('/',' ',$strValue))` konnten wir dies vorerst für uns lösen. Gibt es eine andere Möglichkeit um dies zu erreichen?

Vielen Dank für Eure Hilfe!

**Comment by xantippe** [comment]
Doppelt siehe
https://github.com/MetaModels/core/issues/139
https://github.com/MetaModels/core/issues/139
