### ISSUE TITLE
AND filter works not right, instead of "all" returns "no elements"

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#961]
First take a look at this function. 
https://github.com/MetaModels/core/blob/master/src/MetaModels/Filter/Rules/Condition/ConditionAnd.php#L56

And now the setup. We have two simpleLookups both with "allow empty". Both have no filter param so both will return the "null" for "all values" but here is the problem. The foreach will check on line 63 the null and will go on. So the empty flag is true and the AND-filter will return array() instead of null. So both filter say "all elements" and the and "no elements". Because the flag for empty is not set.

I fix it with a simple line. If we have the "null" as return, we have a result and the AND-filter is not empty. If all sub filter return null the $arrIds will be null as well and return it. If we have a  filter that returns a id list it will merged and everything is okay. 

@discordier What do u think?

```php
            if ($arrChildMatches === null) {
                $blnEmpty = false;
                continue;
            }
```

**Comment by discordier** [comment]
Will be fixed as soon as alpha10 is released.

**Comment by xantippe** [comment]
wie würde ein Testcase aussehen (müssen)?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@stefanheimes could you please have a final look at this and tell if your issue has been resolved?
