### ISSUE TITLE
Auswahlfeld in CE-MM-Liste für statischen Parameter hat nur zugeord. Werte

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#963]
Hat man eine Filterregel "Einfache Auswahl" mit einem "statischen Parameter", so reagiert die Auswahl des Standardwertes auf die Checkbox "Nur zugeordnete Tags" - ist diese nicht gesetzt, werden alle möglichen Items angezeigt

![shot75](https://cloud.githubusercontent.com/assets/1045318/12461685/8571a5ac-bfba-11e5-98d8-7a5ad793acc2.jpg)

Im CE-MM-Liste jedoch wird bei der Auswahl der möglichen Werte nur die angezeigt, die zugeordnet sind - im Beispiel ist "Test" nicht zugeordnet

![shot76](https://cloud.githubusercontent.com/assets/1045318/12461717/b0157b3a-bfba-11e5-8447-4db91c30246d.jpg)

**Comment by xantippe** [comment]
ich habe die Stelle gefunden: https://github.com/MetaModels/core/blob/master/src/MetaModels/Filter/Setting/SimpleLookup.php#L204

wenn man den Parameter von "true" auf "false" stellt
```diff
-        $arrOptions   = $objAttribute->getFilterOptions(null, true);
+        $arrOptions   = $objAttribute->getFilterOptions(null, false);
```

werden auch alle (noch) nicht vergebenen/referenzierten Items angezeigt und die Liste im FE zeigt "Ihre Suche lieferte keine passenden Ergebnisse."

Warum sollte man nicht referenzierte Items auswählen? z.B.

* die Liste soll für das FE schon angelegt werden aber die Werte sind im BE noch nicht eingegeben
* bei Varianten kann man bisher nur auf die (refrerenzierten) Kindelemente zugreifen - mit der Anpassung können auch Elternelemente ausgewählt und per "eig. SQL" die Kinder hinzugefügt werden

**Comment by xantippe** [comment]
PR erstellt #966

**Comment by discordier** [comment]
Fixed in 5789b1002dfa232a7082bb41adaca283f818dd28

**Comment by xantippe** [comment]
hotfix-alpha10 getestet: o.k.

![shot86](https://cloud.githubusercontent.com/assets/1045318/12621717/204794d0-c522-11e5-96af-bdb52bbc9f13.jpg)
