### ISSUE TITLE
FR: CE Liste und Filter fehlt der Block "Sichtbarkeit"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#964]
Contentelement (CE) "MM-Liste" und "MM-Filter" fehlt der "Standard"-Block "Sichtbarkeit" mit Checkbox "unsichtbar" (geht z.Z. nur über Auge) und Anzeigen ab-bis analog beim Contentelement

![shot189](https://cloud.githubusercontent.com/assets/1045318/14492010/a77bbde6-017c-11e6-9253-6e5a32243c01.jpg)

**Comment by baumannsven** [comment]
https://github.com/MetaModels/attribute_checkbox/pull/15

**Comment by zonky2** [comment]
add PR: https://github.com/MetaModels/core/pull/1007
