### ISSUE TITLE
Contao-Erweiterung-Tabelle mit "angehängter" Kindtabelle rutscht in BE-Navigation nach "oben"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#965]
Tabelle einer Contao-Erweiterung mit "angehängter" Kindtabelle rutscht in BE-Navigation nach "oben" - Navigationspunkt sollte dadurch nicht beeinflusst werden

siehe Screenshot bei News

![shot82](https://cloud.githubusercontent.com/assets/1045318/12530973/b70034f8-c1ef-11e5-849a-7d1bf76f66e9.jpg)

**Comment by discordier** [comment]
Should be fixed by 437e8b6

**Comment by zonky2** [comment]
mit dem Fix funktioniert es bzw. das Icon/Eintrag "verrutscht" nicht mehr

![shot195](https://cloud.githubusercontent.com/assets/1045318/15029731/37c429b4-124f-11e6-84bd-0b529e32dfd8.jpg)

eine Anpassung des Eintrages über die dcaconfig.php ist nicht wie im ursprünglichen PR möglich
https://github.com/MetaModels/core/pull/995#issuecomment-216907272
