### ISSUE TITLE
A filter or sub-list attribute to use/display attributes from linked MM (without having to create its own template) ?

### ISSUE THREAD

**Issue by JLBA** [MetaModels/core#968]
Hi everyone,

I'm developing a MM for displaying cultural events. I got 3 MM : 
- season (ex : 2014/2015, 2015/2016…)
- Events (ex : A writer coming)
- Dates : (ex : jan, 15 -> one date with this writer, jan, 16, another date with him…)
  One season has many events, one event has one or many dates. So Events are linked to Seasons and Dates to events. 

I would like to use a MM list based on Season, displaying actual season datas and being able to display attributes/datas from Events linked to this season (sub list) and attributes/datas from Dates for each Event(sub sub list)… without having to create a specific sql filter request. 

Perhaps is it already possible and I haven't yet understood how. Otherwise, could this be a future MM filter ?

Thanks.

**Comment by JLBA** [comment]
Ok. I found this [page](http://de.contaowiki.org/MetaModels_Beispiel:_Referenced_items) in Contao DE wiki which seems to be exactly what I need.

 I still ask for a filter or attribute to sub-list the linked datas.

Thanks.

**Comment by xantippe** [comment]
Hi JLBA, I'm not sure if I understand you correctly...

...you should mal a FE-List with your "basic items" - in your case the "Dates" and filter this list with Events and Seasons.

You can catch any of the referenced items at the "raw" nodes - pls look at http://metamodels.readthedocs.org/de/latest/cookbook/debug/templates.html#debug-templates (sorry, in german)

**Comment by JLBA** [comment]
> (sorry, in german)
One of the problems is probably here ;-)) Even if translate.google.com is a help…
The second one is I'm not developer (htm, css but not php, sql…)

In my actual case, I got 3 MM : 
- Seasons (one at a time, defined by a checkbox)
--- Events (many events by season)
----- Dates (one or many dates by event).

What do i need exactly ?

1. In FE, I have to list events but only the one linked to the actual season. So I created a sql filter attribute to specify this request. But I'm asking if there could be a specific filter attribute for looking in linked datas ?

2. In FE too, I need to list events and for each one its different dates (you can call it a sub list). Could there be a FE

**Comment by xantippe** [comment]
Have every Event a Date (mandantory)? in this case, may be we "connect" the dates with the seasons...

e.g. 
Season 1: 01.01. to 30.06.
Season 2: 01.07. to 31.12.

if we have date with 03.04. the event is in season 1 or date 01.09. in season 2

**Comment by JLBA** [comment]
Perhaps but I got 3 problems : 

- seasons are across two years from september to june ; 
- user must be able to decide when to display the new season's datas and events ; 
- let's rename Dates by Meetings (and mm_Dates by mm_Meetings) ; events have no specific dates but many meetings about ; for example, a writer is coming and we can meet him in 3 occasions ; 

So I prefer having a checkbox ; when it's time, the user checks the new season and unchecks the former one.

**Comment by xantippe** [comment]
may be it´s bette we change to contao community forum 
https://community.contao.org/de/forumdisplay.php?149-MetaModels
- imho is your question not a bug or feature request... 

...you can write in english ;-)

and: have you a test or live website?

**Comment by JLBA** [comment]
My question _is really_ a feature request : in one MM, is it possible to have access to data from linked MM : 
- in filter by using a specific filter attribut (and without having to create a sql request)
- in rendersetting, by using a specific "linked list" or "sub-list" attribute (so without having to create a personnalized template) ?

The example I gave was just for the example.

**Comment by xantippe** [comment]
> in one MM, is it possible to have access to data from linked MM

you can test with ""Mein erstes MetaModel" V2" http://www.e-spin.de/contao-metamodels.html

look at "abteilung" - ist a related MM per [select] attribute
```
Array
(
    [0] => Array
        (
            [raw] => Array
                (
                    [id] => 93
                    [pid] => 0
                    [sorting] => 12032
                    [tstamp] => 1454935856
                    [name] => Avery
                    [vorname] => Amir
                    [email] => Amir.Avery@mmtest.com
                    [abteilung] => Array
                        (
                            [__SELECT_RAW__] => Array
                                (
                                    [id] => 4
                                    [pid] => 0
                                    [sorting] => 0
                                    [tstamp] => 1442499032
                                    [name] => Marketing
                                    [alias] => marketing
                                )

                            [name] => Marketing
                            [alias] => marketing
                        )

                )

            [text] => Array
                (
                    [name] => Avery
                    [vorname] => Amir
                    [email] => Amir.Avery@mmtest.com
                    [abteilung] => Marketing
                )

            [attributes] => Array
                (
                    [name] => Name
                    [vorname] => Vorname
                    [email] => E-Mail
                    [abteilung] => Abteilung
                )

            [html5] => Array
                (
                    [name] => <span class="text">Avery</span>
                    [vorname] => <span class="text">Amir</span>
                    [email] => <span class="text">Amir.Avery@mmtest.com</span>
                    [abteilung] => Marketing
                )

            [class] => first even
            [jumpTo] => Array
                (
                )

        )
...
``

**Comment by JLBA** [comment]
I've downloaded it but how to use it ? I'm on Mac with MAMP. 

Otherwise, how did you insert the sublist in the rendersettings (or in the personalized template) ?

**Comment by JLBA** [comment]
I�ve installed and tested it but this doesn�t exactly what I�m looking for. What if there are many Abeilung for one Name ? 
Or, reported to my case have a list with a sublist within : 
- Event 1 : Meeting 1, meeting 2, meeting 3
- Event 2 : Meeting 1
- Event 3 : meeting 1, meeting 2
- and so on�

So my firstrequest to MM devs is for a rendersetting attribute �sub-list from linked mm� which would create (here) the meetings list for each event,

And the second request is for a filter attribute to be able to add filter condition based on some linked mm datas. For example, I could create an mm_list_module  Events with a filter �where mm_season::actual_season=1 & mm_season::published=1�.

**Comment by xantippe** [comment]
hmmm... sorry, I don't understand your description unfortunately... may be, you can send me a link to your project per PN at Forum (nickname "zonky")

**Comment by xantippe** [comment]
@JLBA I have sent you a reply in the forum..

**Comment by JLBA** [comment]
I saw. I answered to you.

**Comment by xantippe** [comment]
@JLBA o.k. "we" found a solution... and now, we can close the ticket?

**Comment by JLBA** [comment]
Yes we can… Thank. Otherwise, I'm still thinking of it as a feature request.

**Comment by JLBA** [comment]
Just a word to say this feature request existed in Catalog as Reference module. I'm still thinking this could be useful in MM too.
