### ISSUE TITLE
More parameters for the link to detail page

### ISSUE THREAD

**Issue by JLBA** [MetaModels/core#969]
Hi,
There could be some improvments to the link from one list element to the detail page :
- the link text is always the same ; there could be a field to write precisely the text we need ;
- an option to choose some attributes instead of a link bottom (like in Catalog)
- and more : an option to select the entire element (li) to be clicable.

So we don't need to create a specific model.

Thanks

**Comment by asaage** [comment]
you should use ```$arrItem['jumpTo']['url']``` and one (or more) of your  ```$arrItem['text']['attribute']``` or ```$arrItem['raw']['attribute']``` values inside a template.

The href attribute is by spec only allowed for a, area, base and link elements - not for li.

**Comment by JLBA** [comment]
Thanks (again) André.

I know it but this could be more useful if we can have directly the choice in the module parameters. 

JL

**Comment by xantippe** [comment]
The "standard" at contao is to work with your own DCA, e.g. you want to change the link text from "more..." to "follow the white rabbit..." or you can change the template...

**Comment by JLBA** [comment]
Yes I know it but this could be more simpler if there is a text field under the url one to define the word or sentence wanted instead of "see details".

**Comment by discordier** [comment]
This would be many text boxes, as it would need to be available and defined for every language. That's the reason why you can override it via language file.

**Comment by JLBA** [comment]
No more than in other parts of MM which is natively multilingual.

Another problem is that one could need different words depending on what the module is listing. How can  I specify for which module in langconfig.php ?

**Comment by xantippe** [comment]
you can make your own nodes

use this in different templates
```
$GLOBALS['TL_LANG']['MM_Module_1']['link_text'];
```
```
$GLOBALS['TL_LANG']['MM_Module_2']['link_text'];
```

if you use FE-MM-List as FE-Module, you can retrive the Module ID and change link text

**Comment by JLBA** [comment]
Thanks.

**Comment by xantippe** [comment]
that´s all? ... you can close the issue ;-)

**Comment by JLBA** [comment]
I close.
