### ISSUE TITLE
A field to write what text to display when nothing to display in list module

### ISSUE THREAD

**Issue by JLBA** [MetaModels/core#970]
Hi,
This could help to be able to choose what text to display when a list module is empty. With translations possibilities of course.

Thanks.

**Comment by asaage** [comment]
system/config/langconfig.php is the place to go
```
$GLOBALS['TL_LANG']['MSC']['noItemsMsg'] = 'your message for empty list';
```

**Comment by JLBA** [comment]
Thanks André. 

I know it. As MM is natively mutilanguages, I was just thinking this could be more useful if we can indicate it directly in the MM list module parameters.

JL

**Comment by xantippe** [comment]
IMHO: https://github.com/MetaModels/core/issues/969#issuecomment-181749550

**Comment by xantippe** [comment]
any questions or can close it - look at #969 ?

**Comment by JLBA** [comment]
yes, we ca&n ;-) Thanks
