### ISSUE TITLE
isTranslated() Error

### ISSUE THREAD

**Issue by Taskrider** [MetaModels/core#971]
isTranslated() on null in /home/www/composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/RenderSettings/Subscriber.php on line 286

on create renderer

**Comment by petereberlecom** [comment]
same here, i use the **MM v2.0.0** and the **Contao 3.5.4**.

When i try to add a render configuration it throws this error:
```
Fatal error: Call to a member function isTranslated() on a non-object in [...]/composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/RenderSettings/Subscriber.php on line 286
```

**Comment by martonos** [comment]
Jupp, auch hier der gleiche Fehler mit contao 3.5.6 und dem metamodels bundle_all

**Comment by Taskrider** [comment]
hat da schon jemand einen kleinen Workaround?

Ich nehme an, dass das Model nicht richtig geladen wird!?

**Comment by petereberlecom** [comment]
Ich habe noch kein. Habe es erst gestern Installiert und schon in 2 Fehler gelaufen ( #758 und dieser hier). Hatte Metamodels mal installiert als es noch catalog hieß, hatte es eigentlich in sehr guter Erinnerung?

**Comment by martonos** [comment]
Sicher nicht im Sinne des Erfinders, aber ich hab einfach mal Zeile 286 - 305 in der /composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/RenderSettings/Subscriber.php auskommentiert. Damit kann man bis zum Fix erstmal voran kommen.

`/* if ($metaModel->isTranslated()) {
            $arrLanguages = array();
            foreach ((array) $metaModel->getAvailableLanguages() as $strLangCode) {
                $arrLanguages[$strLangCode] = $translator->translate('LNG.'. $strLangCode, 'languages');
            }
            asort($arrLanguages);

            $extra['minCount'] = count($arrLanguages);
            $extra['maxCount'] = count($arrLanguages);

            $extra['columnFields']['langcode']['options'] = $arrLanguages;
        } else {
            $extra['minCount'] = 1;
            $extra['maxCount'] = 1;

            $extra['columnFields']['langcode']['options'] = array
            (
                'xx' => $GLOBALS['TL_LANG']['tl_metamodel_rendersettings']['jumpTo_allLanguages']
            );
        }*/`

**Comment by discordier** [comment]
Need more details, I can not reproduce this issue.
Adding new rendersettings works just fine for me.
Can you supply me with exact steps how to reproduce this?
You may alternatively provide me with a minimal test installation where I can reproduce the issue.

**Comment by discordier** [comment]
Should be fixed by dc-general 2.0.0-beta33

**Comment by discordier** [comment]
Please test.

**Comment by martonos** [comment]
Das Anlegen und speichern funktioniert nun, wenn auch mit Fehler:

`Warning: array_key_exists() expects parameter 2 to be array, null given in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php on line 779`

`Warning: Cannot modify header information - headers already sent by (output started at /Users/marten/Documents/Projekte/Delzepicheis/web/system/helper/functions.php:65) in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php on line 743`

Geht man zurück sind die Änderungen aber gespeichert.

Togglen der Attribute funktioniert auch. Danke!

**Comment by xantippe** [comment]
@martonos die Fehlermeldung könnte/sollte verschwinden bei Update auf hotfix-2.0.0-alpha10

**Comment by discordier** [comment]
Genauer: wurde mit https://github.com/contao-community-alliance/dc-general/commit/b0cbecd0cb1ec0ef7c3b24988b55d3e3a148e99a gefixt.
