### ISSUE TITLE
array_key_exists() Error

### ISSUE THREAD

**Issue by kollp** [MetaModels/core#973]
Moin Leute,
habe folgendes Problem:
![bildschirmfoto 2016-02-09 um 09 30 32](https://cloud.githubusercontent.com/assets/17084821/12911051/ef9ff1ae-cf0f-11e5-98f7-702c7e12482f.png)

Passiert wenn ich z.B. Attribut zu einem Model hinzufügen.
Läuft auf Contao 3.5.3 und

![bildschirmfoto 2016-02-09 um 09 32 40](https://cloud.githubusercontent.com/assets/17084821/12911080/23db2c90-cf10-11e5-9266-6515e3563aa2.png)

**Comment by xantippe** [comment]
probier mal ein "Update" auf die alpha10 - siehe https://community.contao.org/de/showthread.php?61190-Datens%E4tze-lassen-sich-nicht-erstellen-bearbeiten

**Comment by kollp** [comment]
hat leider nicht geklappt, problem bleibt bestehen.

**Comment by xantippe** [comment]
welche DCG-Version? siehe https://community.contao.org/de/showthread.php?61190-Datens%E4tze-lassen-sich-nicht-erstellen-bearbeiten&p=398440&viewfull=1#post398440

**Comment by kollp** [comment]
DCG steht auf beta33

![bildschirmfoto 2016-02-09 um 11 14 53](https://cloud.githubusercontent.com/assets/17084821/12913345/69fbede6-cf1e-11e5-85b0-9c9bed4cd0f4.png)

**Comment by xantippe** [comment]
und was steht in dem Community-Posting..?

**Comment by discordier** [comment]
Ist gefixt in https://github.com/contao-community-alliance/dc-general/commit/b0cbecd0cb1ec0ef7c3b24988b55d3e3a148e99a
