### ISSUE TITLE
Felder sind unsichtbar im BE Eingabe Formular

### ISSUE THREAD

**Issue by transopticmedia** [MetaModels/core#974]
Für mich sind Felder in der Eingabe Formular nur sichtbar wenn "Pflichtfeld" gecheckt ist. Sonst, ist das Fieldset mit dem CSS-Class "collapsed" versteckt. Auch, wenn ich einen Beitrag aus der liste von bestehenden Beitrage bearbeiten möchte, ist den auch mit CSS versteckt, egal ob die Felder "Pflichtfeld" waren oder nicht. Ich weiss nicht ob das ein Bug ist, oder "user error". Danke!

<img width="1191" alt="screen shot 2016-02-09 at 16 48 22" src="https://cloud.githubusercontent.com/assets/302693/12922027/29f8898e-cf50-11e5-8ed5-9a05ac3e153e.png">

<img width="1440" alt="screen shot 2016-02-09 at 17 08 59" src="https://cloud.githubusercontent.com/assets/302693/12922032/2cae7dbe-cf50-11e5-9a7c-01263103e734.png">

**Comment by xantippe** [comment]
dürfte hierzu passen - siehe auch "fixing" 

https://community.contao.org/de/showthread.php?61190-Datens%E4tze-lassen-sich-nicht-erstellen-bearbeiten

**Comment by transopticmedia** [comment]
Danke! Hat geklappt.
