### ISSUE TITLE
BE : losing inputscreen attributes if adding new attribute(s) when MM has some records

### ISSUE THREAD

**Issue by JLBA** [MetaModels/core#975]
Hi,

I got this problem for the second time with Contao 3.5.4 / Composer / MM/bundle_all 2.0.0 (bugfix release). 

I've created some records in a MM. Then I add some new attributes (longtext in this case) and add them to the corresponding rendersetting and inputscreen. 

Then, if I go to the MM in the BE, the list is ok (rendersetting) but if I edit one record, the inputscreen is totally empty. 

If I create a new record, the inputscreen is ok. I can save the record. Sometimes, I can open again former records and see the attributes. Other times, I can not even see the new record.

I purged MM cache. I edit and saved again the MM, the rendersetting, the inputscreen, the I/O combination. I finally deleted all the records and added my new attributes then created new record.  But this works no more.

I deleted my MM and recreated it. Works no more.

I finally uninstaledl MM, deleted the mm_tables in MySQL, purged Contao caches, reinstalled MM and I go again. 

Strange bug.

**Comment by xantippe** [comment]
I hope Google can translate it...
https://community.contao.org/de/showthread.php?61234-Achtung!-wenn-nach-Update-Eingabemasken-nicht-mehr-zu-sehen-sind
https://community.contao.org/de/showthread.php?61190-Datens%E4tze-lassen-sich-nicht-erstellen-bearbeiten
https://github.com/MetaModels/core/issues/974

**Comment by JLBA** [comment]
Thanks xantippe,
your going to become my new best friend on the web ;-))

I have deleted my MM, my tables and MM itself. Reinstalled MM, recreated the MM… and the pb is still here !! Will I have to restart all my website from scratch to suppress it ?

It effectively seems to work if I add an activated legend before like said in the 1st discussion (and perhaps at the end of the second one but I haven't well understood).

Is the problem identified ? May I still use composer update ?

**Comment by xantippe** [comment]
you can use a workariund: add a legend at your input screen - see https://community.contao.org/de/showthread.php?61190-Datens%E4tze-lassen-sich-nicht-erstellen-bearbeiten&p=398526&viewfull=1#post398526

or you can update https://community.contao.org/de/showthread.php?61190-Datens%E4tze-lassen-sich-nicht-erstellen-bearbeiten&p=398514&viewfull=1#post398514
pls read http://metamodels.readthedocs.org/de/latest/manual/install.html#test-von-speziellen-bundles-via-composer
