### ISSUE TITLE
erste Render-Einstellung per Default als Standard

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#976]
da es die Maßgabe gibt, eine Render-Einstellung soll als Standard definiert sein, wäre es gut, die erste Render-Einstellung per Default auf Standard zu setzen

**Comment by discordier** [comment]
Das myssen wir diskutieren.
Ich wollte die Standard Checkboxen entfernen.
Wir haben ja seit langem die combinations

**Comment by zonky2** [comment]
@discordier außer bei den Einstellungen für Sortierung/Gruppierung brauchen wir die Checkboxen nicht mehr - oder?

**Comment by discordier** [comment]
Korrekt, sollte alles per mapping in den combinations erfolgen.

**Comment by zonky2** [comment]
obsolete - look at https://github.com/MetaModels/core/issues/1154
