### ISSUE TITLE
Select/Auswahl-Feld nicht korrekt auswählbar

### ISSUE THREAD

**Issue by HRP2016** [MetaModels/core#977]
Bei den aktuellen Nightly Builds ist die Zuweisung eines Select/Auswahl-Feldes nicht möglich. Mehrfachauswahl geht. (Stand 13.02.2016) Contao Installation 3.5.6, MM Core dev-master @ d4ba65 mit dc-general dev-develop @ 93cc98. 

Div Fehlermedlungen: 

Unbekanntes Attribut! []
Erweiterung fehlt? Der Attributtyp "" ist nicht installiert.

sowie 

Warning: Illegal offset type in system/modules/metamodelsattribute_select/classes/src/MetaModels/DcGeneral/Events/Table/Attribute/Select/Subscriber.php on line 260

Warning: Cannot modify header information - headers already sent by (output started at /var/www/web449/html/redpinata-development/rp_mm/system/helper/functions.php:65) in system/modules/core/library/Contao/Template.php on line 294

Contao Forum:
https://community.contao.org/de/showthread.php?61299-Select-Auswahl-nicht-korrekt-ausw%E4hlbar&p=399246#post399246

**Comment by xantippe** [comment]
Workaround: https://github.com/MetaModels/attribute_select/issues/48#issuecomment-185084637

**Comment by xantippe** [comment]
ist mit hotfix-2.0.0-alpha11 https://github.com/MetaModels/attribute_select/branches gefixt

**Comment by transopticmedia** [comment]
Hallo alle! Ich habe Metamodels "Bundle_all" mit dem Composer installiert. Ist es möglich diesen Hotfix-Branch durch Composer zu installieren? Ich habe zurzeit keinen FTP-Zugang . Danke im Voraus.

**Comment by xantippe** [comment]
aktualisiere per Composer - dann sollte auch das neue select bei Dir ankommen

**Comment by transopticmedia** [comment]
danke, hat geklappt!
