### ISSUE TITLE
Wrong var-group when duplicate a entry

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#980]
See: https://github.com/contao-community-alliance/DC-general/issues/197 for the first error and this
https://github.com/MetaModels/core/blob/master/src/MetaModels/DcGeneral/Events/MetaModel/DuplicateModel.php#L41 for the other problem.

This is the main problem and we are using the wrong event to manipulate the data. We should use the PreDuplicateModelEvent when copy a varbase.

**Comment by stefanheimes** [comment]
Fixed in 3b72eafcd0c22e15c35e6c5744e98bd9628c95ad

**Comment by xantippe** [comment]
der Bug beim Anlegen des Parent ist weg; einen Eintrag kann man kopieren... 

...um Items an anderer Stelle zu verfrachten oder Hinzufügen an bestimmter Stelle, muss man eine manuelle Sortierung als Standard definieren (da per se kommt *keiner* drauf..) - zudem kann man wenn das aktiviert ist, tiefer als einer Kinderebene gehen (was lt. @discordier) bei Varianten nicht sein sollte...  es gibt auch irgendwelche Einfügekombinationen, bei den der Hut mit in die Kinderebene rutscht und Einfügen nach letztem Kind scheint auch nicht zu funktionieren... muss ich aber nochmal genauer testen

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@stefanheimes could you please have a final look at this and tell if your issue has been resolved?
