### ISSUE TITLE
Fehler bzw fehlende Editmaske beim Editieren eines Datensatzes

### ISSUE THREAD

**Issue by Olli** [MetaModels/core#981]
Das kommt als Fehlermeldung bzw "Warnung" im Log. Irgendwelche Parameter fehlen im Array
https://gist.github.com/Olli/dafaacc4507b94511c6c
Ich habe gestern ein Update der Metamodels durchgeführt. Verschiedene Module sind auf verschiedenen Alpha Versionen. Welche Version von welchem Paket wird benötigt für eine Fehleranalyse?

**Comment by xantippe** [comment]
mit dem Suchbegriff "array_key_exists" wird man sowohl hier als auch im Forum fündig...

=> mit Wechsel auf DCG beat34 und MM core alpha10 ist die Sache gefixt

**Comment by Olli** [comment]
Ich bekomme DCG nicht installiert und mm core alpha10 auch nicht - da spacken die filter und attribute rum. 
Ich habe aber gelesen, dass es "nur" eine gesetzte CSS Klasse ist - bis das ins nächste Update einfließt, kann man die auch per Entwicklerwerkzeug on-demand ausschalten.
Danke für den Hinweis.

**Comment by xantippe** [comment]
hast Du das beachtet?
http://metamodels.readthedocs.org/de/latest/manual/install.html#test-von-speziellen-bundles-via-composer

**Comment by Olli** [comment]
Nicht ganz - ich habe es mit Clickibunti probiert weil ich dachte "muss auch so gehen". Es macht am Ende nix - ich habe über die Modelle, wie im Thread beschrieben, eine Legende über die Eingabemasken gemacht. 
Jetzt geht das übergangsweise :)
