### ISSUE TITLE
Filtern nach Feldern ohne Namen (in einer Sprache) funktioniert nicht

### ISSUE THREAD

**Issue by amenk** [MetaModels/core#985]
_Unser Issue: 13403_

Folgender Fall: Wir haben ein `translatedalias` Attribut welches beispielsweise in der Sprache EN keinen Namen eingetragen hat.

Nun greift der `auto_item`Filter in EN nicht mehr - in DE geht es.

Problem scheint zu sein, dass in [ItemList.php](https://github.com/MetaModels/core/blob/e0921c16814f86be390c019677165e77850c4b91/src/MetaModels/ItemList.php#L427) die Parameter aus den Filter-Namen bestimmt werden (`array_keys`) - dort aber ggf. der nötige Eintrag fehlt.

Hier sollte entweder ein Fehler angezeigt werden, oder forciert werden, dass die Attribute für alle Sprachen benannt werden müssen.

**Comment by zonky2** [comment]
@amenk kannst nochmal Deine Einstellungen als Screenshot hier oder im Forum posten, damit ich den Fall (genau so) nachbauen kann.

**Comment by amenk** [comment]
Welche Einstellungen genau? Alle? Ich könnte dir ggf. noch nen DB Dump anbieten (privat - nicht zu veröffentlich) - das wäre vielleicht einfacher? Aber im Prinzip habe ich den Fehler im Code ja schon identifiziert?

**Comment by zonky2** [comment]
Zum Testen brauche ich eine Variante mit dem "Fehler" - ansonsten kannst Du einen PR mit einem Bugfix einladen... 
DB-Dump würde auch gehen - E-Mail siehe Community

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@amenk could you please have a final look at this and tell if your issue has been resolved?
