### ISSUE TITLE
How to list linked MM datas in a detail page ?

### ISSUE THREAD

**Issue by JLBA** [MetaModels/core#986]
Hi everyone,

My problem should be very simple to solve but I don't find the right way to get it…

I got 2 MM : 
- mm_events
- mm_meetings 
- mm_meetings is linked to mm_events by select attribute mm_meetings::linkToEvent.
So there could be many meetings for one event.

In a first FE page, a ce_MM_list for all events. When clicking on an event, I go to the details page.
On this details page, I got the event detail. 
**But I need to display event's meetings too.**

1. Is it possible to simply use a ce_mm_list based on meetings with a filter on the selected event ?

2. Xantippe told me about this example : [http://de.contaowiki.org/MetaModels_Beispiel:_Referenced_items](http://de.contaowiki.org/MetaModels_Beispiel:_Referenced_items) which seems to do the job. I adapted it to my case by just changing tables and attributes names but I got an error on line 13 which is :` <?php foreach ($this->data as $arrItem): ?>`

3. This template should be attached to an mm_events or mm_meetings ce_MM_list ?

Here is my code : 
_(mm_rencontres=mm_meetings ; mm_evenements=mm_events ; lienRencontreEvenement'=linkToEvent)_
```
<?php 
function getRencontresParEvenement($strAlias, $format='html5')
{
  $objMetaModel = MetaModelFactory::byTableName('mm_rencontres'); // my linked mm
  $objFilter = $objMetaModel->prepareFilter(16, array()); // I created the filter but added no rules
  $objFilter->addFilterRule(new MetaModelFilterRuleSearchAttribute($objMetaModel->getAttribute('lienRencontreEvenement'), $strAlias, $objMetaModel->getAvailableLanguages()));
  $objItems = $objMetaModel->findByFilter($objFilter);
  return $objItems->parseAll($format, $objMetaModel->getView(20));
}
?>
 
<div class="evenement_detailview">
  <?php foreach ($this->data as $arrItem): ?> // the problem seems to be here (line 13)
 
  <div class="detailview">
    <h1 class="ce_headline"><?php echo $arrItem['text']['intitule']; ?></h1>
    <p class="description"><?php echo $arrItem['text']['description']; ?></p>
  </div>
 
  <div class="rencontres_liees">
    <h2>Rencontres</h2>
    <?php foreach (getRencontresParEvenement($arrItem['raw']['alias']) as $arrProjects): ?>
  
    <div class="rencontre">
      <h3>
        <a href="{{env::path}}<?php echo $arrProjects['jumpTo']['url']; ?>">
          <?php echo $arrProjects[$this->getFormat()]['intitule']; ?> 
        </a>
      </h3>
      <?php echo $arrProjects[$this->getFormat()]['description']; ?>
    
    </div>
  
  <?php endforeach; ?>
  </div>
 
  <?php endforeach; ?>
</div>
```

And here is the error : 
`Warning: Invalid argument supplied for foreach() in templates/ce_metamodel_list_test_evenement.html5 on line 13#0 templates/ce_metamodel_list_test_evenement.html5(13): __error(2, 'Invalid argumen...', '/Users/pro/CLIE...', 13, Array)
#1 system/modules/core/library/Contao/BaseTemplate.php(88): include('/Users/pro/CLIE...')
#2 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#3 system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#4 system/modules/core/classes/Hybrid.php(258): Contao\FrontendTemplate->parse()
#5 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(102): Contao\Hybrid->generate()
#6 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(54): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#7 system/modules/core/library/Contao/Controller.php(476): MetaModels\FrontendIntegration\HybridList->generate()
#8 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#9 system/modules/core/modules/Module.php(283): Contao\ModuleArticle->compile()
#10 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#11 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#12 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#13 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#14 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#15 index.php(20): Contao\FrontendIndex->run() #16 {main}`

Thanks for your help.

**Comment by xantippe** [comment]
Hi @JLBA,

yu should use the community forum (DE or EN) for your question(s) - this is the area for bugs...

**Comment by JLBA** [comment]
Ok. Sorry. I was just expecting this could be a bug.
