### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#988]
We have to check the code base for PHP7 incompatibilities.
See the following slides for information of what has changed (if you do not know already): http://de.slideshare.net/jpauli/php7-is-coming

**Comment by albirs** [comment]
is here the place to put bugs in relation to php7?

**Comment by zonky2** [comment]
yes, please...

**Comment by albirs** [comment]
Filter "Single selection" on an Attribute "[translatedtext]" is not working. No Values showing in FE an BE. If I Change to "[text]" works fine. 
environment: PHP version: 7, Contao version: 3.5.12, MetaModels version: alpha11, Installation via composer,  Installed MetaModels packages: bundle_all, DCG: beta36 (to keep working on my project I have changed back to PHP 5.6)

**Comment by pepesale** [comment]
Content element "MetaModel List":
If in the select menu "Meta Description" a table field is selected, frontend throws this error:

`Fatal error: Cannot use 'String' as class name as it is reserved in /var/www/ftp_003_1/htdocs/cmsContaoDev/system/modules/core/library/Contao/String.php on line 28`

PHP 7.0.9
Contao version: 3.5.15
MM: alpha14, Installation via composer
DCG: beta38

Error doesn't appear with PHP 5.6.24

**Comment by zonky2** [comment]
Contao should compatible with PHP 7 greater than 3.5.4 - look at https://contao.org/de/news/contao_3-5-5.html
?

**Comment by pepesale** [comment]
Yes, of course. 
But as I have this error exclusively with the MetaModels Content Element "MetaModel List", I thought it might be a MM-problem with PHP 7.

**Comment by zonky2** [comment]
o.k. may be you can change the follow line
at https://github.com/MetaModels/core/blob/master/src/MetaModels/ItemList.php#L775
```diff
-                        $page->description = \String::substr($arrDescription['text'], 120);
+                        $page->description = \StringUtil::substr($arrDescription['text'], 120);
```

**Comment by pepesale** [comment]
Works perfectly! Thanks!

**Comment by zonky2** [comment]
@albirs 
>Filter "Single selection" on an Attribute "[translatedtext]" is not working. No Values showing in FE an BE. If I Change to "[text]" works fine.

have you a error?

**Comment by bizon1** [comment]
**Hi Folks**
		
On a local test environment I'm running Contao-3.5.24 with PHP 7.1

During saving a record in a Metamodel I've got this Message:

	Fatal error: Uncaught exception Error with message [] operator not supported for strings thrown in composer/vendor/metamodels/attribute_alias/src/MetaModels/Attribute/Alias/Alias.php on line 107

I guess that this belongs to: [http://php.net/manual/en/language.types.array.php]
Creating/modifying with square bracket syntax

	$arr[key] = value;

There is a note: 

	As of PHP 7.1.0, applying the empty index operator on a string throws a fatal error. Formerly, the string was silently converted to an array. 

Solution could be in: composer/vendor/metamodels/attribute_alias/src/MetaModels/Attribute/Alias/Alias.php

Changing the line 104    

	// $arrAlias = '';
	unset($arrAlias);

This will work with PHP 7.1 and also with PHP 5.6.30.

**Comment by zonky2** [comment]
may be it´s better to work with

```diff
-unset($arrAlias);
+$arrAlias = array();
```

**Comment by bizon1** [comment]
**@zonky2**
i cannot figure out how to color up the lines. But would you please turn the colors in your comment: First line to green, second to red.
Thx

**Comment by zonky2** [comment]
if you write the three tick and diff like "```diff" you can color the lines with - to red and + to green - that means - delete this line and + add this line

**Comment by zonky2** [comment]
I found only two settings with define a array as string (alias and combinedvalues)
https://github.com/MetaModels/attribute_combinedvalues/issues/15
https://github.com/MetaModels/attribute_alias/issues/17

**Comment by zonky2** [comment]
add https://github.com/MetaModels/core/issues/1128

**Comment by zonky2** [comment]
you can use core >= b15
https://github.com/MetaModels/core/blob/bd9e35909f522ba461a8ea96f357679a52b2fad9/src/MetaModels/ItemList.php#L743

**Comment by zonky2** [comment]
both with PR
https://github.com/MetaModels/attribute_combinedvalues/pull/16
https://github.com/MetaModels/attribute_alias/pull/17

**Comment by zonky2** [comment]
https://github.com/MetaModels/core/pull/1170

**Comment by zonky2** [comment]
https://github.com/MetaModels/core/pull/1191
