### ISSUE TITLE
Eigene Templates werden im FE als nicht mehr gefunden angezeigt

### ISSUE THREAD

**Issue by AgentCT** [MetaModels/core#990]
Bei der Verwendung eigener Template mit der aktuellen Alpha 10 kann man diese im BE auswählen aber im FE erscheint ausschließlich die Fehlermeldung "Template not found (it is maybe within a unreachable theme folder?)"

Die eigenen Templates liegen im Ordner "Templates", es wurde kein Unterordner verwendet.

Fehlerfrei funktionieren nur die Standard-Templates.

Verwendet wird:

Contao 3.5.8
metamodels/bundle_all 2.0.0 (f335503c)
contao-module metamodels/core 2.0.0-alpha10 (c54d60b4)

Installiert wurde Metamodels über Composer.

**Comment by xantippe** [comment]
hast Du aus speziellem Grund die core-a10 installiert? wenn nicht, kannst Du diese löschen, da über bundle_all mit an bei

wie sind die Templates benannt?

**Comment by AgentCT** [comment]
Ich dachte ich brauche den Core noch extra, habe ihn jetzt aber entfernt. Danke für den Tipp.

**Lösung:**
Ich hatte im Seitenlayout .xhmtl als Ausgabeformat ausgewählt, dadurch wurden im BE die .html5 Templates nicht mehr angezeigt. Nachdem ändern der Einstellung geht alles perfekt.

Viele Dank für deine Unterstützung
