### ISSUE TITLE
Custom SQL: Fehler im DCA: codeMirror zu ACE wechseln

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#991]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| Contao version:                     | 3.5.6|                                  |
| MetaModels version:                 | 2.0.0-a10 | DCG b34                 |
| Installation via composer           | yes |                                  |

## Issue description

im DCA ist noch der alte und bei Contao nicht mehr vorhandene Editor codeMirror eingetragen - hier muss der ACE hin...
siehe https://github.com/MetaModels/core/blob/master/contao/dca/tl_metamodel_filtersetting.php#L410

```diff
            'eval'        => array
            (
                'allowHtml'      => true,
                'preserveTags'   => true,
                'decodeEntities' => true,
-                'rte'            => 'codeMirror|sql',
+                'rte'            => 'ace|sql',
                'class'          => 'monospace',
                'helpwizard'     => true,
            ),
```

... vorher muss der ACE vom DCG unterstützt werden - siehe https://github.com/contao-community-alliance/dc-general/issues/205

**Comment by xantippe** [comment]
PR gemacht: https://github.com/MetaModels/core/pull/992
abhängig von DCG - PR https://github.com/contao-community-alliance/dc-general/pull/206

**Comment by zonky2** [comment]
the DCG is ready https://github.com/contao-community-alliance/dc-general/commit/ecd980bf7084d92de2fc8905d2faf80d12fa88f5
we wait at the MM PR ...

**Comment by zonky2** [comment]
Prima & Thanks
come with alpha13

![shot259](https://cloud.githubusercontent.com/assets/1045318/17033370/25a4a42c-4f7e-11e6-90e7-ac4b9552e597.jpg)
