### ISSUE TITLE
delete data that is orphaned

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#993]
how about recursive-deletions?
under present conditions the deletion of items in hirarchical and parented views leafes their child-nodes orphaned. There is no chance of deleting them afterwards by hand nor to reattach them to other nodes. They are simply not accesible in the BackEnd but still might show up in the FrontEnd.
And again: I'm not shure whether to put this here or into the dcg issues..

**Comment by discordier** [comment]
Appears to be a dupe of contao-community-alliance/dc-general#61, therefore I guess it is better off at dcg.

**Comment by asaage** [comment]
jepp
