### ISSUE TITLE
Contract metamodels by mm in the name of the templates

### ISSUE THREAD

**Issue by JLBA** [MetaModels/core#994]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
But found no reference to that
- [x] I have checked the Contao community forums for references https://community.contao.org/
but found no reference to that
- [ ] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue
Because I'm not able to search in german.

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     5.6     |                                  |
| Contao version:                     |     3.5.8     |                                  |
| MetaModels version:                 |      bundle_all 2.0.0    |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |     bundle_all 2.0.0     |                                  |

## Issue description
Not a very important issue but… Templates names seems to be 32 characters max (+ ext). 
But metamodel_prerendererd or metamodel_unrendered are 22 and 20 characters long. So it's a little bit difficult when you want to add something longer than just _list_.

As this should be a Contao's limitation, could you reduce metamodel to just _mm_ in the templates names ? And perhaps prerendered and unrendered by _pre_ and _un_.

## Steps to reproduce

1. Duplicate metamodel_prerendered template
2. Try to name it metamodel_prendered_list_Rencontres
3. That's all ;-))

**Comment by xantippe** [comment]
... i have "update" your checklist => use ```- [x]``` to check the checkbox

**Comment by xantippe** [comment]
Contao should longer names of templates - https://github.com/contao/core/commit/09d672f71b5af484687dcc49e42cddccf689d861
and at the future, we have shorter names (may be..) https://github.com/MetaModels/core/issues/661

**Comment by JLBA** [comment]
Ok. Thanks.
